/* BATTER's native Kitchen sample, note-pattern and GALLEY instrument adapters. */
(function () {
  'use strict';
  const S=window.BatterSchema,P=window.MusicLabPatternSchema;
  const abort=signal=>{if(signal?.aborted)throw new DOMException('BATTER transfer cancelled.','AbortError');};
  const finite=(value,min,max,label)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)throw new Error('Choose a valid '+label+'.');return value;};
  const unwrap=value=>value?.format==='loom-instrument-state'?unwrap(value.state):value?.format==='batter-project'?value.state:value?.state&&value.state.lanes?value.state:value;
  let ready=false,clockRevision=null,nativeEventCache=null;const cancellationBarriers=new Map();
  function engine(){const value=window.BatterUI?.engine;if(!value)throw new Error('BATTER is still opening.');return value;}
  function refresh(){window.BatterUI?.refresh();window.MusicLabHost?.notifyStateChange();document.dispatchEvent(new CustomEvent('musiclab:state-change',{bubbles:true,detail:{app:'batter'}}));}
  const voices=s=>s.lanes.map((l,i)=>({id:l.id,name:l.name,pitch:36+i,pitchRange:[12+i,60+i]}));
  function validateMap(packet,map,state) {if(!map||typeof map!=='object'||Array.isArray(map))throw new Error('Map each source voice explicitly before sending the pattern.');const result={};for(const voice of packet.voices){const id=map[voice.id];if(!S.LANE_IDS.includes(id))throw new Error('Choose a destination drum for '+voice.name+'.');Object.defineProperty(result,voice.id,{value:id,enumerable:true});}if(Object.keys(map).some(id=>!packet.voices.some(v=>v.id===id)))throw new Error('The mapping contains an unknown source voice.');for(const note of packet.notes){const base=36+S.LANE_IDS.indexOf(result[note.voice]);if(Math.abs(note.pitch-base)>24)throw new Error('BATTER supports two octaves of transposition from each drum lane.');}return result;}
  function nativeMap(packet,state) {return validateMap(packet,Object.fromEntries(packet.voices.map(v=>[v.id,v.id])),state);}
  function swungBeat(packet,note) {const grid=Math.round(note.beat*4);return Math.min(packet.lengthBeats-1e-8,note.beat+(Math.abs(note.beat*4-grid)<1e-7&&grid%2?packet.swing/4:0));}
  function capturePattern(options={}) {
    const state=engine().getState();if(state.musicLabPattern){const overlay=state.musicLabPattern,packet=P.parse(overlay.pattern),map=validateMap(packet,overlay.voiceMap,state),used=new Set(Object.values(map));return P.normalize({...packet,name:options.name||packet.name,sourceApp:'batter',kind:'drums',voices:voices(state).filter(v=>used.has(v.id)),notes:packet.notes.map(note=>({...note,voice:map[note.voice]}))});}
    const scope=options.scope==='chain'?'chain':'pattern',score=S.compile(state,{scope}),solo=state.lanes.some(l=>l.solo),notes=[];
    for(const event of score.events){const lane=state.lanes[event.laneIndex];if(lane.mute||solo&&!lane.solo||options.scope==='lane'&&lane.id!==(options.laneId||window.BatterUI?.selectedLaneId||state.lanes[0].id))continue;notes.push({id:event.id,voice:event.laneId,pitch:Math.round(36+event.laneIndex+event.pitch),beat:Math.max(0,event.beat),duration:Math.min(event.gate>0?event.gate:.25,score.lengthBeats-Math.max(0,event.beat)),velocity:event.velocity,probability:1});}
    return P.normalize({format:'musiclab-pattern',version:1,name:options.name||state.name+' · BATTER',sourceApp:'batter',kind:'drums',tempo:state.tempo,swing:0,lengthBeats:score.lengthBeats,meter:[4,4],voices:voices(state),notes,seed:state.seed});
  }
  async function prepare(){cancellationBarriers.clear();await engine().init();await engine().ensureSamples();return true;}
  function nativeEventFor(id,voice){const audio=engine();if(audio.state.musicLabPattern)return null;if(nativeEventCache?.generation!==audio.generation)nativeEventCache={generation:audio.generation,events:new Map(S.compile(audio.state,{scope:audio.state.chainEnabled?'chain':'pattern'}).events.map(e=>[e.id,e]))};const match=/(?:^|:)(batter-\d+)$/.exec(id||'');const event=match?nativeEventCache.events.get(match[1]):null;return event?.laneId===voice?event:null;}
  function scheduleNote({id,pitch,velocity=.8,voice,when,durationSeconds=.25,source='loom'}={}) {const audio=engine(),state=audio.state,index=S.LANE_IDS.indexOf(voice);if(index<0)throw new Error('Choose a BATTER drum voice.');finite(pitch,0,127,'MIDI pitch');if(!Number.isInteger(pitch))throw new Error('Choose an integer MIDI pitch.');finite(velocity,0,1,'velocity');finite(when,0,Number.MAX_SAFE_INTEGER,'note time');finite(durationSeconds,Number.MIN_VALUE,768,'note duration');const transpose=pitch-(36+index);if(Math.abs(transpose)>24)throw new Error('This note exceeds BATTER’s two-octave transpose range.');if(!audio.context||!audio.graph)throw new Error('Prepare BATTER audio before scheduling notes.');if(!velocity)return;if(cancellationBarriers.has(source)&&when>=cancellationBarriers.get(source))return false;const original=nativeEventFor(id,voice),event={id,laneId:voice,laneIndex:index,velocity,pitch:transpose+(original?original.pitch-Math.round(original.pitch):0),reverse:original?.reverse??null,sampleId:original?.sampleId||'',locks:original?.locks||{},duration:original?.gate===0?undefined:durationSeconds,seed:original?.seed??S.hash(state.seed,audio.previewSerial),roundRobin:audio.previewSerial++,source};const sampleId=audio.chooseSample(state.lanes[index],event);if(!sampleId)return;return audio.scheduleHit(event,Math.max(audio.context.currentTime,when));}
  function cancelNotes({source='loom',when}={}) {if(when!==undefined)finite(when,0,Number.MAX_SAFE_INTEGER,'cancellation time');const audio=engine(),now=audio.context?.currentTime||0,at=when===undefined?now:Math.max(now,when);if(when!==undefined&&source)cancellationBarriers.set(source,at);for(const entry of audio.sources)if(!source||entry.sourceId===source){try{if(entry.time>=at)entry.source.stop(at);else {entry.envelope.gain.cancelAndHoldAtTime(at);entry.envelope.gain.linearRampToValueAtTime(0,at+.008);entry.source.stop(at+.009);}}catch{try{entry.source.stop(at+.009);}catch{}}if(at<=now+.001)audio.sources.delete(entry);}return true;}
  async function importPattern({pattern,options={},signal}={}) {abort(signal);abort(options.signal);const state=engine().getState(),packet=P.parse(pattern);if(options.target!==undefined&&options.target!=='current')throw new Error('Choose BATTER’s received performance pattern.');if((state.musicLabPattern?.pattern.notes.length||capturePattern().notes.length)&&options.replace!==true)throw new Error('Confirm replacing the current performance pattern.');const map=validateMap(packet,options.voiceMap,state);abort(signal);abort(options.signal);engine().stop();engine().setState({...state,musicLabPattern:{pattern:packet,voiceMap:map}});window.BatterUI?.recordExternalChange?.(state);refresh();return {app:'batter',target:'current',notes:packet.notes.length,exact:true};}
  function clearImportedPattern(){const state=engine().getState();if(!state.musicLabPattern)return false;engine().stop();const before=engine().getState();delete state.musicLabPattern;engine().setState(state);window.BatterUI?.recordExternalChange?.(before);refresh();return true;}
  async function renderPattern({pattern,state:sourceState,tempo,tailSeconds=0,voiceMap:explicitMap,signal}={}) {
    abort(signal);const packet=P.parse(pattern),state=S.normalize(unwrap(sourceState)||engine().getState()),bpm=tempo??packet.tempo;finite(bpm,30,300,'render tempo');finite(tailSeconds,0,15,'render tail');if(packet.lengthBeats*60/bpm+tailSeconds>120)throw new Error('Split this part into patterns no longer than 120 seconds including the tail.');let map;if(explicitMap)map=validateMap(packet,explicitMap,state);else if(packet.voices.every(v=>S.LANE_IDS.includes(v.id)))map=nativeMap(packet,state);else if(state.musicLabPattern)map=validateMap(packet,state.musicLabPattern.voiceMap,state);else throw new Error('Map the pattern’s voices to BATTER before rendering.');
    const renderer=new window.BatterEngine(state);renderer.registerLibrary(engine().library);renderer.installAssets();const random=S.random(packet.seed??state.seed),native=state.musicLabPattern?[]:S.compile(state,{scope:'pattern'}).events,byId=new Map(native.map(e=>[e.id,e]));const events=[];
    for(const note of packet.notes){if(note.velocity<=0||random()>=note.probability)continue;const laneId=map[note.voice],laneIndex=S.LANE_IDS.indexOf(laneId),beat=swungBeat(packet,note),original=packet.sourceApp==='batter'?byId.get(note.id):null,matching=original?.laneId===laneId;events.push({id:note.id,laneId,laneIndex,beat,velocity:note.velocity,pitch:note.pitch-(36+laneIndex)+(matching?original.pitch-Math.round(original.pitch):0),sampleId:matching?original.sampleId:'',reverse:matching?original.reverse:null,locks:matching?original.locks:{},duration:matching&&original.gate===0?undefined:Math.min(note.duration,packet.lengthBeats-beat)*60/bpm,seed:matching?original.seed:S.hash(packet.seed??state.seed,events.length),roundRobin:matching?original.roundRobin:events.length,source:'loom'});}
    events.sort((a,b)=>a.beat-b.beat||a.laneIndex-b.laneIndex);state.tempo=bpm;try{const result=await renderer.renderScore({events,lengthBeats:packet.lengthBeats},state,{tailSeconds,signal});abort(signal);return {...result,name:packet.name,tempo:bpm,sourceApp:'batter'};}finally{await renderer.dispose();}
  }
  const patternAdapter={app:'batter',get notes(){return {voices:voices(engine().state),polyphonic:true,pitched:true,scheduledCancel:true};},get patternExport(){return {scopes:[{id:'pattern',label:'Current drum recipe'},{id:'chain',label:'Complete bank chain'}],defaultScope:'pattern'};},get patternImport(){const state=engine().state;return {targets:[{id:'current',name:'Received performance · exact timing',occupied:!!(state.musicLabPattern?.pattern.notes.length||capturePattern().notes.length)}],voices:voices(state),mode:'drums',description:'Exact timing, velocity and note lengths. Map voices to twelve acoustic drum lanes. Native recipe edits return to the step grid.'};},get importedPattern(){return engine().state.musicLabPattern?.pattern||null;},getImportedPattern(){return this.importedPattern;},capturePattern,exportPattern:capturePattern,importPattern,clearImportedPattern,prepare,scheduleNote,cancelNotes,renderPattern,validatePattern({pattern,voiceMap}={}){validateMap(P.parse(pattern),voiceMap,engine().state);return true;},validateNote({pitch,voice}={}){finite(pitch,0,127,'MIDI pitch');if(!Number.isInteger(pitch)||!S.LANE_IDS.includes(voice)||Math.abs(pitch-(36+S.LANE_IDS.indexOf(voice)))>24)throw new Error('Choose a note within this drum voice’s two-octave range.');return true;},panic(){engine().panic();},transport({beat,when,revision,playing}={}){if(playing===false||revision!==clockRevision){cancelNotes({source:'loom'});clockRevision=revision;}if(Number.isFinite(beat)&&!engine().playing)engine().meters={...engine().meters,beat,step:Math.floor(beat*4)%engine().state.patterns.find(p=>p.id===engine().state.selectedPattern).length};}};
  function interleave(audio){const pcm=new Float32Array(audio.left.length*2);for(let i=0;i<audio.left.length;i++){pcm[i*2]=audio.left[i];pcm[i*2+1]=audio.right[i];}return pcm;}
  const app={get engine(){return engine();},isPlaying:()=>engine().playing,getState:()=>engine().getState({portable:'external'}),getProject:options=>engine().getProject(options),async loadState(value){engine().panic();await engine().loadProject({format:'batter-project',formatVersion:1,state:unwrap(value)});refresh();return engine().getState();},prepare,play:options=>engine().play(options),stop:()=>engine().stop(),panic:()=>engine().panic(),setTempo(value){finite(value,30,300,'tempo');const state=engine().getState();state.tempo=value;engine().setState(state);refresh();},get audioImport(){return {maxSeconds:120,channels:2,targets:engine().state.lanes.map(l=>({id:l.id,name:l.name,occupied:!!l.sampleId,assetName:engine().metadata.get(l.sampleId)?.name||''})),defaultTarget:'kick'};},get audioExport(){return {scopes:[{id:'pattern',label:'Drum recipe / with effects'},{id:'chain',label:'Bank chain / with effects'},{id:'lane',label:'Selected drum lane / with effects'},{id:'source',label:'Source sample / unprocessed',usesBars:false}],defaultBars:1,maxBars:32};},async importAudio(payload){const options=payload.options||{},target=options.target||'kick';abort(payload.signal);abort(options.signal);if(!S.LANE_IDS.includes(target))throw new Error('Choose a BATTER drum lane.');if(engine().state.lanes.find(l=>l.id===target).sampleId&&options.replace!==true)throw new Error('Confirm replacement before changing the drum sample.');const before=engine().getState();const result=await engine().importAudio(payload,{...options,laneId:target,signal:payload.signal||options.signal});window.BatterUI?.recordExternalChange?.(before);refresh();return result;},async exportAudio({scope='pattern',bars=1,tailSeconds=2,laneId=window.BatterUI?.selectedLaneId||'kick',signal}={}){abort(signal);if(scope==='source'){const lane=engine().state.lanes.find(l=>l.id===laneId);if(!lane?.sampleId)throw new Error('Load a drum sample first.');await engine().ensureSamples([lane.sampleId],{signal});abort(signal);const audio=engine().getSampleAudio(lane.sampleId);return {pcm:interleave(audio),sampleRate:audio.sampleRate,name:audio.name,tempo:engine().state.tempo,sourceApp:'batter',sourceLabel:'Unprocessed source sample'};}if(!['pattern','chain','lane'].includes(scope))throw new Error('Choose a valid BATTER audio export.');const blob=await engine().renderWav({bars,tailSeconds,scope,laneId,signal});abort(signal);return {blob,sampleRate:48000,name:engine().state.name+'.wav',tempo:engine().state.tempo,sourceApp:'batter',sourceLabel:scope};}};
  function install(){if(ready||!window.BatterUI?.engine)return;ready=true;Object.defineProperty(window,'BatterApp',{value:Object.freeze(app),writable:false});Object.defineProperty(window,'MusicLabPatternInstrument',{value:Object.freeze(patternAdapter),writable:false});if(window.MusicLabHost){window.BatterUI.setHosted(true);window.MusicLabHost.registerInstrument({...app,getState:async()=>{await engine().ensureSamples();return engine().getState({portable:'external'});},setState:app.loadState,tempo:app.setTempo,async start({tempo,when,fromBeat=0}={}){if(tempo!==undefined)app.setTempo(tempo);return engine().play({when,offsetBeats:fromBeat});},...patternAdapter});}document.dispatchEvent(new CustomEvent('musiclab:app-ready',{bubbles:true,detail:{app:'batter'}}));}
  document.addEventListener('batter-ready',install);install();
  window.addEventListener('pagehide',()=>{if(ready)engine().dispose();});
})();
