'use strict';

// Exercises the shipped offline instrument and actual Chromium Web Audio.
// Signals generated here are test fixtures; BATTER's factory sound is recorded audio.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const source = __dirname, root = path.resolve(source, '..');
const artifacts = process.env.BATTER_QA_ARTIFACTS || path.join(os.tmpdir(), 'batter-browser-qa');
const passed = [], measurements = [], skipped = [];
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function serve() {
  const server = http.createServer((request, response) => {
    const pathname = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const base=pathname.startsWith('/batter/')?source:root,relative=pathname.startsWith('/batter/')?pathname.slice(7):pathname;
    const file = path.resolve(base, '.' + relative + (pathname.endsWith('/') ? 'index.html' : ''));
    if (!file.startsWith(base + path.sep)) { response.writeHead(403); response.end(); return; }
    fs.readFile(file, (error, bytes) => {
      if (error) { response.writeHead(404); response.end(); return; }
      const mime = { '.html':'text/html', '.json':'application/json', '.css':'text/css', '.js':'application/javascript', '.wav':'audio/wav' }[path.extname(file)] || 'application/octet-stream';
      response.writeHead(200, { 'Content-Type':mime, 'Content-Length':bytes.length, 'Cache-Control':'no-store' }); response.end(bytes);
    });
  });
  await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); });
  return { url:'http://127.0.0.1:' + server.address().port, close:() => new Promise(resolve => server.close(resolve)) };
}

async function prepareOffline(page, serverURL) {
  try { await prepare(page,pathToFileURL(path.join(source,'index.html')).href); measurements.push({offlineMode:'literal file URL'}); }
  catch(error) {
    if(!/ERR_BLOCKED_BY_ADMINISTRATOR/.test(error.message))throw error;
    await page.route('**/*', route => route.request().isNavigationRequest() ? route.fulfill({status:200,contentType:'text/html',body:fs.readFileSync(path.join(source,'index.html'))}) : route.abort('internetdisconnected'));
    await prepare(page,serverURL+'/batter/index.html');measurements.push({offlineMode:'managed Chromium blocks file URLs; exact standalone HTML fulfilled with every external request disabled'});
  }
}

async function prepare(page, url) {
  await page.goto(url, { waitUntil:'load' });
  await page.waitForFunction(() => !!window.BatterUI?.engine && !!window.BatterSchema, null, { timeout:30000 });
  await page.evaluate(() => {
    window.qa = {
      engine:window.BatterUI.engine,
      state:() => window.BatterUI.engine.getState(),
      set:state => { window.BatterUI.engine.setState(state); window.BatterUI.refresh(); },
      clean:() => { const state=window.BatterUI.engine.getState(); state.tempo=240; state.swing=0; state.humanize=0; state.velocityHumanize=0; state.master.volume=1; state.lanes.forEach(l=>{l.room=0;l.delay=0;l.mute=false;l.solo=false;l.volume=.9;l.layerMode='single';}); return state; },
      audio:async blob => { const bytes=await blob.arrayBuffer(),view=new DataView(bytes),frames=(bytes.byteLength-44)/4,left=new Float32Array(frames),right=new Float32Array(frames); for(let i=0;i<frames;i++){left[i]=view.getInt16(44+i*4,true)/32768;right[i]=view.getInt16(46+i*4,true)/32768;} return {left,right,rate:view.getUint32(24,true),frames,bytes:bytes.byteLength,header:String.fromCharCode(...new Uint8Array(bytes,0,4)),dataBytes:view.getUint32(40,true),channels:view.getUint16(22,true)}; },
      stats:audio => { let sumL=0,sumR=0,peak=0,last=-1,finite=true; for(let i=0;i<audio.frames;i++){const l=audio.left[i],r=audio.right[i];sumL+=l*l;sumR+=r*r;peak=Math.max(peak,Math.abs(l),Math.abs(r));finite=finite&&Number.isFinite(l)&&Number.isFinite(r);if(Math.abs(l)+Math.abs(r)>1/32768)last=i;}return {rmsL:Math.sqrt(sumL/audio.frames),rmsR:Math.sqrt(sumR/audio.frames),peak,last,finite,rate:audio.rate,frames:audio.frames,bytes:audio.bytes,header:audio.header,dataBytes:audio.dataBytes,channels:audio.channels}; },
      difference:(a,b) => { let delta=0,reference=0;for(let i=0;i<Math.min(a.frames,b.frames);i++){delta+=(a.left[i]-b.left[i])**2+(a.right[i]-b.right[i])**2;reference+=a.left[i]**2+a.right[i]**2;}return Math.sqrt(delta/Math.max(1e-12,reference)); },
      energy:(audio,start,end) => { let sum=0;const a=Math.floor(start*audio.rate),b=Math.min(audio.frames,Math.floor(end*audio.rate));for(let i=a;i<b;i++)sum+=audio.left[i]**2+audio.right[i]**2;return Math.sqrt(sum/Math.max(1,(b-a)*2)); },
      fixture:(seconds=.2,rate=22050) => { const frames=Math.round(seconds*rate),left=new Float32Array(frames),right=new Float32Array(frames);for(let i=0;i<frames;i++){left[i]=.4*Math.sin(2*Math.PI*330*i/rate)*Math.exp(-i/rate*8);right[i]=.3*Math.sin(2*Math.PI*550*i/rate)*Math.exp(-i/rate*8);}return window.BatterSchema.wav({left,right,sampleRate:rate}); }
    };
  });
}

async function factoryAndRenderChecks(browser, server) {
  const page=await browser.newPage(); const errors=[]; page.on('pageerror',error=>errors.push(error.message));
  try {
    await prepareOffline(page,server.url);
    const factory=await page.evaluate(async () => {
      const q=window.qa,e=q.engine,state=q.clean(),library=window.BatterLibrary;
      const result=[];
      for(let i=0;i<state.lanes.length;i++){
        const output=await e.renderNotes({state,tempo:240,lengthBeats:2,tailSeconds:.2,events:[{note:36+i,startBeat:.25,durationBeats:1,velocity:.9}]});
        const audio=await q.audio(output.blob),s=q.stats(audio),meta=e.metadata.get(state.lanes[i].sampleId);
        result.push({lane:state.lanes[i].id,sampleId:meta.id,license:meta.license,source:meta.source,...s});
      }
      return {starter:library.samples.length,kits:library.kits.length,lanes:state.lanes.length,result,onlineRequests:performance.getEntriesByType('resource').filter(r=>/^https?:/.test(r.name)).length};
    });
    assert.equal(factory.starter,84);assert.equal(factory.kits,3);assert.equal(factory.lanes,12);assert.equal(factory.onlineRequests,0);
    for(const lane of factory.result){assert(lane.source && lane.license,'Recorded sample provenance remains available.');assert(lane.rmsL>.001 && lane.peak>.01,'Factory lane is audible: '+JSON.stringify(lane));assert(lane.finite);assert.equal(lane.header,'RIFF');assert.equal(lane.rate,48000);assert.equal(lane.channels,2);assert.equal(lane.bytes,44+lane.frames*4);assert.equal(lane.dataBytes,lane.frames*4);}
    measurements.push({factory:factory.result});passed.push('Offline HTML: 84 recorded starters / three kits / all twelve audible native lanes / provenance / finite stereo WAV headers');
    const articulation=await page.evaluate(async()=>{const q=window.qa,e=q.engine,state=q.clean(),l=state.lanes[1];l.layerMode='velocity';const soft=e.chooseSample(l,{velocity:.12,seed:1,roundRobin:0}),hard=e.chooseSample(l,{velocity:.95,seed:1,roundRobin:0});const render=async events=>q.audio((await e.renderNotes({state,tempo:240,lengthBeats:4,tailSeconds:0,events})).blob);state.lanes[3].volume=0;const open=await render([{note:40,startBeat:0,velocity:.9}]),choked=await render([{note:40,startBeat:0,velocity:.9},{note:39,startBeat:.5,velocity:.9}]);state.lanes[3].mute=true;const muted=await render([{note:40,startBeat:0,velocity:.9},{note:39,startBeat:.5,velocity:.9}]);return {soft,hard,baseline:q.energy(open,.15,.35),choked:q.energy(choked,.15,.35),muted:q.energy(muted,.15,.35)};});
    assert.notEqual(articulation.soft,articulation.hard,'Soft/hard strikes select distinct recorded velocity layers.');assert(articulation.baseline>.0002);assert(articulation.choked<articulation.baseline*.05,'A zero-volume active closed-hat hit still cuts the ringing open hat.');assert(Math.abs(articulation.muted-articulation.baseline)<1e-6,'Muting a closed-hat lane suppresses its choke events.');measurements.push({articulation});passed.push('Recorded velocity-layer selection / actual acoustic open-closed-hat choke / muted-lane event suppression');


    const shape=await page.evaluate(async () => {
      const q=window.qa,e=q.engine,base=q.clean(),lane=base.lanes[1];
      const render=async patch=>{const state=structuredClone(base);Object.assign(state.lanes[1],patch);return q.audio((await e.renderNotes({state,tempo:240,lengthBeats:4,tailSeconds:0,events:[{note:37,startBeat:.25,durationBeats:3,velocity:.9}]})).blob);};
      const original=await render({}),results=[];
      for(const [name,patch] of [['trim',{start:.18,end:.6}],['envelope',{attack:.06,decay:.05,sustain:.12,release:.09,gate:.3}],['pitch',{tune:12}],['reverse',{reverse:true}],['filter',{lowpass:250,highpass:70}],['texture',{drive:.6,bits:5,decimate:9,transient:-.6,body:.5}]]){const audio=await render(patch);results.push({name,difference:q.difference(original,audio),...q.stats(audio)});}
      const state=structuredClone(base);state.patterns[0].length=16;state.patterns[0].lanes.forEach(l=>l.steps.forEach(h=>h.on=false));Object.assign(state.patterns[0].lanes[1].steps[0],{on:true,velocity:.9,locks:{pan:1,lowpass:300,drive:.8}});const locked=await q.audio(await e.renderWav({state,bars:1,tailSeconds:0}));
      return {results,locked:q.stats(locked)};
    });
    for(const result of shape.results){assert(result.difference>.1,'Editing '+result.name+' must change rendered sound.');assert(result.finite && result.rmsL>.00001);}
    assert(shape.locked.rmsR>shape.locked.rmsL*100,'Per-hit pan lock affects the actual stereo render.');measurements.push({shape});passed.push('Actual trim / ADSR-duration / pitch / reverse / filter / transient-body-crush changes; per-hit locks alter stereo audio');

    const last=await page.evaluate(async()=>{
      const q=window.qa,e=q.engine,state=q.clean();state.lanes[6].room=.8;state.master.roomSize=.8;const p=state.patterns[0];p.length=64;p.lanes.forEach(l=>{l.length=64;l.steps.forEach(h=>h.on=false);});Object.assign(p.lanes[6].steps[63],{on:true,velocity:.9});const audio=await q.audio(await e.renderWav({state,bars:4,tailSeconds:2}));return {...q.stats(audio),before:q.energy(audio,0,3.9),lastHit:q.energy(audio,3.94,4.05),tail:q.energy(audio,4.1,4.8),end:q.energy(audio,5.98,6)};
    });
    assert.equal(last.frames,288000);assert.equal(last.before,0);assert(last.lastHit>.004 && last.tail>.0001,'Step 64 and its recorded acoustic/reverb release survive WAV export.');assert(last.finite && last.peak<=1);measurements.push({lastStep:last});passed.push('Actual 64th-step WAV render / expected duration / audible post-pattern acoustic-room tail / no early events / finite PCM');
    await page.locator('#playButton').click();await page.waitForFunction(()=>window.qa.engine.getMeters().playing);await sleep(350);assert((await page.evaluate(()=>window.qa.engine.getMeters().peak))>.001);await page.locator('#panicButton').click();assert.equal(await page.evaluate(()=>window.qa.engine.playing),false);assert.equal(await page.evaluate(()=>window.qa.engine.sources.size),0);await page.locator('#auditionButton').click();await page.waitForFunction(()=>window.qa.engine.sources.size>0);await sleep(60);const preview=await page.evaluate(()=>{const a=new Float32Array(256);window.qa.engine.graph.analyser.getFloatTimeDomainData(a);return Math.max(...a.map(Math.abs));});assert(preview>.001,'Stopped drum audition reaches the real output graph.');await page.locator('#panicButton').click();assert.equal(await page.evaluate(()=>window.qa.engine.sources.size),0);passed.push('Actual offline Play output meter / stopped audible audition / Panic clears native voices');
    assert.deepEqual(errors,[]);
  } finally {await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}
}

async function sequencingChecks(browser,url){
  const page=await browser.newPage();try{
    await prepare(page,url+'/batter/index.html');
    const result=await page.evaluate(()=>{
      const S=window.BatterSchema,state=window.qa.clean();state.patterns.forEach(p=>p.lanes.forEach(l=>l.steps.forEach(s=>s.on=false)));const a=state.patterns[0],b=state.patterns[1];a.length=64;b.length=16;a.lanes.forEach(l=>l.length=64);b.lanes.forEach(l=>l.length=16);
      a.lanes[0].length=5;a.lanes[0].steps[0]={...S.step(true,.8)};a.lanes[1].steps[63]={...S.step(true,.8),ratchet:4,flam:17,micro:-12};a.lanes[3].steps[1]={...S.step(true,.55),condition:'fill'};a.lanes[4].steps[2]={...S.step(true,.7),condition:'notFill'};b.lanes[1].steps[4]={...S.step(true,.6)};state.chainEnabled=true;state.chain=['A','B'];
      const noFill=S.compile(state),filled=S.compile({...state,fill:true}),swung=S.compile({...state,swing:.4}),seeded={...state,seed:12123,humanize:20,velocityHumanize:.2};a.lanes[9].steps[5]={...S.step(true,.8),probability:.5,ratchet:3};
      const first=S.compile(seeded,{cycles:5}),same=S.compile(seeded,{cycles:5}),other=S.compile({...seeded,seed:12124},{cycles:5});
      return {beats:noFill.lengthBeats,kicks:noFill.events.filter(e=>e.laneId==='kick').map(e=>e.beat),snare:noFill.events.filter(e=>e.laneId==='snare'),offFill:noFill.events.filter(e=>e.laneId==='closedHat').length,onFill:filled.events.filter(e=>e.laneId==='closedHat').length,openNoFill:noFill.events.filter(e=>e.laneId==='openHat').length,openFill:filled.events.filter(e=>e.laneId==='openHat').length,swingDelta:swung.steps[1].beat-noFill.steps[1].beat,repeat:JSON.stringify(first)===JSON.stringify(same),different:JSON.stringify(first)!==JSON.stringify(other)};
    });
    assert.equal(result.beats,20);assert.deepEqual(result.kicks,Array.from({length:13},(_,i)=>i*1.25));assert.equal(result.snare.length,6);assert(result.snare.some(e=>e.step===63&&e.flam));assert(result.snare.some(e=>e.patternId==='B'&&Math.abs(e.beat-17)<1e-10));assert.equal(result.offFill,0);assert.equal(result.onFill,1);assert.equal(result.openNoFill,1);assert.equal(result.openFill,0);assert(Math.abs(result.swingDelta-.05)<1e-10);assert(result.repeat&&result.different);passed.push('64 steps / independent 5-step cycle / A–B chain / four ratchets + flam + microtiming / fill conditions / swing / reproducible seeded chance');

    await page.selectOption('#lengthSelect','64');await page.locator('#nextPage').click();await page.locator('#nextPage').click();await page.locator('#nextPage').click();assert.equal(await page.locator('#pageLabel').textContent(),'49—64');await page.locator('.step-cell[data-lane="kick"][data-step="63"]').click({modifiers:['Shift']});assert.equal(await page.locator('#selectedStepNumber').textContent(),'64');await page.locator('#previousPage').click();await page.locator('#previousPage').click();await page.locator('#previousPage').click();
    await page.locator('.step-cell[data-lane="kick"][data-step="0"]').click({modifiers:['Shift']});await page.locator('#stepLock').check();const protectedHit=await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps[0]);await page.fill('#euclidPulses','7');await page.locator('#euclideanButton').click();const euclid=await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps);assert.deepEqual(euclid[0],protectedHit);assert(euclid.filter(s=>s.on).length>=6&&euclid.filter(s=>s.on).length<=8);await page.locator('#undoButton').click();assert.deepEqual(await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps[0]),protectedHit);await page.locator('#redoButton').click();assert.deepEqual(await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps),euclid);
    await page.locator('#laneLock').check();const before=await page.evaluate(()=>window.qa.state().patterns[0].lanes[0]);for(const button of ['mutateButton','fillButton','clearLaneButton','euclideanButton'])await page.locator('#'+button).click();assert.deepEqual(await page.evaluate(()=>window.qa.state().patterns[0].lanes[0]),before);await page.locator('#laneLock').uncheck();await page.locator('#fillButton').click();assert.equal(await page.evaluate(()=>window.qa.state().fill),true);assert((await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps.slice(56).filter(s=>s.on).length))>=7);assert.deepEqual(await page.evaluate(()=>window.qa.state().patterns[0].lanes[0].steps[0]),protectedHit);passed.push('UI pages to step 64 / hit selection / Euclidean / protected hit and lane / fill / real Undo–Redo state');
  }finally{await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}
}

async function importAndProjectChecks(browser,url){
  const page=await browser.newPage();try{
    await prepare(page,url+'/batter/index.html');
    const imported=await page.evaluate(async()=>{
      const q=window.qa,e=q.engine,blob=q.fixture();await e.importFiles([new File([blob],'Copper.wav'),new File([blob],'Tin.wav')],{laneId:'rim',mode:'layers'});const state=e.getState();const ids=state.lanes[2].sampleIds;return {count:state.assets.length,ids,mode:state.lanes[2].layerMode,names:state.assets.map(a=>a.name)};
    });assert.equal(imported.count,2);assert(imported.ids.length>=3);assert.equal(imported.mode,'roundrobin');assert.deepEqual(imported.names,['Copper','Tin']);passed.push('Actual decoded batch WAV import / real named PCM assets / round-robin lane alternatives');
    const atom=await page.evaluate(async()=>{
      const q=window.qa,e=q.engine,original=JSON.stringify(e.getState()),blob=q.fixture();const cases=[];
      for(const files of [[new File([blob],'Valid.wav'),new File(['not audio'],'Broken.wav')],[{name:'Too-big.wav',size:window.BatterSchema.MAX_BYTES+1,arrayBuffer(){throw Error('must not read oversized file');}}]]){try{await e.importFiles(files,{laneId:'kick',mode:'layers'});cases.push({error:null});}catch(error){cases.push({error:error.message,same:JSON.stringify(e.getState())===original,busy:e.importing});}}
      let resolve;const delayed={name:'Delayed.wav',size:blob.size,arrayBuffer:()=>new Promise(r=>resolve=r)},controller=new AbortController(),pending=e.importFiles([delayed],{laneId:'kick',signal:controller.signal}).catch(error=>error.message);controller.abort();resolve(await blob.arrayBuffer());cases.push({error:await pending,same:JSON.stringify(e.getState())===original,busy:e.importing});
      let release;const slow={name:'Panic.wav',size:blob.size,arrayBuffer:()=>new Promise(r=>release=r)},panic=e.importFiles([slow],{laneId:'kick'}).catch(error=>error.message);e.panic();release(await blob.arrayBuffer());cases.push({error:await panic,same:JSON.stringify(e.getState())===original,busy:e.importing});return cases;
    });for(const result of atom){assert(result.error);assert.equal(result.same,true,'Failed/cancelled import leaves all lane/sample state intact.');assert.equal(result.busy,false);}passed.push('Bad second file / 64 MB per-file budget / AbortSignal / Panic during pending decode: atomic failure and cleared busy state');
    const budget=await page.evaluate(async()=>{
      const q=window.qa,e=q.engine,before=JSON.stringify(e.getState()),blob=q.fixture(110,22050),files=Array.from({length:4},(_,i)=>new File([blob],'Budget-'+i+'.wav'));try{await e.importFiles(files,{laneId:'kick',mode:'layers'});return {error:null};}catch(error){return {error:error.message,same:JSON.stringify(e.getState())===before,busy:e.importing};}
    });assert.match(budget.error,/64 MB|limited|full|budget/i);assert(budget.same&&!budget.busy);passed.push('Actual four decoded long stereo WAV files exceed the total decoded budget without partial lane/assets changes');
    const portable=await page.evaluate(async()=>{
      const q=window.qa,e=q.engine,project=await e.getProject();window.qaPortable=project;const restored=new window.BatterEngine();await restored.loadProject(project);const state=restored.getState(),a=await q.audio((await e.renderNotes({events:[{note:38,startBeat:.17,durationBeats:.6,velocity:.8}],tempo:240,lengthBeats:2,tailSeconds:0})).blob),b=await q.audio((await restored.renderNotes({events:[{note:38,startBeat:.17,durationBeats:.6,velocity:.8}],tempo:240,lengthBeats:2,tailSeconds:0})).blob);const bundle=await e.exportBundle();window.qaBundle=bundle;const cupboard=new window.BatterEngine();cupboard.importBundle(bundle);await cupboard.setKit(bundle.kits[0].id);const external=state.assets.filter(a=>!e.factoryIds.has(a.id));const result={assets:state.assets.length,external:external.length,pcm:external.every(a=>typeof a.pcm==='string'&&a.pcm.length>100),same:JSON.stringify(state)===JSON.stringify(project.state),difference:q.difference(a,b),bundleSamples:bundle.samples.length,bundleAudible:cupboard.state.lanes.every(l=>!!cupboard.audio.get(l.sampleId))};await restored.dispose();await cupboard.dispose();return result;
    });assert(portable.assets>=12&&portable.external===2&&portable.pcm);assert.equal(portable.same,true);assert(portable.difference<.002,JSON.stringify(portable));assert(portable.bundleSamples===portable.assets&&portable.bundleAudible);measurements.push({portable});passed.push('Portable project embeds referenced recorded/external PCM / restores exact state and sound within PCM16 rounding / exported offline bundle loads a complete playable kit');
    const download=page.waitForEvent('download');await page.locator('#saveButton').click();const saved=await download;const savedPath=path.join(artifacts,'BATTER-project.json');await saved.saveAs(savedPath);const json=JSON.parse(fs.readFileSync(savedPath,'utf8'));assert.equal(json.format,'batter-project');assert(json.state.assets.some(a=>a.name==='Copper'));await page.setInputFiles('#projectFile',savedPath);await page.waitForFunction(()=>document.getElementById('toast').textContent==='Recipe restored.');assert.equal(await page.evaluate(()=>window.qa.state().assets.filter(a=>a.name==='Copper').length),1);passed.push('Actual browser Save download / Open file picker reload with external PCM');
    const badProject=await page.evaluate(async()=>{const e=window.qa.engine,before=JSON.stringify(e.getState()),state=e.getState();state.name='Should never replace the recipe';state.lanes[0].sampleId='unavailable-external-recording';state.lanes[0].sampleIds=['unavailable-external-recording'];try{await e.loadProject({format:'batter-project',formatVersion:1,state});return {error:null};}catch(error){return {error:error.message,same:JSON.stringify(e.getState())===before};}});assert.match(badProject.error,/unavailable|sample/i);assert(badProject.same);passed.push('Invalid external-sample project fails before replacing the working recipe');
    const cancelledPlay=await page.evaluate(async()=>{const e=window.qa.engine,original=e.ensureSamples.bind(e);let release;e.ensureSamples=async(...args)=>{await new Promise(resolve=>release=resolve);return original(...args);};const pending=e.play();while(!release)await new Promise(resolve=>setTimeout(resolve,0));e.panic();release();const result=await pending;e.ensureSamples=original;return {result,playing:e.playing,sources:e.sources.size,timer:e.timer};});assert.equal(cancelledPlay.result,false);assert.equal(cancelledPlay.playing,false);assert.equal(cancelledPlay.sources,0);assert.equal(cancelledPlay.timer,null);passed.push('Panic while real playback preparation is pending cannot start late audio or a scheduler');

  }finally{await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}
}

async function libraryChecks(browser,url){
  const page=await browser.newPage();try{
    await prepare(page,url+'/batter/index.html');const bundles=await page.evaluate(()=>window.qa.engine.getCatalog().bundles);const online=bundles.find(b=>!b.requires?.length && /iron/i.test(b.id));assert(online,'An expanded native acoustic kit is available.');const countBefore=await page.evaluate(()=>window.qa.engine.getCatalog().samples.length);await page.locator('#sampleBrowserButton').click();await page.locator('.library-card').filter({hasText:online.name}).getByRole('button',{name:/Load.*use kit/}).click();await page.waitForFunction(id=>window.qa.state().kitId===id&&window.qa.state().lanes[0].sampleIds.length===5,online.id,{timeout:30000});const loaded=await page.evaluate(id=>{const e=window.qa.engine;return {after:e.getCatalog().samples.length,bundle:e.loadedBundles.has(id),kit:e.getCatalog().kits.find(k=>k.id===id),layers:e.state.lanes[0].sampleIds.length};},online.id);assert(loaded.bundle&&loaded.after>countBefore);assert.equal(loaded.layers,5);await page.locator('#closeSampleDialog').click();const selected=await page.evaluate(async id=>{const e=window.qa.engine;await e.setKit(id);const output=await e.renderNotes({events:[{note:36,startBeat:.1,velocity:.9}],tempo:240,lengthBeats:2,tailSeconds:0});return window.qa.stats(await window.qa.audio(output.blob));},online.id);assert(selected.rmsL>.002&&selected.finite);passed.push('Actual Load & use kit control fetches expanded recordings / starter becomes five real velocity layers / audible expanded drum render');
    await page.evaluate(async()=>{const frames=4410,pcm=new Float32Array(frames*2);for(let i=0;i<frames;i++){pcm[i*2]=.22*Math.sin(i*.13);pcm[i*2+1]=.16*Math.cos(i*.2);}await window.BatterApp.importAudio({pcm,sampleRate:22050,name:'Overnight stereo ingredient',options:{target:'percussion',replace:true}});});
    await page.waitForFunction(()=>/kept.*browser|saved.*device|saved.*browser/i.test(document.getElementById('saveStatus').textContent),null,{timeout:15000});const beforeReload=await page.evaluate(()=>window.qa.engine.getState({portable:'external'}));
    await page.route('**/*',route=>route.request().isNavigationRequest()?route.fulfill({status:200,contentType:'text/html',body:fs.readFileSync(path.join(source,'index.html'))}):route.abort('internetdisconnected'));await prepare(page,url+'/batter/index.html');const restored=await page.evaluate(async()=>{const e=window.qa.engine;await e.ensureSamples();return {state:e.getState({portable:'external'}),layers:e.state.lanes[0].sampleIds.length,custom:e.metadata.get(e.state.lanes[11].sampleId)?.name,pcm:e.state.assets.find(a=>a.id===e.state.lanes[11].sampleId)?.pcm};});assert.equal(restored.layers,5);assert.equal(restored.custom,'Overnight stereo ingredient');assert.deepEqual(restored.state,beforeReload,'A durable autosave restores every external drum, stereo PCM, bank and edit without network.');assert(restored.pcm?.length>1000);await page.selectOption('#kitSelect','red-service');await page.waitForFunction(()=>window.qa.state().kitId==='red-service');await page.selectOption('#kitSelect',online.id);await page.waitForFunction(id=>window.qa.state().kitId===id,online.id);assert.deepEqual(await page.evaluate(()=>window.qa.state().lanes.map(l=>l.sampleIds)),beforeReload.lanes.map(l=>l.sampleIds),'Changing away from a recovered kit and back preserves all recorded layers and its custom sample offline.');await page.locator('#playButton').click();await page.waitForFunction(()=>window.qa.engine.playing);await sleep(350);assert((await page.evaluate(()=>window.qa.engine.getMeters().peak))>.001);await page.locator('#panicButton').click();await page.unroute('**/*');passed.push('Actual durable autosave / fresh-page reload with all network disabled / full optional velocity kit + external stereo PCM restored exactly, switch-away/back retained, and audible');

    await page.evaluate(()=>window.BatterUI.refresh());await page.locator('#sampleBrowserButton').click();const button=page.locator('.library-card').filter({hasText:online.name});const downloadPromise=page.waitForEvent('download');await button.getByRole('link',{name:'Download bundle',exact:true}).click();const download=await downloadPromise,bundlePath=path.join(artifacts,'downloaded-acoustic-bundle.json');await download.saveAs(bundlePath);const data=JSON.parse(fs.readFileSync(bundlePath,'utf8'));assert(data.samples.length>=100&&data.samples.every(s=>s.base64&&s.license&&s.source));await page.locator('#closeSampleDialog').click();
    const offline=await browser.newPage();try{await prepareOffline(offline,url);await offline.setInputFiles('#bundleFile',bundlePath);await offline.waitForFunction(()=>document.getElementById('toast').textContent==='Sample bundle opened.');await offline.waitForFunction(()=>/kept.*browser|saved.*device|saved.*browser/i.test(document.getElementById('saveStatus').textContent),null,{timeout:15000});const packedBefore=await offline.evaluate(()=>window.qa.engine.getState({portable:'external'}));await prepare(offline,url+'/batter/index.html');assert.deepEqual(await offline.evaluate(()=>window.qa.engine.getState({portable:'external'})),packedBefore,'Offline-imported expanded samples survive closing and reopening the HTML without network.');const imported=await offline.evaluate(id=>window.qa.engine.getCatalog().kits.some(k=>k.id===id),online.id);assert(imported);assert.equal(await offline.evaluate(()=>window.qa.state().kitId),online.id);await offline.locator('#playButton').click();await offline.waitForFunction(()=>window.qa.engine.playing);await sleep(500);assert((await offline.evaluate(()=>window.qa.engine.getMeters().peak))>.001);passed.push('Real online bundle Download / offline file import / expanded kit remains playable without fetch');}finally{await offline.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await offline.close();}
    const complete=await page.evaluate(async()=>{const e=window.qa.engine,result=[];for(const id of ['iron-service','red-service','late-lunch','rope-tension','pantry-percussion-hands']){await e.loadLibrary(id);const kitId=id.startsWith('pantry-')?'pantry-percussion':id;await e.setKit(kitId);const output=await e.renderNotes({events:[{note:36,startBeat:.1,velocity:.9},{note:47,startBeat:.6,velocity:.8}],tempo:240,lengthBeats:2,tailSeconds:0});result.push({id:kitId,decoded:e.sampleBytes(),referenced:e.referencedIds().length,audio:window.qa.stats(await window.qa.audio(output.blob))});}return {result,metadata:e.getCatalog().samples.length,recorded:e.library.samples.length,hands:e.loadedBundles.has('pantry-percussion-hands'),metal:e.loadedBundles.has('pantry-percussion-metal'),everyLane:e.state.lanes.every(l=>!!e.audio.get(l.sampleId))};});for(const kit of complete.result){assert(kit.decoded<=64*1024*1024);assert(kit.audio.rmsL>.001&&kit.audio.finite);}assert(complete.hands&&complete.metal&&complete.everyLane);assert.equal(complete.recorded,641);measurements.push({completeLibraries:complete});passed.push('All 641 sample entries discoverable / every expanded kit audible / stereo alternate-strike pack / Pantry sibling auto-load / decoded LRU cache stays within 64 MB');
  }finally{await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}
}

async function uiChecks(browser,url){
  for(const width of [320,390,768,1440]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));try{
    await prepare(page,url+'/batter/index.html');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(artifacts,'BATTER-'+width+'.png'),fullPage:true});const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:document.getElementById('waveform').getBoundingClientRect().width,pads:document.querySelectorAll('.lane-pad').length,cells:document.querySelectorAll('.step-cell').length,fonts:document.fonts.status}));assert(layout.scroll<=width+1,'Only the grid may scroll at '+width+'px: '+JSON.stringify(layout));assert.equal(layout.pads,12);assert.equal(layout.cells,192);assert(layout.canvas>150);assert.equal(layout.fonts,'loaded');
    const wave=page.locator('#waveform');await wave.scrollIntoViewIfNeeded();const box=await wave.boundingBox(),before=await page.evaluate(()=>window.qa.state().lanes[0].start);await page.mouse.move(box.x+2,box.y+10);await page.mouse.down();await page.mouse.move(box.x+box.width*.2,box.y+10);await page.mouse.up();assert((await page.evaluate(()=>window.qa.state().lanes[0].start))>.15);await page.locator('#undoButton').click();assert.equal(await page.evaluate(()=>window.qa.state().lanes[0].start),before);await wave.focus();await page.keyboard.press('ArrowRight');assert((await page.evaluate(()=>window.qa.state().lanes[0].start))>before);await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>window.qa.state().lanes[0].start),0);
    await page.locator('#sampleBrowserButton').click();await page.selectOption('#categoryFilter','all');await page.fill('#sampleSearch','snare');assert((await page.locator('.sample-item').count())>0);const dialog=await page.evaluate(()=>{const d=document.getElementById('sampleDialog');return {client:d.clientWidth,scroll:d.scrollWidth,width:innerWidth,rect:d.getBoundingClientRect().toJSON()};});assert(dialog.scroll<=dialog.client+1&&dialog.rect.right<=width+1&&dialog.rect.left>=-1);await page.screenshot({path:path.join(artifacts,'BATTER-cupboard-'+width+'.png')});await page.locator('#closeSampleDialog').click();await page.locator('#helpButton').click();await page.locator('.sample-credits summary').click();const help=await page.locator('#helpDialog').innerText();assert.match(help,/AVL|Glen MacArthur/);assert.match(help,/no separate|plain CC BY-SA/);await page.keyboard.press('Escape');assert.equal(await page.locator('#helpDialog').evaluate(d=>d.open),false);if(width===1440){await page.locator('#playButton').click();await page.waitForFunction(()=>window.qa.engine.playing);await sleep(700);await page.locator('#playButton').click();await page.waitForFunction(()=>!window.qa.engine.playing);const paused=await page.evaluate(()=>window.qa.engine.getMeters().beat);assert(paused>1);await page.locator('#playButton').click();await page.waitForFunction(()=>window.qa.engine.playing);await sleep(60);assert((await page.evaluate(()=>window.qa.engine.getMeters().beat))>=paused-.1,'Play resumes the paused recipe position.');await page.locator('#stopButton').click();await page.locator('#playButton').click();await page.waitForFunction(()=>window.qa.engine.playing);await sleep(60);assert((await page.evaluate(()=>window.qa.engine.getMeters().beat))<.5,'Stop starts the next service at the beginning.');await page.locator('#panicButton').click();passed.push('Actual Pause preserves needle position / Play resumes / Stop resets to beginning');}assert.deepEqual(errors,[]);passed.push(width+'px responsive main/cupboard / loaded fonts / waveform drag + Undo + keyboard / search / license help / Escape');
  }finally{await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}}
}

async function exchangeChecks(browser,url){
  const page=await browser.newPage();try{
    await prepare(page,url+'/batter/index.html');await page.waitForFunction(()=>!!window.MusicLabPatternInstrument&&!!window.BatterApp&&!!window.MusicLabExchange);const contract=await page.evaluate(()=>({pattern:Object.keys(window.MusicLabPatternInstrument),audio:Object.keys(window.BatterApp)}));measurements.push({contracts:contract});
    // Adapter details are intentionally read through the public contract. This
    // catches changes to the shared packet schema without bypassing rendering.
    const result=await page.evaluate(async()=>{const a=window.MusicLabPatternInstrument;const packet=await a.capturePattern({name:'Uneven test service'});return {packet,voices:a.notes.voices};});assert.equal(result.packet.format,'musiclab-pattern');assert.equal(result.packet.sourceApp,'batter');assert(result.packet.notes.length>10&&result.packet.voices.length===12);assert(result.packet.notes.some(n=>Math.abs(n.beat*4-Math.round(n.beat*4))>.0001),'Captured swung/microtimed hits preserve off-grid times.');passed.push('Native Kitchen rhythm capture preserves real off-grid acoustic sequencing and all twelve voice identities');
    const exact=await page.evaluate(async()=>{const S=window.MusicLabPatternSchema,a=window.MusicLabPatternInstrument,q=window.qa;const packet=S.normalize({format:'musiclab-pattern',version:1,sourceApp:'grain',kind:'drums',name:'Unquantized shared drums',tempo:240,swing:0,lengthBeats:2,meter:[4,4],voices:[{id:'tap',name:'Foreign tap',pitch:37}],notes:[{id:'off-grid',voice:'tap',pitch:37,beat:.127123,duration:.083713,velocity:.713,probability:1},{id:'longer',voice:'tap',pitch:40,beat:.51117,duration:.13723,velocity:.49,probability:.6}],seed:413});let replaceError;try{await a.importPattern({pattern:packet,options:{voiceMap:{tap:'snare'}}});}catch(error){replaceError=error.message;}await a.importPattern({pattern:packet,options:{voiceMap:{tap:'snare'},replace:true}});const captured=a.capturePattern(),score=window.BatterSchema.compile(q.state()),render=await a.renderPattern({pattern:captured,tempo:240,tailSeconds:0});const audio=await q.audio(render.blob);let first=-1;for(let i=0;i<audio.frames;i++)if(Math.abs(audio.left[i])+Math.abs(audio.right[i])>1/32768){first=i;break;}const before=JSON.stringify(q.state());let mapError;try{await a.importPattern({pattern:packet,options:{voiceMap:{tap:'missing'},replace:true}});}catch(error){mapError=error.message;}const same=JSON.stringify(q.state())===before;return {packet,captured,score:score.events,replaceError,mapError,same,first,rate:audio.rate,stats:q.stats(audio)};});
    assert.match(exact.replaceError,/Confirm|replace/i);assert.match(exact.mapError,/destination|voice|drum/i);assert(exact.same);for(let i=0;i<exact.packet.notes.length;i++){const a=exact.packet.notes[i],b=exact.captured.notes[i];for(const key of ['beat','duration','velocity','probability','pitch'])assert.equal(b[key],a[key],'Shared rhythm preserves exact '+key);assert.equal(b.voice,'snare');}assert(exact.score.some(e=>Math.abs(e.beat-.127123)<1e-12));assert(exact.first>=Math.floor(.127123*.25*48000)&&exact.first<Math.ceil(.127123*.25*48000)+100);assert(exact.stats.rmsL>.001);passed.push('Shared pattern explicit mapping/replacement / exact off-grid beat, duration, pitch, velocity and chance / real timed audio / invalid mapping atomic');
    const audio=await page.evaluate(async()=>{const q=window.qa,app=window.BatterApp,shared=window.MusicLabExchange,originalSample=q.state().lanes[8].sampleId,frames=2205,pcm=new Float32Array(frames*2);for(let i=0;i<frames;i++){pcm[i*2]=.2*Math.sin(i*.12);pcm[i*2+1]=.13*Math.cos(i*.21);}const packet=shared.packetFromAudio({pcm,sampleRate:22050,name:'Cross-app acoustic ingredient',sourceApp:'spool'}),decoded=shared.audioFromPacket(packet);const interleaved=new Float32Array(frames*2);for(let i=0;i<frames;i++){interleaved[i*2]=decoded.pcm[0][i];interleaved[i*2+1]=decoded.pcm[1][i];}let guarded;try{await app.importAudio({pcm:interleaved,sampleRate:22050,name:packet.name,options:{target:'tomMid'}});}catch(error){guarded=error.message;}await app.importAudio({pcm:interleaved,sampleRate:22050,name:packet.name,options:{target:'tomMid',replace:true}});const source=await app.exportAudio({scope:'source',laneId:'tomMid'}),saved=await shared.save({...source,sourceApp:'batter'}),read=await shared.get(saved.id);let difference=0;for(let i=0;i<frames;i++){difference=Math.max(difference,Math.abs(source.pcm[i*2]-interleaved[i*2]),Math.abs(source.pcm[i*2+1]-interleaved[i*2+1]),Math.abs(read.pcm[0][i]-source.pcm[i*2]),Math.abs(read.pcm[1][i]-source.pcm[i*2+1]));}return {guarded,originalSample,rate:source.sampleRate,frames:source.pcm.length/2,difference,saved:saved.name,targets:app.audioImport.targets.length};});
    assert.match(audio.guarded,/Confirm|replace/i);assert.equal(audio.rate,22050);assert.equal(audio.frames,2205);assert(audio.difference<=2/32768);assert.equal(audio.targets,12);assert.equal(audio.saved,'Cross-app acoustic ingredient');passed.push('Actual shared sample packet / explicit lane replacement / stereo and original-rate source export / IndexedDB shared cupboard roundtrip');
    await page.locator('#undoButton').click();assert.equal(await page.evaluate(()=>window.qa.state().lanes[8].sampleId),audio.originalSample);await page.locator('#redoButton').click();assert.equal(await page.evaluate(()=>window.qa.engine.metadata.get(window.qa.state().lanes[8].sampleId).name),'Cross-app acoustic ingredient');
    const invalid=await page.evaluate(async()=>{const e=window.qa.engine,before=JSON.stringify(e.getState()),results=[];for(const payload of [{pcm:new Float32Array([NaN,.2]),sampleRate:22050,name:'Invalid'},{pcm:new Float32Array([.1,.2]),sampleRate:22050,name:'Cancelled',signal:AbortSignal.abort()}]){try{await window.BatterApp.importAudio({...payload,options:{target:'tomHigh',replace:true}});results.push({error:null});}catch(error){results.push({error:error.message,same:JSON.stringify(e.getState())===before});}}return results;});assert.match(invalid[0].error,/finite|invalid/i);assert.match(invalid[1].error,/cancel/i);assert(invalid.every(r=>r.same));
    await page.locator('[data-musiclab-exchange="batter"]').click();await page.locator('.ml-ex-sample').filter({hasText:'Cross-app acoustic ingredient'}).click();await page.selectOption('.ml-ex-dialog [name="target"]','tomHigh');const old=await page.evaluate(()=>window.qa.state().lanes[9].sampleId);await page.locator('.ml-ex-dialog [data-action="receive"]').click();assert.match(await page.locator('.ml-ex-status').textContent(),/Confirm replacement/i);assert.equal(await page.evaluate(()=>window.qa.state().lanes[9].sampleId),old);await page.locator('.ml-ex-dialog [name="replace"]').check();await page.locator('.ml-ex-dialog [data-action="receive"]').click();await page.waitForFunction(()=>window.qa.engine.metadata.get(window.qa.state().lanes[9].sampleId)?.name==='Cross-app acoustic ingredient');await page.locator('.ml-ex-dialog [data-action="close"]').click();await page.locator('#undoButton').click();assert.equal(await page.evaluate(()=>window.qa.state().lanes[9].sampleId),old);await page.locator('#redoButton').click();assert.equal(await page.evaluate(()=>window.qa.engine.metadata.get(window.qa.state().lanes[9].sampleId).name),'Cross-app acoustic ingredient');passed.push('Shared sample Receive pane confirms destination replacement / external import Undo–Redo / nonfinite PCM and cancelled transfer retain every sample');
    const beforeCancel=await page.evaluate(()=>JSON.stringify(window.qa.state()));await page.locator('[data-musiclab-exchange="batter"]').click();await page.locator('.ml-ex-sample').filter({hasText:'Cross-app acoustic ingredient'}).click();await page.selectOption('.ml-ex-dialog [name="target"]','percussion');await page.locator('.ml-ex-dialog [name="replace"]').check();await page.evaluate(()=>{const e=window.qa.engine;window.qaNativeImport=e.importAudio.bind(e);e.importAudio=async(...args)=>{await new Promise(resolve=>window.qaReleaseImport=resolve);return window.qaNativeImport(...args);};});await page.locator('.ml-ex-dialog [data-action="receive"]').click();await page.waitForFunction(()=>!!window.qaReleaseImport);await page.locator('.ml-ex-dialog [data-action="close"]').click();await page.evaluate(()=>window.qaReleaseImport());await sleep(80);assert.equal(await page.evaluate(()=>JSON.stringify(window.qa.state())),beforeCancel);await page.evaluate(()=>window.qa.engine.importAudio=window.qaNativeImport);passed.push('Closing the actual shared-sample pane aborts pending native transfer without a late sample replacement');


  }finally{await page.evaluate(()=>window.qa?.engine.dispose()).catch(()=>{});await page.close();}
}

(async()=>{fs.mkdirSync(artifacts,{recursive:true});const server=await serve();let browser;try{
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
  const filter=new Set((process.env.BATTER_QA_GROUPS||'factory,sequence,imports,library,ui,exchange').split(','));
  if(filter.has('factory'))await factoryAndRenderChecks(browser,server);if(filter.has('sequence'))await sequencingChecks(browser,server.url);if(filter.has('imports'))await importAndProjectChecks(browser,server.url);if(filter.has('library')){if(fs.existsSync(path.join(source,'samples','kit-iron-service.json')))await libraryChecks(browser,server.url);else skipped.push('Optional acoustic bundles are not included in the compact source archive; acquire them with samples/tools/acquire.py to exercise online-download/offline-import and full-library cache checks.');}if(filter.has('ui'))await uiChecks(browser,server.url);if(filter.has('exchange'))await exchangeChecks(browser,server.url);
  console.log(JSON.stringify({passed:passed.length,groups:passed,skipped,measurements,artifacts},null,2));
}catch(error){console.error(JSON.stringify({passed:passed.length,groups:passed,artifacts,error:error.stack},null,2));process.exitCode=1;}finally{if(browser)await browser.close();await server.close();}})();
