/* BATTER · sampled acoustic drums, precise recipes, and portable ingredients. */
(function (root) {
  'use strict';
  const VERSION = '1.1.0', MAX_BYTES = 64 * 1024 * 1024, MAX_SECONDS = 120;
  const LANE_IDS = ['kick','snare','rim','closedHat','openHat','ride','crash','tomLow','tomMid','tomHigh','clap','percussion'];
  const LANE_NAMES = ['Kick','Snare','Rim / sidestick','Closed hat','Open hat','Ride','Crash','Low tom','Mid tom','High tom','Clap','Percussion'];
  const CONDITIONS = ['always','fill','notFill','first','notFirst','every2','every3','every4'];
  const LFO_DIVISIONS={'1/16':.25,'1/8':.5,'1/8T':1/3,'1/4':1,'1/2':2,'1/1':4,'2/1':8};
  const copy = value => JSON.parse(JSON.stringify(value));
  const number = (value,min,max,fallback) => typeof value === 'number' && Number.isFinite(value) ? Math.max(min,Math.min(max,value)) : fallback;
  const integer = (value,min,max,fallback) => Math.round(number(value,min,max,fallback));
  const text = (value,fallback,length=90) => typeof value === 'string' ? value.replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,length) || fallback : fallback;
  const choice = (value,values,fallback) => values.includes(value) ? value : fallback;
  const mod = (a,b) => ((a % b) + b) % b;
  const floatArray = value => Object.prototype.toString.call(value)==='[object Float32Array]';
  function sampleMetadata(raw={}) {const result={};for(const [key,max] of [['kit',180],['articulation',180],['attribution',6000],['licenseUrl',500],['licenseNotes',6000],['modifications',2000],['originalPath',500],['sourceRevision',80],['author',180],['origin',180]])if(typeof raw[key]==='string')result[key]=text(raw[key],'',max);if(typeof raw.musicLicenseException==='boolean')result.musicLicenseException=raw.musicLicenseException;for(const [key,max] of [['velocityRange',1],['originalVelocityRange',127]])if(Array.isArray(raw[key])&&raw[key].length===2&&raw[key].every(v=>typeof v==='number'&&Number.isFinite(v)))result[key]=raw[key].map(v=>number(v,0,max,0));return result;}
  const aborted = signal => { if (signal?.aborted) throw new DOMException('BATTER operation cancelled.','AbortError'); };
  function step(on=false,velocity=.8) { return {on,velocity,probability:1,pitch:0,reverse:null,sampleId:'',micro:0,ratchet:1,ratchetDecay:.2,flam:0,condition:'always',gate:0,protect:false,locks:{}}; }
  function blend(raw={}) {const sampleIds=Array.isArray(raw.sampleIds)?[...new Set(raw.sampleIds.filter(s=>typeof s==='string'&&s.length<180))].slice(0,128):[],sampleId=text(raw.sampleId,'',180);if(sampleId&&!sampleIds.includes(sampleId))sampleIds.unshift(sampleId);return {enabled:!!raw.enabled,amount:number(raw.amount,0,1,.5),sampleId:sampleId||sampleIds[0]||'',sampleIds,layerMode:choice(raw.layerMode,['single','velocity','roundrobin','random'],'velocity'),tune:number(raw.tune,-24,24,0),fine:number(raw.fine,-100,100,0),level:number(raw.level,0,2,1),offset:number(raw.offset,0,1,0),reverse:!!raw.reverse};}
  function lfo(raw={}) {return {enabled:!!raw.enabled,shape:choice(raw.shape,['sine','triangle','square','saw','random'],'sine'),sync:choice(raw.sync,['free',...Object.keys(LFO_DIVISIONS)],'free'),rate:number(raw.rate,.03,30,1),depth:number(raw.depth,0,1,.25),phase:number(raw.phase,0,1,0),reset:choice(raw.reset,['hit','continuous'],'hit'),target:choice(raw.target,['pitch','lowpass','pan','level','blend'],'pitch')};}
  function lane(id,index) { return {id,name:LANE_NAMES[index],sampleId:'',sampleIds:[],layerMode:'velocity',volume:id==='kick'?.88:id==='snare'?.76:.6,pan:0,mute:false,solo:false,tune:0,fine:0,reverse:false,start:0,end:1,attack:.001,decay:.2,sustain:1,release:.02,gate:8,highpass:20,lowpass:20000,resonance:.707,drive:0,bits:16,decimate:1,transient:0,body:0,room:.12,delay:0,choke:['closedHat','openHat'].includes(id)?1:0,blend:blend(),lfo:lfo()}; }
  function defaultState() {
    const patterns = Array.from({length:8},(_,bank) => ({id:String.fromCharCode(65+bank),name:bank?'Prep '+String.fromCharCode(65+bank):'First service',length:16,lanes:LANE_IDS.map((id,index) => ({id,length:16,rotation:0,steps:Array.from({length:64},(_,i)=>step(bank===0&&i<16&&((index===0&&[0,6,10].includes(i))||(index===1&&[4,12].includes(i))||(index===3&&i%2===0)),index===3?.58:.86))}))}));
    return {version:VERSION,name:'The uneven service',tempo:136,swing:.08,humanize:0,velocityHumanize:.035,seed:871223,selectedPattern:'A',chainEnabled:false,chain:['A','A','B','A'],fill:false,patterns,lanes:LANE_IDS.map(lane),master:{volume:.76,roomSize:.35,delayDivision:'1/8',delayFeedback:.28,delayTone:4800},assets:[]};
  }
  function normalize(raw={}) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('BATTER needs an instrument object.');
    const d=defaultState(),ids=d.patterns.map(p=>p.id),master=raw.master||{};
    const state={version:VERSION,name:text(raw.name,d.name),tempo:number(raw.tempo,30,300,d.tempo),swing:number(raw.swing,0,.65,d.swing),humanize:number(raw.humanize,0,30,0),velocityHumanize:number(raw.velocityHumanize,0,.5,d.velocityHumanize),seed:integer(raw.seed,1,0xffffffff,d.seed),selectedPattern:choice(raw.selectedPattern,ids,'A'),chainEnabled:!!raw.chainEnabled,chain:Array.isArray(raw.chain)?raw.chain.slice(0,64).map(id=>choice(id,ids,'A')):d.chain,fill:!!raw.fill,patterns:[],lanes:[],master:{volume:number(master.volume,0,1.5,.76),roomSize:number(master.roomSize,0,1,.35),delayDivision:choice(master.delayDivision,['1/16','1/8','1/8T','1/4','3/8','1/2'],'1/8'),delayFeedback:number(master.delayFeedback,0,.86,.28),delayTone:number(master.delayTone,200,16000,4800)},assets:[]};
    if(!state.chain.length)state.chain=['A'];
    for(let index=0;index<12;index++) {
      const id=LANE_IDS[index],v=raw.lanes?.find?.(l=>l.id===id)||raw.lanes?.[index]||{},x=d.lanes[index];
      const sampleIds=Array.isArray(v.sampleIds)?[...new Set(v.sampleIds.filter(s=>typeof s==='string'&&s.length<180))].slice(0,128):[];
      const sampleId=text(v.sampleId,'',180);if(sampleId&&!sampleIds.includes(sampleId))sampleIds.unshift(sampleId);
      state.lanes.push({id,name:text(v.name,x.name),sampleId:sampleId||sampleIds[0]||'',sampleIds,layerMode:choice(v.layerMode,['single','velocity','roundrobin','random'],'velocity'),volume:number(v.volume,0,1.5,x.volume),pan:number(v.pan,-1,1,0),mute:!!v.mute,solo:!!v.solo,protect:!!v.protect,normalize:!!v.normalize,tune:number(v.tune,-24,24,0),fine:number(v.fine,-100,100,0),reverse:!!v.reverse,start:number(v.start,0,.9999,0),end:number(v.end,.0001,1,1),attack:number(v.attack,0,1,.001),decay:number(v.decay,.001,6,.2),sustain:number(v.sustain,0,1,1),release:number(v.release,.001,5,.02),gate:number(v.gate,.01,12,8),highpass:number(v.highpass,20,8000,20),lowpass:number(v.lowpass,40,22000,20000),resonance:number(v.resonance,.1,20,.707),drive:number(v.drive,0,1,0),bits:integer(v.bits,4,16,16),decimate:integer(v.decimate,1,32,1),transient:number(v.transient,-1,1,0),body:number(v.body,-1,1,0),room:number(v.room,0,1,.12),delay:number(v.delay,0,1,0),choke:integer(v.choke,0,8,x.choke)});
      const last=state.lanes.at(-1);last.blend=blend(v.blend);last.lfo=lfo(v.lfo);if(last.end<=last.start)last.end=Math.min(1,last.start+.0001);
    }
    for(let bank=0;bank<8;bank++) {
      const id=ids[bank],p=raw.patterns?.find?.(p=>p.id===id)||raw.patterns?.[bank]||{},def=d.patterns[bank],length=choice(p.length,[16,32,64],16);
      state.patterns.push({id,name:text(p.name,def.name),length,lanes:LANE_IDS.map((laneId,index)=>{
        const l=p.lanes?.find?.(l=>l.id===laneId)||p.lanes?.[index]||{};
        return {id:laneId,length:integer(l.length,1,64,length),rotation:integer(l.rotation,-63,63,0),steps:Array.from({length:64},(_,i)=>{
          const v=l.steps?.[i]||{},x=def.lanes[index].steps[i],locks={};for(const [key,min,max] of [['volume',0,1.5],['pan',-1,1],['highpass',20,8000],['lowpass',40,22000],['drive',0,1],['start',0,.9999],['end',.0001,1],['blend',0,1]])if(typeof v.locks?.[key]==='number'&&Number.isFinite(v.locks[key]))locks[key]=number(v.locks[key],min,max,min);return {on:typeof v.on==='boolean'?v.on:x.on,velocity:number(v.velocity,0,1,x.velocity),probability:number(v.probability,0,1,1),pitch:number(v.pitch,-24,24,0),reverse:typeof v.reverse==='boolean'?v.reverse:null,sampleId:text(v.sampleId,'',180),micro:number(v.micro,-60,60,0),ratchet:integer(v.ratchet,1,8,1),ratchetDecay:number(v.ratchetDecay,0,.95,.2),flam:number(v.flam,0,45,0),condition:choice(v.condition,CONDITIONS,'always'),gate:number(v.gate,0,16,0),protect:!!v.protect,locks};
        })};
      })});
    }
    if(raw.assets!==undefined&&!Array.isArray(raw.assets))throw new Error('The sample cupboard must be an array.');
    if((raw.assets?.length||0)>256)throw new Error('BATTER holds up to 256 imported or portable samples.');
    let decodedBytes=0;const seen=new Set();
    for(const a of raw.assets||[]) {
      if(!a||typeof a!=='object'||typeof a.id!=='string'||!a.id||seen.has(a.id))throw new Error('Every sample needs a unique ID.');
      if(!Number.isInteger(a.frames)||a.frames<1||!Number.isInteger(a.sampleRate)||a.sampleRate<8000||a.sampleRate>192000||![1,2].includes(a.channels)||typeof a.pcm!=='string'||a.pcm.length!==Math.ceil(a.frames*a.channels*2/3)*4||!/^[A-Za-z0-9+/]*={0,2}$/.test(a.pcm))throw new Error('A portable sample has invalid PCM data.');
      if(a.frames/a.sampleRate>MAX_SECONDS)throw new Error('An individual sample can be at most 120 seconds.');
      decodedBytes+=a.frames*a.channels*4;if(decodedBytes>MAX_BYTES)throw new Error('BATTER’s decoded sample cupboard is limited to 64 MB.');
      seen.add(a.id);state.assets.push({id:a.id.slice(0,180),name:text(a.name,'Imported ingredient'),sampleRate:a.sampleRate,channels:a.channels,frames:a.frames,pcm:a.pcm,velocity:number(a.velocity,0,1,1),roundRobin:integer(a.roundRobin,0,128,0),type:text(a.type,'percussion'),license:text(a.license,'User supplied'),source:text(a.source,'',500),...sampleMetadata(a)});
    }
    if(typeof raw.kitId==='string')state.kitId=text(raw.kitId,'',180);if(typeof raw.kitName==='string')state.kitName=text(raw.kitName,'',180);
    if(raw.musicLabPattern!==undefined){if(!root.MusicLabPatternSchema)throw new Error('The shared pattern schema is unavailable.');const overlay=raw.musicLabPattern,pattern=root.MusicLabPatternSchema.parse(overlay?.pattern),voiceMap={};if(!overlay?.voiceMap||typeof overlay.voiceMap!=='object'||Array.isArray(overlay.voiceMap))throw new Error('Map every imported voice to a drum lane.');for(const voice of pattern.voices){const id=overlay.voiceMap[voice.id];if(!LANE_IDS.includes(id))throw new Error('Choose a BATTER drum lane for every imported voice.');voiceMap[voice.id]=id;}if(Object.keys(overlay.voiceMap).some(id=>!pattern.voices.some(v=>v.id===id)))throw new Error('The imported pattern has an unknown source voice.');for(const note of pattern.notes){const index=LANE_IDS.indexOf(voiceMap[note.voice]);if(Math.abs(note.pitch-(36+index))>24)throw new Error('BATTER supports two octaves of transposition from each drum lane.');}state.musicLabPattern={pattern,voiceMap};}
    return state;
  }
  function random(seed) { let x=seed>>>0||1;return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296;}; }
  function hash(seed,...values) {let x=seed>>>0;for(const value of values){x^=value>>>0;x=Math.imul(x^x>>>16,0x45d9f3b);x=Math.imul(x^x>>>16,0x45d9f3b);x^=x>>>16;}return x>>>0||1;}
  function blendWeights(amount) {const at=number(amount,0,1,.5);return {a:at>=1?0:Math.cos(at*Math.PI/2),b:at<=0?0:Math.sin(at*Math.PI/2)};}
  function lfoRate(patch,tempo) {return patch.sync==='free'?patch.rate:tempo/60/LFO_DIVISIONS[patch.sync];}
  function lfoValue(patch,seconds,{tempo=120,beat=0,seed=1}={}) {const rate=lfoRate(patch,tempo),cycles=patch.phase+seconds*rate+(patch.reset==='continuous'?beat*60/tempo*rate:0),phase=mod(cycles,1);if(patch.shape==='triangle')return 1-4*Math.abs(phase-.5);if(patch.shape==='square')return phase<.5?1:-1;if(patch.shape==='saw')return phase*2-1;if(patch.shape==='random')return random(hash(seed,Math.floor(cycles),319))()*2-1;return Math.sin(phase*Math.PI*2);}
  function modulationPlan(patch,duration,{tempo=120,beat=0,seed=1}={}) {const rate=lfoRate(patch,tempo),held=patch.shape==='square'||patch.shape==='random',plan=[];if(held){const granularity=patch.shape==='square'?.5:1,phase=patch.phase+(patch.reset==='continuous'?beat*60/tempo*rate:0);plan.push({time:0,value:lfoValue(patch,0,{tempo,beat,seed})});for(let cycle=Math.floor(phase/granularity)+1;cycle*granularity<phase+duration*rate-1e-10;cycle++){const time=(cycle*granularity-phase)/rate;plan.push({time,value:lfoValue(patch,time+1e-9,{tempo,beat,seed})});}return {held:true,points:plan};}const count=Math.max(2,Math.ceil(duration*Math.max(240,rate*32))+1);for(let i=0;i<count;i++){const time=duration*i/(count-1);plan.push({time,value:lfoValue(patch,time,{tempo,beat,seed})});}return {held:false,points:plan};}
  function patternOrder(state,scope='auto') {return (scope==='chain'||scope==='auto'&&state.chainEnabled)?state.chain:[state.selectedPattern];}
  function patternSpan(raw,scope='auto') {const state=normalize(raw);if(state.musicLabPattern&&scope!=='native')return state.musicLabPattern.pattern.lengthBeats;return patternOrder(state,scope).reduce((sum,id)=>sum+state.patterns.find(p=>p.id===id).length/4,0);}
  function conditionFires(condition,iteration,fill) {return condition==='always'||condition==='fill'&&fill||condition==='notFill'&&!fill||condition==='first'&&iteration===0||condition==='notFirst'&&iteration!==0||/^every[234]$/.test(condition)&&iteration%Number(condition.slice(-1))===0;}
  function compile(raw,{cycles=1,cycleIndex=0,scope='auto',lengthBeats=null,laneId=null,roundRobinOffsets=null}={}) {
    const state=normalize(raw);if(state.musicLabPattern&&scope!=='native')return compileOverlay(state,{cycles,cycleIndex,lengthBeats,laneId,roundRobinOffsets});const order=patternOrder(state,scope),span=order.reduce((sum,id)=>sum+state.patterns.find(p=>p.id===id).length/4,0),secondsPerBeat=60/state.tempo,hitOrdinals=Array.from({length:12},(_,i)=>integer(roundRobinOffsets?.[i],0,0x7fffffff,cycleIndex*257));
    cycles=integer(cycles,1,256,1);cycleIndex=integer(cycleIndex,0,0xffffff,0);const wanted=lengthBeats===null?span*cycles:number(lengthBeats,.25,2048,span),events=[],steps=[];let serial=0;
    for(let cycle=0;cycle<Math.ceil(wanted/span);cycle++) {
      let offset=cycle*span;
      for(let slot=0;slot<order.length;slot++) {
        const pattern=state.patterns.find(p=>p.id===order[slot]),count=pattern.length,patternBeat=offset;
        for(let i=0;i<count;i++) {
          const straight=offset+i/4;if(straight>=wanted-1e-9)break;
          const swung=straight+(i%2?state.swing/8:0);steps.push({beat:swung,step:i,pattern:pattern.id});
          for(let laneIndex=0;laneIndex<12;laneIndex++) {
            const l=state.lanes[laneIndex],sequence=pattern.lanes[laneIndex];if(laneId&&l.id!==laneId)continue;
            const absolute=Math.round(cycleIndex*span*4+offset*4+i),position=mod(absolute-sequence.rotation,sequence.length),s=sequence.steps[position],iteration=Math.floor(absolute/sequence.length);
            if(!s.on||s.velocity<=0||s.probability<=0||!conditionFires(s.condition,iteration,state.fill))continue;
            const rng=random(hash(state.seed,cycleIndex+cycle,slot,laneIndex,i));if(rng()>=s.probability)continue;
            const velocity=number(s.velocity+(rng()*2-1)*state.velocityHumanize,0,1,s.velocity),jitter=(rng()*2-1)*state.humanize/1000/secondsPerBeat,micro=s.micro/1000/secondsPerBeat;
            const origin=swung+jitter+micro;
            for(let ratchet=0;ratchet<s.ratchet;ratchet++) {
              const beat=Math.max(cycleIndex===0?0:-.5,origin+ratchet*.25/s.ratchet);if(beat>=wanted)continue;
              const event={id:'batter-'+serial++,laneId:l.id,laneIndex,patternId:pattern.id,step:position,beat,velocity:velocity*Math.pow(1-s.ratchetDecay,ratchet),pitch:s.pitch,reverse:s.reverse,sampleId:s.sampleId,gate:s.gate,locks:s.locks,seed:hash(state.seed,cycleIndex+cycle,slot,laneIndex,i,ratchet),roundRobin:hitOrdinals[laneIndex]++,ratchet};events.push(event);
              if(s.flam>0&&ratchet===0) {const flamBeat=beat+s.flam/1000/secondsPerBeat;if(flamBeat<wanted)events.push({...event,id:'batter-'+serial++,beat:flamBeat,velocity:velocity*.66,seed:hash(event.seed,9387),flam:true,roundRobin:hitOrdinals[laneIndex]++});}
            }
          }
        }
        offset=patternBeat+count/4;
      }
    }
    if(events.length>65536)throw new Error('The recipe produces too many hits. Reduce length or ratchets.');
    events.sort((a,b)=>a.beat-b.beat||a.laneIndex-b.laneIndex||a.id.localeCompare(b.id));const orderedCounts=Array.from({length:12},(_,i)=>integer(roundRobinOffsets?.[i],0,0x7fffffff,cycleIndex*257));for(const event of events)event.roundRobin=orderedCounts[event.laneIndex]++;steps.sort((a,b)=>a.beat-b.beat);return {events,steps,lengthBeats:wanted,cycleBeats:span,tempo:state.tempo,roundRobinCounts:orderedCounts};
  }
  function compileOverlay(state,{cycles=1,cycleIndex=0,lengthBeats=null,laneId=null}={}) {const packet=state.musicLabPattern.pattern,span=packet.lengthBeats,wanted=lengthBeats===null?span*integer(cycles,1,256,1):number(lengthBeats,.25,2048,span),events=[],steps=[];for(let cycle=0;cycle<Math.ceil(wanted/span);cycle++){const rng=random(hash(packet.seed??state.seed,cycleIndex+cycle));for(let step=0;step<Math.ceil(span*4);step++)if(cycle*span+step/4<wanted)steps.push({beat:cycle*span+step/4,step:step%64,pattern:state.selectedPattern});for(const note of packet.notes){const id=state.musicLabPattern.voiceMap[note.voice],index=LANE_IDS.indexOf(id),grid=Math.round(note.beat*4),swung=Math.abs(note.beat*4-grid)<1e-7&&grid%2,beat=Math.min(span-1e-8,note.beat+(swung?packet.swing/4:0))+cycle*span;if(rng()>=note.probability||note.velocity<=0||beat>=wanted||laneId&&id!==laneId)continue;events.push({id:note.id+'-'+cycle,laneId:id,laneIndex:index,patternId:state.selectedPattern,step:Math.floor(note.beat*4)%64,beat,velocity:note.velocity,pitch:note.pitch-(36+index),reverse:null,sampleId:'',duration:Math.min(note.duration,span-(beat-cycle*span))*60/state.tempo,seed:hash(packet.seed??state.seed,cycleIndex+cycle,index,events.length),roundRobin:(cycleIndex+cycle)*packet.notes.length+events.length,source:'native'});}}if(events.length>65536)throw new Error('This imported performance contains too many hits.');events.sort((a,b)=>a.beat-b.beat||a.laneIndex-b.laneIndex);return {events,steps,lengthBeats:wanted,cycleBeats:span,tempo:state.tempo};}
  function euclidean(length,pulses,rotation=0) {length=integer(length,1,64,16);pulses=integer(pulses,0,length,4);return Array.from({length},(_,i)=>pulses>0&&mod((i-rotation)*pulses,length)<pulses);}
  function mutate(raw,{amount=.2,density=.3,laneId=null,seed=null,preserveBackbeat=true}={}) {
    const state=normalize(raw),pattern=state.patterns.find(p=>p.id===state.selectedPattern),rng=random(seed??state.seed);amount=number(amount,0,1,.2);density=number(density,0,1,.3);
    for(const l of pattern.lanes)if((!laneId||l.id===laneId)&&!state.lanes.find(v=>v.id===l.id).protect)for(let i=0;i<l.length;i++) {
      const s=l.steps[i];if(s.protect||preserveBackbeat&&['kick','snare'].includes(l.id)&&i%8===4)continue;
      if(rng()<amount){s.on=rng()<density;if(s.on){s.velocity=.3+rng()*.65;s.ratchet=rng()<.18?2+Math.floor(rng()*3):1;s.probability=rng()<.18?.55+rng()*.4:1;s.micro=(rng()*2-1)*12;}}
    }
    state.seed=hash(state.seed,0x1773);return state;
  }
  function rollFill(raw,{laneId='snare',steps=4,ratchets=4}={}) {const state=normalize(raw),p=state.patterns.find(p=>p.id===state.selectedPattern),l=p.lanes.find(l=>l.id===laneId);if(!l)throw new Error('Choose a drum lane.');if(state.lanes.find(v=>v.id===laneId).protect)return state;const count=integer(steps,1,l.length,4);for(let i=l.length-count;i<l.length;i++)if(!l.steps[i].protect)l.steps[i]={...step(true,.48+(i-l.length+count)/count*.47),ratchet:integer(ratchets,1,8,4),ratchetDecay:.08,condition:'always'};return state;}
  function rotate(raw,laneId,amount=1) {const state=normalize(raw),l=state.patterns.find(p=>p.id===state.selectedPattern).lanes.find(l=>l.id===laneId);if(!l)throw new Error('Choose a drum lane.');if(state.lanes.find(v=>v.id===laneId).protect)return state;const editable=Array.from({length:l.length},(_,i)=>i).filter(i=>!l.steps[i].protect),steps=editable.map(i=>l.steps[i]);for(let i=0;i<editable.length;i++)l.steps[editable[mod(i+Math.round(amount),editable.length)]]=steps[i];return state;}
  function bytesFromBase64(value) {if(typeof Buffer!=='undefined')return new Uint8Array(Buffer.from(value,'base64'));const str=atob(value),bytes=new Uint8Array(str.length);for(let i=0;i<str.length;i++)bytes[i]=str.charCodeAt(i);return bytes;}
  function base64FromBytes(bytes) {if(typeof Buffer!=='undefined')return Buffer.from(bytes.buffer,bytes.byteOffset,bytes.byteLength).toString('base64');let result='';for(let i=0;i<bytes.length;i+=0x8000)result+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(result);}
  function decodeAsset(asset) {const bytes=bytesFromBase64(asset.pcm);if(bytes.length!==asset.frames*asset.channels*2)throw new Error('The sample’s decoded size does not match its header.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),left=new Float32Array(asset.frames),right=asset.channels===1?left:new Float32Array(asset.frames);for(let i=0;i<asset.frames;i++){left[i]=view.getInt16(i*asset.channels*2,true)/32768;if(asset.channels===2)right[i]=view.getInt16((i*2+1)*2,true)/32768;}return {left,right,sampleRate:asset.sampleRate,name:asset.name,channels:asset.channels};}
  function encodeAsset(audio,meta={}) {const sampleRate=integer(audio.sampleRate,8000,192000,44100),left=audio.left,right=audio.right||left;if(!floatArray(left)||!floatArray(right)||!left.length||left.length!==right.length)throw new Error('Audio needs equal, nonempty Float32 channels.');if(left.length/sampleRate>MAX_SECONDS)throw new Error('An individual sample can be at most 120 seconds.');let mono=audio.channels===1||left===right;const channels=mono?1:2,bytes=new Uint8Array(left.length*channels*2),view=new DataView(bytes.buffer);for(let i=0;i<left.length;i++)for(let c=0;c<channels;c++){const value=number(c?right[i]:left[i],-1,1,0);view.setInt16((i*channels+c)*2,Math.round(value<0?value*32768:value*32767),true);}return {id:meta.id||'ingredient-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:text(meta.name||audio.name,'Imported ingredient'),sampleRate,channels,frames:left.length,pcm:base64FromBytes(bytes),velocity:number(meta.velocity,0,1,1),roundRobin:integer(meta.roundRobin,0,128,0),type:text(meta.type,'percussion'),license:text(meta.license,'User supplied'),source:text(meta.source,'',500),...sampleMetadata(meta)};}
  function decodeWav(input) {
    const bytes=input instanceof Uint8Array?input:new Uint8Array(input),v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),str=(p,n)=>String.fromCharCode(...bytes.subarray(p,p+n));
    if(bytes.length<44||str(0,4)!=='RIFF'||str(8,4)!=='WAVE')throw new Error('This is not a PCM WAV file.');let format=0,channels=0,sampleRate=0,bits=0,blockAlign=0,data=null;
    for(let p=12;p+8<=bytes.length;){const size=v.getUint32(p+4,true),start=p+8;if(start+size>bytes.length)throw new Error('The WAV file is truncated.');if(str(p,4)==='fmt '&&size>=16){format=v.getUint16(start,true);channels=v.getUint16(start+2,true);sampleRate=v.getUint32(start+4,true);blockAlign=v.getUint16(start+12,true);bits=v.getUint16(start+14,true);if(format===0xfffe&&size>=40)format=v.getUint16(start+24,true);}if(str(p,4)==='data'&&!data)data={start,size};p=start+size+(size%2);}
    if(!data||![1,3].includes(format)||![1,2].includes(channels)||sampleRate<8000||sampleRate>192000||!([8,16,24,32].includes(bits))||format===3&&bits!==32||blockAlign!==channels*bits/8)throw new Error('This WAV format needs browser decoding.');
    const frames=Math.floor(data.size/blockAlign);if(!frames||frames/sampleRate>MAX_SECONDS)throw new Error('Choose nonempty audio no longer than 120 seconds.');if(frames*channels*4>MAX_BYTES)throw new Error('This decoded sample exceeds the 64 MB cupboard.');const left=new Float32Array(frames),right=channels===1?left:new Float32Array(frames),read=p=>{if(format===3)return number(v.getFloat32(p,true),-1,1,0);if(bits===8)return (v.getUint8(p)-128)/128;if(bits===16)return v.getInt16(p,true)/32768;if(bits===24){let n=v.getUint8(p)|(v.getUint8(p+1)<<8)|(v.getUint8(p+2)<<16);if(n&0x800000)n|=0xff000000;return n/8388608;}return v.getInt32(p,true)/2147483648;};for(let i=0;i<frames;i++){const p=data.start+i*blockAlign;left[i]=read(p);if(channels===2)right[i]=read(p+bits/8);}return {left,right,sampleRate,channels};
  }
  function processSample(audio,patch,reverse=false) {
    const begin=Math.min(audio.left.length-1,Math.floor(patch.start*audio.left.length)),end=Math.max(begin+1,Math.min(audio.left.length,Math.ceil(patch.end*audio.left.length))),frames=end-begin,left=new Float32Array(frames),right=new Float32Array(frames),levels=Math.pow(2,patch.bits-1),drive=1+patch.drive*15,normalizer=Math.tanh(drive),edge=Math.max(1,Math.min(Math.round(audio.sampleRate*.0007),Math.floor(frames/4)));let heldL=0,heldR=0;
    for(let i=0;i<frames;i++) {
      const from=reverse?end-1-i:begin+i,t=i/audio.sampleRate,transient=Math.exp(-t/.014),shape=Math.exp(patch.transient*1.45*transient+patch.body*.85*(1-transient)),fade=Math.min(1,i/edge,(frames-1-i)/edge);
      if(i%patch.decimate===0) {heldL=audio.left[from]*shape;heldR=audio.right[from]*shape;if(patch.drive){heldL=Math.tanh(heldL*drive)/normalizer;heldR=Math.tanh(heldR*drive)/normalizer;}if(patch.bits<16){heldL=Math.round(heldL*levels)/levels;heldR=Math.round(heldR*levels)/levels;}}
      left[i]=heldL*fade;right[i]=heldR*fade;
    }
    if(patch.normalize){let peak=0;for(let i=0;i<frames;i++)peak=Math.max(peak,Math.abs(left[i]),Math.abs(right[i]));if(peak>1e-6){const gain=.95/peak;for(let i=0;i<frames;i++){left[i]*=gain;right[i]*=gain;}}}return {left,right,sampleRate:audio.sampleRate,name:audio.name,channels:audio.channels};
  }
  function wav(audio) {const left=audio.left,right=audio.right||left,sampleRate=audio.sampleRate,frames=left.length,bytes=new ArrayBuffer(44+frames*4),view=new DataView(bytes),put=(p,s)=>{for(let i=0;i<s.length;i++)view.setUint8(p+i,s.charCodeAt(i));};put(0,'RIFF');view.setUint32(4,36+frames*4,true);put(8,'WAVE');put(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*4,true);view.setUint16(32,4,true);view.setUint16(34,16,true);put(36,'data');view.setUint32(40,frames*4,true);for(let i=0;i<frames;i++)for(let channel=0;channel<2;channel++){const value=number(channel?right[i]:left[i],-1,1,0);view.setInt16(44+(i*2+channel)*2,Math.round(value<0?value*32768:value*32767),true);}return new Blob([bytes],{type:'audio/wav'});}
  const Schema={VERSION,MAX_BYTES,MAX_SECONDS,LANE_IDS,LANE_NAMES,CONDITIONS,LFO_DIVISIONS,copy,step,lane,blend,lfo,blendWeights,lfoRate,lfoValue,modulationPlan,defaultState,normalize,random,hash,patternSpan,compile,euclidean,mutate,rollFill,rotate,decodeWav,decodeAsset,encodeAsset,processSample,wav};
  class Engine {
    constructor(state) {this.library={samples:[],kits:[],bundles:[]};this.metadata=new Map();this.factoryIds=new Set();this.audio=new Map();this.processed=new Map();this.loading=new Map();this.loadedBundles=new Set();this.context=null;this.graph=null;this.initializing=null;this.playing=false;this.timer=null;this.sources=new Set();this.generation=0;this.importing=false;this.exporting=false;this.disposed=false;this.previewSerial=0;this.state=normalize(state||defaultState());if(root.BatterLibrary){this.registerLibrary(root.BatterLibrary);for(const s of root.BatterLibrary.samples)this.factoryIds.add(s.id);}if(!state&&this.library.kits.length)this.applyKit(this.library.kits[0]);this.installAssets();this.onStatus=null;this.onStep=null;this.meters={playing:false,beat:0,step:-1,pattern:this.state.selectedPattern,peak:0};}
    registerLibrary(manifest) {if(!manifest||!Array.isArray(manifest.samples)||!Array.isArray(manifest.kits))throw new Error('This is not a BATTER sample library.');const known=new Set(this.library.samples.map(a=>a.id));for(const sample of manifest.samples){if(!sample||typeof sample.id!=='string'||!sample.id||sample.id.length>180||!sample.base64&&!sample.url)continue;if(!known.has(sample.id)){this.library.samples.push(sample);known.add(sample.id);}this.metadata.set(sample.id,sample);}for(const kit of manifest.kits)if(kit&&typeof kit.id==='string'){const index=this.library.kits.findIndex(k=>k.id===kit.id);if(index<0)this.library.kits.push(kit);else this.library.kits[index]=kit;}if(Array.isArray(manifest.bundles)&&manifest.bundles.length)this.library.bundles=manifest.bundles.slice(0,128);return this.library;}
    validateSampleBudget(state=this.state) {let bytes=0;const assets=new Map(state.assets.map(a=>[a.id,a]));for(const id of this.referencedIds(state)){const meta=assets.get(id)||this.metadata.get(id);if(meta?.frames&&meta?.channels)bytes+=meta.frames*meta.channels*4;}if(bytes>MAX_BYTES)throw new Error('The assigned sample layers exceed the 64 MB decoded cupboard. Choose fewer layers or shorter samples.');}
    installAssets() {const keep=this.referencedIds();this.validateSampleBudget();for(const asset of this.state.assets){this.metadata.set(asset.id,{...this.metadata.get(asset.id),...asset});if(keep.includes(asset.id)&&(!this.audio.has(asset.id)||this.audio.get(asset.id)._encoded!==asset.pcm)){const old=this.audio.get(asset.id);if(old)this.audio.delete(asset.id);const audio=decodeAsset(asset);this.reserveSampleSpace(this.audioBytes(audio),keep);audio._encoded=asset.pcm;this.audio.set(asset.id,audio);for(const key of this.processed.keys())if(JSON.parse(key)[0]===asset.id)this.processed.delete(key);}}}
    applyKit(kit) {for(let i=0;i<12;i++){const item=kit.lanes?.find(l=>l.type===LANE_IDS[i])||kit.lanes?.[i];if(!item)continue;const ids=(item.sampleIds||[item.sampleId]).filter(id=>this.metadata.has(id));this.state.lanes[i].sampleIds=ids;this.state.lanes[i].sampleId=ids.includes(item.sampleId)?item.sampleId:ids[0]||'';if(item.name)this.state.lanes[i].name=text(item.name,this.state.lanes[i].name);this.state.lanes[i].layerMode=ids.length>1?'velocity':'single';if(item.blend)this.state.lanes[i].blend=blend(item.blend);if(item.lfo)this.state.lanes[i].lfo=lfo(item.lfo);}this.state.kitId=kit.id;this.state.kitName=text(kit.name,kit.id,180);}
    referencedIds(state=this.state) {const ids=new Set();for(const l of state.lanes)for(const id of [...l.sampleIds,l.sampleId,...(l.blend?.sampleIds||[]),l.blend?.sampleId])if(id)ids.add(id);for(const p of state.patterns)for(const l of p.lanes)for(const s of l.steps)if(s.sampleId)ids.add(s.sampleId);return [...ids];}
    getState({portable=false}={}) {const state=copy({...this.state,assets:[]});state.assets=this.state.assets.map(a=>({...a}));if(portable){const existing=new Set(state.assets.map(a=>a.id));for(const id of this.referencedIds(state))if(!existing.has(id)&&!(portable==='external'&&this.factoryIds.has(id))){const audio=this.audio.get(id),meta=this.metadata.get(id);if(!audio)throw new Error('Load the selected kit before saving a portable project.');state.assets.push(encodeAsset(audio,{...meta,id}));existing.add(id);}normalize(state);}return state;}
    setState(value) {if(this.disposed)throw new Error('The BATTER engine has been closed.');const next=normalize(value),previous=this.state;this.validateSampleBudget(next);if(previous.musicLabPattern&&next.musicLabPattern&&(JSON.stringify(previous.patterns)!==JSON.stringify(next.patterns)||previous.selectedPattern!==next.selectedPattern||previous.chainEnabled!==next.chainEnabled||JSON.stringify(previous.chain)!==JSON.stringify(next.chain)))delete next.musicLabPattern;this.generation++;this.state=next;this.installAssets();if(this.graph)this.updateGraph(this.graph);if(this.playing)this.reschedule();return this.getState();}
    getCatalog() {return {samples:[...this.metadata.values()].map(({base64,pcm,...meta})=>({...meta,loaded:this.audio.has(meta.id)})),kits:this.library.kits.map(copy),bundles:this.library.bundles.map(copy),decodedBytes:this.sampleBytes(),maxBytes:MAX_BYTES};}
    importBundle(value) {const bundle=typeof value==='string'?JSON.parse(value):value;if(bundle?.format!=='kitchen-batter-library'||bundle.version!==1)throw new Error('Choose a Kitchen BATTER sample bundle.');if(bundle.samples?.length>2048)throw new Error('This sample bundle contains too many entries.');this.registerLibrary(bundle);if(bundle.id)this.loadedBundles.add(bundle.id);return this.getCatalog();}
    async loadLibrary(id,{signal}={}) {aborted(signal);if(this.loadedBundles.has(id))return this.getCatalog();const bundle=this.library.bundles.find(b=>b.id===id);if(!bundle)throw new Error('Choose an available sample bundle.');if(root.location?.protocol==='file:')throw new Error('Online sample bundles need the Kitchen website. Download a bundle there and use Import bundle here.');const response=await fetch(bundle.url,{signal});if(!response.ok)throw new Error('The sample bundle could not be downloaded ('+response.status+').');const length=Number(response.headers.get('Content-Length'));if(length>128*1024*1024)throw new Error('The sample bundle exceeds the 128 MB download limit.');const raw=await response.text();aborted(signal);if(raw.length>128*1024*1024)throw new Error('The sample bundle exceeds the 128 MB download limit.');const manifest=JSON.parse(raw);this.importBundle(manifest);this.loadedBundles.add(id);const requires=manifest.requires||bundle.requires||[];for(const sibling of requires)if(sibling!==id&&!this.loadedBundles.has(sibling))await this.loadLibrary(sibling,{signal});return this.getCatalog();}
    async init() {if(this.disposed)throw new Error('The BATTER engine has been closed.');if(this.initializing)return this.initializing;if(this.context){if(this.context.state==='suspended')await this.context.resume();return this.context;}this.initializing=(async()=>{const AC=root.AudioContext||root.webkitAudioContext;if(!AC)throw new Error('This browser does not support Web Audio.');const context=new AC({latencyHint:'interactive'});try{this.context=context;this.graph=this.createGraph(context);await context.resume();if(this.disposed){await context.close();throw new Error('The BATTER engine has been closed.');}return context;}catch(error){try{await context.close();}catch{}this.context=null;this.graph=null;throw error;}})();try{return await this.initializing;}finally{this.initializing=null;}}
    async decode(bytes,name='Imported ingredient') {try{return {...decodeWav(bytes),name};}catch(wavError){if(bytes.byteLength>MAX_BYTES)throw new Error('The audio file is too large.');await this.init();let buffer;try{buffer=await this.context.decodeAudioData(bytes.slice(0));}catch{throw new Error('This audio file could not be decoded. Choose WAV, AIFF, MP3, AAC or Ogg supported by your browser.');}if(!buffer.length||buffer.duration>MAX_SECONDS)throw new Error('Choose audio no longer than 120 seconds.');if(buffer.length*Math.min(2,buffer.numberOfChannels)*4>MAX_BYTES)throw new Error('This decoded sample exceeds the 64 MB cupboard.');const left=new Float32Array(buffer.getChannelData(0));return {left,right:buffer.numberOfChannels===1?left:new Float32Array(buffer.getChannelData(1)),sampleRate:buffer.sampleRate,channels:Math.min(2,buffer.numberOfChannels),name};}}
    audioBytes(audio) {return audio.left.byteLength+(audio.right===audio.left?0:audio.right.byteLength);}
    sampleBytes() {let bytes=0;for(const audio of this.audio.values())bytes+=this.audioBytes(audio);return bytes;}
    reserveSampleSpace(bytes,keep=[]) {const protectedIds=new Set(keep);for(const [id,audio] of this.audio){if(this.sampleBytes()+bytes<=MAX_BYTES)break;if(!protectedIds.has(id)){this.audio.delete(id);for(const key of this.processed.keys())if(JSON.parse(key)[0]===id)this.processed.delete(key);}}if(this.sampleBytes()+bytes>MAX_BYTES)throw new Error('The decoded sample cupboard is full (64 MB). Choose fewer layers or shorter samples.');}
    async loadSample(id,{signal,keep=this.referencedIds()}={}) {aborted(signal);if(this.audio.has(id))return this.audio.get(id);if(this.loading.has(id)){const value=await this.loading.get(id);aborted(signal);return value;}const meta=this.metadata.get(id);if(!meta)throw new Error('The selected sample is unavailable: '+id);const promise=(async()=>{let bytes;if(meta.pcm){const decoded=decodeAsset(meta);this.reserveSampleSpace(this.audioBytes(decoded),keep);this.audio.set(id,decoded);return decoded;}if(meta.base64)bytes=bytesFromBase64(meta.base64);else {if(root.location?.protocol==='file:')throw new Error('This kit is online. Open BATTER on the Kitchen site or import a downloaded sample bundle.');const response=await fetch(meta.url,{signal});if(!response.ok)throw new Error('The sample could not be downloaded ('+response.status+').');const length=Number(response.headers.get('Content-Length'));if(length>MAX_BYTES)throw new Error('This sample download is too large.');bytes=new Uint8Array(await response.arrayBuffer());}aborted(signal);const audio=await this.decode(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),meta.name);aborted(signal);this.reserveSampleSpace(this.audioBytes(audio),keep);this.audio.set(id,audio);return audio;})();this.loading.set(id,promise);try{return await promise;}finally{this.loading.delete(id);}}
    async ensureSamples(ids=this.referencedIds(),{signal}={}) {const keep=[...new Set(ids)];for(const id of keep){aborted(signal);await this.loadSample(id,{signal,keep});}return true;}
    getSampleAudio(id) {const audio=this.audio.get(id);if(!audio)throw new Error('The selected sample has not loaded yet.');return audio;}
    async setKit(id,{signal}={}) {let kit=this.library.kits.find(k=>k.id===id);if(!kit)throw new Error('Choose an available acoustic kit.');if(kit.lanes.some(l=>(l.sampleIds||[l.sampleId]).some(sampleId=>!this.metadata.has(sampleId))))for(const required of kit.requires||[])if(!this.loadedBundles.has(required))await this.loadLibrary(required,{signal});kit=this.library.kits.find(k=>k.id===id);const generation=this.generation,blendIds=kit.lanes.flatMap((item,i)=>{const b=item.blend||this.state.lanes[i]?.blend;return [...(b?.sampleIds||[]),b?.sampleId].filter(Boolean);}),locks=this.state.patterns.flatMap(p=>p.lanes.flatMap(l=>l.steps.map(s=>s.sampleId).filter(Boolean)));await this.ensureSamples([...kit.lanes.flatMap(l=>l.sampleIds||[l.sampleId]).filter(Boolean),...locks,...blendIds],{signal});aborted(signal);if(this.generation!==generation)throw new Error('The instrument changed while the kit was loading. Try selecting the kit again.');this.stop();this.applyKit(kit);this.generation++;this.processed.clear();return this.getState();}
    async importFiles(files,{laneId=this.state.lanes[0].id,mode='replace',appendLayers=true,source='a',signal}={}) {if(this.importing)throw new Error('A sample import is already in progress.');const items=Array.from(files||[]);if(!items.length)throw new Error('Choose at least one audio file.');if(items.length>128)throw new Error('Import up to 128 drum samples at once.');if(source==='b'&&mode==='lanes')throw new Error('Source B supports a single sample or a layer group.');if(mode==='replace'&&items.length>1)throw new Error('Choose Layers or Separate lanes for a batch import.');const generation=this.generation;this.importing=true;try{const assets=[];for(const file of items){aborted(signal);if(file.size>MAX_BYTES)throw new Error('An audio file exceeds the 64 MB import budget.');const bytes=await file.arrayBuffer();aborted(signal);const audio=await this.decode(bytes,file.name.replace(/\.[^.]+$/,''));aborted(signal);assets.push(encodeAsset(audio,{name:audio.name}));}if(generation!==this.generation)throw new Error('The instrument changed while samples were loading. No samples were replaced.');return this.commitImported(assets,{laneId,mode,appendLayers,source});}finally{this.importing=false;}}
    commitImported(assets,{laneId,mode='replace',appendLayers=true,source='a'}={}) {const state=this.getState(),index=state.lanes.findIndex(l=>l.id===laneId);if(index<0)throw new Error('Choose a destination drum lane.');if(!['a','b'].includes(source))throw new Error('Choose source A or B.');if(source==='b'&&mode==='lanes')throw new Error('Source B supports a single sample or a layer group.');if(mode==='lanes'&&assets.length>12-index)throw new Error('There are not enough remaining lanes for this batch. Choose Layers or a higher lane.');state.assets.push(...assets);if(mode==='lanes')assets.forEach((a,i)=>{const l=state.lanes[index+i];l.sampleId=a.id;l.sampleIds=[a.id];l.name=a.name;l.start=0;l.end=1;l.layerMode='single';});else {const original=state.lanes[index],l=source==='b'?original.blend:original;l.sampleIds=mode==='layers'&&appendLayers?[...l.sampleIds,...assets.map(a=>a.id)]:assets.map(a=>a.id);l.sampleId=assets[0].id;l.layerMode=mode==='layers'?'roundrobin':'single';if(source==='b')l.enabled=true;else {l.start=0;l.end=1;}}return this.setState(state);}
    async importAudio(payload,options={}) {aborted(options.signal);const pcm=payload?.pcm,sampleRate=payload?.sampleRate;let audio;if(floatArray(pcm)||Array.isArray(pcm)){if(pcm.length%2)throw new Error('Stereo PCM must have an even sample count.');if(!pcm.length||pcm.length*4>MAX_BYTES)throw new Error('The stereo PCM sample is empty or exceeds the 64 MB decoded cupboard.');for(const value of pcm)if(typeof value!=='number'||!Number.isFinite(value))throw new Error('Imported PCM must contain finite numeric samples.');const frames=pcm.length/2,left=new Float32Array(frames),right=new Float32Array(frames);for(let i=0;i<frames;i++){left[i]=number(pcm[i*2],-1,1,0);right[i]=number(pcm[i*2+1],-1,1,0);}audio={left,right,sampleRate,name:payload.name};}else if(floatArray(payload?.left)){for(const channel of [payload.left,payload.right||payload.left])for(const value of channel)if(!Number.isFinite(value))throw new Error('Imported PCM must contain finite numeric samples.');audio=payload;}else throw new Error('The imported audio needs stereo PCM data.');if(typeof sampleRate!=='number'||!Number.isFinite(sampleRate)||sampleRate<8000||sampleRate>192000)throw new Error('Choose a valid sample rate.');const asset=encodeAsset(audio,{name:payload.name||'Shared ingredient'});aborted(options.signal);return this.commitImported([asset],{laneId:options.laneId||options.target||LANE_IDS[0],mode:options.mode||'replace',appendLayers:options.appendLayers??true,source:options.source||'a'});}
    async getProject({signal}={}) {const generation=this.generation;await this.ensureSamples(this.referencedIds(),{signal});aborted(signal);if(generation!==this.generation)throw new Error('The instrument changed while the project was being prepared. Save it again.');return {format:'batter-project',formatVersion:1,appVersion:VERSION,state:this.getState({portable:true})};}
    async exportBundle({signal}={}) {const project=await this.getProject({signal}),samples=[];for(const asset of project.state.assets){aborted(signal);const pcm=bytesFromBase64(asset.pcm),bytes=new Uint8Array(44+pcm.length),view=new DataView(bytes.buffer),put=(p,s)=>{for(let i=0;i<s.length;i++)bytes[p+i]=s.charCodeAt(i);};put(0,'RIFF');view.setUint32(4,36+pcm.length,true);put(8,'WAVE');put(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,asset.channels,true);view.setUint32(24,asset.sampleRate,true);view.setUint32(28,asset.sampleRate*asset.channels*2,true);view.setUint16(32,asset.channels*2,true);view.setUint16(34,16,true);put(36,'data');view.setUint32(40,pcm.length,true);bytes.set(pcm,44);const {pcm:ignore,...metadata}=asset;samples.push({...metadata,...this.metadata.get(asset.id),base64:base64FromBytes(bytes),mime:'audio/wav'});delete samples.at(-1).pcm;}return {format:'kitchen-batter-library',version:1,id:'batter-export-'+Date.now().toString(36),samples,kits:[{id:'saved-kit-'+Date.now().toString(36),name:project.state.name,lanes:project.state.lanes.map(l=>({name:l.name,type:l.id,sampleId:l.sampleId,sampleIds:l.sampleIds,blend:l.blend,lfo:l.lfo}))}],bundles:[]};}
    async loadProject(value,{signal}={}) {aborted(signal);const project=typeof value==='string'?JSON.parse(value):value;if(project?.format!=='batter-project'||project.formatVersion!==1)throw new Error('Choose a BATTER instrument project.');const state=normalize(project.state),generation=this.generation,candidate=new Engine(state);candidate.registerLibrary(this.library);candidate.installAssets();try{await candidate.ensureSamples(candidate.referencedIds(),{signal});aborted(signal);if(generation!==this.generation||this.disposed)throw new Error('The instrument changed while the project was loading. No recipe was replaced.');this.stop();this.audio=candidate.audio;candidate.audio=new Map();for(const [id,metadata] of candidate.metadata)this.metadata.set(id,metadata);this.processed.clear();this.setState(state);return this.getState();}finally{await candidate.dispose();}}
    createGraph(context,state=this.state) {
      const graph={context,state,lanes:[],master:context.createGain(),limiter:context.createWaveShaper(),room:context.createConvolver(),roomGain:context.createGain(),delay:context.createDelay(4),delayFilter:context.createBiquadFilter(),feedback:context.createGain(),delayGain:context.createGain(),analyser:null};
      const curve=new Float32Array(2049);for(let i=0;i<curve.length;i++){const x=i/(curve.length-1)*2-1,a=Math.abs(x);curve[i]=a<=.9?x:Math.sign(x)*(.9+.1*Math.tanh((a-.9)/.1));}graph.limiter.curve=curve;graph.limiter.oversample='none';graph.master.connect(graph.limiter);graph.limiter.connect(context.destination);
      graph.room.connect(graph.roomGain);graph.roomGain.connect(graph.master);graph.roomGain.gain.value=.55;graph.delay.connect(graph.delayFilter);graph.delayFilter.type='lowpass';graph.delayFilter.connect(graph.feedback);graph.feedback.connect(graph.delay);graph.delayFilter.connect(graph.delayGain);graph.delayGain.connect(graph.master);graph.delayGain.gain.value=.6;
      for(let i=0;i<12;i++) {const input=context.createGain(),hp=context.createBiquadFilter(),lp=context.createBiquadFilter(),volume=context.createGain(),pan=context.createGain(),room=context.createGain(),delay=context.createGain();hp.type='highpass';lp.type='lowpass';input.connect(volume);volume.connect(pan);pan.connect(graph.master);pan.connect(room);room.connect(graph.room);pan.connect(delay);delay.connect(graph.delay);graph.lanes.push({input,hp,lp,volume,pan,room,delay});}
      this.updateGraph(graph,state);if(context.createAnalyser){graph.analyser=context.createAnalyser();graph.analyser.fftSize=256;graph.limiter.connect(graph.analyser);}return graph;
    }
    updateGraph(graph,state=this.state) {graph.state=state;const now=graph.context.currentTime,assign=(param,value)=>{if(graph.initialized&&param.setTargetAtTime)param.setTargetAtTime(value,now,.01);else param.value=value;},solo=state.lanes.some(l=>l.solo);assign(graph.master.gain,state.master.volume);assign(graph.delay.delayTime,Math.min(3.9,60/state.tempo*({'1/16':.25,'1/8':.5,'1/8T':1/3,'1/4':1,'3/8':1.5,'1/2':2}[state.master.delayDivision]||.5)));assign(graph.feedback.gain,state.master.delayFeedback);assign(graph.delayFilter.frequency,state.master.delayTone);for(let i=0;i<12;i++){const l=state.lanes[i],g=graph.lanes[i];assign(g.hp.frequency,l.highpass);assign(g.lp.frequency,Math.min(l.lowpass,graph.context.sampleRate*.45));assign(g.lp.Q,l.resonance);assign(g.volume.gain,l.mute||solo&&!l.solo?0:l.volume);if(g.pan.pan)assign(g.pan.pan,l.pan);assign(g.room.gain,l.room);assign(g.delay.gain,l.delay);}if(graph.roomSize!==state.master.roomSize){graph.roomSize=state.master.roomSize;const sr=graph.context.sampleRate,duration=.12+state.master.roomSize*2.6,frames=Math.round(sr*duration),ir=graph.context.createBuffer(2,frames,sr),rng=random(328171);for(let c=0;c<2;c++){const data=ir.getChannelData(c);for(let i=0;i<frames;i++){const t=i/sr;data[i]=(rng()*2-1)*Math.pow(1-i/frames,2.5)*.22*(t<.007?t/.007:1);}}graph.room.buffer=ir;}graph.initialized=true;}
    chooseSample(l,event) {if(event.sampleId)return event.sampleId;const ids=l.sampleIds.length?l.sampleIds:[l.sampleId];if(!ids.length||!ids[0])return null;if(l.layerMode==='single')return l.sampleId||ids[0];const rng=random(event.seed);if(l.layerMode==='random')return ids[Math.floor(rng()*ids.length)];if(l.layerMode==='roundrobin')return ids[mod(event.roundRobin||0,ids.length)];let distance=Infinity,group=[];for(const id of ids){const metadata=this.metadata.get(id)||{},velocity=number(metadata.velocity,0,1,1),delta=Math.abs(velocity-event.velocity);if(delta<distance-.001){distance=delta;group=[id];}else if(Math.abs(delta-distance)<.001)group.push(id);}group.sort((a,b)=>(this.metadata.get(a)?.roundRobin||0)-(this.metadata.get(b)?.roundRobin||0));return group[mod(event.roundRobin||0,group.length)]||ids[0];}
    preparedSample(id,l,reverse,context) {const key=JSON.stringify([id,l.start,l.end,l.drive,l.bits,l.decimate,l.transient,l.body,reverse,l.normalize]),cached=this.processed.get(key);let audio;if(cached)audio=cached;else {audio=processSample(this.getSampleAudio(id),l,reverse);this.processed.set(key,audio);let bytes=0;for(const a of this.processed.values())bytes+=a.left.byteLength+a.right.byteLength;while(bytes>32*1024*1024&&this.processed.size>1){const first=this.processed.keys().next().value,a=this.processed.get(first);this.processed.delete(first);bytes-=a.left.byteLength+a.right.byteLength;}}if(!audio.buffers)audio.buffers=new WeakMap();if(audio.buffers.has(context))return audio.buffers.get(context);const buffer=context.createBuffer(2,audio.left.length,audio.sampleRate);buffer.copyToChannel(audio.left,0);buffer.copyToChannel(audio.right,1);audio.buffers.set(context,buffer);return buffer;}
    stopEntry(entry,when) {for(const source of entry.sources||[entry.source])try{when===undefined?source.stop():source.stop(when);}catch{}}
    sourceIds(l,event) {const a=this.chooseSample(l,event),b=this.chooseSample(l.blend||blend(),{...event,sampleId:event.blendSampleId||'',seed:hash(event.seed,717)});return {a,b};}
    modulationBeat(event,time,state=this.state) {if(Number.isFinite(event.modulationBeat))return event.modulationBeat;if(Number.isFinite(event.beat))return event.beat;if(this.playing&&this.transportStart!==undefined)return Math.max(0,(time-this.transportStart)*state.tempo/60);return Math.max(0,time*state.tempo/60);}
    automate(param,plan,time,duration,convert) {if(plan.held){for(const point of plan.points)param.setValueAtTime(convert(point.value),time+point.time);}else {const curve=new Float32Array(plan.points.length);for(let i=0;i<curve.length;i++)curve[i]=convert(plan.points[i].value);param.setValueCurveAtTime(curve,time,duration);}}
    scheduleHit(event,time,graph=this.graph,state=this.state,registry=this.sources) {
      const original=state.lanes[event.laneIndex??state.lanes.findIndex(l=>l.id===event.laneId)];if(!original||original.mute||state.lanes.some(l=>l.solo)&&!original.solo)return null;
      const l={...original,...event.locks,blend:{...original.blend,amount:event.locks?.blend??original.blend?.amount}};if(l.end<=l.start)l.end=Math.min(1,l.start+.0001);
      const modulation=l.lfo?.enabled&&l.lfo.depth>0,hasB=!!(l.blend?.sampleId||l.blend?.sampleIds?.length),mixing=l.blend?.enabled&&hasB;
      if(!mixing&&!modulation&&event.soloSource!=='b')return this.scheduleLegacyHit(event,time,graph,state,registry);
      const ids=this.sourceIds(l,event),weights=mixing?blendWeights(l.blend.amount):{a:1,b:0},blendMod=modulation&&l.lfo.target==='blend'&&mixing&&!event.soloSource;
      if(event.soloSource==='a'){weights.a=1;weights.b=0;}if(event.soloSource==='b'){weights.a=0;weights.b=1;}
      const parts=[],context=graph.context,pitchMod=modulation&&l.lfo.target==='pitch',stretch=pitchMod?Math.pow(2,l.lfo.depth):1;
      for(const sourceName of ['a','b']) {const id=ids[sourceName],isB=sourceName==='b',weight=weights[sourceName];if(!id||!weight&&!blendMod||isB&&l.blend.level===0)continue;if(!this.audio.has(id))throw new Error('Load both selected sources before playing.');const reverse=event.reverse===null||event.reverse===undefined?(isB?l.blend.reverse:l.reverse):event.reverse,buffer=this.preparedSample(id,l,reverse,context),rate=Math.pow(2,(l.tune+(event.pitch||0)+l.fine/100+(isB?l.blend.tune+l.blend.fine/100:0))/12),offset=isB?l.blend.offset:0;parts.push({id,sourceName,buffer,rate,offset,weight:weight*(isB?l.blend.level:1),level:isB?l.blend.level:1,natural:buffer.duration/rate*stretch});}
      if(!parts.length)return null;
      const explicit=event.duration??(event.gate>0?event.gate*60/state.tempo:Infinity),duration=Math.max(.003,Math.min(l.gate,explicit,Math.max(...parts.map(p=>p.offset+p.natural)))),finish=time+duration;
      const input=context.createGain(),envelope=context.createGain(),hp=context.createBiquadFilter(),lp=context.createBiquadFilter(),pan=context.createStereoPanner?context.createStereoPanner():context.createGain(),tremolo=context.createGain(),nodes=[input,envelope,hp,lp,pan,tremolo],sources=[];
      hp.type='highpass';hp.frequency.value=l.highpass;lp.type='lowpass';lp.frequency.value=Math.min(l.lowpass,context.sampleRate*.45);lp.Q.value=l.resonance;if(pan.pan)pan.pan.value=l.pan;input.connect(hp);hp.connect(lp);lp.connect(pan);pan.connect(envelope);envelope.connect(tremolo);tremolo.connect(graph.lanes[state.lanes.indexOf(original)].input);
      const attack=Math.min(l.attack,duration*.3),decay=Math.min(l.decay,Math.max(0,duration-attack)*.6),release=Math.min(l.release,Math.max(.001,duration-attack-decay)),velocity=number(event.velocity,0,1,.8)*(event.locks?.volume!==undefined?l.volume/Math.max(.0001,original.volume):1),sustain=velocity*l.sustain;envelope.gain.setValueAtTime(attack?0:velocity,time);if(attack)envelope.gain.linearRampToValueAtTime(velocity,time+attack);envelope.gain.linearRampToValueAtTime(sustain,time+attack+decay);envelope.gain.setValueAtTime(sustain,Math.max(time+attack+decay,finish-release));envelope.gain.linearRampToValueAtTime(0,finish);
      const seed=l.lfo?.reset==='continuous'?hash(state.seed,state.lanes.indexOf(original),517):hash(event.seed||state.seed,517),beat=this.modulationBeat(event,time,state),plan=modulation?modulationPlan(l.lfo,duration,{tempo:state.tempo,beat,seed}):null;
      if(plan&&l.lfo.target==='lowpass')this.automate(lp.frequency,plan,time,duration,w=>Math.max(40,Math.min(context.sampleRate*.45,l.lowpass*Math.pow(2,w*l.lfo.depth*4))));
      if(plan&&l.lfo.target==='pan'&&pan.pan)this.automate(pan.pan,plan,time,duration,w=>Math.max(-1,Math.min(1,l.pan+w*l.lfo.depth)));
      if(plan&&l.lfo.target==='level')this.automate(tremolo.gain,plan,time,duration,w=>1-l.lfo.depth*.5+w*l.lfo.depth*.5);
      const entry={source:null,sources,envelope,time,end:finish,laneId:l.id,choke:l.choke,sourceId:event.source||'native',sampleId:ids.a,blendSampleId:ids.b,modulationBeat:beat};let remaining=parts.filter(p=>p.offset<duration).length;
      if(!remaining){for(const node of nodes)node.disconnect();return null;}
      for(const part of parts) {if(part.offset>=duration)continue;const source=context.createBufferSource(),gain=context.createGain();source.buffer=part.buffer;source.playbackRate.value=part.rate;gain.gain.value=part.weight;source.connect(gain);gain.connect(input);nodes.push(gain);sources.push(source);if(!entry.source)entry.source=source;
        if(plan&&l.lfo.target==='pitch'&&source.detune)this.automate(source.detune,plan,time,duration,w=>w*l.lfo.depth*1200);
        if(plan&&blendMod)this.automate(gain.gain,plan,time,duration,w=>blendWeights(Math.max(0,Math.min(1,l.blend.amount+w*l.lfo.depth*.5)))[part.sourceName]*part.level);
        source.onended=()=>{try{source.disconnect();}catch{}if(--remaining===0){registry.delete(entry);for(const node of nodes)try{node.disconnect();}catch{}}};source.start(time+part.offset);source.stop(finish+.001);
      }
      if(l.choke)for(const previous of registry)if(previous.choke===l.choke&&previous.time<=time&&previous.end>time){const stop=Math.min(previous.end,time+.006);try{previous.envelope.gain.cancelAndHoldAtTime(time);previous.envelope.gain.linearRampToValueAtTime(0,stop);}catch{}this.stopEntry(previous,stop+.001);previous.end=stop;}
      registry.add(entry);return entry;
    }
    scheduleLegacyHit(event,time,graph=this.graph,state=this.state,registry=this.sources) {
      const original=state.lanes[event.laneIndex??state.lanes.findIndex(l=>l.id===event.laneId)];if(!original||original.mute||state.lanes.some(l=>l.solo)&&!original.solo)return null;const l={...original,...event.locks};if(l.end<=l.start)l.end=Math.min(1,l.start+.0001);const sampleId=this.chooseSample(l,event);if(!sampleId)return null;if(!this.audio.has(sampleId))throw new Error('Load the selected sample before playing.');const context=graph.context,reverse=event.reverse===null||event.reverse===undefined?l.reverse:event.reverse,buffer=this.preparedSample(sampleId,l,reverse,context),rate=Math.pow(2,(l.tune+(event.pitch||0)+l.fine/100)/12),natural=buffer.duration/rate,explicit=event.duration??(event.gate>0?event.gate*60/state.tempo:Infinity),duration=Math.max(.003,Math.min(natural,l.gate,explicit)),source=context.createBufferSource(),envelope=context.createGain(),hp=context.createBiquadFilter(),lp=context.createBiquadFilter(),pan=context.createStereoPanner?context.createStereoPanner():context.createGain();hp.type='highpass';hp.frequency.value=l.highpass;lp.type='lowpass';lp.frequency.value=Math.min(l.lowpass,context.sampleRate*.45);lp.Q.value=l.resonance;if(pan.pan)pan.pan.value=l.pan;source.buffer=buffer;source.playbackRate.value=rate;source.connect(hp);hp.connect(lp);lp.connect(pan);pan.connect(envelope);envelope.connect(graph.lanes[state.lanes.indexOf(original)].input);
      const attack=Math.min(l.attack,duration*.3),decay=Math.min(l.decay,Math.max(0,duration-attack)*.6),release=Math.min(l.release,Math.max(.001,duration-attack-decay)),velocity=number(event.velocity,0,1,.8)*(event.locks?.volume!==undefined?l.volume/Math.max(.0001,original.volume):1),sustain=velocity*l.sustain,finish=time+duration;envelope.gain.setValueAtTime(attack?0:velocity,time);if(attack)envelope.gain.linearRampToValueAtTime(velocity,time+attack);envelope.gain.linearRampToValueAtTime(sustain,time+attack+decay);envelope.gain.setValueAtTime(sustain,Math.max(time+attack+decay,finish-release));envelope.gain.linearRampToValueAtTime(0,finish);
      const entry={source,envelope,time,end:finish,laneId:l.id,choke:l.choke,sourceId:event.source||'native',sampleId};if(l.choke)for(const previous of registry)if(previous.choke===l.choke&&previous.time<=time&&previous.end>time){const stop=Math.min(previous.end,time+.006);try{previous.envelope.gain.cancelAndHoldAtTime(time);previous.envelope.gain.linearRampToValueAtTime(0,stop);this.stopEntry(previous,stop+.001);previous.end=stop;}catch{try{this.stopEntry(previous,stop);}catch{}}}registry.add(entry);source.onended=()=>{registry.delete(entry);for(const node of [source,envelope,hp,lp,pan])node.disconnect();};source.start(time);source.stop(finish+.001);return entry;
    }
    async trigger(laneId,velocity=.8,options={}) {const generation=this.generation,l=this.state.lanes.find(l=>l.id===laneId);if(!l)throw new Error('Choose a drum lane.');const event={laneId,laneIndex:this.state.lanes.indexOf(l),velocity,pitch:options.pitch||0,reverse:options.reverse??null,sampleId:options.soloSource==='b'?'':options.sampleId||'',blendSampleId:options.soloSource==='b'?options.sampleId||'':options.blendSampleId||'',soloSource:options.soloSource,duration:options.duration,beat:options.beat,modulationBeat:options.modulationBeat,seed:hash(this.state.seed,this.previewSerial),roundRobin:this.previewSerial++,source:options.source||'preview'};const ids=this.sourceIds(l,event),wanted=event.soloSource==='b'?[ids.b]:event.soloSource==='a'?[ids.a]:[ids.a,l.blend.enabled?ids.b:null];if(!wanted.some(Boolean))throw new Error(event.soloSource==='b'?'Choose a source B sample first.':'Load a sample into this drum lane.');await Promise.all([this.init(),this.ensureSamples(wanted.filter(Boolean))]);if(this.generation!==generation||this.disposed)return false;return this.scheduleHit(event,options.when??this.context.currentTime+.004);}
    async play({offsetBeats=0,when}={}) {if(this.importing)throw new Error('Wait for the sample import to finish.');if(this.playing)return true;const generation=++this.generation;await Promise.all([this.init(),this.ensureSamples()]);if(generation!==this.generation||this.disposed)return false;this.playing=true;this.transportStart=Math.max(this.context.currentTime+.015,Number.isFinite(when)?when:this.context.currentTime+.035)-number(offsetBeats,0,2048,0)*60/this.state.tempo;this.lastTempo=this.state.tempo;this.cycle=0;this.eventAt=0;this.score=compile(this.state,{cycleIndex:0});this.seekScheduler(Math.max(0,offsetBeats));this.tick();this.timer=setInterval(()=>this.tick(),25);return true;}
    seekScheduler(beat) {const span=patternSpan(this.state);this.cycle=Math.floor(beat/span);this.score=compile(this.state,{cycleIndex:this.cycle});this.eventAt=0;while(this.eventAt<this.score.events.length&&this.score.events[this.eventAt].beat+this.cycle*span<beat-1e-7)this.eventAt++;}
    reschedule() {const now=this.context.currentTime,oldTempo=this.lastTempo||this.state.tempo,beat=Math.max(0,(now-this.transportStart)*oldTempo/60);this.transportStart=now-beat*60/this.state.tempo;this.lastTempo=this.state.tempo;for(const entry of this.sources)if(entry.sourceId==='native'&&entry.time>now+.008){try{this.stopEntry(entry);}catch{}this.sources.delete(entry);}this.seekScheduler(beat+.01*this.state.tempo/60);}
    tick() {if(!this.playing||!this.context)return;const now=this.context.currentTime,horizon=now+.14,span=this.score.cycleBeats,secondsPerBeat=60/this.state.tempo;this.lastTempo=this.state.tempo;let guard=0;try{while(guard++<8192){if(this.eventAt>=this.score.events.length){this.cycle++;this.score=compile(this.state,{cycleIndex:this.cycle,roundRobinOffsets:this.score.roundRobinCounts});this.eventAt=0;if(!this.score.events.length){const cycleTime=this.transportStart+this.cycle*span*secondsPerBeat;if(cycleTime>horizon)break;continue;}}const event=this.score.events[this.eventAt],when=this.transportStart+(this.cycle*span+event.beat)*secondsPerBeat;if(when>horizon)break;this.eventAt++;if(when<now-.03)continue;this.scheduleHit({...event,modulationBeat:this.cycle*span+event.beat},Math.max(when,now+.001));}const beat=Math.max(0,(now-this.transportStart)/secondsPerBeat),local=mod(beat,span);let position=this.score.steps[0]||{step:-1,pattern:this.state.selectedPattern};for(const step of this.score.steps){if(step.beat>local+1e-8)break;position=step;}let peak=0;if(this.graph.analyser){const wave=new Float32Array(256);this.graph.analyser.getFloatTimeDomainData(wave);for(const value of wave)peak=Math.max(peak,Math.abs(value));}this.meters={playing:true,beat,step:position.step,pattern:position.pattern,peak};this.onStep?.(this.meters);}catch(error){this.stop();this.onStatus?.(error.message);}}
    stop({tails=false}={}) {this.generation++;this.playing=false;if(this.timer)clearInterval(this.timer);this.timer=null;const now=this.context?.currentTime||0;for(const entry of this.sources)if(!tails||entry.time>now){try{entry.envelope.gain.cancelScheduledValues(now);entry.envelope.gain.setTargetAtTime(0,now,.006);this.stopEntry(entry,now+.035);}catch{}this.sources.delete(entry);}this.meters={...this.meters,playing:false,step:-1};return true;}
    disconnectGraph(graph) {if(!graph)return;for(const node of Object.values(graph))if(node&&typeof node.disconnect==='function')try{node.disconnect();}catch{}for(const lane of graph.lanes)for(const node of Object.values(lane))try{node.disconnect();}catch{}}
    panic() {this.stop();this.sources.clear();if(this.graph){this.disconnectGraph(this.graph);this.graph=this.createGraph(this.context);}return true;}
    getMeters() {let peak=0;if(this.graph?.analyser){if(!this.meterWave)this.meterWave=new Float32Array(256);this.graph.analyser.getFloatTimeDomainData(this.meterWave);for(const value of this.meterWave)peak=Math.max(peak,Math.abs(value));}return {...this.meters,playing:this.playing,peak};}
    async renderWav({bars=1,tailSeconds=2,scope='pattern',laneId=null,signal,state=this.state}={}) {if(this.exporting)throw new Error('A BATTER render is already in progress.');this.exporting=true;const snapshot=normalize(state);try{aborted(signal);const lengthBeats=integer(bars,1,64,1)*4,score=compile(snapshot,{scope:scope==='chain'?'chain':'pattern',lengthBeats,laneId:scope==='lane'?laneId:null});return (await this.renderScore(score,snapshot,{tailSeconds,signal})).blob;}finally{this.exporting=false;}}
    async renderScore(score,state,{tailSeconds=2,signal}={}) {aborted(signal);await this.ensureSamples(this.referencedIds(state),{signal});aborted(signal);const sampleRate=48000,duration=score.lengthBeats*60/state.tempo+number(tailSeconds,0,12,2);if(duration>300)throw new Error('Export at most five minutes at once.');const frames=Math.max(1,Math.ceil(duration*sampleRate)),Offline=root.OfflineAudioContext||root.webkitOfflineAudioContext;if(!Offline)throw new Error('This browser does not support offline audio export.');const context=new Offline(2,frames,sampleRate),graph=this.createGraph(context,state),registry=new Set();for(const event of score.events){aborted(signal);this.scheduleHit(event,event.beat*60/state.tempo,graph,state,registry);}const result=await context.startRendering();aborted(signal);const left=result.getChannelData(0),right=result.getChannelData(1),fade=Math.min(Math.round(sampleRate*.005),frames);for(let i=0;i<fade;i++){const gain=i/(Math.max(1,fade-1)),at=frames-1-i;left[at]*=gain;right[at]*=gain;}return {blob:wav({left,right,sampleRate}),sampleRate,duration,name:state.name+'.wav',tempo:state.tempo,sourceApp:'batter',sourceLabel:state.name};}
    async renderNotes({events=[],state=this.state,tempo=state.tempo,lengthBeats=4,tailSeconds=2,signal,seed}={}) {const snapshot=normalize({...state,tempo}),score={events:[],lengthBeats:number(lengthBeats,.25,2048,4)},rng=random(seed??snapshot.seed);if(events.length>65536)throw new Error('The drum note queue is too large.');for(let i=0;i<events.length;i++){const e=events[i],index=e.voiceId?LANE_IDS.indexOf(e.voiceId):Math.round(e.note??36)-36;if(index<0||index>=12)throw new Error('Map drum notes to one of BATTER’s twelve lanes (MIDI 36–47).');const beat=number(e.startBeat??e.beat,0,score.lengthBeats,0);if(beat>=score.lengthBeats||rng()>=number(e.probability,0,1,1))continue;score.events.push({laneId:LANE_IDS[index],laneIndex:index,beat,velocity:number(e.velocity,0,1,.8),duration:e.durationBeats?e.durationBeats*60/snapshot.tempo:undefined,pitch:e.voiceId?number((e.note??36+index)-(36+index),-24,24,0):0,reverse:null,sampleId:'',seed:hash(seed??snapshot.seed,i),roundRobin:i,source:'loom'});}score.events.sort((a,b)=>a.beat-b.beat||a.laneIndex-b.laneIndex);return this.renderScore(score,snapshot,{tailSeconds,signal});}
    noteOn({note=36,voiceId,velocity=.8,when,duration=.3,source='loom'}={}) {const id=voiceId||LANE_IDS[Math.round(note)-36];if(!id)throw new Error('Choose a BATTER drum voice (MIDI 36–47).');return this.trigger(id,velocity,{when,duration,source,pitch:voiceId?number(note-(36+LANE_IDS.indexOf(id)),-24,24,0):0});}
    stopNotes(source='loom') {const now=this.context?.currentTime||0;for(const entry of this.sources)if(!source||entry.sourceId===source){try{entry.envelope.gain.cancelScheduledValues(now);entry.envelope.gain.setTargetAtTime(0,now,.004);this.stopEntry(entry,now+.025);}catch{}this.sources.delete(entry);}}
    async dispose() {this.disposed=true;this.stop();this.loading.clear();if(this.initializing)try{await this.initializing;}catch{}this.disconnectGraph(this.graph);if(this.context)try{await this.context.close();}catch{}this.context=null;this.graph=null;this.audio.clear();this.processed.clear();}
  }
  root.BatterSchema=Schema;root.BatterEngine=Engine;if(typeof module!=='undefined'&&module.exports)module.exports={BatterSchema:Schema,BatterEngine:Engine};
})(typeof window!=='undefined'?window:globalThis);
