'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
require(fs.existsSync(path.join(__dirname,'shared/pattern-schema.js'))?'./shared/pattern-schema.js':'../shared/pattern-schema.js');
require('./engine.js');
const S=global.BatterSchema,E=global.BatterEngine;
const checks=[];
function test(name,fn){checks.push({name,fn});}
function blank(){const state=S.defaultState();state.humanize=0;state.swing=0;state.velocityHumanize=0;for(const p of state.patterns)for(const l of p.lanes)for(const s of l.steps)s.on=false;return state;}
function audio(value=.35,frames=1000,channels=1){const left=new Float32Array(frames).fill(value);return {left,right:channels===1?left:new Float32Array(frames).fill(-value),sampleRate:44100,channels,name:'Test ingredient'};}
const asset=S.encodeAsset(audio(),{id:'fixture',name:'Known strike'});
function withAsset(){const state=blank();state.assets=[asset];state.lanes[0].sampleId='fixture';state.lanes[0].sampleIds=['fixture'];return state;}
function canonical(events){return events.map(({id,...e})=>e);}
test('Twelve lanes, eight banks, 64 preserved step cells and bounded practical controls',()=>{const state=S.normalize(S.defaultState());assert.equal(state.lanes.length,12);assert.equal(state.patterns.length,8);assert(state.patterns.every(p=>p.lanes.every(l=>l.steps.length===64)));const raw=S.defaultState();raw.tempo=NaN;raw.lanes[0].tune=999;raw.lanes[0].start=.9;raw.lanes[0].end=.1;const n=S.normalize(raw);assert.equal(n.tempo,136);assert.equal(n.lanes[0].tune,24);assert(n.lanes[0].end>n.lanes[0].start);});
test('Seeded probability, microtiming, velocity humanize and all repeated exports are deterministic',()=>{const state=blank();state.humanize=15;state.velocityHumanize=.2;state.patterns[0].lanes[1].steps.forEach((s,i)=>{s.on=i<16;s.probability=.62;s.micro=i%2?13:-8;});assert.deepEqual(S.compile(state,{cycles:4}),S.compile(state,{cycles:4}));const events=S.compile(state,{cycles:4}).events;assert(events.length>0&&events.length<64);assert(events.every(e=>e.beat>=0&&e.beat<16&&e.velocity>=0&&e.velocity<=1));});
test('Final-step eight-strike ratchets and flam remain in the exported recipe',()=>{const state=blank(),hit=state.patterns[0].lanes[1].steps[15];Object.assign(hit,{on:true,ratchet:8,flam:10,ratchetDecay:.1});const score=S.compile(state);assert.equal(score.events.length,9);assert(score.events.every(e=>e.beat>=3.75&&e.beat<4));assert(score.events.at(-1).beat>3.9);assert.equal(score.lengthBeats,4);});
test('Five-step polymeter continues across recipe loops rather than resetting at bar lines',()=>{const state=blank(),lane=state.patterns[0].lanes[0];lane.length=5;lane.steps[0].on=true;const score=S.compile(state,{cycles:3});assert.deepEqual(score.events.map(e=>e.beat),[0,1.25,2.5,3.75,5,6.25,7.5,8.75,10,11.25]);});
test('Unequal A/B chain and independent lane cycles preserve global positions',()=>{const state=blank();state.chainEnabled=true;state.chain=['A','B'];state.patterns[1].length=32;for(const p of state.patterns.slice(0,2)){p.lanes[0].length=5;p.lanes[0].steps[0].on=true;}const score=S.compile(state);assert.equal(score.lengthBeats,12);assert.deepEqual(score.events.map(e=>e.beat),[0,1.25,2.5,3.75,5,6.25,7.5,8.75,10,11.25]);});
test('Fill, first cycle, and every-second-cycle conditions honor their separate counters',()=>{const state=blank(),l=state.patterns[0].lanes[0];Object.assign(l.steps[0],{on:true,condition:'first'});Object.assign(l.steps[1],{on:true,condition:'every2'});Object.assign(l.steps[2],{on:true,condition:'fill'});let score=S.compile(state,{cycles:3});assert.equal(score.events.filter(e=>e.step===0).length,1);assert.equal(score.events.filter(e=>e.step===1).length,2);assert.equal(score.events.filter(e=>e.step===2).length,0);state.fill=true;assert.equal(S.compile(state,{cycles:3}).events.filter(e=>e.step===2).length,3);});
test('A 16-position five-hit Euclidean rhythm has exactly five evenly distributed hits',()=>{const ring=S.euclidean(16,5);assert.equal(ring.filter(Boolean).length,5);const at=ring.flatMap((on,i)=>on?[i]:[]),distances=at.map((n,i)=>(at[(i+1)%at.length]+(i===at.length-1?16:0))-n);assert(distances.every(n=>n===3||n===4));assert.equal(S.euclidean(16,0).filter(Boolean).length,0);});
test('Mutation, rolls and rotation leave protected hit cells and lanes intact',()=>{const state=blank(),l=state.patterns[0].lanes[1];Object.assign(l.steps[15],{on:true,velocity:.31,protect:true});assert.deepEqual(S.mutate(state,{laneId:'snare',amount:1}).patterns[0].lanes[1].steps[15],l.steps[15]);assert.deepEqual(S.rollFill(state).patterns[0].lanes[1].steps[15],l.steps[15]);assert.deepEqual(S.rotate(state,'snare',3).patterns[0].lanes[1].steps[15],l.steps[15]);state.lanes[1].protect=true;assert.deepEqual(S.mutate(state,{laneId:'snare',amount:1}).patterns[0].lanes[1],l);});
test('Trimming and reverse operate on sample positions, and peak normalization reaches the intended level',()=>{const a=audio(.2,1000),patch=S.defaultState().lanes[0];a.left[600]=.5;const cut=S.processSample(a,{...patch,start:.4,end:.8},false),reverse=S.processSample(a,{...patch,start:.4,end:.8},true);assert.equal(cut.left.length,400);assert.equal(cut.left[200],.5);assert.equal(reverse.left[199],.5);const normalized=S.processSample(a,{...patch,normalize:true},false);assert(Math.abs(Math.max(...normalized.left)-.95)<1e-6);});
test('Bit depth and rate reduction produce quantized held samples instead of cosmetic controls',()=>{const a=audio(0,1000);for(let i=0;i<1000;i++)a.left[i]=Math.sin(i*.07)*.31;const out=S.processSample(a,{...S.defaultState().lanes[0],bits:4,decimate:5},false);for(let i=100;i<900;i+=5){assert(Math.abs(out.left[i]*8-Math.round(out.left[i]*8))<1e-6);assert.equal(out.left[i],out.left[i+1]);}});
test('PCM16 assets preserve stereo polarity and mono channels share one decoded buffer',()=>{const stereo=S.encodeAsset(audio(.35,1000,2),{id:'stereo'}),decoded=S.decodeAsset(stereo);assert(decoded.left[200]>0&&decoded.right[200]<0);const mono=S.decodeAsset(asset);assert.equal(mono.left,mono.right);assert.equal(mono.channels,1);});
test('WAV round trip carries accurate rate, stereo length and sample values',async()=>{const blob=S.wav(audio(.35,1000,2)),decoded=S.decodeWav(await blob.arrayBuffer());assert.equal(decoded.left.length,1000);assert.equal(decoded.sampleRate,44100);assert.equal(decoded.channels,2);assert(Math.abs(decoded.left[500]-.35)<1/32768);});
test('Truncated WAVs and malformed or oversized PCM headers are rejected',()=>{assert.throws(()=>S.decodeWav(new Uint8Array(44)),/not a PCM/);const state=withAsset();state.assets[0]={...asset,frames:2};assert.throws(()=>S.normalize(state),/invalid PCM/);state.assets=[{...asset,frames:Math.ceil(44100*121),pcm:''}];assert.throws(()=>S.normalize(state),/invalid PCM|120 seconds/);});
test('Real velocity zones choose quiet/loud recordings and regular beats cycle every recorded alternate',()=>{const engine=new E(blank());for(let i=0;i<4;i++)engine.metadata.set('rr'+i,{id:'rr'+i,velocity:.8,roundRobin:i});const l={...engine.state.lanes[0],sampleIds:['rr0','rr1','rr2','rr3'],sampleId:'rr0',layerMode:'velocity'},state=blank();for(const i of [0,4,8,12])state.patterns[0].lanes[0].steps[i].on=true;const score=S.compile(state,{cycles:2});assert.deepEqual(score.events.map(e=>engine.chooseSample(l,e)),['rr0','rr1','rr2','rr3','rr0','rr1','rr2','rr3']);engine.metadata.set('quiet',{velocity:.15});engine.metadata.set('loud',{velocity:.9});assert.equal(engine.chooseSample({...l,sampleIds:['quiet','loud']},{velocity:.16,seed:1,roundRobin:0}),'quiet');});
test('Live cycle compilation with carried hit counters matches the deterministic offline sequence',()=>{const state=blank();state.patterns[0].lanes[0].steps.forEach((s,i)=>{s.on=i<16&&i%3===0;s.probability=.8;s.ratchet=i===6?3:1;});const all=S.compile(state,{cycles:3}),live=[];let counters=null;for(let cycle=0;cycle<3;cycle++){const part=S.compile(state,{cycleIndex:cycle,roundRobinOffsets:counters});counters=part.roundRobinCounts;live.push(...part.events.map(e=>({...e,beat:e.beat+cycle*part.cycleBeats})));}const comparable=events=>events.map(({id,...e})=>e);assert.deepEqual(comparable(live),comparable(all.events));});
test('Several imported files can replace a layer group or occupy separate drum lanes',async()=>{const engine=new E(withAsset()),bytes=await S.wav(audio()).arrayBuffer(),file=name=>({name,size:bytes.byteLength,arrayBuffer:async()=>bytes.slice(0)});await engine.importFiles([file('A.wav'),file('B.wav')],{laneId:'kick',mode:'layers',appendLayers:false});assert.equal(engine.state.lanes[0].sampleIds.length,2);assert(!engine.state.lanes[0].sampleIds.includes('fixture'));await engine.importFiles([file('C.wav'),file('D.wav')],{laneId:'snare',mode:'lanes'});assert.equal(engine.state.lanes[1].name,'C');assert.equal(engine.state.lanes[2].name,'D');await engine.dispose();});
test('Shared audio accepts Float32 PCM from another browser realm and rejects nonfinite samples',async()=>{const vm=require('node:vm'),pcm=vm.runInNewContext('new Float32Array([.2,-.2,.3,-.3,.4,-.4,.2,-.2])');assert(!(pcm instanceof Float32Array));const engine=new E(withAsset());await engine.importAudio({pcm,sampleRate:44100,name:'Other realm'},{laneId:'snare'});assert.equal(engine.state.lanes[1].sampleIds.length,1);const bad=vm.runInNewContext('new Float32Array([NaN,0,0,0])');await assert.rejects(engine.importAudio({pcm:bad,sampleRate:44100},{laneId:'snare'}),/finite/);await engine.dispose();});
test('An aborted file import and a Panic during pending decoding never replace the current drum',async()=>{const engine=new E(withAsset()),bytes=await S.wav(audio()).arrayBuffer();let release;const pending={name:'Waiting.wav',size:bytes.byteLength,arrayBuffer:()=>new Promise(r=>release=r)},promise=engine.importFiles([pending],{laneId:'kick'});engine.panic();release(bytes);await assert.rejects(promise,/instrument changed/);assert.equal(engine.state.lanes[0].sampleId,'fixture');const controller=new AbortController();controller.abort();await assert.rejects(engine.importFiles([pending],{laneId:'kick',signal:controller.signal}),/cancelled/);await engine.dispose();});
test('An unavailable project reference fails atomically and keeps the original recipe and sample',async()=>{const engine=new E(withAsset()),state=blank();state.name='Missing kit';state.lanes[0].sampleId='missing';state.lanes[0].sampleIds=['missing'];await assert.rejects(engine.loadProject({format:'batter-project',formatVersion:1,state}),/unavailable/);assert.equal(engine.state.lanes[0].sampleId,'fixture');assert.equal(engine.state.name,'The uneven service');await engine.dispose();});
test('Portable saves embed referenced samples only; hosted saves retain embedded factory IDs',async()=>{const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'factory-samples.json'),'utf8'));global.BatterLibrary=manifest;const engine=new E();await engine.ensureSamples();const hosted=engine.getState({portable:'external'}),portable=await engine.getProject();assert.equal(hosted.assets.length,0);assert.equal(portable.state.assets.length,engine.referencedIds().length);assert.equal(engine.getCatalog().samples.length,manifest.samples.length);assert(engine.sampleBytes()<S.MAX_BYTES);await engine.dispose();delete global.BatterLibrary;});
test('Complete downloaded kits upgrade starter definitions to all five actual velocity layers',async()=>{const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'factory-samples.json'),'utf8')),full=fs.existsSync(path.join(__dirname,'samples/kit-iron-service.json'))?JSON.parse(fs.readFileSync(path.join(__dirname,'samples/kit-iron-service.json'),'utf8')):(()=>{const kit=JSON.parse(JSON.stringify(manifest.kits.find(k=>k.id==='iron-service'))),extra=[{...manifest.samples[0],id:'archive-test-dynamic-2',velocity:.3},{...manifest.samples[0],id:'archive-test-dynamic-4',velocity:.7}];kit.lanes[0].sampleIds.push(...extra.map(a=>a.id));return {format:'kitchen-batter-library',version:1,samples:extra,kits:[kit],bundles:[]};})();global.BatterLibrary=manifest;const engine=new E();assert.equal(engine.library.kits.find(k=>k.id==='iron-service').lanes[0].sampleIds.length,3);engine.importBundle(full);assert.equal(engine.library.kits.find(k=>k.id==='iron-service').lanes[0].sampleIds.length,5);await engine.setKit('iron-service');assert.equal(engine.state.lanes[0].sampleIds.length,5);assert(engine.sampleBytes()<S.MAX_BYTES);await engine.dispose();delete global.BatterLibrary;});
test('A exported sample bundle reopens with actual audio and lane assignments, without network access',async()=>{const engine=new E(withAsset()),bundle=await engine.exportBundle(),copyEngine=new E(blank());copyEngine.importBundle(bundle);await copyEngine.setKit(bundle.kits[0].id);assert.equal(copyEngine.state.lanes[0].sampleId,'fixture');const decoded=copyEngine.getSampleAudio('fixture');assert(Math.abs(decoded.left[200]-.35)<1/32768);await engine.dispose();await copyEngine.dispose();});
test('Shared off-grid note overlays remain exact and native grid edits deliberately clear the overlay',()=>{const engine=new E(withAsset()),packet={format:'musiclab-pattern',version:1,name:'Exact',sourceApp:'roux',kind:'drums',tempo:136,swing:0,lengthBeats:4,voices:[{id:'source',name:'Source',pitch:36}],notes:[{id:'a',voice:'source',pitch:37,beat:.137,duration:.21,velocity:.72,probability:1}]};engine.setState({...engine.getState(),musicLabPattern:{pattern:packet,voiceMap:{source:'kick'}}});assert.equal(S.compile(engine.state).events[0].beat,.137);assert.equal(S.compile(engine.state).events[0].pitch,1);const next=engine.getState();next.lanes[0].lowpass=8500;engine.setState(next);assert(engine.state.musicLabPattern);const edit=engine.getState();edit.patterns[0].lanes[0].steps[0].on=true;engine.setState(edit);assert(!engine.state.musicLabPattern);});
test('Portable offline restores retain selected kit name and the original sample’s license and provenance',async()=>{const engine=new E(withAsset()),meta={kit:'rope-tension',articulation:'Closed hat',attribution:'Recorded by the credited original author',licenseUrl:'https://creativecommons.org/licenses/by-sa/3.0/',musicLicenseException:false,licenseNotes:'No separate music license exception',velocityRange:[.2,.4],originalVelocityRange:[26,51]},state=engine.getState();state.kitId='rope-tension';state.kitName='Rope tension';state.assets[0]={...state.assets[0],...meta};engine.setState(state);const project=await engine.getProject(),restored=new E(blank());await restored.loadProject(project);assert.equal(restored.state.kitId,'rope-tension');assert.equal(restored.state.kitName,'Rope tension');for(const [key,value] of Object.entries(meta))assert.deepEqual(restored.state.assets[0][key],value);const encoded=S.encodeAsset(audio(),{id:'credited',...meta});assert.equal(encoded.attribution,meta.attribution);const bundle=await restored.exportBundle();assert.equal(bundle.samples[0].licenseNotes,meta.licenseNotes);await engine.dispose();await restored.dispose();});
(async()=>{let passed=0;for(const {name,fn} of checks){await fn();passed++;process.stdout.write('✓ '+name+'\n');}process.stdout.write('\n'+passed+' BATTER engine checks passed.\n');})().catch(error=>{console.error(error);process.exitCode=1;});
