(() => {
  'use strict';
  const S = window.FableSchema, presets = window.FablePresets || [], $ = id => document.getElementById(id);
  const clamp = (v, a, b) => Math.max(a, Math.min(b, Number(v))), escape = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const noteName = n => ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][((Math.round(n)%12)+12)%12] + (Math.floor(n / 12)-1);
  const MAX_BYTES = S.MAX_PCM_BYTES || 64*1024*1024, MAX_ZONES = S.MAX_ZONES || 64, MAX_ASSETS = S.MAX_ASSETS || 32;
  let state = S.normalize(S.defaultState()), history = [], future = [], lifecycle = 0, importBusy = false, exporting = null, persistTimer = 0, storageOkay = true, revision = 0, storageDB = null, storageOpening = null;
  let selectedStep = 0, sequencePage = 0, playing = false, inspectorTab = 'sample', zoom = {start:0,end:1}, waveDrag = null, dragHistory = false;
  let held = new Map(), noteVoices = new Map(), sustain = false, midi = null, midiDevice = null, midiChannel = 0, expression = {wheel:0,pressure:0,bend:0};
  let recording = null, recordAudio = null, recordPreview = null, recordRequest = 0, recordTimer = null, deleting = null, actionGuard = 0;
  const engine = new window.FableAudio({getState:() => state, onStatus:say, onStep:onStep, onNote:onNote, onMeters:updateMeters});
  function say(message, error = false) { const el = $('status'); if(el){el.textContent = message;el.classList.toggle('error',error);} }
  function getPath(object,path){return path.split('.').reduce((o,k)=>o?.[k],object);}
  function setPath(object,path,value){const keys=path.split('.');let target=object;for(const key of keys.slice(0,-1)){if(!target[key]||typeof target[key]!=='object')target[key]={};target=target[key];}target[keys.at(-1)]=value;}
  function zone(){return state.zones.find(z=>z.id===state.selectedZone)||state.zones[0]||null;}
  function asset(z=zone()){return z?state.assets.find(a=>a.id===z.assetId):null;}
  function pattern(){return state.patterns[state.selectedPattern];}
  function snapshot(){return S.copy(state);}
  function assetBytes(a){return a.kind==='pcm'?a.frames*a.channels*4:Math.ceil(a.duration*a.sampleRate)*(a.channels||2)*4;}
  function budget(st=state){return st.assets.reduce((n,a)=>n+assetBytes(a),0);}
  function trimHistory(){let unique=new Set(),bytes=0;const count=()=>{unique=new Set();bytes=0;for(const item of [state,...history,...future])for(const a of item.assets)if(a.kind==='pcm'&&!unique.has(a.pcm)){unique.add(a.pcm);bytes+=a.pcm.length*2;}};count();while(history.length>1&&(history.length>30||bytes>128*1024*1024)){history.shift();count();}while(future.length>1&&bytes>128*1024*1024){future.shift();count();}}
  function remember(){history.push(snapshot());future=[];trimHistory();deleting=null;}
  function notify(){try{window.MusicLabHost?.notifyStateChange?.();}catch(_){}}
  function openStorage(){if(window.MusicLabHost)return Promise.resolve(null);if(storageDB)return Promise.resolve(storageDB);if(storageOpening)return storageOpening;storageOpening=new Promise(resolve=>{try{const request=indexedDB.open('fable-instruments-v1',1);let done=false,timer=setTimeout(()=>{done=true;resolve(null);},2500);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('projects'))request.result.createObjectStore('projects');};request.onsuccess=()=>{clearTimeout(timer);const db=request.result;if(done){db.close();return;}storageDB=db;db.onversionchange=()=>{db.close();storageDB=null;storageOpening=null;};resolve(db);};request.onerror=request.onblocked=()=>{clearTimeout(timer);done=true;resolve(null);};}catch(_){resolve(null);}});return storageOpening;}
  function storageTransaction(db,mode,action){return new Promise((resolve,reject)=>{try{const tx=db.transaction('projects',mode),request=action(tx.objectStore('projects'));let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>reject(tx.error||new Error('Browser storage is unavailable.'));}catch(error){reject(error);}});}
  function persist(){clearTimeout(persistTimer);persistTimer=setTimeout(async()=>{let text;try{text=S.serializeProject(state);}catch(error){say('Save project: '+error.message,true);return;}const db=await openStorage();if(db){try{await storageTransaction(db,'readwrite',store=>store.put(text,'current'));storageOkay=true;return;}catch(_){}}try{localStorage.setItem('fable-project-v1',text);storageOkay=true;}catch(_){storageOkay=false;say('Browser storage cannot keep this instrument. Save project downloads every sample and setting.');}},450);}
  async function recoverStoredProject(){const token=lifecycle,edit=revision,db=await openStorage();if(!db)return;try{const saved=await storageTransaction(db,'readonly',store=>store.get('current'));if(saved&&token===lifecycle&&edit===revision){const next=S.parseProject(saved);state=next;engine.setState(state);renderKeyboard();render();say('Your saved stock is ready for service.');}}catch(_){if(token===lifecycle&&edit===revision)say('Stored stock could not be opened. Save instrument keeps a portable copy.');}}
  function commit(redraw=true){revision++;engine.setState(state);persist();notify();if(redraw)render();else refreshFields();}
  function releaseHeld(){for(const [key,item]of held){engine.noteOff(item.note,{source:item.source});held.delete(key);}sustain=false;engine.setSustain(false);if($('sustain'))$('sustain').classList.remove('active');}
  function stop(){actionGuard++;engine.stop();releaseHeld();playing=false;updateTransport();onStep(-1);}
  function panic(){lifecycle++;actionGuard++;stop();engine.panic();noteVoices.clear();expression={wheel:0,pressure:0,bend:0};engine.setExpression(expression);cancelRecording();window.MusicLabExchange?.stopPreview?.();refreshKeys();say('All voices, echoes, and held notes are silent. The line is clear.');}
  async function prepare(){await engine.init();engine.setState(state);return engine;}
  async function play(){const request=++actionGuard;await prepare();if(request!==actionGuard)return;const started=await engine.start();if(request!==actionGuard||started===false)return;playing=true;updateTransport();}
  async function togglePlay(){if(playing){stop();return;}try{await play();}catch(error){say(error.message,true);}}
  function updateTransport(){if($('play')){const label=$('play').querySelector('span');if(label)label.textContent=playing?'Pause':'Play';else $('play').textContent=playing?'Pause':'Play';$('play').classList.toggle('active',playing);$('play').setAttribute('aria-pressed',String(playing));}}
  function undo(){if(!history.length)return;stop();lifecycle++;future.push(snapshot());state=history.pop();selectedStep=0;zoom={start:0,end:1};renderKeyboard();commit();say('The previous inventory has been restored.');}
  function redo(){if(!future.length)return;stop();lifecycle++;history.push(snapshot());state=future.pop();selectedStep=0;zoom={start:0,end:1};renderKeyboard();commit();say('The next inventory has been restored.');}
  function loadState(value,{keepHistory=true}={}){const candidate=value?.format?S.parseProject(JSON.stringify(value)):S.normalize(value);if(keepHistory)remember();stop();lifecycle++;cancelRecording();state=candidate;selectedStep=0;sequencePage=0;zoom={start:0,end:1};renderKeyboard();commit();say('Instrument opened, samples and all four patterns included.');return snapshot();}
  const field = (label,path,min,max,step=1,kind='master',type='range') => '<label class="field"><span>'+escape(label)+' <output data-output="'+escape(path)+'"></output></span><input type="'+type+'" data-'+kind+'-field="'+escape(path)+'" min="'+min+'" max="'+max+'" step="'+step+'"></label>';
  const select = (label,path,options,kind='master') => '<label class="field"><span>'+escape(label)+'</span><select data-'+kind+'-field="'+escape(path)+'">'+options.map(o=>'<option value="'+escape(Array.isArray(o)?o[0]:o)+'">'+escape(Array.isArray(o)?o[1]:o)+'</option>').join('')+'</select></label>';
  const toggle = (label,path,kind='zone') => '<label class="field toggle-field"><span>'+escape(label)+'</span><input type="checkbox" data-'+kind+'-field="'+escape(path)+'"></label>';
  function createDynamicControls(){
    if($('masterControls'))$('masterControls').innerHTML='<div class="control-grid">'+field('Output','level',0,1,.01)+field('Transpose','transpose',-36,36,1)+field('Fine tune · cents','tune',-100,100,1)+select('Polyphony','polyphony',[8,16,24,32,48,64])+field('Bend range · semitones','bendRange',1,24,1)+field('Velocity response','velocityCurve',.25,3,.01)+field('Drive','drive',0,1,.01)+field('Chorus','chorus',0,1,.01)+field('Echo','delay',0,1,.01)+field('Feedback','feedback',0,.85,.01)+select('Echo time · beats','delaySync',[[.125,'1/32'],[.25,'1/16'],[.375,'Dotted 1/16'],[.5,'1/8'],[.75,'Dotted 1/8'],[1,'1/4'],[1.5,'Dotted 1/4'],[2,'1/2']])+field('Space','space',0,1,.01)+field('Tone · Hz','tone',200,20000,10)+field('Stereo width','width',0,2,.01)+'</div>';
    if($('performanceControls'))$('performanceControls').innerHTML='<div class="control-grid">'+select('Transport plays','mode',[['sequence','Step sequence'],['arp','Held-note arpeggiator']],'performance')+select('Arpeggio direction','arpMode',[['up','Up'],['down','Down'],['updown','Up / down'],['random','Random'],['asplayed','As played'],['chord','Chord']],'performance')+toggle('Latch held notes','hold','performance')+field('Arpeggio octaves','octaves',1,4,1,'performance','number')+select('Arpeggio division','division',[[.125,'1/32'],[.25,'1/16'],[.5,'1/8'],[1,'1/4']],'performance')+field('Arpeggio gate','gate',.05,1,.01,'performance')+field('Arpeggio velocity','velocity',.05,1,.01,'performance')+'</div>';
    if($('lfoControls'))$('lfoControls').innerHTML=[0,1].map(i=>'<div class="control-group"><h4>LFO '+(i+1)+'</h4><div class="control-grid">'+select('Shape',i+':shape',['sine','triangle','square','random'],'lfo')+field('Rate · Hz',i+':rate',.01,20,.01,'lfo')+toggle('Tempo sync',i+':sync','lfo')+select('Period · beats',i+':division',[[.125,'1/32'],[.25,'1/16'],[.5,'1/8'],[1,'1/4'],[2,'1/2'],[4,'1 bar'],[8,'2 bars'],[16,'4 bars']],'lfo')+field('Depth',i+':depth',0,1,.01,'lfo')+toggle('Retrigger on note',i+':retrigger','lfo')+'</div></div>').join('');
    if($('modRoutes'))$('modRoutes').innerHTML=Array.from({length:8},(_,i)=>'<div class="mod-route control-grid"><span class="route-number">'+String(i+1).padStart(2,'0')+'</span>'+select('Source',i+':source',[['off','Off'],['lfo1','LFO 1'],['lfo2','LFO 2'],['velocity','Velocity'],['key','Key position'],['wheel','Mod wheel'],['pressure','Pressure'],['random','Per-note random'],['envelope','Amplitude envelope']],'route')+select('Destination',i+':target',['pitch','cutoff','pan','level','start','position'],'route')+field('Amount',i+':amount',-1,1,.01,'route')+'</div>').join('');
    if($('sampleControls')&&!$('sampleControls').children.length)$('sampleControls').innerHTML='<div class="control-grid">'+field('Root note','root',0,127,1,'zone','number')+field('Low key','low',0,127,1,'zone','number')+field('High key','high',0,127,1,'zone','number')+field('Low velocity','velLow',1,127,1,'zone','number')+field('High velocity','velHigh',1,127,1,'zone','number')+field('Level','level',0,2,.01,'zone')+field('Pan','pan',-1,1,.01,'zone')+field('Width','width',0,2,.01,'zone')+field('Transpose','transpose',-48,48,1,'zone')+field('Tune · cents','tune',-100,100,1,'zone')+select('Engine','engine',[['classic','Classic sampler'],['texture','Texture / granular']],'zone')+select('Playback','playMode',[['gate','Gate'],['oneshot','One shot']],'zone')+select('Loop mode','loopMode',[['off','Off'],['forward','Forward'],['pingpong','Ping pong']],'zone')+toggle('Pitch tracking','tracking')+toggle('Reverse','reverse')+toggle('Enabled','enabled')+field('Loop crossfade · s','crossfade',0,.2,.001,'zone')+field('Time stretch','stretch',.125,8,.01,'zone')+field('Grain size · s','grainSize',.01,.4,.001,'zone')+field('Grain density','grainDensity',2,48,1,'zone')+field('Grain jitter','jitter',0,.5,.001,'zone')+field('Texture position','position',0,1,.001,'zone')+field('Choke group','choke',0,8,1,'zone','number')+field('Round robin group','roundRobin',0,8,1,'zone','number')+'</div>';
    if($('envelopeControls')&&!$('envelopeControls').children.length)$('envelopeControls').innerHTML='<div class="control-grid">'+['attack','decay','sustain','release'].map(p=>field('Amplitude '+p,'envelope.'+p,0,p==='sustain'?1:8,.001,'zone')).join('')+select('Filter type','filter.type',['lowpass','highpass','bandpass','notch'],'zone')+field('Cutoff · Hz','filter.cutoff',20,20000,1,'zone')+field('Resonance','filter.q',.1,20,.1,'zone')+field('Filter drive','filter.drive',0,1,.01,'zone')+field('Key tracking','filter.keytrack',-1,1,.01,'zone')+field('Velocity tracking','filter.velocity',-1,1,.01,'zone')+field('Envelope · octaves','filter.amount',-8,8,.1,'zone')+['attack','decay','sustain','release'].map(p=>field('Filter '+p,'filter.envelope.'+p,0,p==='sustain'?1:8,.001,'zone')).join('')+'</div>';
  }
  function formatValue(path,value){if(typeof value==='boolean')return value?'On':'Off';if(typeof value!=='number')return value??'';if(['root','low','high','note'].includes(path))return noteName(value)+' · '+Math.round(value);if(path.endsWith('cutoff')||path==='tone')return value>=1000?(value/1000).toFixed(1)+' kHz':Math.round(value)+' Hz';if(path.includes('attack')||path.includes('decay')||path.includes('release')||path.includes('grainSize')||path==='crossfade')return value<1?Math.round(value*1000)+' ms':value.toFixed(2)+' s';return Number.isInteger(value)?String(value):value.toFixed(3).replace(/0+$/,'').replace(/\.$/,'');}
  function fieldValue(el){if(el.type==='checkbox')return el.checked;if(el.tagName==='SELECT'){const n=Number(el.value);return el.value!==''&&Number.isFinite(n)?n:el.value;}if(el.type==='color'||el.type==='text')return el.value;return Number(el.value);}
  function fieldObject(el){for(const kind of ['zone','master','performance','lfo','route','step']){const path=el.dataset[kind+'Field'];if(path===undefined)continue;if(kind==='zone')return{object:zone(),path,kind};if(kind==='master')return{object:state.master,path,kind};if(kind==='performance')return{object:state.performance,path,kind};if(kind==='step')return{object:pattern().steps[selectedStep],path,kind};const [index,...parts]=path.split(':');return{object:kind==='lfo'?state.lfos[Number(index)]:state.modulation[Number(index)],path:parts.join(':'),kind};}return null;}
  function refreshFields(){document.querySelectorAll('[data-zone-field],[data-master-field],[data-performance-field],[data-lfo-field],[data-route-field],[data-step-field]').forEach(el=>{const info=fieldObject(el);if(!info?.object){el.disabled=true;return;}el.disabled=info.kind==='zone'&&['stretch','grainSize','grainDensity','jitter','position'].includes(info.path)&&info.object.engine!=='texture';const value=getPath(info.object,info.path);if(document.activeElement!==el){if(el.type==='checkbox')el.checked=!!value;else el.value=value??'';}const output=el.closest('.field')?.querySelector('output');if(output)output.textContent=formatValue(info.path,value);});if($('undo'))$('undo').disabled=!history.length;if($('redo'))$('redo').disabled=!future.length;}
  function zoneAdjust(z,path){if(path==='low'&&z.low>z.high)z.high=z.low;if(path==='high'&&z.high<z.low)z.low=z.high;if(path==='velLow'&&z.velLow>z.velHigh)z.velHigh=z.velLow;if(path==='velHigh'&&z.velHigh<z.velLow)z.velLow=z.velHigh;if(path==='start'&&z.start>=z.end)z.start=Math.max(0,z.end-.0001);if(path==='end'&&z.end<=z.start)z.end=Math.min(1,z.start+.0001);const epsilon=Math.min(.0001,(z.end-z.start)/4);z.loopStart=clamp(z.loopStart,z.start,z.end-epsilon);z.loopEnd=clamp(z.loopEnd,z.loopStart+epsilon,z.end);}
  const editing=new WeakSet();
  document.addEventListener('input',e=>{const el=e.target,info=fieldObject(el);if(!info?.object)return;let value=fieldValue(el);if(typeof value==='number'){if(!Number.isFinite(value))return;if(el.hasAttribute('min'))value=Math.max(Number(el.min),value);if(el.hasAttribute('max'))value=Math.min(Number(el.max),value);if(el.step==='1')value=Math.round(value);}if(!editing.has(el)){remember();editing.add(el);}setPath(info.object,info.path,value);if(info.kind==='zone')zoneAdjust(info.object,info.path);commit(false);if(info.kind==='zone'){drawWave();drawMap();drawEnvelopes();renderZoneList();}if(info.kind==='step')renderSteps();});
  document.addEventListener('change',e=>{const info=fieldObject(e.target);if(info){editing.delete(e.target);render();}});
  function renderZoneList(){if(!$('zoneList'))return;$('zoneList').innerHTML=state.zones.map((z,i)=>'<button type="button" class="zone-item zone-card'+(z.id===state.selectedZone?' selected':'')+(!z.enabled?' muted':'')+'" data-zone="'+escape(z.id)+'" aria-pressed="'+(z.id===state.selectedZone)+'"><i class="zone-color" style="--zone-color:'+escape(z.color||'#ff8d45')+';background:'+escape(z.color||'#ff8d45')+'"></i><span class="zone-name">'+escape(z.name||'Zone '+(i+1))+'</span><span class="zone-meta">'+noteName(z.low)+'–'+noteName(z.high)+' · v '+z.velLow+'–'+z.velHigh+(z.roundRobin?' · RR '+z.roundRobin:'')+'</span></button>').join('');}
  function renderSteps(){if(!$('steps'))return;const p=pattern(),start=sequencePage*16;$('steps').innerHTML=Array.from({length:Math.min(16,p.length-start)},(_,i)=>{const ix=i+start,step=p.steps[ix];return'<button type="button" class="step'+(step.on?' on':'')+(selectedStep===ix?' selected':'')+'" data-step="'+ix+'" aria-label="Step '+(ix+1)+', '+noteName(step.note)+', '+(step.on?'on':'off')+'" aria-pressed="'+step.on+'"><span class="step-number">'+String(ix+1).padStart(2,'0')+'</span><span class="step-note">'+noteName(step.note)+'</span><i class="step-velocity" style="width:'+Math.round(step.velocity*100)+'%"></i></button>';}).join('');if($('stepPageLabel'))$('stepPageLabel').textContent='Steps '+(start+1)+'–'+Math.min(p.length,start+16);if($('stepPagePrev'))$('stepPagePrev').disabled=sequencePage===0;if($('stepPageNext'))$('stepPageNext').disabled=(sequencePage+1)*16>=p.length;}
  function renderStepEditor(){if(!$('stepEditor'))return;$('stepEditor').innerHTML='<span class="step-label">STEP '+String(selectedStep+1).padStart(2,'0')+'</span><div class="control-grid">'+toggle('Enabled','on','step')+field('Note','note',0,127,1,'step','number')+field('Velocity','velocity',.01,1,.01,'step')+field('Gate','gate',.02,1,.01,'step')+field('Probability','probability',0,1,.01,'step')+field('Ratchets','ratchet',1,8,1,'step','number')+'</div>';}
  function renderKeyboard(){if(!$('keyboard'))return;const first=clamp(state.keyOctave*12,0,96),last=state.keyOctave===8?127:first+24,whites=[];for(let n=first;n<=last;n++)if(![1,3,6,8,10].includes(n%12))whites.push(n);let html='';for(let n=first;n<=last;n++){const black=[1,3,6,8,10].includes(n%12),index=whites.filter(k=>k<n).length,left=black?(index/whites.length*100-2.1):(whites.indexOf(n)/whites.length*100);html+='<button type="button" class="key '+(black?'black':'white')+'" data-note="'+n+'" aria-label="Play '+noteName(n)+'" aria-pressed="false" style="left:'+left+'%;width:'+(black?4.2:100/whites.length)+'%"><span>'+noteName(n)+'</span></button>';}$('keyboard').innerHTML=html;if($('octaveLabel'))$('octaveLabel').textContent=noteName(first)+'–'+noteName(last);refreshKeys();}
  function refreshKeys(){document.querySelectorAll('.key[data-note]').forEach(el=>{const note=Number(el.dataset.note),active=Array.from(held.values()).some(h=>h.note===note)||(noteVoices.get(note)?.size||0)>0;el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});}
  function render(){const z=zone(),a=asset(z);if($('stockPlayingLabel'))$('stockPlayingLabel').textContent=state.name+' · '+state.zones.length+' '+(state.zones.length===1?'zone':'zones');if($('projectName')&&document.activeElement!==$('projectName'))$('projectName').value=state.name;if($('tempo')&&document.activeElement!==$('tempo'))$('tempo').value=state.tempo;if($('swing')&&document.activeElement!==$('swing'))$('swing').value=state.swing;if($('zoneCount'))$('zoneCount').textContent=state.zones.length+' / '+MAX_ZONES+' zones';if($('assetBudget'))$('assetBudget').textContent=state.assets.length+' / '+MAX_ASSETS+' samples · '+(budget()/1048576).toFixed(1)+' / 64 MB';if($('selectedZoneName'))$('selectedZoneName').textContent=z?.name||'No sample selected';if($('selectedZoneInfo'))$('selectedZoneInfo').textContent=a?(a.name+' · '+Number(a.duration).toFixed(2)+' s · '+(a.channels===1?'MONO':'STEREO')+' · '+noteName(z.root)):'Import a sound, or choose a sample zone.';if($('reuseAsset')){const previous=$('reuseAsset').value;$('reuseAsset').innerHTML='<option value="">Reuse a sample…</option>'+state.assets.map(a=>'<option value="'+escape(a.id)+'">'+escape(a.name)+'</option>').join('');$('reuseAsset').value=previous;}if($('patternSelect'))$('patternSelect').value=state.selectedPattern;if($('patternLength'))$('patternLength').value=pattern().length;selectedStep=Math.min(selectedStep,pattern().length-1);sequencePage=Math.min(sequencePage,Math.ceil(pattern().length/16)-1);renderZoneList();renderSteps();renderStepEditor();refreshFields();drawWave();drawMap();drawEnvelopes();updateTransport();if($('deleteZone'))$('deleteZone').disabled=!z;if($('duplicateZone'))$('duplicateZone').disabled=!z||state.zones.length>=MAX_ZONES;}
  function onNote(event){if(!event)return;const set=noteVoices.get(event.note)||new Set();if(event.on)set.add(event.voiceId??event.zoneId);else set.delete(event.voiceId??event.zoneId);if(set.size)noteVoices.set(event.note,set);else noteVoices.delete(event.note);refreshKeys();}
  function onStep(index){document.querySelectorAll('[data-step]').forEach(el=>el.classList.toggle('current',Number(el.dataset.step)===index));if(index>=0&&$('sequencePosition'))$('sequencePosition').textContent=String(index+1).padStart(2,'0')+' / '+pattern().length;}
  function updateMeters(m){if(!m)return;const peak=Math.max(0,Number(m.peak)||0);if($('peakMeter'))$('peakMeter').style.width=Math.min(100,Math.max(0,(20*Math.log10(Math.max(1e-6,peak))+60)/60*100))+'%';if($('peakReadout'))$('peakReadout').textContent=peak>1e-5?Math.round(20*Math.log10(peak))+' dB':'−∞ dB';if($('voiceCount'))$('voiceCount').textContent=(m.voices||0)+' / '+state.master.polyphony+' voices';if(typeof m.playing==='boolean'&&m.playing!==playing){playing=m.playing;updateTransport();}}
  function canvasSize(canvas,height){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,window.devicePixelRatio||1),width=Math.max(1,rect.width),h=rect.height||height;if(canvas.width!==Math.round(width*ratio)||canvas.height!==Math.round(h*ratio)){canvas.width=Math.round(width*ratio);canvas.height=Math.round(h*ratio);}const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,width,height:h};}
  function selectedAudio(){const a=asset();if(!a)return null;return engine.getAssetAudio(a);}
  // Decoded sample data is immutable; trim and envelope edits only move visual overlays.
  const waveformPeaks = new WeakMap();
  function displayPeaks(audio,width,start,end){const left=audio.left,right=audio.right,range=end-start;let cached=waveformPeaks.get(left);if(cached&&cached.right===right&&cached.width===width&&cached.start===start&&cached.end===end)return cached.values;const values=new Float32Array(Math.ceil(width)*2),frames=left.length;for(let x=0;x<width;x++){const a=Math.floor((start+x/width*range)*frames),b=Math.min(frames,Math.ceil((start+(x+1)/width*range)*frames)),stride=Math.max(1,Math.floor((b-a)/64));let lo=0,hi=0;for(let i=a;i<b;i+=stride){lo=Math.min(lo,left[i],right?.[i]??0);hi=Math.max(hi,left[i],right?.[i]??0);}values[x*2]=lo;values[x*2+1]=hi;}waveformPeaks.set(left,{right,width,start,end,values});return values;}
  function drawWave(){const canvas=$('waveform'),z=zone();if(!canvas)return;const {ctx,width,height}=canvasSize(canvas,190);ctx.clearRect(0,0,width,height);ctx.fillStyle='#141719';ctx.fillRect(0,0,width,height);let audio;try{audio=selectedAudio();}catch(error){say(error.message,true);return;}if(!audio||!z)return;const left=audio.left,range=zoom.end-zoom.start,toX=v=>(v-zoom.start)/range*width;ctx.strokeStyle='#ffffff0c';ctx.lineWidth=1;for(let row=1;row<4;row++){ctx.beginPath();ctx.moveTo(0,height*row/4);ctx.lineTo(width,height*row/4);ctx.stroke();}const start=toX(z.start),end=toX(z.end);ctx.fillStyle='#ff8d450d';ctx.fillRect(start,0,end-start,height);if(z.loopMode!=='off'){ctx.fillStyle='#f3cb4f15';ctx.fillRect(toX(z.loopStart),0,toX(z.loopEnd)-toX(z.loopStart),height);}ctx.strokeStyle=z.color||'#ff8d45';ctx.beginPath();const peaks=displayPeaks(audio,width,zoom.start,zoom.end);for(let x=0;x<width;x++){const lo=peaks[x*2],hi=peaks[x*2+1];ctx.moveTo(x+.5,height/2-hi*height*.42);ctx.lineTo(x+.5,height/2-lo*height*.42);}ctx.stroke();for(const [path,color,label]of[['start','#ff8d45','START'],['end','#ff8d45','END'],['loopStart','#f3cb4f','LOOP IN'],['loopEnd','#f3cb4f','LOOP OUT']]){if(path.startsWith('loop')&&z.loopMode==='off')continue;const x=toX(z[path]);if(x<0||x>width)continue;ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();ctx.fillStyle=color;ctx.fillRect(x-4,0,8,10);ctx.font='9px monospace';ctx.fillText(label,Math.max(4,Math.min(width-58,x+5)),height-9);}if($('waveformInfo'))$('waveformInfo').textContent=((z.end-z.start)*audio.duration).toFixed(3)+' s selected · '+(1/range).toFixed(1)+'× zoom';}
  function drawMap(){const canvas=$('zoneMap');if(!canvas)return;const {ctx,width,height}=canvasSize(canvas,124);ctx.clearRect(0,0,width,height);ctx.fillStyle='#141719';ctx.fillRect(0,0,width,height);for(let n=0;n<=128;n+=12){ctx.strokeStyle='#ffffff0a';ctx.beginPath();ctx.moveTo(n/128*width,0);ctx.lineTo(n/128*width,height);ctx.stroke();if(n<128){ctx.fillStyle='#8b9499';ctx.font='8px monospace';ctx.fillText(noteName(n),n/128*width+2,height-4);}}state.zones.filter(z=>z.enabled).forEach(z=>{const x=z.low/128*width,w=Math.max(2,(z.high-z.low+1)/128*width),y=(127-z.velHigh)/127*(height-18),h=Math.max(3,(z.velHigh-z.velLow+1)/127*(height-18));ctx.fillStyle=z.color||'#ff8d45';ctx.globalAlpha=z.id===state.selectedZone?.45:.18;ctx.fillRect(x,y,w,h);ctx.globalAlpha=1;ctx.strokeStyle=z.id===state.selectedZone?'#efe6d4':z.color||'#ff8d45';ctx.lineWidth=z.id===state.selectedZone?1.5:1;ctx.strokeRect(x+.5,y+.5,w-1,h-1);ctx.fillStyle='#efe6d4';ctx.font='8px monospace';if(w>35&&z.id===state.selectedZone)ctx.fillText(z.name.slice(0,18),x+4,y+Math.min(h-2,12));const root=z.root/128*width;ctx.fillStyle='#f3cb4f';ctx.fillRect(root,y,2,Math.min(h,8));});ctx.globalAlpha=1;}
  function drawEnvelopes(){const z=zone();if(!z)return;for(const [id,envelope]of [['amplitudeEnvelope',z.envelope],['filterEnvelope',z.filter.envelope]]){const canvas=$(id);if(!canvas)continue;const {ctx,width,height}=canvasSize(canvas,90),padding=12,w=width-padding*2,h=height-28;ctx.clearRect(0,0,width,height);ctx.fillStyle='#141719';ctx.fillRect(0,0,width,height);const heldTime=Math.max(.08,Math.min(1,(envelope.attack+envelope.decay+envelope.release)*.2)),total=envelope.attack+envelope.decay+envelope.release+heldTime,at=seconds=>padding+seconds/total*w,level=value=>padding+(1-value)*h;const points=[[0,0],[envelope.attack,1],[envelope.attack+envelope.decay,envelope.sustain],[envelope.attack+envelope.decay+heldTime,envelope.sustain],[total,0]];ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(at(x),level(y)):ctx.moveTo(at(x),level(y)));ctx.lineTo(at(total),level(0));ctx.lineTo(at(0),level(0));ctx.closePath();ctx.fillStyle=id==='amplitudeEnvelope'?'#ff8d4521':'#f3cb4f21';ctx.fill();ctx.strokeStyle=id==='amplitudeEnvelope'?'#ff8d45':'#f3cb4f';ctx.lineWidth=1.5;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(at(x),level(y)):ctx.moveTo(at(x),level(y)));ctx.stroke();ctx.fillStyle='#8b9499';ctx.font='8px monospace';const phases=[['A',envelope.attack/2],['D',envelope.attack+envelope.decay/2],['S',envelope.attack+envelope.decay+heldTime/2],['R',total-envelope.release/2]];for(const [label,time]of phases)ctx.fillText(label,at(time)-2,height-5);}}
  function selectZone(id){if(!state.zones.some(z=>z.id===id))return;state.selectedZone=id;zoom={start:0,end:1};deleting=null;commit();}
  function zeroCross(position,audio=selectedAudio()){if(!audio)return position;const data=audio.left,at=Math.floor(position*data.length),radius=Math.max(16,Math.min(2048,Math.ceil(audio.sampleRate*.008)));let best=at,score=Infinity;for(let i=Math.max(1,at-radius);i<Math.min(data.length-1,at+radius);i++){if((data[i-1]<=0&&data[i]>=0)||(data[i-1]>=0&&data[i]<=0)){const cost=Math.abs(i-at)+Math.abs(audio.right?.[i]||0)*radius*.1;if(cost<score){score=cost;best=i;}}}return clamp(best/data.length,0,1);}
  if($('waveform')){$('waveform').addEventListener('pointerdown',e=>{const z=zone();if(!z)return;const r=e.currentTarget.getBoundingClientRect(),at=zoom.start+clamp((e.clientX-r.left)/r.width,0,1)*(zoom.end-zoom.start);const paths=['start','end',...(z.loopMode!=='off'?['loopStart','loopEnd']:[])];const nearest=paths.map(path=>({path,distance:Math.abs(z[path]-at)/(zoom.end-zoom.start)*r.width})).sort((a,b)=>a.distance-b.distance)[0];if(nearest.distance>20){const span=zoom.end-zoom.start;zoom.start=clamp(at-span/2,0,1-span);zoom.end=zoom.start+span;drawWave();return;}waveDrag={path:nearest.path,pointer:e.pointerId};dragHistory=false;e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault();});$('waveform').addEventListener('pointermove',e=>{if(!waveDrag||waveDrag.pointer!==e.pointerId)return;if(!dragHistory){remember();dragHistory=true;}const r=e.currentTarget.getBoundingClientRect(),z=zone();let at=zoom.start+clamp((e.clientX-r.left)/r.width,0,1)*(zoom.end-zoom.start);if(e.shiftKey||$('snapZero')?.checked)at=zeroCross(at);z[waveDrag.path]=at;zoneAdjust(z,waveDrag.path);commit(false);drawWave();});const release=()=>{waveDrag=null;dragHistory=false;render();};$('waveform').addEventListener('pointerup',release);$('waveform').addEventListener('pointercancel',release);}
  if($('zoneMap'))$('zoneMap').addEventListener('pointerdown',e=>{const r=e.currentTarget.getBoundingClientRect(),note=clamp(Math.floor((e.clientX-r.left)/r.width*128),0,127),velocity=clamp(Math.round(127-(e.clientY-r.top)/(r.height-18)*127),1,127);const candidates=state.zones.filter(z=>z.enabled&&note>=z.low&&note<=z.high&&velocity>=z.velLow&&velocity<=z.velHigh);if(candidates.length){const ix=candidates.findIndex(z=>z.id===state.selectedZone);selectZone(candidates[(ix+1)%candidates.length].id);}});
  function interleave(value){if(value.pcm instanceof Float32Array&&!Array.isArray(value.pcm))return value.pcm;const left=value.left||value.pcm?.[0],right=value.right||value.pcm?.[1]||left;if(!(left instanceof Float32Array)||!(right instanceof Float32Array)||left.length!==right.length)throw new Error('Expected finite mono or stereo audio.');const pcm=new Float32Array(left.length*2);for(let i=0;i<left.length;i++){pcm[i*2]=left[i];pcm[i*2+1]=right[i];}return pcm;}
  function pitchFromPCM(pcm,sampleRate){const frames=pcm.length/2,stride=Math.max(1,Math.floor(frames/24000));let strongest=0,peakAt=0;for(let i=0;i<frames;i+=stride){const level=Math.max(Math.abs(pcm[i*2]),Math.abs(pcm[i*2+1]));if(level>strongest){strongest=level;peakAt=i;}}if(strongest<.0003)return null;const count=Math.min(frames,Math.ceil(sampleRate*.6)),start=Math.max(0,Math.min(frames-count,peakAt-Math.floor(count*.15))),left=new Float32Array(count),right=new Float32Array(count);for(let i=0;i<count;i++){left[i]=pcm[(start+i)*2];right[i]=pcm[(start+i)*2+1];}return S.detectPitch({left,right,sampleRate});}
  function collectUnused(st){const used=new Set(st.zones.map(z=>z.assetId));st.assets=st.assets.filter(a=>used.has(a.id));}
  function buildImportCandidate(items,options={}){if(!items.length)throw new Error('No audio was selected.');const candidate=snapshot(),target=String(options.target??'new'),existing=target==='new'?null:candidate.zones.find(z=>z.id===target);if(target!=='new'&&!existing)throw new Error('The selected destination no longer exists.');if(existing&&!options.replace)throw new Error('Confirm replacement before changing an existing zone.');if(existing&&items.length!==1)throw new Error('Batch imports need a new sample destination.');const previousAssetId=existing?.assetId;const newAssets=items.map((item,index)=>S.encodeAsset({pcm:item.pcm,sampleRate:item.sampleRate,name:item.name||'Incoming ingredient',root:options.root!==undefined?clamp(Math.round(options.root)+index,0,127):item.root??60}));if(existing){existing.assetId=newAssets[0].id;existing.name=newAssets[0].name;existing.start=0;existing.end=1;existing.loopStart=.1;existing.loopEnd=.9;existing.position=0;if(options.root!==undefined)existing.root=clamp(Math.round(options.root),0,127);candidate.selectedZone=existing.id;}else for(const [index,a]of newAssets.entries()){const overrides={tune:-(items[index].cents||0)};if(options.root!==undefined){overrides.root=clamp(Math.round(options.root)+index,0,127);overrides.low=overrides.high=overrides.root;}const z=S.createZone(a,overrides);candidate.zones.push(z);candidate.selectedZone=z.id;}candidate.assets.push(...newAssets);if(previousAssetId&&!candidate.zones.some(z=>z.assetId===previousAssetId))candidate.assets=candidate.assets.filter(a=>a.id!==previousAssetId);if(candidate.zones.length>MAX_ZONES)throw new Error('STOCK supports up to '+MAX_ZONES+' zones. Delete a zone first.');if(candidate.assets.length>MAX_ASSETS)throw new Error('STOCK supports up to '+MAX_ASSETS+' unique samples. Reuse an existing sample or delete unused zones.');if(budget(candidate)>MAX_BYTES)throw new Error('The decoded sample budget is 64 MB. Trim audio or remove unused zones first.');return S.normalize(candidate);}
  async function importAudio({pcm,sampleRate,name='Incoming ingredient',tempo,options={},signal}={}){signal=signal||options.signal;if(signal?.aborted)throw new DOMException('Import cancelled.','AbortError');if(importBusy)throw new Error('Another import is in progress.');importBusy=true;const token=lifecycle,edit=revision;try{if(Object.prototype.toString.call(pcm)!=='[object Float32Array]'||!pcm.length||pcm.length%2)throw new Error('Expected interleaved stereo Float32 audio.');if(!Number.isFinite(sampleRate)||sampleRate<8000||sampleRate>192000)throw new Error('Sample rate must be 8–192 kHz.');if(pcm.length/2/sampleRate>120+1e-6)throw new Error('Trim the sample to 120 seconds or less before importing.');const item={pcm,sampleRate,name};if(String(options.target??'new')==='new'&&options.root===undefined){const pitch=pitchFromPCM(pcm,sampleRate);if(pitch&&pitch.confidence>=.8){item.root=pitch.note;item.cents=pitch.cents;}}const candidate=buildImportCandidate([item],options);await new Promise(resolve=>setTimeout(resolve,0));if(signal?.aborted||token!==lifecycle)throw new DOMException('Import cancelled.','AbortError');if(edit!==revision)throw new Error('The instrument changed while importing. Try receiving the sample again.');remember();state=candidate;zoom={start:0,end:1};commit();say(name+' filed in '+zone().name+'. Undo restores the previous instrument.');return{zoneId:state.selectedZone,assetId:zone().assetId,duration:asset().duration};}finally{importBusy=false;}}
  async function decodeFile(file,signal){if(signal?.aborted)throw new DOMException('Import cancelled.','AbortError');if(file.size>96*1024*1024)throw new Error('Audio files must be smaller than 96 MB.');if(window.MusicLabExchange?.decodeFile){const a=await window.MusicLabExchange.decodeFile(file);if(signal?.aborted)throw new DOMException('Import cancelled.','AbortError');return{pcm:interleave(a),sampleRate:a.sampleRate,name:a.name||file.name.replace(/\.[^.]+$/,'')};}await prepare();const audio=await engine.context.decodeAudioData(await file.arrayBuffer()),left=audio.getChannelData(0),right=audio.numberOfChannels>1?audio.getChannelData(1):left;return{pcm:interleave({left,right}),sampleRate:audio.sampleRate,name:file.name.replace(/\.[^.]+$/,'')};}
  async function importFiles(files,options={}){if(!files?.length)return;if(importBusy){say('An import is already in progress.',true);return;}importBusy=true;const token=lifecycle,edit=revision;try{if(files.length>MAX_ASSETS)throw new Error('Import no more than 32 files at once.');const audio=[];for(const f of files){say('Opening '+f.name+'…');const a=await decodeFile(f);if(token!==lifecycle)throw new DOMException('Import cancelled.','AbortError');if(a.pcm.length/2/a.sampleRate>120+1e-6)throw new Error(f.name+' exceeds 120 seconds. Use Samples → Receive audio to trim it first.');if(options.root===undefined){const pitch=pitchFromPCM(a.pcm,a.sampleRate);if(pitch&&pitch.confidence>=.8){a.root=pitch.note;a.cents=pitch.cents;}}audio.push(a);if(audio.reduce((n,item)=>n+item.pcm.byteLength,0)>MAX_BYTES)throw new Error('This batch exceeds the 64 MB decoded-audio budget.');}const candidate=buildImportCandidate(audio,{target:'new',...options});if(token!==lifecycle)throw new DOMException('Import cancelled.','AbortError');if(edit!==revision)throw new Error('The instrument changed while importing. Try importing these files again.');remember();state=candidate;zoom={start:0,end:1};commit();say(audio.length+' sample'+(audio.length===1?'':'s')+(options.root!==undefined?' assigned from '+noteName(Number(options.root))+'. Consecutive keys play each sample.':' imported. Pitched roots were detected where possible; Auto-map keys or build velocity layers.'));}catch(error){if(error.name!=='AbortError')say('Import: '+error.message,true);}finally{importBusy=false;}}
  async function exportAudio({scope='zone',bars=1,tailSeconds=0,signal,...options}={}){const st=snapshot();if(signal?.aborted)throw new DOMException('Render cancelled.','AbortError');if(scope==='source'){const z=st.zones.find(item=>item.id===st.selectedZone),a=st.assets.find(item=>item.id===z?.assetId);if(!a)throw new Error('Select a sample zone first.');const audio=engine.getAssetAudio(a);return{pcm:interleave(audio),sampleRate:audio.sampleRate,name:a.name,tempo:st.tempo,sourceApp:'fable',sourceLabel:'Source sample / unprocessed'};}if(!['zone','pattern'].includes(scope))throw new Error('Choose a zone, pattern, or source export.');return engine.render({state:st,scope,zoneId:st.selectedZone,note:st.zones.find(z=>z.id===st.selectedZone)?.root??60,velocity:velocity(),bars:clamp(Math.round(bars),1,16),tailSeconds:clamp(tailSeconds,0,8),signal,...options});}

  function encodeWav(value){if(window.MusicLabExchange?.encodeWav)return window.MusicLabExchange.encodeWav(value);const pcm=value.pcm,sr=value.sampleRate,channels=2,buffer=new ArrayBuffer(44+pcm.length*2),view=new DataView(buffer),write=(at,s)=>{for(let i=0;i<s.length;i++)view.setUint8(at+i,s.charCodeAt(i));};write(0,'RIFF');view.setUint32(4,36+pcm.length*2,true);write(8,'WAVE');write(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,sr,true);view.setUint32(28,sr*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);write(36,'data');view.setUint32(40,pcm.length*2,true);for(let i=0;i<pcm.length;i++)view.setInt16(44+i*2,Math.round(clamp(pcm[i],-1,1)*(pcm[i]<0?32768:32767)),true);return new Blob([buffer],{type:'audio/wav'});}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'-');document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function bind(id,fn,type='click'){const el=$(id);if(el)el.addEventListener(type,event=>{try{const result=fn(event);if(result?.catch)result.catch(error=>{if(error.name!=='AbortError')say(error.message,true);});}catch(error){say(error.message,true);}});}
  function openDialog(id){const d=$(id);if(!d)return;releaseHeld();d.showModal?d.showModal():d.setAttribute('open','');}
  function closeDialog(id){const d=$(id);if(d?.open)d.close();}
  bind('play',togglePlay);bind('stop',()=>{stop();say('Transport returned to the first step.');});bind('panic',panic);bind('undo',undo);bind('redo',redo);
  bind('tempo',e=>{const n=Number(e.target.value);if(!Number.isFinite(n))return;remember();state.tempo=clamp(n,30,240);commit();},'change');bind('swing',e=>{remember();state.swing=clamp(e.target.value,0,.6);commit();},'change');bind('projectName',e=>{remember();state.name=e.target.value.trim().slice(0,80)||'Untitled stock';commit();},'change');
  if($('presetSelect')){$('presetSelect').innerHTML='<option value="">Choose a house recipe…</option>'+presets.map(p=>'<option value="'+escape(p.id)+'">'+escape(p.name)+'</option>').join('');bind('presetSelect',e=>{const p=presets.find(p=>p.id===e.target.value);if(p){loadState(p.create());say(p.name+' · '+p.description);}} ,'change');}
  bind('newProject',()=>{const next=S.defaultState();next.name='Untitled stock';next.zones=[];next.assets=[];next.selectedZone='';next.patterns.forEach(p=>p.steps.forEach(s=>s.on=false));loadState(next);say('The stock room is empty. Import audio or choose a house preset.');});
  bind('openProject',()=>$('projectFile')?.click());bind('saveProject',()=>{download(new Blob([S.serializeProject(state)],{type:'application/json'}),(state.name||'STOCK')+'.fable.json');say('Portable instrument saved, with every sample and setting.');});
  bind('projectFile',async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const token=lifecycle;if(f.size>(S.MAX_PROJECT_BYTES||64*1024*1024))throw new Error('Project files must be 64 MB or less.');const text=await f.text(),next=S.parseProject(text);if(token===lifecycle)loadState(next);},'change');
  bind('importFiles',()=>$('audioFiles')?.click());bind('audioFiles',e=>{const files=Array.from(e.target.files||[]);e.target.value='';return importFiles(files);},'change');
  bind('addZone',()=>{if(state.zones.length>=MAX_ZONES)throw new Error('The 64-zone cabinet is full.');const a=asset()||state.assets[0];if(!a){$('audioFiles')?.click();return;}remember();const z=S.createZone(a,{name:a.name+' · new zone'});state.zones.push(z);state.selectedZone=z.id;commit();say('New zone reuses the same sample without increasing the audio budget.');});
  bind('reuseAsset',e=>{const a=state.assets.find(a=>a.id===e.target.value);if(!a)return;if(state.zones.length>=MAX_ZONES)throw new Error('The 64-zone cabinet is full.');remember();const z=S.createZone(a);state.zones.push(z);state.selectedZone=z.id;commit();},'change');
  bind('duplicateZone',()=>{const z=zone();if(!z)return;if(state.zones.length>=MAX_ZONES)throw new Error('The 64-zone cabinet is full.');remember();const clone=S.copy(z);clone.id=S.uid('zone');clone.name=z.name+' · twin';state.zones.push(clone);state.selectedZone=clone.id;commit();});
  bind('deleteZone',()=>{const z=zone();if(!z)return;if(deleting!==z.id){deleting=z.id;say('Click Delete zone again to remove '+z.name+'. Other zones using its sample stay intact.');return;}remember();engine.allNotesOff();state.zones=state.zones.filter(item=>item.id!==z.id);collectUnused(state);state.selectedZone=state.zones[0]?.id||'';deleting=null;commit();say('Zone removed. Undo can return it.');});
  bind('zoneList',e=>{const el=e.target.closest('[data-zone]');if(el)selectZone(el.dataset.zone);});
  ['Keys','Velocity','Drums'].forEach(mode=>bind('autoMap'+mode,()=>{remember();state.zones=S.autoMap(state.zones,mode.toLowerCase());commit();say(mode==='Keys'?'Key ranges arranged around each sample’s root.':mode==='Velocity'?'Zones arranged as soft-to-hard velocity layers.':'Zones assigned to consecutive drum keys.');}));
  bind('splitZone',()=>{const z=zone(),a=selectedAudio();if(!z||!a)return;const count=clamp(Math.round($('splitCount')?.value||8),2,32);if(state.zones.length+count-1>MAX_ZONES)throw new Error('Splitting would exceed 64 zones.');const selected={left:a.left.subarray(Math.floor(z.start*a.left.length),Math.ceil(z.end*a.left.length)),right:a.right.subarray(Math.floor(z.start*a.right.length),Math.ceil(z.end*a.right.length)),sampleRate:a.sampleRate};const boundaries=S.onsets(selected,count);if(boundaries.length<3)throw new Error('No useful onset boundaries were found.');remember();const span=z.end-z.start,clones=boundaries.slice(0,-1).map((p,i)=>({...S.copy(z),id:S.uid('zone'),name:z.name+' '+(i+1),start:z.start+p*span,end:z.start+boundaries[i+1]*span,loopMode:'off',playMode:'oneshot',tracking:false,root:clamp(z.root+i,0,127),low:clamp(z.root+i,0,127),high:clamp(z.root+i,0,127),roundRobin:0,choke:0}));state.zones.splice(state.zones.indexOf(z),1,...clones);state.selectedZone=clones[0].id;commit();say(clones.length+' transient zones share one sample. Consecutive keys play each slice.');});
  bind('detectPitch',()=>{const z=zone(),audio=selectedAudio();if(!z||!audio)return;say('Listening for the sample’s fundamental…');const found=S.detectPitch(audio);if(!found||found.confidence<.25){say('No reliable pitched root found. Set the root note manually for noisy or percussive material.');return;}remember();z.root=clamp(found.note,0,127);z.tune=-clamp(found.cents,-100,100);commit();say('Detected '+noteName(found.note)+' · '+found.frequency.toFixed(1)+' Hz · '+Math.round(found.confidence*100)+'% confidence. Root and corrective fine tune set.');});
  bind('trimSilence',()=>{const z=zone(),audio=selectedAudio();if(!z||!audio)return;const bounds=S.trimSilence(audio);remember();z.start=bounds.start;z.end=bounds.end;zoneAdjust(z,'start');commit();say('Quiet margins trimmed. The original sample remains whole.');});
  bind('normalizeGain',()=>{const z=zone(),a=selectedAudio();if(!z||!a)return;let peak=0;for(let i=Math.floor(z.start*a.left.length),end=Math.ceil(z.end*a.left.length);i<end;i++)peak=Math.max(peak,Math.abs(a.left[i]),Math.abs(a.right[i]));if(peak<1e-6)throw new Error('This selection is silent.');remember();z.level=clamp(.95/peak,0,2);commit();say('Zone gain adjusted toward −0.45 dB peak; maximum +6 dB gain.');});
  bind('snapZero',()=>say($('snapZero').checked?'Waveform handles snap to nearby zero crossings.':'Waveform handles move freely; hold Shift to snap temporarily.'));
  function changeZoom(factor){const z=zone(),span=clamp((zoom.end-zoom.start)*factor,.0002,1),center=z?clamp((z.start+z.end)/2,span/2,1-span/2):.5;zoom={start:center-span/2,end:center+span/2};drawWave();}
  bind('zoomIn',()=>changeZoom(.5));bind('zoomOut',()=>changeZoom(2));bind('zoomReset',()=>{zoom={start:0,end:1};drawWave();});bind('auditionZone',async()=>{const z=zone();if(!z)return;await prepare();engine.noteOn(z.root,velocity(),{zoneId:z.id,duration:Math.min(8,Math.max(.2,(z.end-z.start)*asset(z).duration)),source:'preview'});});
  bind('patternSelect',e=>{remember();state.selectedPattern=clamp(Math.round(e.target.value),0,3);selectedStep=0;sequencePage=0;commit();},'change');bind('patternLength',e=>{const n=Number(e.target.value);if(![16,32,64].includes(n))return;remember();pattern().length=n;sequencePage=0;commit();},'change');
  bind('steps',e=>{const el=e.target.closest('[data-step]');if(!el)return;selectedStep=Number(el.dataset.step);if(!e.shiftKey){remember();pattern().steps[selectedStep].on=!pattern().steps[selectedStep].on;commit();}else render();});
  if($('steps'))$('steps').addEventListener('contextmenu',e=>{const el=e.target.closest('[data-step]');if(!el)return;e.preventDefault();selectedStep=Number(el.dataset.step);render();});
  bind('stepPagePrev',()=>{sequencePage=Math.max(0,sequencePage-1);selectedStep=sequencePage*16;render();});bind('stepPageNext',()=>{sequencePage=Math.min(Math.ceil(pattern().length/16)-1,sequencePage+1);selectedStep=sequencePage*16;render();});
  bind('copyPattern',()=>{remember();const target=(state.selectedPattern+1)%4;state.patterns[target]=S.copy(pattern());state.patterns[target].name='Pattern '+String.fromCharCode(65+target);commit();say('Pattern copied into '+String.fromCharCode(65+target)+'.');});
  bind('clearPattern',()=>{remember();pattern().steps.forEach(s=>s.on=false);commit();say('Every step is empty, and yet the staircase remains.');});
  bind('randomizePattern',()=>{remember();const z=zone(),root=z?.root??60,notes=[0,0,3,5,7,10,12];pattern().steps.forEach((s,i)=>{s.on=i<pattern().length&&Math.random()<.58;s.note=clamp(root+notes[Math.floor(Math.random()*notes.length)],0,127);s.velocity=.45+Math.random()*.5;s.gate=.3+Math.random()*.6;s.probability=Math.random()<.12?.65:1;s.ratchet=Math.random()<.12?2:1;});commit();say('A politely unruly sequence. Undo remembers its manners.');});
  function velocity(){const el=$('velocity'),value=Number(el?.value??.8);return clamp(Number(el?.max)>1?value/127:value,.01,1);}
  async function press(key,note,source,vel=velocity()){if(held.has(key))return;held.set(key,{note,source});refreshKeys();try{await prepare();if(!held.has(key))return;engine.noteOn(note,vel,{source});}catch(error){held.delete(key);refreshKeys();say(error.message,true);}}
  function release(key){const item=held.get(key);if(!item)return;engine.noteOff(item.note,{source:item.source});held.delete(key);refreshKeys();}
  if($('keyboard')){$('keyboard').addEventListener('pointerdown',e=>{const el=e.target.closest('[data-note]');if(!el)return;e.preventDefault();el.setPointerCapture(e.pointerId);press('pointer:'+e.pointerId,Number(el.dataset.note),'pointer:'+e.pointerId);});const releasePointer=e=>release('pointer:'+e.pointerId);$('keyboard').addEventListener('pointerup',releasePointer);$('keyboard').addEventListener('pointercancel',releasePointer);$('keyboard').addEventListener('lostpointercapture',releasePointer);}
  function octave(change){releaseHeld();remember();state.keyOctave=clamp(state.keyOctave+change,0,8);commit();renderKeyboard();}
  bind('octaveDown',()=>octave(-1));bind('octaveUp',()=>octave(1));bind('sustain',()=>{sustain=!sustain;engine.setSustain(sustain);$('sustain').classList.toggle('active',sustain);$('sustain').setAttribute('aria-pressed',String(sustain));});
  const computerKeys=['a','w','s','e','d','f','t','g','y','h','u','j','k','o','l','p',';'];
  function blockedKeyboard(e){return document.querySelector('dialog[open]')||e.target.closest('input,select,textarea,[contenteditable="true"]');}
  document.addEventListener('keydown',e=>{if(blockedKeyboard(e))return;if(e.key==='Escape'){panic();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(e.code==='Space'){if(e.target.closest('button,a'))return;e.preventDefault();togglePlay();return;}const index=computerKeys.indexOf(e.key.toLowerCase());if(index>=0){e.preventDefault();press('computer:'+e.code,clamp(clamp(state.keyOctave*12,0,96)+index,0,127),'computer:'+e.code);}});
  document.addEventListener('keyup',e=>release('computer:'+e.code));window.addEventListener('blur',()=>{releaseHeld();engine.allNotesOff();});document.addEventListener('visibilitychange',()=>{if(document.hidden){releaseHeld();engine.allNotesOff();}});window.addEventListener('pagehide',()=>{try{const text=S.serializeProject(state);if(storageDB){const tx=storageDB.transaction('projects','readwrite');tx.objectStore('projects').put(text,'current');}else localStorage.setItem('fable-project-v1',text);}catch(_){}panic();clearTimeout(persistTimer);});
  function midiMessage(e){const [status,a=0,b=0]=e.data,kind=status&0xf0,channel=(status&15)+1;if(midiChannel&&channel!==midiChannel)return;const key='midi:'+channel+':'+a;if(kind===0x90&&b>0)press(key,a,'midi:'+channel,b/127);else if(kind===0x80||(kind===0x90&&b===0))release(key);else if(kind===0xb0){if(a===1)expression.wheel=b/127;if(a===64){sustain=b>=64;engine.setSustain(sustain);if($('sustain'))$('sustain').classList.toggle('active',sustain);}if(a===120||a===123){releaseHeld();engine.allNotesOff();}engine.setExpression(expression);}else if(kind===0xe0){expression.bend=((b*128+a)-8192)/8192;engine.setExpression(expression);}else if(kind===0xd0){expression.pressure=a/127;engine.setExpression(expression);}else if(kind===0xa0){expression.pressure=b/127;engine.setExpression(expression);}}
  function connectMidi(){if(midiDevice)midiDevice.onmidimessage=null;midiDevice=null;releaseHeld();const id=$('midiInput')?.value;if(midi&&id){midiDevice=midi.inputs.get(id);if(midiDevice)midiDevice.onmidimessage=midiMessage;}if($('midiButton'))$('midiButton').textContent=midiDevice?'MIDI connected':'Enable MIDI';}
  function listMidi(){if(!$('midiInput')||!midi)return;const current=$('midiInput').value;$('midiInput').innerHTML='<option value="">No MIDI input</option>'+Array.from(midi.inputs.values()).map(i=>'<option value="'+escape(i.id)+'">'+escape(i.name||'MIDI input')+'</option>').join('');$('midiInput').value=midi.inputs.has(current)?current:Array.from(midi.inputs.keys())[0]||'';connectMidi();}
  bind('midiButton',async()=>{if(!navigator.requestMIDIAccess)throw new Error('This browser does not support Web MIDI. The screen and computer keyboards remain available.');if(!midi){midi=await navigator.requestMIDIAccess({sysex:false});midi.onstatechange=listMidi;}listMidi();say(midiDevice?'MIDI input connected. Pitch bend, mod wheel, pressure, and sustain are available.':'No MIDI input found. Connect a controller and choose it here.');});bind('midiInput',connectMidi,'change');bind('midiChannel',e=>{releaseHeld();midiChannel=Number(e.target.value)||0;},'change');
  document.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files')){e.preventDefault();$('waveformWrap')?.classList.add('drop-active');}});document.addEventListener('dragleave',e=>{if(!e.relatedTarget)$('waveformWrap')?.classList.remove('drop-active');});document.addEventListener('drop',e=>{const files=Array.from(e.dataTransfer?.files||[]);if(!files.length)return;e.preventDefault();$('waveformWrap')?.classList.remove('drop-active');if(document.querySelector('dialog[open]'))return;const key=e.target.closest('[data-note]'),map=e.target.closest('#zoneMap');let root=key?Number(key.dataset.note):undefined;if(map){const rect=map.getBoundingClientRect();root=clamp(Math.floor((e.clientX-rect.left)/rect.width*128),0,127);}importFiles(files,root===undefined?{}:{root});});
  bind('helpButton',()=>openDialog('helpDialog'));bind('exportButton',()=>{if($('exportScope'))$('exportScope').value='zone';if($('exportBars'))$('exportBars').disabled=true;if($('exportTail'))$('exportTail').disabled=false;if($('exportStatus'))$('exportStatus').textContent='48 kHz · stereo WAV';openDialog('exportDialog');});
  bind('exportRun',async()=>{if(exporting)return;const scope=$('exportScope')?.value||'zone',controller=new AbortController();exporting=controller;if($('exportRun'))$('exportRun').disabled=true;if($('exportStatus'))$('exportStatus').textContent='Rendering locally…';try{if(scope==='assets'){const st=snapshot();if(!st.assets.length)throw new Error('There are no samples in this cabinet.');if(!window.FableZip?.pack)throw new Error('The sample archive exporter is unavailable. Save instrument includes every sample.');const files=[],manifest={format:'fable-samples',version:1,instrument:st.name,tempo:st.tempo,samples:[]};for(let i=0;i<st.assets.length;i++){if(controller.signal.aborted)throw new DOMException('Render cancelled.','AbortError');const a=st.assets[i],audio=engine.getAssetAudio(a),name=String(i+1).padStart(2,'0')+'-'+a.name.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'-').slice(0,96)+'.wav';files.push({name,data:encodeWav({pcm:interleave(audio),sampleRate:audio.sampleRate,name:a.name})});const mappings=st.zones.filter(z=>z.assetId===a.id).map(z=>({name:z.name,root:z.root,tune:z.tune,low:z.low,high:z.high,velLow:z.velLow,velHigh:z.velHigh,start:z.start,end:z.end}));manifest.samples.push({filename:name,id:a.id,name:a.name,root:mappings[0]?.root??a.root,assetRoot:a.root,sampleRate:audio.sampleRate,channels:2,duration:audio.left.length/audio.sampleRate,zones:mappings});if($('exportStatus'))$('exportStatus').textContent='Packing '+(i+1)+' / '+st.assets.length+' samples…';await new Promise(resolve=>setTimeout(resolve,0));}files.push({name:'manifest.json',data:JSON.stringify(manifest,null,2)});const archive=await window.FableZip.pack(files,{signal:controller.signal});if(controller.signal.aborted)throw new DOMException('Render cancelled.','AbortError');download(archive,st.name+'-samples.zip');if($('exportStatus'))$('exportStatus').textContent=st.assets.length+' WAV samples and a root-note manifest downloaded in one ZIP.';}else{const value=await exportAudio({scope,bars:Number($('exportBars')?.value||1),tailSeconds:Number($('exportTail')?.value||0),signal:controller.signal});if(controller.signal.aborted)return;download(encodeWav(value),(value.name||state.name)+'.wav');if($('exportStatus'))$('exportStatus').textContent='Stereo WAV downloaded.';}}catch(error){if($('exportStatus'))$('exportStatus').textContent=error.name==='AbortError'?'Rendering cancelled.':error.message;}finally{if(exporting===controller)exporting=null;if($('exportRun'))$('exportRun').disabled=false;}});
  bind('exportScope',()=>{const pattern=$('exportScope').value==='pattern';if($('exportBars'))$('exportBars').disabled=!pattern;if($('exportTail'))$('exportTail').disabled=['source','assets'].includes($('exportScope').value);},'change');
  bind('exportCancel',()=>{exporting?.abort();closeDialog('exportDialog');});if($('exportDialog'))$('exportDialog').addEventListener('close',()=>exporting?.abort());
  document.querySelectorAll('[data-close-dialog]').forEach(el=>el.addEventListener('click',()=>closeDialog(el.dataset.closeDialog)));['helpDialog','exportDialog','recordDialog'].forEach(id=>{const d=$(id);if(d)d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(id);});});
  document.querySelectorAll('[data-inspector-tab]').forEach(el=>el.addEventListener('click',()=>{inspectorTab=el.dataset.inspectorTab;document.querySelectorAll('[data-inspector-tab]').forEach(t=>{const active=t.dataset.inspectorTab===inspectorTab;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));});document.querySelectorAll('[data-inspector-panel]').forEach(p=>p.hidden=p.dataset.inspectorPanel!==inspectorTab);drawEnvelopes();}));
  function recordStatus(text){if($('recordStatus'))$('recordStatus').textContent=text;}
  function stopRecordPreview(){try{recordPreview?.stop();recordPreview?.disconnect();}catch(_){}recordPreview=null;}
  function disconnectRecording(rec){if(!rec)return;try{rec.source.disconnect();rec.processor.disconnect();rec.gain.disconnect();}catch(_){}rec.stream.getTracks().forEach(t=>t.stop());clearInterval(recordTimer);recordTimer=null;}
  function cancelRecording(){recordRequest++;disconnectRecording(recording);recording=null;recordAudio=null;stopRecordPreview();if($('recordStart'))$('recordStart').disabled=false;if($('recordStop'))$('recordStop').disabled=true;if($('recordCommit'))$('recordCommit').disabled=true;if($('recordPreview'))$('recordPreview').disabled=true;}
  async function startRecording(){
    if(recording)return;if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone recording needs a browser with microphone access. You can import recordings from files.');
    const request=++recordRequest,token=lifecycle;recordAudio=null;stopRecordPreview();if($('recordPreview'))$('recordPreview').disabled=true;if($('recordCommit'))$('recordCommit').disabled=true;recordStatus('Waiting for microphone permission…');if($('recordStart'))$('recordStart').disabled=true;let stream=null;
    try{await prepare();if(request!==recordRequest||token!==lifecycle)return;stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(request!==recordRequest||token!==lifecycle){stream.getTracks().forEach(t=>t.stop());return;}
      const context=engine.context,source=context.createMediaStreamSource(stream),processor=context.createScriptProcessor(4096,2,2),gain=context.createGain();gain.gain.value=0;
      const maximum=Math.floor(Math.min(120,MAX_BYTES/8/context.sampleRate)*context.sampleRate),rec={source,processor,gain,stream,sampleRate:context.sampleRate,left:[],right:[],frames:0,maximum,started:performance.now()};recording=rec;
      processor.onaudioprocess=e=>{if(recording!==rec)return;const length=Math.min(e.inputBuffer.length,rec.maximum-rec.frames);if(length<=0){finishRecording();return;}const left=e.inputBuffer.getChannelData(0).slice(0,length),right=e.inputBuffer.numberOfChannels>1?e.inputBuffer.getChannelData(1).slice(0,length):left.slice();rec.left.push(left);rec.right.push(right);rec.frames+=length;if(rec.frames>=rec.maximum)finishRecording();};
      source.connect(processor);processor.connect(gain);gain.connect(context.destination);if($('recordStop'))$('recordStop').disabled=false;recordTimer=setInterval(()=>recordStatus('Recording '+(rec.frames/rec.sampleRate).toFixed(1)+' / 120 s. Stop to trim before adding a zone.'),250);recordStatus('Recording. Stop to trim before adding a zone.');
    }catch(error){if(stream)stream.getTracks().forEach(t=>t.stop());if(request===recordRequest){recordStatus('Microphone: '+error.message);if($('recordStart'))$('recordStart').disabled=false;}throw error;}
  }
  function finishRecording(){const rec=recording;if(!rec)return;recording=null;disconnectRecording(rec);if(!rec.frames){recordStatus('No audio was captured. Try recording again.');if($('recordStart'))$('recordStart').disabled=false;return;}const left=new Float32Array(rec.frames),right=new Float32Array(rec.frames);let offset=0;rec.left.forEach((a,i)=>{left.set(a,offset);right.set(rec.right[i],offset);offset+=a.length;});recordAudio={left,right,sampleRate:rec.sampleRate,duration:rec.frames/rec.sampleRate};if($('recordStart'))$('recordStart').disabled=false;if($('recordStop'))$('recordStop').disabled=true;if($('recordCommit'))$('recordCommit').disabled=false;if($('recordPreview'))$('recordPreview').disabled=false;if($('recordTrimStart')){$('recordTrimStart').value=0;$('recordTrimStart').max=recordAudio.duration;}if($('recordTrimEnd')){$('recordTrimEnd').value=recordAudio.duration.toFixed(3);$('recordTrimEnd').max=recordAudio.duration;}recordStatus(recordAudio.duration.toFixed(2)+' s captured. Trim the start and end, then Add sample.');}
  function selectedRecording(){if(!recordAudio)throw new Error('Record a sample first.');const a=recordAudio,start=clamp($('recordTrimStart')?.value||0,0,a.duration),end=clamp($('recordTrimEnd')?.value||a.duration,0,a.duration);if(end<=start)throw new Error('Recording end must follow its start.');return{left:a.left.subarray(Math.floor(start*a.sampleRate),Math.min(a.left.length,Math.ceil(end*a.sampleRate))),right:a.right.subarray(Math.floor(start*a.sampleRate),Math.min(a.right.length,Math.ceil(end*a.sampleRate))),sampleRate:a.sampleRate};}
  bind('recordSample',()=>{openDialog('recordDialog');recordStatus('Click Record to request microphone access. Nothing is added until you choose Add sample.');});bind('recordStart',startRecording);bind('recordStop',finishRecording);bind('recordCancel',()=>{cancelRecording();closeDialog('recordDialog');});bind('recordCommit',async()=>{const a=selectedRecording();await importAudio({pcm:interleave(a),sampleRate:a.sampleRate,name:'Microphone intake '+new Date().toLocaleTimeString(),options:{target:'new'}});cancelRecording();closeDialog('recordDialog');});bind('recordPreview',async()=>{if(recordPreview){stopRecordPreview();return;}const a=selectedRecording();await prepare();const context=engine.context,buffer=context.createBuffer(2,a.left.length,a.sampleRate);buffer.copyToChannel(a.left,0);buffer.copyToChannel(a.right,1);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);recordPreview=source;source.onended=()=>{if(recordPreview===source)recordPreview=null;source.disconnect();};source.start();});if($('recordDialog'))$('recordDialog').addEventListener('close',cancelRecording);
  try{const saved=localStorage.getItem('fable-project-v1');if(saved)state=S.parseProject(saved);}catch(error){if(error.name==='SecurityError')storageOkay=false;else say('The saved instrument could not be opened. A fresh cabinet is ready.');}
  // Workspace choice is transient UI state: no project, history or audio changes.
  function setStockView(view){
    const edit=view==='edit';document.querySelector('.app-shell').dataset.stockView=edit?'edit':'perform';
    $('stockEditor').hidden=!edit;$('stockSequence').hidden=edit;
    document.querySelectorAll('[data-stock-view]').forEach(button=>{const active=button.dataset.stockView===(edit?'edit':'perform');button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
    $('stockViewHint').textContent=edit?'Inspect, trim, map & season every sample.':'Choose a sound. Play it. Write the order.';
    requestAnimationFrame(()=>{drawWave();drawMap();drawEnvelopes();});
  }
  document.querySelectorAll('[data-stock-view]').forEach(button=>button.addEventListener('click',()=>setStockView(button.dataset.stockView)));
  createDynamicControls();engine.setState(state);renderKeyboard();render();if(window.ResizeObserver){const observer=new ResizeObserver(()=>{drawWave();drawMap();drawEnvelopes();});if($('waveform'))observer.observe($('waveform'));if($('zoneMap'))observer.observe($('zoneMap'));if($('amplitudeEnvelope'))observer.observe($('amplitudeEnvelope'));if($('filterEnvelope'))observer.observe($('filterEnvelope'));}
  const api={getState:snapshot,isPlaying:()=>!!engine.getMeters().playing,getProject:()=>JSON.parse(S.serializeProject(state)),loadState,prepare,play,stop,panic,setTempo:value=>{const n=Number(value);if(!Number.isFinite(n))throw new Error('Tempo must be finite.');remember();state.tempo=clamp(n,30,240);commit();},importAudio,exportAudio,get audioImport(){return{maxSeconds:120,channels:2,targets:[{id:'new',name:'New sample zone',occupied:false},...state.zones.map(z=>({id:z.id,name:z.name,occupied:true,assetName:state.assets.find(a=>a.id===z.assetId)?.name||''}))]};},get audioExport(){return{scopes:[{id:'zone',label:'Selected zone / processed',usesBars:false},{id:'source',label:'Source sample / unprocessed',usesBars:false},{id:'pattern',label:'Current pattern / with effects'}],defaultBars:1,maxBars:16};},get engine(){return engine;}};
  Object.defineProperty(window,'FableApp',{value:Object.freeze(api),writable:false});document.dispatchEvent(new CustomEvent('musiclab:app-ready',{bubbles:true,detail:{app:'fable'}}));
  recoverStoredProject();
  const meterFrame=()=>{updateMeters(engine.getMeters());requestAnimationFrame(meterFrame);};requestAnimationFrame(meterFrame);
  if(location.protocol==='file:'){if($('labLink'))$('labLink').href='https://calebhaines.github.io/sidequest-prototypes/music/';if($('sourceDownload'))$('sourceDownload').href='https://calebhaines.github.io/sidequest-prototypes/music/fable/FABLE-source.zip';}
})();
