/* Browser integration checks: PLAYWRIGHT_MODULE=/path/to/playwright CHROMIUM_PATH=/path/to/chromium node fable/engine-checks.cjs */
'use strict';
const path = require('node:path'), assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '..');
const browser = () => chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, headless: true, args: ['--no-sandbox', '--autoplay-policy=no-user-gesture-required'] });
(async()=>{
 const b=await browser(),page=await b.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.goto('about:blank');
  for(const filename of ['schema.js','presets.js','audio-engine.js'])await page.addScriptTag({path:path.join(root,'fable',filename)});
  const report=await page.evaluate(async()=>{
   const results=[];const test=async(name,fn)=>{try{const detail=await Promise.race([fn(),new Promise((_,reject)=>setTimeout(()=>reject(Error('QA timed out after 12 seconds')),12000))]);results.push({name,ok:true,detail});}catch(e){results.push({name,ok:false,error:e.message,stack:e.stack});}};
   const check=(v,m)=>{if(!v)throw Error(m);};const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
   const S=window.FableSchema;let engine;const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
   const tone=(frequency=440,duration=.7,rate=24000)=>{const pcm=new Float32Array(Math.floor(duration*rate)*2);for(let n=0;n<pcm.length/2;n++){pcm[2*n]=.35*Math.sin(2*Math.PI*frequency*n/rate);pcm[2*n+1]=.2*Math.sin(2*Math.PI*frequency*n/rate);}return {pcm,sampleRate:rate,name:'QA 440 Hz',root:69};};
   const energy=(pcm,rate,start=0,end=Infinity)=>{let sq=0,peak=0,bad=0;const from=Math.floor(start*rate)*2,to=Math.min(pcm.length,Math.floor(end*rate)*2);for(let n=from;n<to;n++){const v=pcm[n];sq+=v*v;peak=Math.max(peak,Math.abs(v));if(!Number.isFinite(v))bad++;}return {rms:Math.sqrt(sq/Math.max(1,to-from)),peak,bad,frames:pcm.length/2};};
   const frequency=(pcm,rate,start=.03,end=.16)=>{let crossings=0;const a=Math.floor(start*rate),b=Math.min(Math.floor(end*rate),pcm.length/2);for(let i=a+1;i<b;i++)if(pcm[(i-1)*2]<=0&&pcm[i*2]>0)crossings++;return crossings/((b-a)/rate);};
   const patch=()=>{const state=S.defaultState(),asset=S.encodeAsset(tone());state.assets=[asset];const z=S.createZone(asset,{name:'QA sine',root:69,low:0,high:127,level:.8,pan:0,width:1,playMode:'oneshot',envelope:{attack:.001,decay:.001,sustain:1,release:.03},filter:{type:'lowpass',cutoff:18000,q:.7,drive:0,keytrack:0,velocity:0,amount:0,envelope:{attack:.001,decay:.001,sustain:1,release:.02}}});state.zones=[z];state.selectedZone=z.id;state.master={...state.master,level:.7,drive:0,chorus:0,delay:0,space:0,tone:18000,width:1};state.modulation=state.modulation.map(route=>({...route,source:'off',amount:0}));return state;};
   await test('Portable PCM preserves stereo and sample rate',()=>{const asset=S.encodeAsset(tone());const decoded=S.decodeAsset(asset);check(decoded.sampleRate===24000,'native source rate lost');check(Math.abs(decoded.left[123]-.35*Math.sin(2*Math.PI*440*123/24000))<.00004,'left PCM changed');check(Math.abs(decoded.right[123]-.2*Math.sin(2*Math.PI*440*123/24000))<.00004,'right PCM changed');return {frames:decoded.left.length,sampleRate:decoded.sampleRate};});
   await test('Pitch detection finds A4 and silence yields no fabricated root',()=>{const decoded=S.decodeAsset(S.encodeAsset(tone())),found=S.detectPitch(decoded);check(found&&Math.abs(found.note-69)<=1,'440 Hz pitch not A4: '+JSON.stringify(found));const quiet={left:new Float32Array(24000),right:new Float32Array(24000),sampleRate:24000,duration:1};check(!S.detectPitch(quiet),'silence fabricated a root');return found;});
   await test('Malformed sample metadata is rejected before allocation',()=>{const asset=S.encodeAsset(tone()),cases=[{...asset,frames:asset.frames+1},{...asset,sampleRate:1},{...asset,channels:3},{...asset,pcm:asset.pcm.slice(0,-4)},{...asset,frames:2**31}];let rejected=0;for(const bad of cases)try{S.decodeAsset(bad);}catch(e){rejected++;}check(rejected===cases.length,'malformed decode accepted '+(cases.length-rejected)+' cases');return {rejected};});
   await test('Eight presets contain playable samples and portable states',()=>{check(FablePresets.length===8,'eight presets expected');return FablePresets.map(p=>{const state=p.create();check(state.zones.length&&state.assets.length,p.id+' missing voices');const parsed=S.parseProject(S.serializeProject(state));check(parsed.zones.length===state.zones.length,p.id+' project lost zones');return {id:p.id,zones:state.zones.length,assets:state.assets.length};});});
   await test('Actual offline stereo render is finite and pitch tracks an octave',async()=>{const state=patch();engine=new FableAudio({getState:()=>state});const low=await engine.render({state,scope:'zone',zoneId:state.zones[0].id,note:69,velocity:.9,tailSeconds:.1});const high=await engine.render({state,scope:'zone',zoneId:state.zones[0].id,note:81,velocity:.9,tailSeconds:.1});const a=energy(low.pcm,low.sampleRate),b=energy(high.pcm,high.sampleRate),fa=frequency(low.pcm,low.sampleRate),fb=frequency(high.pcm,high.sampleRate);check(!a.bad&&!b.bad,'nonfinite render');check(a.rms>.01&&b.rms>.01,'render silent');check(fa>410&&fa<470,'root frequency unexpected '+fa);check(fb>830&&fb<930,'octave frequency unexpected '+fb);check(low.pcm instanceof Float32Array&&low.pcm.length%2===0&&low.sampleRate===48000,'stereo float output contract');return {low:a,high:b,rootHz:fa,octaveHz:fb};});
   await test('Sample playhead reversal changes the heard transient',async()=>{const state=patch(),rate=24000,pcm=new Float32Array(rate*2);for(let i=0;i<rate;i++){const amp=i<rate*.2?.4:0;pcm[2*i]=pcm[2*i+1]=amp*Math.sin(2*Math.PI*440*i/rate);}const a=S.encodeAsset({pcm,sampleRate:rate,name:'QA head transient',root:69});state.assets=[a];state.zones[0].assetId=a.id;const zone=state.zones[0];zone.end=1;zone.start=0;zone.reverse=false;const forward=await engine.render({state,scope:'zone',zoneId:zone.id,note:69,velocity:1,tailSeconds:0});zone.reverse=true;const reverse=await engine.render({state,scope:'zone',zoneId:zone.id,note:69,velocity:1,tailSeconds:0});const fa=energy(forward.pcm,48000,.03,.15),ra=energy(reverse.pcm,48000,.03,.15),late=energy(reverse.pcm,48000,.82,.94);check(fa.rms>.025&&ra.rms<fa.rms*.1,'reverse did not reverse transient position');check(late.rms>.015,'reversed tail missing');return {forwardEarly:fa.rms,reverseEarly:ra.rms,reverseLate:late.rms};});
   await test('Velocity alters audible level rather than only metadata',async()=>{const state=patch(),quiet=await engine.render({state,scope:'zone',zoneId:state.zones[0].id,note:69,velocity:.25}),loud=await engine.render({state,scope:'zone',zoneId:state.zones[0].id,note:69,velocity:1});const a=energy(quiet.pcm,48000,.03,.15),b=energy(loud.pcm,48000,.03,.15);check(b.rms>a.rms*1.9,'velocity barely affects signal');return {quiet:a.rms,loud:b.rms,ratio:b.rms/a.rms};});
   await test('Cancelled rendering rejects without altering sampler state',async()=>{const state=patch(),before=JSON.stringify(state),signal=new AbortController();signal.abort();let rejected=false;try{await engine.render({state,scope:'pattern',bars:16,signal:signal.signal});}catch(e){rejected=e.name==='AbortError';}check(rejected,'pre-aborted render accepted');check(JSON.stringify(state)===before,'render mutated sampler');return {cancelled:true};});
   await test('Realtime zone key/velocity mapping and round robin',async()=>{const state=patch(),notes=[];const first=state.zones[0],second=S.createZone(state.assets[0],{...first,id:S.uid('zone'),name:'QA upper',low:72,high:84,velLow:65,velHigh:127,roundRobin:0});first.low=60;first.high=71;first.velLow=1;first.velHigh=127;state.zones=[first,second];const live=new FableAudio({getState:()=>state,onNote:e=>notes.push(e)});await live.init();live.setState(state);const hit1=live.noteOn(60,.8),hit2=live.noteOn(72,.25),hit3=live.noteOn(72,.9);check(hit1.length===1,'lower key not selected');check(hit2.length===0,'velocity layer fired below its range');check(hit3.length===1,'upper loud velocity key not selected');live.panic();first.low=second.low=0;first.high=second.high=127;first.velLow=second.velLow=1;first.roundRobin=second.roundRobin=1;live.setState(state);const seen=[];for(let i=0;i<4;i++){const old=notes.length;live.noteOn(69,.9);const n=notes.slice(old).filter(n=>n.on);check(n.length===1,'RR should choose exactly one zone');seen.push(n[0].zoneId);}check(seen[0]!==seen[1]&&seen[0]===seen[2],'RR does not alternate');live.panic();await live.context.close();return {keyHits:[hit1.length,hit2.length,hit3.length],roundRobin:seen};});
   await test('Forward and ping-pong loops sustain beyond the source length',async()=>{const state=patch(),zone=state.zones[0];zone.playMode='gate';zone.loopStart=.12;zone.loopEnd=.7;zone.crossfade=.015;const output=[];for(const mode of ['forward','pingpong']){zone.loopMode=mode;const result=await engine.render({state,scope:'zone',zoneId:zone.id,note:69,velocity:.8,tailSeconds:.15});const late=energy(result.pcm,48000,1.1,1.4),tail=energy(result.pcm,48000,result.pcm.length/2/48000-.08);check(!late.bad&&late.rms>.025,mode+' loop died with its original buffer');check(tail.rms<.003,mode+' loop never releases');output.push({mode,seconds:result.pcm.length/2/48000,lateRms:late.rms,tailRms:tail.rms});}return output;});
   await test('Granular texture stretches independently of note pitch',async()=>{const state=patch(),zone=state.zones[0];zone.engine='texture';zone.playMode='oneshot';zone.stretch=2;zone.grainSize=.12;zone.grainDensity=32;zone.jitter=0;zone.position=0;const base=await engine.render({state,scope:'zone',zoneId:zone.id,note:69,velocity:1,tailSeconds:.05}),high=await engine.render({state,scope:'zone',zoneId:zone.id,note:81,velocity:1,tailSeconds:.05});const a=energy(base.pcm,48000,.4,.7),b=energy(high.pcm,48000,.4,.7),fa=frequency(base.pcm,48000,.4,.7),fb=frequency(high.pcm,48000,.4,.7);check(base.pcm.length===high.pcm.length,'texture octave also halved duration');check(a.rms>.005&&b.rms>.005,'texture is silent');check(fa>380&&fa<490&&fb>770&&fb<960,'texture pitch did not track octave '+fa+'/'+fb);const late=energy(base.pcm,48000,1.15,1.3);check(late.rms>.003,'time stretch did not sustain later source material');return {seconds:base.pcm.length/2/48000,rootHz:fa,octaveHz:fb,rootRms:a.rms,octaveRms:b.rms,lateRms:late.rms};});
   await test('Gate release, sustain pedal, choke groups and bounded polyphony work live',async()=>{const state=patch(),zone=state.zones[0];zone.playMode='gate';zone.loopMode='forward';zone.envelope.release=.035;state.master.polyphony=8;const live=new FableAudio({getState:()=>state});await live.init();live.setState(state);live.noteOn(69,.8);await wait(30);live.setSustain(true);live.noteOff(69);await wait(90);check(live.getMeters().voices===1,'sustain lost released key');live.setSustain(false);await wait(90);check(live.getMeters().voices===0,'pedal release kept notes alive');zone.choke=1;live.setState(state);live.noteOn(60,.8);await wait(25);live.noteOn(62,.8);await wait(40);check(live.getMeters().voices===1,'choke leaves previous voice running');live.panic();zone.choke=0;live.setState(state);for(let i=0;i<32;i++)live.noteOn(48+i,.8);await wait(35);const limited=live.getMeters().voices;check(limited<=8&&limited>0,'polyphony overflow '+limited);live.panic();check(live.getMeters().voices===0&&!live.getMeters().playing,'panic did not clear notes');await live.context.close();return {sustainReleased:true,chokeVoices:1,polyphonyVoices:limited};});
   await test('Arpeggiator schedules held-note chord and Stop clears held notes',async()=>{const state=patch();state.performance={...state.performance,mode:'arp',arpMode:'up',division:.125,velocity:1};state.tempo=240;state.swing=0;state.zones[0].playMode='gate';const notes=[],live=new FableAudio({getState:()=>state,onNote:e=>{if(e.on)notes.push(e.note)}});await live.init();live.noteOn(60,.8);live.noteOn(64,.8);live.noteOn(67,.8);notes.length=0;await live.start();await wait(230);const seen=notes.slice();check(seen.length>=6,'arp clock did not schedule notes');check(seen[0]===60&&seen[1]===64&&seen[2]===67,'arp order incorrect '+seen);live.stop();await wait(100);check(!live.getMeters().playing&&live.held.size===0,'Stop retained arp clock/held notes');await live.context.close();return {notes:seen};});
   await test('Held loops respond audibly to filter and level edits',async()=>{const state=patch(),zone=state.zones[0];zone.playMode='gate';zone.loopMode='forward';const live=new FableAudio({getState:()=>state});await live.init();live.noteOn(69,1);await wait(130);const open=live.getMeters().rms;zone.filter.cutoff=70;live.setState(state);await wait(170);const filtered=live.getMeters().rms;check(open>.02&&filtered<open*.15,'held cutoff edit was inaudible '+open+'/'+filtered);zone.filter.cutoff=18000;live.setState(state);await wait(130);zone.level=0;live.setState(state);await wait(130);const muted=live.getMeters().rms;check(muted<.00001,'held level edit failed '+muted);live.panic();await live.context.close();return {openRms:open,filteredRms:filtered,mutedRms:muted};});
   await test('Reducing polyphony also cancels notes scheduled in the future',async()=>{const state=patch();state.zones[0].playMode='gate';state.zones[0].loopMode='forward';const live=new FableAudio({getState:()=>state});await live.init();const at=live.context.currentTime+.25;for(let i=0;i<32;i++)live.noteOn(48+i,.7,{when:at});state.master.polyphony=8;live.setState(state);await wait(340);check(live.getMeters().voices<=8,'future voices ignored reduced voice budget');live.panic();await live.context.close();return {limit:8};});
   await test('Layered notes do not choke their own sibling zones',async()=>{const state=patch(),a=state.zones[0];a.playMode='gate';a.loopMode='forward';a.choke=1;const b=S.createZone(state.assets[0],{...a,id:S.uid('zone')});state.zones=[a,b];const live=new FableAudio({getState:()=>state});await live.init();live.noteOn(69,.8);await wait(65);check(live.getMeters().voices===2,'layered choke removed a sibling');live.noteOn(71,.8);await wait(65);check(live.getMeters().voices===2,'new layered note did not choke old pair');live.panic();await live.context.close();return {layers:2};});
   await test('All factory presets export audible finite stereo patterns',async()=>{const presets=[];for(const p of FablePresets){const state=p.create(),result=await engine.render({state,scope:'pattern',bars:1,tailSeconds:.08}),level=energy(result.pcm,48000);check(!level.bad&&level.rms>.0001,p.id+' silent/nonfinite');presets.push({id:p.id,...level});}return presets;});
   await test('Rendering snapshots remain stable across concurrent edits and active cancellation',async()=>{const state=patch(),initial=S.copy(state),reference=await engine.render({state:initial,scope:'pattern',bars:2});const pending=engine.render({state,scope:'pattern',bars:2});state.master.level=0;state.zones[0].reverse=true;const snapshot=await pending;check(snapshot.pcm.length===reference.pcm.length,'snapshot duration changed');let diff=0;for(let i=0;i<reference.pcm.length;i++)diff=Math.max(diff,Math.abs(reference.pcm[i]-snapshot.pcm[i]));check(diff<.000001,'mid-render edits leaked into snapshot '+diff);const controller=new AbortController(),cancelled=engine.render({state:initial,scope:'pattern',bars:16,signal:controller.signal});setTimeout(()=>controller.abort(),0);let aborted=false;try{await cancelled;}catch(e){aborted=e.name==='AbortError';}check(aborted,'active renderer ignored cancellation');return {snapshotMaxDifference:diff,activeCancelled:true};});
   if(engine?.context)await engine.context.close().catch(()=>{});
   return results;
  });
  const result={tests:report,errors};for (const item of report) console.log((item.ok ? 'PASS ' : 'FAIL ') + item.name + (item.error ? ': ' + item.error : '')); console.log(report.filter(item => item.ok).length + '/' + report.length + ' real Web Audio checks passed.');assert.equal(report.filter(x=>!x.ok).length,0,'native QA failures');assert.deepEqual(errors,[]);
 }finally{await page.close();await b.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
