(() => {
'use strict';
const S=window.RouxSchema,P=window.RouxPresets,$=id=>document.getElementById(id),storageKey='roux-project-v1';
let state=S.copy(P?.[0]?.state||S.defaultState()),selectedStep=0,history=[],future=[],editActive=false,saveTimer=0,toastTimer=0,loadGeneration=0,exporting=false,storageWarned=false,compiled=null,positions=[],lastPosition=-1,midiAccess=null,lastTransport=null;
const midiHeld=new Set();
try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw);state=parsed.format?S.parseProject(raw):S.normalize(parsed);}}catch{}
const engine=new window.RouxAudio(state);
const playIcon='<svg class="play-glyph" viewBox="0 0 14 14" aria-hidden="true"><path d="M3 2L12 7L3 12Z"/></svg>',stopIcon='<svg class="play-glyph" viewBox="0 0 14 14" aria-hidden="true"><path d="M3 3H11V11H3Z"/></svg>',arrowIcon='<svg class="action-glyph" viewBox="0 0 14 14" aria-hidden="true"><path d="M3 11L11 3M3 3H11V11"/></svg>';
engine.onStatus=message=>toast(message);
function toast(message){$('toast').textContent=String(message);$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3600);}
function saveLocal(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(storageKey,S.serialize(state));$('saveStatus').textContent='RECIPES KEPT IN THIS BROWSER';}catch{if(!storageWarned){storageWarned=true;toast('Browser storage is unavailable. Save recipe keeps a portable copy.');}$('saveStatus').textContent='SAVE RECIPE FOR A PORTABLE COPY';}},250);}
function snapshot(){history.push(S.copy(state));if(history.length>70)history.shift();future=[];updateHistory();}
function updateHistory(){$('undoButton').disabled=!history.length;$('redoButton').disabled=!future.length;}
function beginEdit(){if(!editActive){snapshot();editActive=true;}}
function commit(fn,{capture=true,native=false}={}){if(capture)snapshot();const next=S.copy(state);if(native)delete next.musicLabPattern;fn(next);state=S.normalize(next);engine.setState(state);renderState();saveLocal();return S.copy(state);}
function decodeState(value){if(typeof value==='string'){let parsed;try{parsed=JSON.parse(value);}catch{throw new Error('The recipe is not valid JSON.');}return parsed.format?S.parseProject(value):S.normalize(parsed);}if(value?.format)return S.parseProject(JSON.stringify(value));return S.normalize(value);}
function loadState(value,capture=true){const next=decodeState(value);if(capture)snapshot();loadGeneration++;midiHeld.clear();engine.panic();state=next;selectedStep=Math.min(selectedStep,state.recipe.length-1);engine.setState(state);renderState();saveLocal();return S.copy(state);}
function undo(){if(!history.length)return;future.push(S.copy(state));state=history.pop();engine.setState(state);renderState();saveLocal();toast('The previous recipe is back on the line.');}
function redo(){if(!future.length)return;history.push(S.copy(state));state=future.pop();engine.setState(state);renderState();saveLocal();toast('The next recipe has returned.');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function safeName(){return state.name.replace(/[^a-z0-9 -]/gi,'').trim().replace(/\s+/g,'-').slice(0,70)||'ROUX';}
function updateTransport(){const playing=!!engine.isPlaying;if(lastTransport===playing)return;lastTransport=playing;$('playButton').innerHTML=playing?stopIcon+' Stop':playIcon+' Play';$('playButton').setAttribute('aria-pressed',String(playing));$('liveDot').classList.toggle('playing',playing);$('audioStatus').textContent=playing?'The bottom is moving':'Ready for service';}
async function play(){try{if(engine.isPlaying){engine.stop();updateTransport();return false;}const result=await engine.start();updateTransport();return result;}catch(e){toast(e.message);return false;}}
function stop(){engine.stop();updateTransport();}
function panic(){midiHeld.clear();engine.panic();document.querySelectorAll('.key.pressed').forEach(key=>key.classList.remove('pressed'));updateTransport();}
async function rewind(){const playing=!!engine.isPlaying;midiHeld.clear();engine.panic();if(playing)await engine.start();lastPosition=-1;updateTransport();toast('Back to the beginning of the order.');}
const percent=value=>Math.round(value*100)+'%',seconds=value=>value<.1?Math.round(value*1000)+' ms':value.toFixed(value<1?2:1)+' s',signed=value=>(value>0?'+':'')+value,capitalize=value=>value.charAt(0).toUpperCase()+value.slice(1),frequency=value=>value>=1000?(value/1000).toFixed(2)+' kHz':Math.round(value)+' Hz';
const controls=[];
function getPath(source,path){if(path.startsWith('step.'))return source.recipe.steps[selectedStep][path.slice(5)];return path.split('.').reduce((object,key)=>object[key],source);}
function setPath(source,path,value){if(path.startsWith('step.')){source.recipe.steps[selectedStep][path.slice(5)]=value;return;}const keys=path.split('.'),last=keys.pop();keys.reduce((object,key)=>object[key],source)[last]=value;}
const isNative=path=>path.startsWith('step.')||path.startsWith('recipe.')||['root','scale','swing','seed'].includes(path);
function control(container,path,label,{min=0,max=1,step=.01,format=percent,description='',values=null,checkbox=false}={}){const id=path.replaceAll('.','-'),wrapper=document.createElement('label');wrapper.className='control';const heading=document.createElement('span');heading.className='control-heading';heading.textContent=label;const output=document.createElement('output');output.id=id+'-value';output.htmlFor=id;heading.append(output);const input=document.createElement(values?'select':'input');input.id=id;
 if(values){values.forEach(value=>{const option=document.createElement('option');option.value=Array.isArray(value)?value[0]:value;option.textContent=Array.isArray(value)?value[1]:capitalize(value);input.append(option);});}
 else if(checkbox)input.type='checkbox';else{input.type='range';input.min=min;input.max=max;input.step=step;}
 const hint=document.createElement('span');hint.className='control-description';hint.textContent=description;wrapper.append(heading,input,hint);$(container).append(wrapper);controls.push({id,path,input,output,format,values,checkbox});
 if(values||checkbox)input.addEventListener('change',()=>commit(next=>setPath(next,path,checkbox?input.checked:input.value),{native:isNative(path)}));
 else{input.addEventListener('pointerdown',beginEdit);input.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(event.key))beginEdit();});input.addEventListener('input',()=>{beginEdit();commit(next=>setPath(next,path,+input.value),{capture:false,native:isNative(path)});});input.addEventListener('change',()=>{editActive=false;});}
 return input;
}
const range=(container,path,label,min,max,step,format,description='')=>control(container,path,label,{min,max,step,format,description});
const select=(container,path,label,values,description='')=>control(container,path,label,{values,description});
range('stepControls','step.move','Scale movement',-7,7,1,signed);
range('stepControls','step.octave','Octave',-1,1,1,signed);
range('stepControls','step.velocity','Velocity',.05,1,.01,percent);
range('stepControls','step.gate','Gate',.1,1,.01,percent);
range('stepControls','step.probability','Probability',0,1,.01,percent);
range('clockControls','root','Root note',24,60,1,S.noteName,'Home note for the circular recipe.');
select('clockControls','scale','Scale',Object.keys(S.SCALES).map(x=>[x,x==='whole'?'Whole tone':x==='harmonic'?'Harmonic minor':capitalize(x)]),'Movement follows these intervals.');
range('clockControls','recipe.length','Recipe length',1,16,1,value=>value+' stops','Active positions around the pot.');
select('clockControls','recipe.division','Step division',['1/16','1/8','1/4','1/8T','1/16T'].map(x=>[x,x]),'Time between visits; T means triplet.');
select('clockControls','recipe.direction','Direction',[['forward','Clockwise'],['reverse','Counterclockwise'],['pendulum','Back & forth']],'How the spoon travels.');
range('clockControls','recipe.stride','Stride',1,8,1,value=>value+' stops','Skip this many positions per visit.');
range('clockControls','recipe.rotation','Start rotation',0,15,1,value=>value+' stops','Shift where traversal begins.');
range('clockControls','recipe.gate','Global gate',.1,1,.01,percent,'Scales each stop’s note length.');
range('clockControls','recipe.drift','Circuit drift',-7,7,1,signed,'Scale-degree shift after each circuit.');
range('clockControls','swing','Swing',0,.6,.01,percent,'Alternating long and short intervals.');
range('accentControls','recipe.accents.length','Length',1,16,1,value=>value+' steps');
range('accentControls','recipe.accents.pulses','Pulses',0,16,1,value=>String(value));
range('accentControls','recipe.accents.rotation','Rotate',0,15,1,value=>String(value));
range('accentControls','recipe.accents.amount','Amount',0,.8,.01,percent);
range('slideControls','recipe.slides.length','Length',1,16,1,value=>value+' steps');
range('slideControls','recipe.slides.pulses','Pulses',0,16,1,value=>String(value));
range('slideControls','recipe.slides.rotation','Rotate',0,15,1,value=>String(value));
select('oscControls','synth.waveform','Waveform',[['saw','Saw'],['square','Pulse'],['triangle','Triangle'],['fold','Folded sine']],'Four distinct harmonic foundations.');
range('oscControls','synth.oscillator','Oscillator',0,1,.01,percent,'Harmonic oscillator level.');
range('oscControls','synth.sub','Sub',0,1,.01,percent,'Deep sine fundamental.');
range('oscControls','synth.pulseWidth','Pulse width',.08,.92,.01,percent,'Pulse balance when Pulse is selected.');
range('oscControls','synth.fold','Wavefold',0,1,.01,percent,'Fold the mixed tone into new harmonics.');
select('bodyControls','synth.material','Material',S.MATERIALS,'Changes excitation and resonance.');
range('bodyControls','synth.body','Vessel mix',0,1,.01,percent,'Blend the tuned waveguide with the bass.');
range('bodyControls','synth.bodyDecay','Body decay',.08,8,.01,seconds,'Energy retained by the resonant vessel.');
range('bodyControls','synth.damping','Damping',0,1,.01,percent,'High frequency absorption in the loop.');
range('bodyControls','synth.bodyTune','Body tuning',-12,12,.1,value=>signed(value.toFixed(1))+' st','Tune the vessel relative to the note.');
range('bodyControls','synth.excitation','Excitation',0,1,.01,percent,'Energy feeding the resonant vessel.');
range('bodyControls','synth.bite','Bite',0,1,.01,percent,'Transient emphasis in the excitation.');
select('filterControls','synth.filterType','Filter type',[['lowpass','Low pass'],['bandpass','Band pass'],['highpass','High pass']],'Choose which part of the bass escapes.');
range('filterControls','synth.cutoff','Cutoff',35,16000,1,frequency,'Filter frequency before modulation.');
range('filterControls','synth.resonance','Resonance',0,.95,.01,percent,'Emphasize frequencies around the cutoff.');
range('filterControls','synth.filterEnv.amount','Envelope amount',-6,8,.1,value=>signed(value.toFixed(1))+' oct','Signed filter sweep in octaves.');
for(const [container,path] of [['ampControls','synth.amp'],['filterEnvControls','synth.filterEnv']]){range(container,path+'.attack','Attack',.001,3,.001,seconds);range(container,path+'.decay','Decay',.008,5,.001,seconds);range(container,path+'.sustain','Sustain',0,1,.01,percent);range(container,path+'.release','Release',.008,5,.001,seconds);}
range('heatControls','synth.drive','Drive',0,1,.01,percent,'Saturation after the resonant filter.');
range('heatControls','synth.glide','Glide',0,1.5,.005,seconds,'Transition time for sliding notes.');
control('heatControls','synth.legato','Legato',{checkbox:true,description:'Keep envelopes moving across a slide.'});
range('heatControls','synth.pitchDepth','Pitch envelope',-24,24,.1,value=>signed(value.toFixed(1))+' st','Initial pitch bend at each note onset.');
range('heatControls','synth.pitchDecay','Pitch decay',.008,1.5,.001,seconds,'Time for the bend to return to the note.');
select('lfoControls','synth.lfo.shape','LFO shape',[['triangle','Triangle'],['sine','Sine'],['square','Square'],['random','Sample & hold']],'The motion of the automatic stirrer.');
select('lfoControls','synth.lfo.target','Destination',[['cutoff','Filter cutoff'],['body','Vessel mix'],['pitch','Pitch'],['drive','Drive'],['pulse','Pulse width']],'One destination at a time.');
select('lfoControls','synth.lfo.sync','LFO clock',[['free','Free'],['1/16','1/16'],['1/8','1/8'],['1/4','1/4'],['1/2','1/2'],['1/1','1 bar']],'Free rate or tempo-synchronized motion.');
range('lfoControls','synth.lfo.rate','Free rate',.03,24,.01,value=>value.toFixed(2)+' Hz','Frequency when the LFO clock is Free.');
range('lfoControls','synth.lfo.depth','Depth',0,1,.01,percent,'Amount of movement at the destination.');
range('masterControls','master.volume','Output',0,1,.01,percent);
range('masterControls','master.width','Width',0,1,.01,percent);
range('masterControls','master.echo','Echo',0,1,.01,percent);
select('masterControls','master.division','Echo time',['1/16','1/8','1/4','3/8','1/2'].map(x=>[x,x]));
range('masterControls','master.feedback','Feedback',0,.82,.01,percent);
range('masterControls','master.tone','Echo tone',0,1,.01,percent);
window.addEventListener('pointerup',()=>{editActive=false;});window.addEventListener('pointercancel',()=>{editActive=false;});window.addEventListener('keyup',()=>{editActive=false;});
const stepNodes=[];
for(let index=0;index<16;index++){const button=document.createElement('button');button.className='recipe-step';button.dataset.step=index;const angle=-Math.PI/2+index*Math.PI/8;button.style.setProperty('--x',(50+43*Math.cos(angle))+'%');button.style.setProperty('--y',(50+43*Math.sin(angle))+'%');button.innerHTML='<strong></strong><small></small><span class="step-flags" aria-hidden="true"></span>';button.addEventListener('click',()=>{selectedStep=index;renderState();});button.addEventListener('dblclick',()=>commit(next=>{const node=next.recipe.steps[index];node.mode=node.mode==='rest'?'note':'rest';},{native:true}));button.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowUp','ArrowRight','ArrowDown'].includes(event.key)){event.preventDefault();selectedStep=(index+(['ArrowRight','ArrowDown'].includes(event.key)?1:15))%16;renderState();stepNodes[selectedStep].focus();}});$('recipeRing').append(button);stepNodes.push(button);}
function firstPosition(index){return positions.find(position=>position.index===index)||{pitch:S.degreeMidi(state,0)+state.recipe.steps[index].octave*12};}
const cyclePositions={accentCycle:-1,slideCycle:-1};
function renderCycle(id,ring){const container=$(id);while(container.children.length>ring.length)container.lastElementChild.remove();while(container.children.length<ring.length)container.append(document.createElement('i'));for(let index=0;index<ring.length;index++){const pip=container.children[index];pip.classList.toggle('on',S.necklace(index,ring));}cyclePositions[id]=NaN;const noun=id==='accentCycle'?'ACCENTS':'SLIDES';$(id==='accentCycle'?'accentSummary':'slideSummary').textContent=ring.pulses+' / '+ring.length+' '+noun;}
function envelope(id,value){const scale=3/(value.attack+value.decay+value.release+3),a=12+value.attack*110*scale,d=a+value.decay*110*scale,r=388-value.release*110*scale,y=72-value.sustain*60;$(id).querySelector('.envelope-shape').setAttribute('d',`M12 72L${a.toFixed(1)} 12L${d.toFixed(1)} ${y.toFixed(1)}L${Math.max(d+8,r).toFixed(1)} ${y.toFixed(1)}L388 72`);}
function renderState(){lastPosition=NaN;compiled=S.compileRecipe(state,{cycles:1});positions=compiled.steps;const step=state.recipe.steps[selectedStep],pitch=firstPosition(selectedStep).pitch;
 controls.forEach(config=>{const value=getPath(state,config.path);if(config.checkbox){config.input.checked=value;config.output.textContent=value?'On':'Off';}else{config.input.value=value;config.output.textContent=config.values?'':config.format(value);}config.input.disabled=config.path==='step.move'&&step.mode!=='note';if(config.path==='synth.lfo.rate')config.input.disabled=state.synth.lfo.sync!=='free';});
 $('recipe-accents-pulses').max=state.recipe.accents.length;$('recipe-slides-pulses').max=state.recipe.slides.length;
 stepNodes.forEach((button,index)=>{const node=state.recipe.steps[index],position=firstPosition(index);button.className='recipe-step mode-'+node.mode+(index>=state.recipe.length?' outside':'')+(index===selectedStep?' selected':'');button.querySelector('strong').textContent=node.mode==='rest'?'—':node.mode==='root'?'⌂':node.mode==='hold'?'↔':signed(node.move);button.querySelector('small').textContent=String(index+1).padStart(2,'0');button.querySelector('.step-flags').textContent=(node.accent?'•':'')+(node.slide?'↝':'');button.setAttribute('aria-pressed',String(index===selectedStep));button.setAttribute('aria-label',`Step ${index+1}, ${node.mode}, ${node.mode==='note'?signed(node.move)+' scale degrees, ':''}${S.noteName(position.pitch)}, velocity ${Math.round(node.velocity*100)} percent, probability ${Math.round(node.probability*100)} percent${node.accent?', accent':''}${node.slide?', slide':''}${index>=state.recipe.length?', outside recipe length':''}`);button.title=`Stop ${index+1} · ${capitalize(node.mode)} · ${S.noteName(position.pitch)}${index>=state.recipe.length?' · Outside active length':''}`;});
 $('selectedStepLabel').textContent=String(selectedStep+1).padStart(2,'0');$('stepPitch').textContent=S.noteName(pitch);$('stepDescription').textContent={root:'Return to the root.',note:'Move '+signed(step.move)+' scale degrees.',hold:'Join the preceding note.',rest:'Leave a little space.'}[step.mode];$('stepAccent').checked=step.accent;$('stepSlide').checked=step.slide;
 document.querySelectorAll('[data-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.mode===step.mode)));
 $('recipeLengthLabel').textContent=state.recipe.length+' STOPS / ONE VESSEL';$('tempo').value=state.tempo;$('seed').value=state.seed;$('exportBars').value=state.exportBars;
 const imported=!!state.musicLabPattern;$('nativeSequenceButton').hidden=!imported;$('recipeHint').textContent=imported?'An exact shared pattern is playing. Sound controls keep it intact. Use native recipe or edit a recipe control to return to stirring.':'Choose a stop to edit it. Each Move adds scale degrees to the previous note. Root brings it home; Hold joins the previous note.';$('ringState').textContent=imported?'IMPORTED ORDER':'READY TO STIR';
 $('ringDirection').textContent=({forward:'CLOCKWISE',reverse:'COUNTERCLOCKWISE',pendulum:'BACK & FORTH'}[state.recipe.direction])+' / STRIDE '+state.recipe.stride;
 renderCycle('accentCycle',state.recipe.accents);renderCycle('slideCycle',state.recipe.slides);envelope('ampEnvelope',state.synth.amp);envelope('filterEnvelope',state.synth.filterEnv);
 document.querySelectorAll('.key').forEach((key,index)=>{const name=S.noteName(S.degreeMidi(state,index));key.querySelector('strong').textContent=name;key.setAttribute('aria-label',`Play ${name}, keyboard ${keyLetters[index]}`);});
 const preset=P?.find(value=>value.state?.name===state.name);$('presetSelect').value=preset?.id||'';updateHistory();updateTransport();
}
const customOption=document.createElement('option');customOption.value='';customOption.textContent='Custom recipe';$('presetSelect').append(customOption);
(P||[]).forEach(preset=>{const option=document.createElement('option');option.value=preset.id;option.textContent=preset.name;$('presetSelect').append(option);});
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>commit(next=>{next.recipe.steps[selectedStep].mode=button.dataset.mode;},{native:true})));
['stepAccent','stepSlide'].forEach((id,index)=>$(id).addEventListener('change',()=>commit(next=>{next.recipe.steps[selectedStep][index?'slide':'accent']=$(id).checked;},{native:true})));
$('tempo').addEventListener('change',()=>commit(next=>{next.tempo=+$('tempo').value;}));$('seed').addEventListener('change',()=>commit(next=>{next.seed=+$('seed').value;},{native:true}));$('exportBars').addEventListener('change',()=>commit(next=>{next.exportBars=+$('exportBars').value;}));
$('presetSelect').addEventListener('change',()=>{const preset=P?.find(value=>value.id===$('presetSelect').value);if(preset){loadState(preset.state);toast('Fresh sound. The spoon has its instructions.');}});
$('generateButton').addEventListener('click',()=>commit(next=>{let seed=next.seed>>>0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;seed=seed>>>0||1;return seed/4294967296;};next.recipe.steps.forEach((node,index)=>{node.mode=index===0||index===8?'root':random()<.18?'rest':random()<.15?'hold':'note';node.move=[-2,-1,0,0,1,2,3][Math.floor(random()*7)];node.octave=random()<.08?1:0;node.velocity=.53+random()*.28;node.gate=.6+random()*.38;node.probability=random()<.1?.7:1;node.accent=false;node.slide=random()<.13;});next.seed=seed;next.name='The changing order';},{native:true}));
$('rotateButton').addEventListener('click',()=>commit(next=>{next.recipe.rotation=(next.recipe.rotation+1)%next.recipe.length;},{native:true}));
$('clearButton').addEventListener('click',()=>commit(next=>{next.recipe.steps.forEach(node=>{node.mode='rest';});},{native:true}));
$('nativeSequenceButton').addEventListener('click',()=>commit(()=>{},{native:true}));
$('undoButton').addEventListener('click',undo);$('redoButton').addEventListener('click',redo);$('playButton').addEventListener('click',play);$('stopButton').addEventListener('click',stop);$('rewindButton').addEventListener('click',()=>rewind().catch(error=>toast(error.message)));$('panicButton').addEventListener('click',()=>{panic();toast('The range is quiet.');});
async function audition(pitch,velocity=.8){try{await engine.liveNote(pitch,velocity,.5);$('audioStatus').textContent='Tasting the low end';}catch(error){toast(error.message);}}
$('auditionButton').addEventListener('click',()=>audition(firstPosition(selectedStep).pitch,state.recipe.steps[selectedStep].velocity));
const keyLetters=['A','S','D','F','G','H','J','K'];
for(let index=0;index<8;index++){const button=document.createElement('button');button.className='key';button.dataset.degree=index;button.innerHTML='<span>'+keyLetters[index]+'</span><strong></strong><small>'+String(index+1)+'</small>';button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);button.classList.add('pressed');audition(S.degreeMidi(state,index));});button.addEventListener('click',event=>{if(event.detail===0)audition(S.degreeMidi(state,index));});['pointerup','pointercancel','lostpointercapture','keyup','blur'].forEach(type=>button.addEventListener(type,()=>button.classList.remove('pressed')));$('keys').append(button);}
async function exportAudio({scope='pattern',bars=state.exportBars,tailSeconds=4,signal}={}){if(signal?.aborted)throw new DOMException('Audio export cancelled.','AbortError');if(!['pattern','note'].includes(scope))throw new Error('Choose the complete bass recipe or the selected bass note.');if(exporting)throw new Error('A ROUX render is already in progress.');const score=S.copy(state),selectedPitch=firstPosition(selectedStep).pitch,velocity=score.recipe.steps[selectedStep].velocity;exporting=true;try{const renderer=new window.RouxAudio(score),blob=scope==='pattern'?await renderer.renderWav(bars,tailSeconds,{signal}):(await renderer.renderNotes({events:[{note:selectedPitch,velocity,startBeat:0,durationBeats:.5,voiceId:'bass'}],state:score,tempo:score.tempo,lengthBeats:1,tailSeconds,signal})).blob;return {blob,sampleRate:48000,name:'roux-'+score.name.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'-'+scope+'.wav',tempo:score.tempo,sourceApp:'roux',sourceLabel:scope==='note'?S.noteName(selectedPitch):score.name,scope};}finally{exporting=false;}}
$('exportButton').addEventListener('click',async()=>{if(exporting)return;const button=$('exportButton');button.disabled=true;button.textContent='Thickening WAV…';button.setAttribute('aria-busy','true');try{const result=await exportAudio({bars:state.exportBars});download(result.blob,safeName()+'.wav');toast('Fresh stereo WAV. The low end travels well.');}catch(error){toast(error.message);}finally{button.disabled=false;button.innerHTML='Export WAV '+arrowIcon;button.removeAttribute('aria-busy');}});
$('saveButton').addEventListener('click',()=>{download(new Blob([S.serialize(state)],{type:'application/json'}),safeName()+'.roux.json');toast('The complete sound and recipe have been saved.');});$('openButton').addEventListener('click',()=>$('projectFile').click());$('projectFile').addEventListener('change',async()=>{const file=$('projectFile').files[0];$('projectFile').value='';if(!file)return;const token=++loadGeneration;try{if(file.size>1024*1024)throw new Error('Choose a ROUX project smaller than 1 MB.');const text=await file.text();if(token!==loadGeneration)return;const next=S.parseProject(text);loadState(next);toast('Your recipe is back on the range.');}catch(error){toast(error.message);}});
document.querySelectorAll('.tab').forEach(button=>button.addEventListener('click',()=>setTab(button.dataset.tab)));
function setTab(tab){document.querySelectorAll('.tab').forEach(button=>{const active=button.dataset.tab===tab;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});['foundation','envelopes','motion'].forEach(value=>$(value+'Panel').hidden=value!==tab);}
document.querySelector('.tab-bar').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const tabs=[...document.querySelectorAll('.tab')],index=tabs.indexOf(document.activeElement),next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length;setTab(tabs[next].dataset.tab);tabs[next].focus();});
$('helpButton').addEventListener('click',()=>$('helpDialog').showModal());$('closeHelp').addEventListener('click',()=>$('helpDialog').close());$('helpDialog').addEventListener('click',event=>{if(event.target===$('helpDialog')){const rect=$('helpDialog').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)$('helpDialog').close();}});
async function connectMIDI(){if(!navigator.requestMIDIAccess){toast('This browser does not support Web MIDI. The on-screen keys are ready.');return;}const button=$('midiButton');button.disabled=true;try{midiAccess=await navigator.requestMIDIAccess({sysex:false});const attach=()=>{let count=0;for(const input of midiAccess.inputs.values()){if(input.state==='connected'){count++;input.onmidimessage=onMIDI;}}$('midiStatus').textContent=count?count+' MIDI input'+(count===1?'':'s')+' connected. CC 74 opens the filter.':'MIDI is ready. Connect a keyboard to begin.';};midiAccess.onstatechange=attach;attach();button.textContent='MIDI connected ✓';await engine.init();}catch(error){toast('MIDI could not connect: '+error.message);}finally{button.disabled=false;}}
function onMIDI(event){const [status,note,velocity]=event.data,type=status&0xf0,source='roux-midi-'+(status&15)+'-'+note;if(type===0x90&&velocity>0){midiHeld.add(source);void midiNote(note,velocity/127,status&15);}else if(type===0x80||(type===0x90&&velocity===0)){midiHeld.delete(source);engine.stopNotes({source});}else if(type===0xb0&&note===74){commit(next=>{next.synth.cutoff=35*Math.pow(16000/35,velocity/127);},{capture:false});}else if(type===0xb0&&(note===120||note===123))panic();}
async function midiNote(note,velocity,channel){try{await engine.init();const source='roux-midi-'+channel+'-'+note;if(!midiHeld.has(source))return;const context=engine.context||engine.ctx;if(context)engine.scheduleNote({voiceId:'bass',note,velocity,when:context.currentTime+.003,durationSeconds:30,source,slide:false});else await engine.liveNote(note,velocity,1.5);}catch(error){toast(error.message);}}
$('midiButton').addEventListener('click',connectMIDI);
window.addEventListener('keydown',event=>{if(event.defaultPrevented)return;const target=event.target,typing=target instanceof HTMLElement&&(target.matches('input,select,textarea')||target.isContentEditable);if(event.key==='Escape'){if(!$('helpDialog').open)panic();return;}if($('helpDialog').open||typing)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();return;}if(event.ctrlKey||event.metaKey||event.altKey)return;if(event.code==='Space'){if(target instanceof Element&&target.closest('button,a[href]'))return;event.preventDefault();if(!event.repeat)play();return;}if(event.repeat)return;const index=keyLetters.indexOf(event.key.toUpperCase());if(index>=0){event.preventDefault();document.querySelectorAll('.key')[index].classList.add('pressed');audition(S.degreeMidi(state,index));}});
window.addEventListener('keyup',event=>{const index=keyLetters.indexOf(event.key.toUpperCase());if(index>=0)document.querySelectorAll('.key')[index].classList.remove('pressed');});window.addEventListener('blur',()=>{editActive=false;document.querySelectorAll('.key').forEach(key=>key.classList.remove('pressed'));});
if(location.protocol==='file:'){const base='https://calebhaines.github.io/sidequest-prototypes/music/';$('labLink').href=base;$('htmlDownload').href=base+'roux/index.html';$('sourceDownload').href=base+'roux/ROUX-source.zip';}
const canvas=$('stirCanvas'),context=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let size=1,dpr=1;
function sizeCanvas(){const rect=canvas.getBoundingClientRect();size=Math.max(1,rect.width);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(size*dpr);canvas.height=Math.round(size*dpr);context.setTransform(dpr,0,0,dpr,0,0);}
new ResizeObserver(sizeCanvas).observe(canvas);sizeCanvas();
// The five display bands share identical angles; retain their double-precision geometry.
const ringGeometry=Array.from({length:129},(_,point)=>{const angle=point/128*Math.PI*2;return{angle,cos:Math.cos(angle),sin:Math.sin(angle)};});
const meterNodes=Object.fromEntries(['pitchReadout','positionReadout','ringState','meterReadout','meterFill','ringMeter'].map(id=>[id,$(id)])),meterWidths=new WeakMap();
function meterText(id,value){const node=meterNodes[id];if(node.textContent!==value)node.textContent=value;}
function meterWidth(node,value){if(meterWidths.get(node)!==value){node.style.width=value;meterWidths.set(node,value);}}
function draw(time){const meters=engine.getMeters()||{},playing=!!engine.isPlaying,position=typeof meters.position==='number'?meters.position:-1;context.clearRect(0,0,size,size);const center=size/2,radius=size*.27,amplitude=Math.min(size*.04,(meters.rms||0)*size*.25);context.lineWidth=.75;context.strokeStyle='#5d8d8450';for(let band=0;band<5;band++){context.beginPath();for(let point=0;point<=128;point++){const {angle,cos,sin}=ringGeometry[point],wave=meters.waveform?.length?meters.waveform[Math.floor(point/128*(meters.waveform.length-1))]||0:Math.sin(angle*7+(reduced.matches?0:time*.0008))*(playing?.3:.04),r=radius+band*size*.011+wave*amplitude,x=center+cos*r,y=center+sin*r;point?context.lineTo(x,y):context.moveTo(x,y);}context.closePath();context.stroke();}
 if(playing&&!state.musicLabPattern&&position>=0){const angle=-Math.PI/2+position*Math.PI/8;context.strokeStyle='#e4cf7950';context.lineWidth=1;context.beginPath();context.moveTo(center+Math.cos(angle)*size*.245,center+Math.sin(angle)*size*.245);context.lineTo(center+Math.cos(angle)*size*.38,center+Math.sin(angle)*size*.38);context.stroke();}
 const current=playing&&!state.musicLabPattern?position:-1;if(current!==lastPosition){stepNodes.forEach((button,index)=>button.classList.toggle('current',index===current));lastPosition=current;}
 const pitch=(playing||(meters.rms||0)>1e-4)&&meters.frequency>0?Math.round(69+12*Math.log2(meters.frequency/440)):playing&&position>=0?firstPosition(position).pitch:firstPosition(selectedStep).pitch;meterText('pitchReadout',S.noteName(pitch));meterText('positionReadout',playing?(state.musicLabPattern?'BEAT '+(Math.floor((meters.beat||0)%4)+1):'STOP '+String(position+1).padStart(2,'0')+' / '+state.recipe.length):'STOP — / '+state.recipe.length);meterText('ringState',state.musicLabPattern?'IMPORTED ORDER':playing?'THE BOTTOM IS MOVING':'READY TO STIR');
 const rms=meters.rms||0,db=20*Math.log10(Math.max(.00001,rms));meterText('meterReadout',rms>1e-5?db.toFixed(1)+' dB':'−∞ dB');meterWidth(meterNodes.meterFill,Math.min(100,Math.max(0,(db+60)/60*100))+'%');meterWidth(meterNodes.ringMeter,Math.min(100,rms*350)+'%');
 const visits=playing?Math.floor((meters.beat||0)/S.DIVISIONS[state.recipe.division]):-1;for(const id of ['accentCycle','slideCycle']){const ring=id==='accentCycle'?state.recipe.accents:state.recipe.slides,current=playing?visits%ring.length:-1;if(current!==cyclePositions[id]){const pips=$(id).children;for(let index=0;index<pips.length;index++)pips[index].classList.toggle('current',index===current);cyclePositions[id]=current;}}
 updateTransport();requestAnimationFrame(draw);
}
Object.defineProperty(window,'RouxApp',{value:Object.freeze({getState:()=>S.copy(state),getProject:()=>S.copy(state),setState:value=>loadState(value),loadState:value=>loadState(value),loadProject:value=>loadState(value),get engine(){return engine;},get state(){return S.copy(state);},prepare:()=>engine.init(),play,start:play,stop,panic,rewind,exportAudio,audioExport:{scopes:[{id:'pattern',label:'Complete bass recipe'},{id:'note',label:'Selected bass note'}],defaultBars:4,maxBars:16}}),writable:false,configurable:false});
renderState();setTab('foundation');requestAnimationFrame(draw);window.RouxAppReady=true;document.dispatchEvent(new CustomEvent('musiclab:app-ready',{detail:{app:'roux'},bubbles:true}));
})();
