/* Actual-DSP regression checks; no browser or installation is needed. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const sharedRoot=fs.existsSync(path.join(__dirname,'shared','pattern-schema.js'))?path.join(__dirname,'shared'):path.resolve(__dirname,'..','shared'),sandbox={window:{},Blob,DOMException,TextEncoder,Float32Array,ArrayBuffer,DataView,Math,JSON,Number,Object,String,Array,Set,Map,Promise,setTimeout,clearTimeout};
vm.createContext(sandbox);for(const file of [path.join(sharedRoot,'pattern-schema.js'),...['schema.js','audio-engine.js','presets.js'].map(file=>path.join(__dirname,file))])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
const S=sandbox.window.RouxSchema,D=sandbox.window.RouxDSP,A=sandbox.window.RouxAudio,P=sandbox.window.MusicLabPatternSchema;
function render(core,frames){const pcm=new Float32Array(frames);for(let at=0;at<frames;){const size=Math.min(1024,frames-at),l=new Float32Array(size),r=new Float32Array(size);core.processBlock(l,r);for(let i=0;i<size;i++){assert(Number.isFinite(l[i])&&Number.isFinite(r[i]),'Every output frame must be finite');assert(Math.abs(l[i])<=1&&Math.abs(r[i])<=1,'Output must remain bounded');pcm[at+i]=(l[i]+r[i])*.5;}at+=size;}return pcm;}
function rms(pcm,start=0,end=pcm.length){let sum=0;for(let i=start;i<end;i++)sum+=pcm[i]*pcm[i];return Math.sqrt(sum/Math.max(1,end-start));}
function frequency(pcm,sr,expected){const period=sr/expected,low=Math.max(2,Math.floor(period*.965)),high=Math.ceil(period*1.035),start=Math.min(Math.round(sr*.2),Math.floor(pcm.length*.25));let best=0,min=Infinity;for(let lag=low;lag<=high;lag++){let error=0,count=0;for(let i=start;i<pcm.length-high;i+=2){const d=pcm[i]-pcm[i+lag];error+=d*d;count++;}error/=count;if(error<min){min=error;best=lag;}}return sr/best;}
function dry(){const s=S.defaultState();Object.assign(s.master,{echo:0,volume:.72});Object.assign(s.synth,{oscillator:0,body:0,sub:1,cutoff:16000,resonance:0,drive:0,fold:0,pitchDepth:0});Object.assign(s.synth.filterEnv,{amount:0});Object.assign(s.synth.lfo,{depth:0});Object.assign(s.synth.amp,{attack:.005,decay:.1,sustain:1,release:.008});return s;}
(async()=>{
 const base=S.defaultState(),recipe=S.compileRecipe(base,{cycles:4});assert.equal(recipe.lengthBeats,32);assert(recipe.notes.length>32);assert.deepEqual(S.compileRecipe(base,{cycles:4}),recipe,'The recipe must repeat deterministically');
 const shifted=S.copy(base);shifted.recipe.drift=1;const drift=S.compileRecipe(shifted,{cycles:4});const starts=[0,8,16,24].map(beat=>drift.notes.find(n=>n.beat===beat)?.pitch);assert.deepEqual(Array.from(starts),[36,38,39,41],'Drift must change each complete circuit');
 const reverse=S.copy(base);reverse.recipe.direction='reverse';const backwards=S.compileRecipe(reverse);assert.equal(backwards.steps[0].index,15);assert.notDeepEqual(backwards.notes.map(n=>n.pitch),S.compileRecipe(base).notes.map(n=>n.pitch));
 const tie=S.copy(base);tie.recipe.length=4;tie.recipe.slides.pulses=0;tie.recipe.steps[0].mode='root';tie.recipe.steps[1].mode='hold';tie.recipe.steps[2].mode='rest';tie.recipe.steps[3].mode='hold';const held=S.compileRecipe(tie);assert.equal(held.notes.length,1);assert(held.notes[0].duration<=held.steps[2].beat,'A hold must never bridge an explicit rest');
 const slide=S.copy(base);slide.recipe.length=4;slide.recipe.slides.pulses=0;slide.recipe.steps[0].mode='root';slide.recipe.steps[1].mode='note';slide.recipe.steps[1].slide=true;assert(S.compileRecipe(slide).notes[0].duration>S.compileRecipe(slide).notes[1].beat,'A portable slide must use overlap');
 const round=S.serialize(base);assert.deepEqual(JSON.parse(JSON.stringify(S.parseProject(round))),JSON.parse(JSON.stringify(base)));for(const change of [s=>s.tempo=999,s=>s.synth.cutoff=-1,s=>s.recipe.direction='sideways',s=>s.recipe.steps[0].gate=NaN]){const bad=S.copy(base);change(bad);assert.throws(()=>S.parseProject(JSON.stringify({format:'roux-project',formatVersion:1,state:bad})));}
 const packet=P.normalize({format:'musiclab-pattern',version:1,name:'Mono',sourceApp:'QA',kind:'notes',tempo:120,swing:0,lengthBeats:4,meter:[4,4],voices:[{id:'a',name:'Bass'}],notes:[{id:'n',pitch:36,beat:0,duration:1,velocity:.8,voice:'a',probability:1}]});const overlay=S.normalize({...base,musicLabPattern:{pattern:packet,voiceMap:{a:'bass'}}});assert.equal(S.parseProject(S.serialize(overlay)).musicLabPattern.pattern.notes[0].pitch,36);
 const chord=S.copy(packet);chord.notes.push({...chord.notes[0],id:'chord',pitch:40});assert.throws(()=>S.normalize({...base,musicLabPattern:{pattern:chord,voiceMap:{a:'bass'}}}),/one bass line/);const outside=S.copy(packet);outside.notes[0].pitch=0;assert.throws(()=>S.normalize({...base,musicLabPattern:{pattern:outside,voiceMap:{a:'bass'}}}),/C0/);
 const pitches=[];for(const pitch of [24,36,48,60,84]){const state=dry(),core=new D.Core(48000,state,S.compileRecipe(state));core.note(pitch,.85,1,'pitch');const audio=render(core,36000),expected=440*Math.pow(2,(pitch-69)/12),found=frequency(audio,48000,expected);assert(Math.abs(found-expected)/expected<.012,`Fundamental ${pitch} should be in tune: ${found} vs ${expected}`);assert(rms(audio)>.05);pitches.push({pitch,hz:+found.toFixed(2)});}
 const materials=[];for(const material of S.MATERIALS){const state=dry();Object.assign(state.synth,{sub:0,body:1,excitation:1,bite:.6,damping:.18,bodyDecay:3,material});const core=new D.Core(48000,state,S.compileRecipe(state));core.note(36,.85,1,'body');const audio=render(core,36000),found=frequency(audio,48000,65.406);assert(rms(audio)>.01,material+' waveguide must be audible');assert(Math.abs(found-65.406)/65.406<.035,material+' waveguide must retain its tuned fundamental');materials.push({material,hz:+found.toFixed(2),rms:+rms(audio).toFixed(4)});}
 const services=[];for(const preset of sandbox.window.RouxPresets){const core=new D.Core(48000,preset.state,S.compileRecipe(preset.state,{cycles:4}));core.start();const audio=render(core,72000),level=rms(audio);assert(preset.id==='empty'?level===0:level>.002,preset.name+' must have the expected output');services.push({id:preset.id,rms:+level.toFixed(4)});}
 for(const filterType of ['lowpass','bandpass','highpass'])for(const pitch of [12,108]){const state=S.defaultState();Object.assign(state.synth,{material:'ceramic',filterType,drive:1,fold:1,body:1,sub:1,oscillator:1,bodyDecay:8,damping:0,cutoff:16000,resonance:.95,pitchDepth:24,excitation:1});Object.assign(state.synth.lfo,{shape:'square',target:'cutoff',depth:1,rate:24});state.master.feedback=.82;state.master.echo=1;const core=new D.Core(48000,state,S.compileRecipe(state));core.note(pitch,1,.7,'extreme');render(core,48000);}
 const cancelState=dry(),cancel=new D.Core(48000,cancelState,S.compileRecipe(cancelState));cancel.scheduleNote(36,.85,2400,.4,'a');cancel.stopNotes('a',10560);assert.equal(cancel.scheduleNote(48,.85,17000,.3,'a'),false,'Cancelled future sources may not refill their queue');cancel.scheduleNote(43,.85,24000,.3,'b');const first=render(cancel,24000);assert(rms(first,5000,8000)>.05,'A must sound before its cutoff');assert(rms(first,19000,21000)<.00001,'A must be silent after its release');const next=render(cancel,12000);assert(rms(next,3000,7000)>.05,'Cancelling A must preserve B');cancel.stopNotes('b');const release=render(cancel,6000);assert(rms(release,4000,6000)<.00001,'Immediate source cancellation must release B');cancel.stopNotes('a');assert.equal(cancel.scheduleNote(36,.85,cancel.frame+100,.2,'a'),true,'Immediate cancellation must clear the old source cutoff');
 const engine=new A(base),before=JSON.stringify(engine.state);const one=await engine.renderWav(1,.3),two=await engine.renderWav(1,.3);assert.equal(JSON.stringify(engine.state),before,'Rendering must not mutate the patch');const buffer=Buffer.from(await one.arrayBuffer());assert(buffer.equals(Buffer.from(await two.arrayBuffer())),'Independent renders must be byte-for-byte deterministic');assert.equal(buffer.toString('ascii',0,4),'RIFF');assert.equal(buffer.readUInt16LE(22),2);assert.equal(buffer.readUInt32LE(24),48000);assert(buffer.length>100000);
 const controller=new AbortController();controller.abort();await assert.rejects(engine.renderWav(1,1,{signal:controller.signal}),e=>e.name==='AbortError');
 const fast=await engine.renderNotes({events:[{note:36,velocity:.8,startBeat:0,durationBeats:.5}],tempo:1920,lengthBeats:1,tailSeconds:.1});assert(fast.blob.size>44,'GALLEY playback rates must remain supported');
 console.log(JSON.stringify({passed:true,recipeNotes:recipe.notes.length,pitches,materials,services,deterministicWavBytes:buffer.length},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
