/* Twelve service cards: distinct synthesis, distinct ways around the pan. */
(() => {
 'use strict';const S=window.RouxSchema;
 const merge=(target,source)=>{for(const [key,value]of Object.entries(source||{})){if(value&&typeof value==='object'&&!Array.isArray(value))merge(target[key]||(target[key]={}),value);else target[key]=value;}return target;};
 function make(id,name,description,changes={},instructions=null){const state=merge(S.defaultState(),changes);state.name=name;state.seed=([...id].reduce((n,c)=>Math.imul(n,31)+c.charCodeAt(0),43971)>>>0)||1;if(instructions)state.recipe.steps=instructions.map((instruction,i)=>typeof instruction==='string'?{...S.step(instruction),velocity:i%4===0?.88:.69}:merge(S.step('note'),instruction));return {id,name,description,state:S.normalize(state)};}
 const instructions=(moves,rests=[])=>Array.from({length:16},(_,i)=>({mode:i===0||i===8?'root':rests.includes(i)?'rest':'note',move:moves[i%moves.length],velocity:i%4===0?.88:.68,gate:.84,probability:1,accent:false,slide:false,octave:0}));
 window.RouxPresets=[
  make('simmer','The low simmer','Round-bottomed bass, one unruly spoon.'),
  make('acid','Health inspector on acid','A sharp little resonant line with an uneven slide necklace.',{tempo:128,root:36,scale:'phrygian',swing:.08,recipe:{division:'1/16',accents:{length:7,pulses:3,amount:.35},slides:{length:5,pulses:2}},synth:{waveform:'saw',sub:.44,body:.12,drive:.68,fold:.1,cutoff:370,resonance:.78,filterEnv:{amount:5,decay:.16,sustain:0},amp:{attack:.002,decay:.15,sustain:.22,release:.05},glide:.07},master:{echo:.19,feedback:.38}},instructions([0,0,2,-1,3,-3,1,-2],[5,13])),
  make('stock','Stock reduction','A weighty sine foundation under a nearly closed lid.',{tempo:78,root:29,scale:'minor',swing:.3,recipe:{slides:{pulses:0},accents:{length:4,pulses:1,amount:.15}},synth:{waveform:'triangle',sub:1,oscillator:.14,body:.2,cutoff:480,drive:.08,fold:0,filterEnv:{amount:.6,decay:.5},amp:{attack:.01,decay:.5,sustain:.65,release:.32},lfo:{depth:0}},master:{echo:.28,feedback:.56,tone:.19}},instructions([0,0,0,2,0,-2,0,0],[2,3,6,7,10,11,14,15])),
  make('rubber','Rubber spatula funk','Snapped envelopes and a wobbling waveguide.',{tempo:103,root:36,scale:'dorian',swing:.32,recipe:{slides:{length:9,pulses:2},accents:{length:5,pulses:3}},synth:{waveform:'square',pulseWidth:.32,oscillator:.3,body:.68,material:'rubber',damping:.68,bodyDecay:.48,bite:.68,drive:.38,cutoff:630,filterEnv:{amount:4.7,decay:.13,sustain:0},amp:{attack:.003,decay:.11,sustain:.09,release:.055},lfo:{target:'pulse',depth:.32,rate:2.8}},master:{echo:.08}},instructions([0,2,-1,0,3,-3,0,1],[3,6,10,14])),
  make('copper','Copper-bottomed trouble','A metallic bass reed that rings under the filter.',{tempo:116,root:31,scale:'harmonic',recipe:{rotation:3,accents:{length:9,pulses:4},slides:{length:6,pulses:1}},synth:{sub:.36,oscillator:.28,body:.95,material:'copper',bodyDecay:3.2,damping:.16,excitation:.92,bite:.79,bodyTune:0,cutoff:2300,resonance:.36,drive:.53,filterEnv:{amount:1.5},amp:{decay:.38,sustain:.5,release:.27},lfo:{target:'body',rate:.6,depth:.25}},master:{echo:.22,feedback:.35}},instructions([0,2,1,-2,4,-1,-3,0],[4,12])),
  make('glaze','Ceramic glaze','Glossy bowed bass from a stretched resonant pot.',{tempo:91,root:33,scale:'pentatonic',swing:0,recipe:{division:'1/8',gate:1,slides:{length:4,pulses:3},accents:{amount:.12}},synth:{waveform:'fold',sub:.52,oscillator:.22,body:.83,material:'ceramic',damping:.4,bodyDecay:4.4,excitation:.46,bite:.18,drive:.21,fold:.42,cutoff:950,resonance:.24,glide:.26,amp:{attack:.028,decay:.65,sustain:.7,release:.35},filterEnv:{attack:.08,decay:.62,amount:1.5},lfo:{target:'body',shape:'sine',sync:'1/1',depth:.3}},master:{echo:.32,width:.65,feedback:.46}},instructions([0,0,1,1,-1,2,-2,0])),
  make('char','Charred iron','A hard-edged bass grind with short gates.',{tempo:139,root:28,scale:'minor',swing:.04,recipe:{division:'1/16',stride:3,accents:{length:7,pulses:4},slides:{pulses:0}},synth:{waveform:'square',pulseWidth:.27,body:.7,material:'iron',damping:.18,bite:1,excitation:1,bodyDecay:.9,drive:.95,fold:.5,cutoff:1400,resonance:.62,amp:{attack:.002,decay:.1,sustain:.12,release:.028},filterEnv:{amount:2.7,decay:.09},lfo:{shape:'square',target:'drive',sync:'1/8',depth:.25}},master:{volume:.58,echo:.11,feedback:.22}},instructions([0,0,-2,1,0,3,-1,0],[3,7,11,15])),
  make('butter','Butter in reverse','A warm square wave takes the long route home.',{tempo:96,root:36,scale:'major',recipe:{direction:'reverse',rotation:7,slides:{length:3,pulses:1},accents:{length:6,pulses:2}},synth:{waveform:'square',pulseWidth:.54,sub:.78,body:.2,drive:.19,cutoff:760,resonance:.1,fold:0,amp:{attack:.005,decay:.25,sustain:.48,release:.14},filterEnv:{amount:1.6},lfo:{target:'pulse',shape:'sine',rate:.18,depth:.2}},master:{echo:.14}},instructions([0,1,2,0,-2,0,3,-1],[3,10])),
  make('ladle','The pendulum ladle','Seven stations, thirteen orders, and a triplet clock.',{tempo:122,root:38,scale:'dorian',swing:0,recipe:{length:7,division:'1/8T',direction:'pendulum',accents:{length:5,pulses:2},slides:{length:8,pulses:3}},synth:{waveform:'triangle',oscillator:.46,body:.58,material:'rubber',damping:.32,drive:.28,cutoff:1650,resonance:.36,amp:{decay:.19,sustain:.24,release:.08},filterEnv:{amount:2.8},lfo:{sync:'1/2',shape:'sine',target:'cutoff',depth:.19}},master:{echo:.2,division:'1/4',feedback:.42}},instructions([0,2,-1,3,-2,0,1,-1],[3])),
  make('walking','The walking pantry','Each completed circuit moves the root another scale degree.',{tempo:118,root:31,scale:'dorian',recipe:{drift:1,slides:{pulses:0},accents:{length:4,pulses:1,amount:.2}},synth:{waveform:'triangle',oscillator:.23,sub:.85,body:.48,material:'copper',damping:.65,bodyDecay:1.2,drive:.13,cutoff:1050,filterEnv:{amount:.9,decay:.22},amp:{attack:.008,decay:.26,sustain:.13,release:.09},lfo:{depth:0}},master:{echo:.05}},instructions([0,1,1,1,-1,-1,2,-2],[5,13])),
  make('wobble','Extractor wobble','A moving filter and a stubborn low-frequency foundation.',{tempo:140,root:27,scale:'minor',recipe:{division:'1/8',gate:1,slides:{length:4,pulses:3},accents:{amount:.12}},synth:{waveform:'saw',sub:.9,oscillator:.64,body:.2,drive:.75,fold:.32,cutoff:610,resonance:.5,amp:{attack:.01,decay:.3,sustain:.8,release:.1},filterEnv:{amount:.7,decay:.16},lfo:{target:'cutoff',sync:'1/4',shape:'triangle',depth:.95}},master:{echo:.1,width:.12}},instructions([0,0,0,0,3,0,-3,0],[6,14])),
  make('empty','An empty pan','No sequence. The keyboard and live notes remain ready.',{recipe:{slides:{pulses:0},accents:{pulses:0}}},Array.from({length:16},()=>S.step('rest'))),
 ];
})();
