/* One physical delay-loop core, shared by the audio thread, fallback and WAV renderer. */
(function(){
'use strict';
function createBowerDSP(){
 const TAU=Math.PI*2,clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(+n)?+n:a));
 const scales={minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],dorian:[0,2,3,5,7,9,10],pentatonic:[0,2,4,7,9],lydian:[0,2,4,6,7,9,11],whole:[0,2,4,6,8,10]},divisions={'1/16':.25,'1/8':.5,'1/4':1,'3/8':1.5,'1/2':2};
 class StringVoice{
  constructor(sr,note,velocity,lane,index,random){
   this.index=index;this.sr=sr;this.age=0;this.energy=1;this.prev=0;this.allpassIn=0;this.allpassOut=0;this.body=0;this.bodyVelocity=0;this.dc=0;
   this.frequency=clamp(440*Math.pow(2,(note-69+lane.tension/100)/12),32,3200);
   // Fractional delay compensates the one-pole averaging filter's group delay.
   this.bright=clamp(lane.brightness,0,1);this.mix=.04+(1-this.bright)*.46;
   this.delay=Math.max(4,sr/this.frequency-this.mix);this.length=Math.ceil(this.delay)+3;this.buffer=new Float32Array(this.length);this.write=0;
   this.decay=clamp(lane.decay,.15,12);this.feedback=Math.pow(.001,1/(this.frequency*this.decay));this.dispersion=clamp(lane.dispersion,0,.6)*.48;
   this.velocity=clamp(velocity,.05,1);this.level=1.26;this.panL=Math.cos((lane.pan+1)*Math.PI/4);this.panR=Math.sin((lane.pan+1)*Math.PI/4);
   this.bodyType=lane.body;const bodyHz={wood:210,steel:860,glass:1270,hollow:120}[lane.body]||210;this.bodyW=TAU*bodyHz/sr;this.bodyQ={wood:.055,steel:.018,glass:.012,hollow:.035}[lane.body]||.04;
   const size=Math.max(4,Math.round(this.delay)),noise=new Float32Array(size);let low=0,mean=0;
   for(let i=0;i<size;i++){const x=random()*2-1;low+=({finger:.19,pick:.84,hammer:.38,wire:1}[lane.exciter]||.5)*(x-low);noise[i]=low;mean+=low;}mean/=size;
   const shift=Math.max(1,Math.round(clamp(lane.position,.03,.49)*size));let max=.001;
   for(let i=0;i<size;i++){const x=(noise[i]-mean)-(noise[(i-shift+size)%size]-mean);this.buffer[i]=x;max=Math.max(max,Math.abs(x));}
   for(let i=0;i<size;i++)this.buffer[i]*=.68*this.velocity/max;
  }
  tick(damp){
   let read=this.write-this.delay;while(read<0)read+=this.length;const a=Math.floor(read),f=read-a,x=this.buffer[a]*(1-f)+this.buffer[(a+1)%this.length]*f;
   let filtered=x*(1-this.mix)+this.prev*this.mix;this.prev=x;
   if(this.dispersion>.0001){const y=-this.dispersion*filtered+this.allpassIn+this.dispersion*this.allpassOut;this.allpassIn=filtered;this.allpassOut=y;filtered=y;}
   this.buffer[this.write]=clamp(filtered*this.feedback*(damp?.965:1),-2,2);this.write=(this.write+1)%this.length;
   // A broad, damped body mode colours the string without replacing its delay-loop pitch.
   this.bodyVelocity+=(x-this.body)*this.bodyW*this.bodyW;this.bodyVelocity*=1-this.bodyQ;this.body+=this.bodyVelocity;
   const out=x+this.body*({wood:.26,steel:.15,glass:.12,hollow:.38}[this.bodyType]||.2);this.dc+=.0008*(out-this.dc);
   this.energy+=.002*(x*x-this.energy);this.age++;return(out-this.dc)*this.level*(this.gateFrames===undefined||this.age<=this.gateFrames?1:Math.exp(-(this.age-this.gateFrames)/(this.sr*.012)));
  }
 }
 class Core{
  constructor(sampleRate,state){this.sr=clamp(sampleRate,8000,192000);this.frame=0;this.transport=0;this.running=false;this.voices=[];this.events=[];this.cancellations=[];this.damping=false;this.positions=[-1,-1,-1,-1];this.rms=0;this.peak=0;this.laneRms=[0,0,0,0];this.waveform=new Float32Array(128);this.waveAt=0;this.echo=[new Float32Array(Math.ceil(this.sr*4)+2),new Float32Array(Math.ceil(this.sr*4)+2)];this.echoAt=0;this.echoLow=[0,0];this.room=[.0297,.0371,.0411,.0437,.0317,.0393,.0439,.0473].map(t=>({buffer:new Float32Array(Math.round(t*this.sr)),at:0,low:0}));this.volume=.7;this.laneMix=Array.from({length:4},()=>[0,0]);this.setState(state);this.rewind();}
  random(){let x=this.seed;x^=x<<13;x^=x>>>17;x^=x<<5;this.seed=x>>>0||1;return this.seed/4294967296;}
  setState(state){this.state=state;this.tempo=clamp(state.tempo,40,190);this.master=state.master;this.lanes=state.lanes;this.stepsPerBeat=this.sr*60/this.tempo;}
  rewind(){this.transport=0;this.seed=this.state.seed>>>0||1;this.clocks=Array.from({length:4},()=>({next:0,count:0}));this.positions.fill(-1);this.events=[];}
  start(rewind=true){if(rewind)this.rewind();this.running=true;}
  stop(){this.running=false;this.events=[];this.cancellations=[];}
  panic(){this.stop();this.voices=[];this.echo.forEach(b=>b.fill(0));this.echoLow.fill(0);this.room.forEach(r=>{r.buffer.fill(0);r.low=0;});this.laneRms.fill(0);this.peak=this.rms=0;this.waveform.fill(0);this.damping=false;this.positions.fill(-1);}
  damp(active){this.damping=!!active;}
  degreeMidi(index,degree){const sc=scales[this.state.scale]||scales.minor,d=Math.round(degree),oct=Math.floor(d/sc.length),at=((d%sc.length)+sc.length)%sc.length;return clamp(this.state.root+this.lanes[index].octave*12+oct*12+sc[at],24,100);}
  pluck(index,degree=0,velocity=.8,midiNote=null,duration=null,source='native'){index=clamp(index,0,3)|0;const l=this.lanes[index],solo=this.lanes.some(x=>x.solo);if(l.mute||(solo&&!l.solo))return;const note=midiNote===null?this.degreeMidi(index,degree):clamp(midiNote,24,100);if(this.voices.length>=16){let quiet=0;for(let i=1;i<this.voices.length;i++)if(this.voices[i].energy<this.voices[quiet].energy)quiet=i;this.voices.splice(quiet,1);}const voice=new StringVoice(this.sr,note,velocity,l,index,()=>this.random());voice.source=source;if(Number.isFinite(duration)&&duration>0)voice.gateFrames=Math.max(1,Math.round(duration*this.sr));this.voices.push(voice);}
  scheduleNote(index,note,velocity,frame,duration,source='native'){if(this.cancellations.some(c=>(!c.source||c.source===source)&&frame>=c.frame))return false;if(this.events.length>=8192)throw new Error('The note queue is full.');this.events.push({at:Math.max(this.frame,Math.round(frame)),lane:clamp(index,0,3)|0,degree:0,velocity:clamp(velocity,.01,1),note:clamp(note,24,100),duration,source});}
  stopNotes(source,frame=this.frame){frame=Math.max(this.frame,Math.round(Number.isFinite(frame)?frame:this.frame));if(frame>this.frame){this.events=this.events.filter(e=>(source&&e.source!==source)||e.at<frame);if(this.cancellations.length>=256)throw new Error('The cancellation queue is full.');this.cancellations.push({source,frame});this.cancellations.sort((a,b)=>a.frame-b.frame);return;}this.cancellations=source?this.cancellations.filter(c=>c.source!==source):[];this.events=source?this.events.filter(e=>e.source!==source):[];for(const voice of this.voices)if(!source||voice.source===source)voice.gateFrames=Math.min(voice.gateFrames??Infinity,voice.age);}
  strum(){for(let i=0;i<4;i++)this.events.push({at:this.frame+i*Math.round(this.sr*.045),lane:i,degree:[0,2,4,7][i],velocity:.9});}
  sequence(){for(let i=0;i<4;i++){const c=this.clocks[i],l=this.lanes[i];if(this.transport+.001<c.next)continue;const length=clamp(l.length,1,16)|0,k=c.count;let at=k%length;if(l.direction==='reverse')at=length-1-at;else if(l.direction==='pendulum')at=length===1?0:(k%(length*2-2)<length?k%(length*2-2):length*2-2-k%(length*2-2));else if(l.direction==='random')at=Math.floor(this.random()*length);this.positions[i]=at;const step=l.steps[at];if(step.on&&this.random()<step.probability){let degree=step.degree;if(this.state.evolution&&this.random()<l.evolve)degree+=this.random()<.5?-1:1;const velocity=clamp(step.velocity*(1+(this.random()*2-1)*this.state.humanize*5),.05,1);this.events.push({at:this.frame+Math.round(this.random()*this.state.humanize*this.sr),lane:i,degree,velocity});}const interval=this.stepsPerBeat*(divisions[l.division]||.5);c.next+=interval*(1+(k%2===0?1:-1)*this.state.swing*.5);c.count++;}}
  processBlock(left,right){let sum=0,peak=0;const laneSum=[0,0,0,0],m=this.master,echoFrames=clamp((divisions[m.division]||.5)*this.stepsPerBeat,1,this.echo[0].length-1),delay=Math.round(echoFrames),feedback=clamp(m.feedback,0,.8),target=clamp(m.volume,0,1),width=clamp(m.width,0,1);for(let j=0;j<left.length;j++){
   while(this.cancellations.length&&this.cancellations[0].frame<=this.frame){const cancel=this.cancellations.shift();this.stopNotes(cancel.source);}if(this.running)this.sequence();for(let k=this.events.length-1;k>=0;k--)if(this.events[k].at<=this.frame){const e=this.events[k];this.pluck(e.lane,e.degree,e.velocity,e.note??null,e.duration??null,e.source??'native');this.events.splice(k,1);}let l=0,r=0;const lanes=[0,0,0,0],solo=this.lanes.some(x=>x.solo);for(let i=0;i<4;i++){const targetLane=this.lanes[i],gain=targetLane.mute||(solo&&!targetLane.solo)?0:clamp(targetLane.level,0,1);this.laneMix[i][0]+=.002*(gain*Math.cos((targetLane.pan+1)*Math.PI/4)-this.laneMix[i][0]);this.laneMix[i][1]+=.002*(gain*Math.sin((targetLane.pan+1)*Math.PI/4)-this.laneMix[i][1]);}
   for(let k=this.voices.length-1;k>=0;k--){const v=this.voices[k],x=v.tick(this.damping),current=this.lanes[v.index];l+=x*this.laneMix[v.index][0];r+=x*this.laneMix[v.index][1];lanes[v.index]+=x;if(v.age>(v.gateFrames??Infinity)+this.sr*.15||v.age>this.sr*18||(v.age>this.sr*.2&&v.energy<1e-10)||!Number.isFinite(x))this.voices.splice(k,1);}
   for(let i=0;i<4;i++)laneSum[i]+=lanes[i]*lanes[i]*(this.laneMix[i][0]*this.laneMix[i][0]+this.laneMix[i][1]*this.laneMix[i][1])*.5;const ep=(this.echoAt-delay+this.echo[0].length)%this.echo[0].length,el=this.echo[0][ep],er=this.echo[1][ep];this.echoLow[0]+=.24*(el-this.echoLow[0]);this.echoLow[1]+=.24*(er-this.echoLow[1]);this.echo[0][this.echoAt]=Math.tanh(l+this.echoLow[1]*feedback);this.echo[1][this.echoAt]=Math.tanh(r+this.echoLow[0]*feedback);this.echoAt=(this.echoAt+1)%this.echo[0].length;l+=el*clamp(m.echo,0,1)*.65;r+=er*clamp(m.echo,0,1)*.65;
   let roomL=0,roomR=0;for(let k=0;k<this.room.length;k++){const d=this.room[k],v=d.buffer[d.at];d.low+=.25*(v-d.low);d.buffer[d.at]=Math.tanh((k<4?l:r)*.16+d.low*.74);d.at=(d.at+1)%d.buffer.length;if(k<4)roomL+=v;else roomR+=v;}l+=roomL*clamp(m.room,0,1)*.35;r+=roomR*clamp(m.room,0,1)*.35;const mid=(l+r)*.5,side=(l-r)*.5*width;this.volume+=(target-this.volume)*.002;l=Math.tanh((mid+side)*this.volume);r=Math.tanh((mid-side)*this.volume);left[j]=Number.isFinite(l)?l:0;right[j]=Number.isFinite(r)?r:0;sum+=(l*l+r*r)*.5;peak=Math.max(peak,Math.abs(l),Math.abs(r));if(this.frame%Math.max(1,Math.floor(this.sr/300))===0)this.waveform[this.waveAt++%128]=(l+r)*.5;this.frame++;if(this.running)this.transport++;}
   this.rms=Math.sqrt(sum/left.length);this.peak=Math.max(peak,this.peak*.88);for(let i=0;i<4;i++)this.laneRms[i]=Math.sqrt(laneSum[i]/left.length);
  }
  getMeters(){return{rms:this.rms,peak:this.peak,lanes:this.laneRms.slice(),positions:this.positions.slice(),voices:this.voices.length,beat:this.transport/this.stepsPerBeat,waveform:Array.from(this.waveform)};}
 }
 return{Core,StringVoice};
}
const DSP=createBowerDSP();window.BowerDSP=DSP;
function wav(chunks,sampleRate){let frames=0;for(const c of chunks)frames+=c.length/2;const bytes=new ArrayBuffer(44+frames*4),v=new DataView(bytes),text=(p,s)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i));};text(0,'RIFF');v.setUint32(4,36+frames*4,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,frames*4,true);let at=44;for(const c of chunks)for(const x of c){const a=Math.max(-1,Math.min(1,Number.isFinite(x)?x:0));v.setInt16(at,Math.round(a<0?a*32768:a*32767),true);at+=2;}return new Blob([bytes],{type:'audio/wav'});}
class Audio{
 constructor(state){this.state=window.BowerSchema.normalize(state);this.context=null;this.node=null;this.core=null;this.isPlaying=false;this.isRecording=false;this.recordFrames=0;this.chunks=[];this.generation=0;this.meters={rms:0,peak:0,lanes:[0,0,0,0],positions:[-1,-1,-1,-1],voices:0,beat:0,waveform:[]};this.onStatus=null;this.onRecordingLimit=null;this.initPromise=null;this.recordId=0;this.activeRecord=0;this.recordRequest=0;this.recordStopPromise=null;this.recordFinish=null;}
 async init(){if(this.initPromise)return this.initPromise;if(this.context){if(this.context.state==='suspended')await this.context.resume();return true;}if(this.initPromise)return this.initPromise;this.initPromise=this.setup();try{return await this.initPromise;}finally{this.initPromise=null;}}
 async setup(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('This browser does not support Web Audio.');const ctx=new AC({latencyHint:'interactive'});this.context=ctx;let worklet=false;try{if(ctx.audioWorklet&&window.AudioWorkletNode){const source=`${createBowerDSP.toString()}\nconst DSP=createBowerDSP();class BowerProcessor extends AudioWorkletProcessor{constructor(){super();this.core=null;this.record=false;this.recordId=0;this.blocks=0;this.port.onmessage=e=>{const m=e.data;if(m.type==='state'){if(this.core)this.core.setState(m.state);else {this.core=new DSP.Core(sampleRate,m.state);this.core.frame=currentFrame;}}else if(this.core){if(m.type==='start')this.core.start();if(m.type==='stop')this.core.stop();if(m.type==='panic')this.core.panic();if(m.type==='damp')this.core.damp(m.active);if(m.type==='pluck')this.core.pluck(m.index,m.degree,m.velocity,m.note);if(m.type==='note')this.core.scheduleNote(m.index,m.note,m.velocity,m.frame,m.duration,m.source);if(m.type==='stopNotes')this.core.stopNotes(m.source,m.frame);if(m.type==='strum')this.core.strum();if(m.type==='record'){this.record=m.active;this.recordId=m.id;if(!m.active)this.port.postMessage({type:'recordStopped',id:m.id});}}};}process(inputs,outputs){const o=outputs[0];if(!this.core||!o?.[0])return true;this.core.processBlock(o[0],o[1]||o[0]);if(this.record){const p=new Float32Array(o[0].length*2);for(let i=0;i<o[0].length;i++){p[i*2]=o[0][i];p[i*2+1]=(o[1]||o[0])[i];}this.port.postMessage({type:'record',id:this.recordId,pcm:p},[p.buffer]);}if(++this.blocks%12===0)this.port.postMessage({type:'meters',meters:this.core.getMeters()});return true;}}registerProcessor('bower-strings',BowerProcessor);`;const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));try{await ctx.audioWorklet.addModule(url);}finally{URL.revokeObjectURL(url);}this.node=new AudioWorkletNode(ctx,'bower-strings',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2]});this.node.port.onmessage=e=>{if(e.data.type==='meters')this.meters=e.data.meters;else if(e.data.type==='record')this.capture(e.data.pcm,e.data.id);else if(e.data.type==='recordStopped'&&e.data.id===this.activeRecord)this.recordFinish?.();};worklet=true;}}catch(e){this.onStatus?.('Using the compatible audio engine.');}
 if(!worklet){this.core=new DSP.Core(ctx.sampleRate,this.state);this.node=ctx.createScriptProcessor(1024,0,2);this.node.onaudioprocess=e=>{const l=e.outputBuffer.getChannelData(0),r=e.outputBuffer.getChannelData(1);this.core.frame=Math.round(e.playbackTime*ctx.sampleRate);this.core.processBlock(l,r);this.meters=this.core.getMeters();if(this.isRecording){const p=new Float32Array(l.length*2);for(let i=0;i<l.length;i++){p[i*2]=l[i];p[i*2+1]=r[i];}this.capture(p,this.activeRecord);}};}this.node.connect(ctx.destination);this.command('state',{state:this.state});await ctx.resume();return true;}
 command(type,data={}){if(this.core){if(type==='state')this.core.setState(data.state);if(type==='start')this.core.start();if(type==='stop')this.core.stop();if(type==='panic')this.core.panic();if(type==='damp')this.core.damp(data.active);if(type==='pluck')this.core.pluck(data.index,data.degree,data.velocity,data.note??null);if(type==='note')this.core.scheduleNote(data.index,data.note,data.velocity,data.frame,data.duration,data.source);if(type==='stopNotes')this.core.stopNotes(data.source,data.frame);if(type==='strum')this.core.strum();}else if(this.node)this.node.port.postMessage({type,...data});}
 setState(state){this.state=window.BowerSchema.normalize(state);this.command('state',{state:this.state});}
 async start(){const g=this.generation;await this.init();if(g!==this.generation)return false;this.command('start');this.isPlaying=true;return true;}
 stop(){this.generation++;this.command('stop');this.isPlaying=false;}
 panic(){this.generation++;this.recordRequest++;this.command('panic');this.isPlaying=false;this.damp(false);this.meters={...this.meters,rms:0,peak:0,lanes:[0,0,0,0],positions:[-1,-1,-1,-1]};const recordingId=this.activeRecord;this.activeRecord=0;this.isRecording=false;if(this.recordFinish)this.recordFinish(true);this.chunks=[];this.recordFrames=0;this.command('record',{active:false,id:recordingId});}
 async pluck(index,degree=0,velocity=.8,note=null){const g=this.generation;await this.init();if(g!==this.generation)return false;this.command('pluck',{index,degree,velocity,note});return true;}
 async strum(){const g=this.generation;await this.init();if(g!==this.generation)return false;this.command('strum');return true;}
 damp(active){this.command('damp',{active:!!active});}
 scheduleNote({voiceId='0',note=60,velocity=.8,when,durationSeconds=.25,source='loom'}={}){if(!this.context||!this.node)throw new Error('Prepare the instrument before scheduling notes.');const index=Number(voiceId);if(!Number.isInteger(index)||index<0||index>3)throw new Error('Choose one of SKEWER’s four strings.');this.command('note',{index,note,velocity,frame:Math.round(Math.max(this.context.currentTime,Number(when)||this.context.currentTime)*this.context.sampleRate),duration:durationSeconds,source});return true;}
 stopNotes({source,when}={}){this.command('stopNotes',{source,frame:this.context?Math.round(Math.max(this.context.currentTime,Number.isFinite(when)?when:this.context.currentTime)*this.context.sampleRate):undefined});}
 async renderNotes({events,tempo=120,lengthBeats=4,tailSeconds=2,signal,state=this.state}={}){const check=()=>{if(signal?.aborted)throw new DOMException('Pattern render cancelled.','AbortError');};check();const snapshot=window.BowerSchema.normalize(state);snapshot.tempo=tempo;const sr=48000,body=lengthBeats*60/tempo,tail=Math.min(30,Math.max(0,Number(tailSeconds)||0));if(!Number.isFinite(body)||body<=0||body+tail>180)throw new Error('Pattern render must be between zero and 180 seconds.');const core=new DSP.Core(sr,snapshot),frames=Math.ceil((body+tail)*sr),chunks=[];for(const e of events)core.scheduleNote(Number(e.voiceId??0),e.note,e.velocity,Math.round(e.startBeat*60/tempo*sr),e.durationBeats*60/tempo);for(let at=0;at<frames;){check();const size=Math.min(2048,frames-at),l=new Float32Array(size),r=new Float32Array(size),pcm=new Float32Array(size*2);core.processBlock(l,r);for(let i=0;i<size;i++){pcm[i*2]=l[i];pcm[i*2+1]=r[i];}chunks.push(pcm);at+=size;if(chunks.length%48===0)await new Promise(resolve=>setTimeout(resolve,0));}check();return{blob:wav(chunks,sr),sampleRate:sr,tempo,sourceApp:'bower'};}
 getMeters(){return{...this.meters,recordSeconds:this.recordFrames/(this.context?.sampleRate||48000)};}
 async startRecording(){const g=this.generation,request=++this.recordRequest;if(this.recordStopPromise)await this.recordStopPromise;await this.init();if(g!==this.generation||request!==this.recordRequest)return false;if(this.isRecording)return true;this.chunks=[];this.recordFrames=0;this.activeRecord=++this.recordId;this.isRecording=true;this.command('record',{active:true,id:this.activeRecord});return true;}
 capture(pcm,id){if(!this.isRecording||id!==this.activeRecord)return;const available=Math.max(0,Math.round(this.context.sampleRate*180)-this.recordFrames),frames=Math.min(available,pcm.length/2);if(frames){this.chunks.push(frames===pcm.length/2?pcm:new Float32Array(pcm.subarray(0,frames*2)));this.recordFrames+=frames;}if(frames<pcm.length/2||this.recordFrames>=this.context.sampleRate*180){this.command('record',{active:false,id:this.activeRecord});this.isRecording=false;this.onRecordingLimit?.();}}
 async stopRecording(){this.recordRequest++;if(this.recordStopPromise)return this.recordStopPromise;if(!this.activeRecord&&!this.chunks.length)return null;let finish;const pending=new Promise(resolve=>{finish=cancelled=>{clearTimeout(timer);const out=cancelled||!this.recordFrames?null:wav(this.chunks,this.context?.sampleRate||48000);this.isRecording=false;this.activeRecord=0;this.chunks=[];this.recordFrames=0;this.recordFinish=null;resolve(out);};});const timer=setTimeout(()=>finish(false),1000);this.recordFinish=finish;this.recordStopPromise=pending;this.command('record',{active:false,id:this.activeRecord});if(this.core||!this.node)finish(false);const out=await pending;this.recordStopPromise=null;return out;}
 async renderWav(bars=4,tailSeconds=8,options={}){const checkCancelled=()=>{if(options.signal?.aborted)throw new DOMException('Audio export cancelled.','AbortError');};checkCancelled();const state=window.BowerSchema.normalize(this.state),sr=48000,lengthBars=Math.max(1,Math.min(16,Math.round(Number(bars)||4))),tail=Math.max(0,Math.min(15,Number(tailSeconds)||0)),frames=Math.round(sr*(lengthBars*240/state.tempo+tail)),playFrames=Math.round(sr*lengthBars*240/state.tempo),core=new DSP.Core(sr,state),chunks=[];core.start();for(let at=0,blocks=0;at<frames;blocks++){if(blocks%48===0)checkCancelled();const size=Math.min(2048,frames-at,at<playFrames?playFrames-at:2048);if(at>=playFrames)core.stop();const l=new Float32Array(size),r=new Float32Array(size),pcm=new Float32Array(size*2);core.processBlock(l,r);for(let i=0;i<size;i++){pcm[i*2]=l[i];pcm[i*2+1]=r[i];}chunks.push(pcm);at+=size;if(blocks%48===0)await new Promise(resolve=>setTimeout(resolve,0));}checkCancelled();return wav(chunks,sr);}
}
window.BowerAudio=Audio;
})();
