(() => {
  'use strict';
  const $ = id => document.getElementById(id), S = RavelSchema, padKeys=['1','2','3','4','q','w','e','r','a','s','d','f','z','x','c','v'];
  let state=S.copy(RavelPresets[0].state),selectedStep=0,selectedSlice=0,history=[],storageNotice=false,persistTimer=0,action=0,micBusy=false,captureBusy=false,renderBusy=false,playBusy=false,playOp=0,captureOp=0,drag=null,lastStep=-1;
  try{const saved=localStorage.getItem('ravel-project-v1');if(saved)state=S.parseProject(saved);}catch(error){storageNotice=true;}
  const engine=new RavelAudio(state); const stepDefs=[['velocity','Velocity',0,1,.01,'percent'],['probability','Probability',0,1,.01,'percent'],['ratchet','Ratchets',1,4,1,'int'],['pitch','Pitch',-12,12,1,'semitone'],['micro','Micro timing',-.45,.45,.01,'micro'],['gate','Gate',.05,2,.01,'gate']];
  const sampleDefs=[['pitch','Global pitch',-24,24,1,'semitone'],['level','Sample level',0,1.5,.01,'percent'],['trimStart','Trim start',0,.995,.001,'percent'],['trimEnd','Trim end',.005,1,.001,'percent'],['fade','Slice fade',0,80,1,'ms']];
  const masterDefs=[['volume','Output',0,1,.01,'percent'],['tone','Low-pass',200,18000,100,'hz'],['highpass','High-pass',20,3000,10,'hz'],['drive','Drive',0,1,.01,'percent'],['crush','Bit crush',0,1,.01,'percent'],['echo','Echo',0,1,.01,'percent'],['feedback','Echo feedback',0,.8,.01,'percent'],['space','Room',0,1,.01,'percent'],['pan','Pan',-1,1,.01,'pan']];
  const format=(v,type)=>type==='percent'?Math.round(v*100)+'%':type==='semitone'?(v>0?'+':'')+v+' st':type==='micro'?(v>0?'+':'')+Math.round(v*100)+'%':type==='gate'?Math.round(v*100)+'%':type==='hz'?v>=1000?(v/1000).toFixed(1)+' kHz':Math.round(v)+' Hz':type==='ms'?v+' ms':type==='pan'?v===0?'Center':Math.round(Math.abs(v)*100)+(v<0?' L':' R'):String(v);
  const say=message=>{$('status').textContent=message;};
  function snapshot(){return {...state,asset:{...state.asset},sample:{...state.sample},master:{...state.master},boundaries:[...state.boundaries],patterns:state.patterns.map(p=>({...p,steps:p.steps.map(x=>({...x}))}))};}
  function remember(){history.push(snapshot());if(history.length>40)history.shift();$('undoButton').disabled=false;}
  function persist(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>{try{localStorage.setItem('ravel-project-v1',S.serializeProject(state));}catch(error){if(!storageNotice){storageNotice=true;say('Browser recovery storage is full or unavailable. Save project keeps every piece.');}}},500);}
  function commit(redraw=true){state=S.normalize(state);engine.setState(state);persist();if(redraw)render();else drawWave();}
  function download(blob,name){if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  const filename=()=>state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'ravel';
  function renderControls(target,group,defs){const holder=$(target);for(const [key,label,min,max,step,type] of defs){const wrap=document.createElement('label');wrap.className='control';const head=document.createElement('span');head.className='control-header';const title=document.createElement('span');title.textContent=label;const out=document.createElement('output');out.id=group+'-'+key+'-value';head.append(title,out);const input=document.createElement('input');input.type='range';input.id=group+'-'+key;input.min=min;input.max=max;input.step=step;input.dataset.group=group;input.dataset.key=key;input.dataset.format=type;input.setAttribute('aria-label',label);wrap.append(head,input);holder.append(wrap);input.addEventListener('pointerdown',()=>remember());input.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key)&&!e.repeat)remember();});input.addEventListener('input',()=>{if(group==='step')state.patterns[state.selectedPattern].steps[selectedStep][key]=+input.value;else state[group][key]=+input.value;if(group==='sample'){if(key==='trimStart')state.sample.trimEnd=Math.max(state.sample.trimEnd,state.sample.trimStart+.005);if(key==='trimEnd')state.sample.trimStart=Math.min(state.sample.trimStart,state.sample.trimEnd-.005);}commit();});}}
  renderControls('stepControls','step',stepDefs);renderControls('sampleControls','sample',sampleDefs);renderControls('masterControls','master',masterDefs);
  RavelPresets.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('preset').append(o);});S.RECIPES.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('recipe').append(o);});for(let i=0;i<16;i++){const o=document.createElement('option');o.value=i;o.textContent=String(i+1).padStart(2,'0');$('stepSlice').append(o);const pad=document.createElement('button');pad.className='pad';pad.dataset.slice=i;pad.setAttribute('aria-label','Play and assign slice '+(i+1));const num=document.createElement('span');num.className='pad-no';num.textContent=String(i+1).padStart(2,'0');const key=document.createElement('small');key.textContent=padKeys[i].toUpperCase();pad.append(num,key);$('padGrid').append(pad);pad.addEventListener('pointerdown',e=>{e.preventDefault();audition(i,true);});pad.addEventListener('click',e=>{if(e.detail===0)audition(i,true);});const step=document.createElement('div');step.className='step';step.dataset.step=i;const main=document.createElement('button');main.className='step-main';main.setAttribute('aria-label','Edit step '+(i+1));main.innerHTML='<span class="step-num">'+String(i+1).padStart(2,'0')+'</span><span class="step-slice">01</span><span class="step-vel"><i></i></span>';const toggle=document.createElement('button');toggle.className='step-toggle';toggle.setAttribute('aria-label','Enable step '+(i+1));step.append(main,toggle);$('stepGrid').append(step);main.addEventListener('click',()=>{selectedStep=i;selectedSlice=state.patterns[state.selectedPattern].steps[i].slice;render();});toggle.addEventListener('click',()=>{remember();const s=state.patterns[state.selectedPattern].steps[i];s.on=!s.on;commit();});}
  function render(){const p=state.patterns[state.selectedPattern],step=p.steps[selectedStep];$('tempo').value=Math.round(state.tempo);$('swing').value=state.swing;$('swingValue').textContent=Math.round(state.swing*100)+'%';$('chain').checked=state.chain;$('sampleName').textContent=state.asset.name;$('sampleDuration').textContent=S.duration(state.asset).toFixed(2)+'s';$('sampleMeta').textContent=(state.asset.kind==='seed'?'SYNTHESIZED LOCALLY':'IMPORTED / '+state.asset.sampleRate+' HZ')+' / STEREO';if(state.asset.kind==='seed')$('recipe').value=state.asset.recipe;const matched=RavelPresets.find(x=>x.name===state.name);$('preset').value=matched?.id||'';$('editorStep').textContent='STEP '+String(selectedStep+1).padStart(2,'0');$('stepSummary').textContent='STEP '+String(selectedStep+1).padStart(2,'0')+' / SLICE '+String(step.slice+1).padStart(2,'0');$('sliceLabel').textContent='SLICE '+String(selectedSlice+1).padStart(2,'0');$('stepSlice').value=step.slice;$('stepOn').textContent=step.on?'Enabled':'Disabled';$('stepOn').classList.toggle('active',step.on);$('stepReverse').classList.toggle('active',step.reverse);$('stepReverse').setAttribute('aria-pressed',step.reverse);$('sampleReverse').classList.toggle('active',state.sample.reverse);$('sampleReverse').setAttribute('aria-pressed',state.sample.reverse);document.querySelectorAll('[data-bank]').forEach(b=>b.classList.toggle('active',+b.dataset.bank===state.selectedPattern));document.querySelectorAll('.step').forEach((el,i)=>{const s=p.steps[i];el.classList.toggle('enabled',s.on);el.classList.toggle('selected',i===selectedStep);el.querySelector('.step-slice').textContent=String(s.slice+1).padStart(2,'0');el.querySelector('.step-vel i').style.width=s.velocity*100+'%';el.querySelector('.step-toggle').setAttribute('aria-pressed',s.on);});document.querySelectorAll('.pad').forEach((p,i)=>{p.classList.toggle('selected',i===selectedSlice);p.setAttribute('aria-pressed',i===selectedSlice);});for(const [group,defs] of [['step',stepDefs],['sample',sampleDefs],['master',masterDefs]])for(const [key,,,,,type] of defs){const value=(group==='step'?step:state[group])[key];$(group+'-'+key).value=value;$(group+'-'+key+'-value').textContent=format(value,type);}const dur=S.duration(state.asset);$('trimReadout').textContent=(dur*state.sample.trimStart).toFixed(2)+' → '+(dur*state.sample.trimEnd).toFixed(2)+'s';$('undoButton').disabled=!history.length;updateTransport();drawWave();}
  function updateTransport(){$('playButton').innerHTML=playBusy?'Waking…':engine.isPlaying?'■ Stop':'<svg class="play-icon" viewBox="0 0 10 12" aria-hidden="true"><path d="M1 1 9 6 1 11Z" fill="currentColor"/></svg> Play';$('saveButton').disabled=micBusy;$('saveButton').textContent=engine.micCapturing?'Finish take & save':'Save project';$('playButton').setAttribute('aria-pressed',engine.isPlaying);$('micButton').textContent=engine.micCapturing?'■ Finish '+(engine.getMeters().micSeconds||0).toFixed(1)+'s':micBusy?'Cancel mic':'● Microphone';$('micButton').classList.toggle('recording',engine.micCapturing||micBusy);$('captureButton').textContent=engine.isRecording?'■ Finish capture':'● Capture live mix';$('captureButton').classList.toggle('recording',engine.isRecording);}
  async function audition(i,assign){selectedSlice=i;if(assign){remember();state.patterns[state.selectedPattern].steps[selectedStep].slice=i;commit();}else render();const pad=$('padGrid').children[i];pad.classList.add('lit');setTimeout(()=>pad.classList.remove('lit'),130);try{await engine.triggerSlice(i);}catch(e){say(e.message);}}
  async function togglePlay(){if(engine.isPlaying||playBusy){playOp++;playBusy=false;engine.stop();say('The procession is paused.');updateTransport();return;}const request=++playOp;playBusy=true;updateTransport();try{if(await engine.start()&&request===playOp)say('Sixteen corners, moving in a suspiciously orderly fashion.');}catch(e){if(request===playOp)say(e.message);}finally{if(request===playOp){playBusy=false;updateTransport();}}}

  function panic(){action++;playOp++;captureOp++;playBusy=false;micBusy=false;captureBusy=false;engine.panic();updateTransport();say('Panic: sound silenced, pending takes discarded, microphone released.');}
  $('playButton').addEventListener('click',togglePlay);$('panicButton').addEventListener('click',panic);$('tempo').addEventListener('change',()=>{remember();state.tempo=+ $('tempo').value;commit();});$('swing').addEventListener('pointerdown',remember);$('swing').addEventListener('input',()=>{state.swing=+ $('swing').value;commit();});$('chain').addEventListener('change',()=>{remember();state.chain=$('chain').checked;commit();});$('banks').addEventListener('click',e=>{const b=e.target.closest('[data-bank]');if(!b)return;remember();state.selectedPattern=+b.dataset.bank;commit();say(engine.isPlaying?'Pattern '+String.fromCharCode(65+state.selectedPattern)+' is queued for the next bar.':'Editing pattern '+String.fromCharCode(65+state.selectedPattern)+'.');});$('stepSlice').addEventListener('change',()=>{remember();state.patterns[state.selectedPattern].steps[selectedStep].slice=+$('stepSlice').value;selectedSlice=+$('stepSlice').value;commit();});$('stepOn').addEventListener('click',()=>{remember();const s=state.patterns[state.selectedPattern].steps[selectedStep];s.on=!s.on;commit();});$('stepReverse').addEventListener('click',()=>{remember();const s=state.patterns[state.selectedPattern].steps[selectedStep];s.reverse=!s.reverse;commit();});$('sampleReverse').addEventListener('click',()=>{remember();state.sample.reverse=!state.sample.reverse;commit();});
  function stopForAsset(){action++;playOp++;captureOp++;playBusy=false;micBusy=false;captureBusy=false;engine.panic();updateTransport();}
  function installAsset(asset){remember();stopForAsset();state.asset=asset;state.boundaries=Array.from({length:17},(_,i)=>i/16);Object.assign(state.sample,{trimStart:0,trimEnd:1,pitch:0,reverse:false});commit();say('A fresh ribbon: '+asset.name+'. Sixteen pieces, all accounted for.');}
  function importAudio({pcm,sampleRate,name='Audio sample',options={}}={}){
    if(micBusy||engine.micCapturing||captureBusy||engine.isRecording||renderBusy)throw new Error('Finish the current RAVEL recording or render before sending audio.');
    const target=options.target??options.deck;
    if(target!==undefined&&target!==0)throw new Error('RAVEL receives audio into its sample slot.');
    if(state.asset&&options.replace!==true)throw new Error('Confirm replacing the RAVEL sample before sending audio.');
    if(!Number.isInteger(sampleRate)||sampleRate<8000||sampleRate>192000||Object.prototype.toString.call(pcm)!=='[object Float32Array]'||pcm.length<4||pcm.length%2)throw new Error('Provide valid interleaved stereo audio.');
    if(pcm.length/2/sampleRate>20)throw new Error('RAVEL accepts clips up to 20 seconds. Shorten the clip before sending it.');
    for(let i=0;i<pcm.length;i++)if(!Number.isFinite(pcm[i]))throw new Error('The incoming audio contains invalid samples.');
    const asset=S.normalizeAsset(RavelAudio.encodePCM(pcm,sampleRate,String(name).replace(/[\u0000-\u001f\u007f]/g,'').slice(0,80)||'Audio sample'));
    installAsset(asset);window.MusicLabHost?.notifyStateChange();say('Audio sample received. Sixteen fresh slices; Undo restores the previous sample.');
    return {deck:0,name:asset.name,duration:asset.duration,sampleRate:asset.sampleRate};
  }
  async function exportAudio({scope='pattern',bars=1,tailSeconds=3,signal}={}){
    if(signal?.aborted)throw new DOMException('Audio export cancelled.','AbortError');
    if(!['pattern','slice','source'].includes(scope))throw new Error('Choose a slice pattern, processed slice, or unprocessed source sample.');
    if(renderBusy||micBusy||engine.micCapturing||captureBusy||engine.isRecording)throw new Error('Finish the current RAVEL recording or render before sharing audio.');
    const score=snapshot(),slice=selectedSlice,sourceLabel=scope==='slice'?score.asset.name+' / slice '+(slice+1):scope==='source'?score.asset.name:score.name;
    const name='ravel-'+sourceLabel.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()+'-'+scope+'.wav';
    renderBusy=true;
    try{
      if(scope==='source'){const audio=engine.getSample();return{pcm:audio.pcm.slice(),sampleRate:audio.sampleRate,name,tempo:score.asset.tempo||score.tempo,sourceApp:'ravel',sourceLabel,scope};}
      const blob=scope==='slice'?await engine.renderSliceWav(slice,tailSeconds,{signal}):await engine.renderWav(bars,tailSeconds,{signal});
      return{blob,sampleRate:48000,name,tempo:score.tempo,sourceApp:'ravel',sourceLabel,scope};
    }finally{renderBusy=false;}
  }
  $('generateButton').addEventListener('click',()=>{const recipe=$('recipe').value;installAsset({kind:'seed',name:S.RECIPES.find(x=>x.id===recipe).name,recipe,seed:Math.floor(Math.random()*4294967294)+1,tempo:state.tempo});});$('evenButton').addEventListener('click',()=>{remember();state.boundaries=Array.from({length:17},(_,i)=>i/16);commit();say('Sixteen even slices. The ruler is satisfied.');});$('transientButton').addEventListener('click',()=>{remember();state.boundaries=RavelDSP.detectTransients(engine.getSample(),state.sample.trimStart,state.sample.trimEnd);commit();say('Transient boundaries found. Drag a line to make your own amendment.');});
  $('importButton').addEventListener('click',()=>$('audioFile').click());$('audioFile').addEventListener('change',async()=>{const f=$('audioFile').files[0];$('audioFile').value='';if(!f)return;stopForAsset();const request=action;say('Unfolding '+f.name+'…');try{const asset=await engine.decodeSample(f);if(asset&&request===action)installAsset(asset);}catch(e){if(request===action)say('Import: '+e.message);}});
  async function finishMic(){const asset=engine.stopMicCapture();micBusy=false;updateTransport();if(asset)installAsset(asset);else say('No microphone audio was captured.');}
  $('micButton').addEventListener('click',async()=>{if(engine.micCapturing){await finishMic();return;}if(micBusy){action++;micBusy=false;engine.cancelMicCapture();updateTransport();say('Microphone request cancelled.');return;}micBusy=true;const request=++action;updateTransport();say('Waiting for microphone permission…');try{if(await engine.startMicCapture()&&request===action){micBusy=false;updateTransport();say('Recording the microphone. Tap Finish or Panic. Maximum 20 seconds.');}}catch(e){if(request===action)say('Microphone: '+e.message);}finally{if(request===action){micBusy=false;updateTransport();}}});engine.onMicLimit=finishMic;
  $('shuffleButton').addEventListener('click',()=>{remember();const steps=state.patterns[state.selectedPattern].steps,a=steps.map(s=>s.slice);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}steps.forEach((s,i)=>s.slice=a[i]);commit();say('The pieces have exchanged their seats.');});$('mutateButton').addEventListener('click',()=>{remember();state.patterns[state.selectedPattern].steps.forEach(s=>{if(Math.random()<.32){s.on=Math.random()>.2;s.slice=Math.floor(Math.random()*16);s.velocity=.4+Math.random()*.6;s.ratchet=Math.random()<.25?2+Math.floor(Math.random()*3):1;s.reverse=Math.random()<.18;s.pitch=[-7,-5,0,0,0,5,7][Math.floor(Math.random()*7)];s.probability=Math.random()<.22?.7:1;}});state.seed=Math.floor(Math.random()*4294967294)+1;commit();say('A little mischief. Undo knows the way home.');});$('fillButton').addEventListener('click',()=>{remember();state.patterns[state.selectedPattern].steps.forEach((s,i)=>{s.on=true;s.slice=i;});commit();});$('clearButton').addEventListener('click',()=>{remember();state.patterns[state.selectedPattern].steps.forEach(s=>s.on=false);commit();say('An empty pattern, full of possibilities.');});$('copyButton').addEventListener('click',()=>{remember();const target=(state.selectedPattern+1)%4;state.patterns[target].steps=state.patterns[state.selectedPattern].steps.map(x=>({...x}));commit();say('Copied into pattern '+String.fromCharCode(65+target)+'.');});
  function undo(){if(!history.length)return;stopForAsset();state=history.pop();engine.setState(state);persist();render();say('The previous arrangement has returned, wearing its old hat.');} $('undoButton').addEventListener('click',undo);
  function loadState(next,keepHistory=true){if(keepHistory)remember();stopForAsset();state=S.normalize(next);selectedStep=0;selectedSlice=state.patterns[state.selectedPattern].steps[0].slice;engine.setState(state);persist();render();}
  $('preset').addEventListener('change',()=>{const p=RavelPresets.find(p=>p.id===$('preset').value);if(!p)return;loadState(p.state);say(p.name+' Undo restores the previous ribbon.');});$('saveButton').addEventListener('click',async()=>{if(micBusy)return;if(engine.micCapturing)await finishMic();download(new Blob([S.serializeProject(state)],{type:'application/json'}),filename()+'.ravel.json');say('Project saved, sample and all four patterns included.');});$('openButton').addEventListener('click',()=>$('projectFile').click());$('projectFile').addEventListener('change',async()=>{const f=$('projectFile').files[0];$('projectFile').value='';if(!f)return;stopForAsset();const request=action;try{if(f.size>16*1024*1024)throw new Error('Projects must be smaller than 16 MB.');const next=S.parseProject(await f.text());if(request===action){loadState(next);say('Project opened. Every piece has come home.');}}catch(e){if(request===action)say('Open: '+e.message);}});
  async function finishCapture(){if(captureBusy)return;captureBusy=true;const request=++captureOp;try{const blob=await engine.stopRecording();if(blob&&request===captureOp){download(blob,filename()+'-live.wav');say('Live mix captured as a stereo WAV.');}}catch(e){if(request===captureOp)say(e.message);}finally{if(request===captureOp){captureBusy=false;updateTransport();}}}
  $('captureButton').addEventListener('click',async()=>{if(captureBusy)return;if(engine.isRecording){await finishCapture();return;}captureBusy=true;const request=++captureOp;try{if(await engine.startRecording()&&request===captureOp)say('Capturing the live stereo mix. Tap Finish to download. Maximum three minutes.');}catch(e){if(request===captureOp)say(e.message);}finally{if(request===captureOp){captureBusy=false;updateTransport();}}});engine.onRecordingLimit=finishCapture;engine.onStatus=say;
  $('exportButton').addEventListener('click',async()=>{if(renderBusy)return;renderBusy=true;$('exportButton').disabled=true;$('exportButton').textContent='Rendering…';try{const blob=await engine.renderWav(+$('exportBars').value,3);download(blob,filename()+'-mix.wav');say('Stereo WAV rendered with a three-second effect tail.');}catch(e){say('Render: '+e.message);}finally{renderBusy=false;$('exportButton').disabled=false;$('exportButton').textContent='↓ Render stereo WAV';}});
  function showHelp(){$('helpDialog').showModal();} $('helpButton').addEventListener('click',showHelp);$('footerHelp').addEventListener('click',showHelp);$('closeHelp').addEventListener('click',()=>$('helpDialog').close());$('helpDialog').addEventListener('click',e=>{if(e.target===$('helpDialog')){const r=$('helpDialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('helpDialog').close();}});
  if(location.protocol==='file:'){$('labLink').href='https://calebhaines.github.io/sidequest-prototypes/music/';$('sourceDownload').href='https://calebhaines.github.io/sidequest-prototypes/music/ravel/RAVEL-source.zip';}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){panic();return;}if($('helpDialog').open||e.target.closest('input,select,textarea,[contenteditable]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return;}if(e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;if(e.code==='Space'){if(e.target.closest('button,a'))return;e.preventDefault();togglePlay();return;}const i=padKeys.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();audition(i,false);}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&engine.micCapturing)say('Microphone recording continues until Finish, Panic, or the 20-second limit.');});window.addEventListener('pagehide',()=>engine.panic());
  const canvas=$('waveform'),ctx=canvas.getContext('2d');let peaks=engine.getWaveform(700),waveKey=state.asset,canvasWidth=0,canvasHeight=0;
  function drawWave(){if(!ctx)return;const rect=canvas.getBoundingClientRect(),dpr=Math.min(3,window.devicePixelRatio||1),w=rect.width,h=rect.height;if(w<=0||h<=0)return;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);canvasWidth=w;canvasHeight=h;if(waveKey!==state.asset){peaks=engine.getWaveform(700);waveKey=state.asset;}const trim=state.sample.trimEnd-state.sample.trimStart,x1=state.sample.trimStart*w,x2=state.sample.trimEnd*w;ctx.fillStyle='#0f1924';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#293745';ctx.lineWidth=1;for(let y=30;y<h;y+=30){ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(w,y+.5);ctx.stroke();}const selectedA=(state.sample.trimStart+state.boundaries[selectedSlice]*trim)*w,selectedB=(state.sample.trimStart+state.boundaries[selectedSlice+1]*trim)*w;ctx.fillStyle='#ed846d18';ctx.fillRect(selectedA,0,selectedB-selectedA,h);ctx.fillStyle='#90c8da';for(let i=0;i<peaks.length;i++){const x=i*w/peaks.length,height=Math.max(1,peaks[i]*(h-40));ctx.globalAlpha=x<x1||x>x2?.2:.7;ctx.fillRect(x,h/2-height/2,Math.max(1,w/peaks.length*.72),height);}ctx.globalAlpha=1;for(let i=0;i<=16;i++){const x=(state.sample.trimStart+state.boundaries[i]*trim)*w;ctx.strokeStyle=i===selectedSlice||i===selectedSlice+1?'#ed846d':'#5d7c91';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+.5,5);ctx.lineTo(x+.5,h-17);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x-3,0);ctx.lineTo(x+3,0);ctx.lineTo(x,5);ctx.fill();if(i<16&&w>360){ctx.font='7px "Ravel Sans",sans-serif';ctx.fillText(String(i+1).padStart(2,'0'),x+3,15);}}}
  canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,trim=state.sample.trimEnd-state.sample.trimStart;let nearest=-1,distance=12;for(let i=1;i<16;i++){const at=(state.sample.trimStart+state.boundaries[i]*trim)*r.width,d=Math.abs(at-x);if(d<distance){nearest=i;distance=d;}}if(nearest>=0){remember();drag=nearest;canvas.setPointerCapture(e.pointerId);}else{const pos=(x/r.width-state.sample.trimStart)/trim;const slice=state.boundaries.findIndex((b,i)=>i<16&&pos>=b&&pos<state.boundaries[i+1]);if(slice>=0)audition(slice,false);}});canvas.addEventListener('pointermove',e=>{if(drag===null)return;const r=canvas.getBoundingClientRect(),trim=state.sample.trimEnd-state.sample.trimStart,p=(e.clientX-r.left)/r.width;state.boundaries[drag]=Math.max(state.boundaries[drag-1]+.0002,Math.min(state.boundaries[drag+1]-.0002,(p-state.sample.trimStart)/trim));commit(false);});const release=()=>{drag=null;};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);new ResizeObserver(()=>drawWave()).observe(canvas);
  function animate(){const m=engine.getMeters();$('meterFill').style.width=Math.min(100,Math.max(0,(20*Math.log10(Math.max(.00001,m.rms))+60)/60*100))+'%';$('meterLabel').textContent=m.rms>.00001?Math.round(20*Math.log10(m.rms))+' dB':'−∞ dB';$('transportClock').textContent=String(Math.max(1,m.bar||1)).padStart(2,'0')+' : '+String((engine.isPlaying?Math.max(0,m.step):0)+1).padStart(2,'0');if(m.step!==lastStep||!engine.isPlaying){lastStep=m.step;document.querySelectorAll('.step').forEach((s,i)=>s.classList.toggle('playing',engine.isPlaying&&i===m.step));}document.querySelectorAll('[data-bank]').forEach(b=>b.classList.toggle('pending',engine.isPlaying&&m.pending===+b.dataset.bank));if(engine.micCapturing)updateTransport();requestAnimationFrame(animate);}
  Object.defineProperty(window,'RavelApp',{value:Object.freeze({getState:()=>snapshot(),loadState:next=>loadState(next),get engine(){return engine;},importAudio,exportAudio,audioExport:{scopes:[{id:'pattern',label:'Slice pattern / with effects'},{id:'slice',label:'Selected slice / processed',usesBars:false},{id:'source',label:'Source sample / unprocessed',usesBars:false}],defaultBars:1,maxBars:16},get audioImport(){return {maxSeconds:20,decks:1,targets:[{id:0,name:'Sample',occupied:!!state.asset,assetName:state.asset?.name||''}]};},selectStep:i=>{selectedStep=Math.max(0,Math.min(15,Math.round(i)));selectedSlice=state.patterns[state.selectedPattern].steps[selectedStep].slice;render();}}),writable:false});
  render();requestAnimationFrame(animate);
})();
