(function () {
  'use strict';
  const S = window.ProofSchema, $ = id => document.getElementById(id), copy = value => S.copy(value);
  const arp = window.createProofArp();
  const hosted = window.parent !== window || !!window.MusicLabHost;
  const listeners = new Set(), controls = new Map();
  const labels = { up:'Up',down:'Down',updown:'Up / down',downup:'Down / up',outsidein:'Outside → in',insideout:'Inside → out',random:'Seeded random',walk:'Random walk',skip:'Skip alternate',chord:'Whole chord',none:'No fold',rise:'Rise an octave',fall:'Fall an octave',reverse:'Reverse order',rotate:'Rotate order',mirror:'Mirror order',diatonic:'In the scale',major:'Major',minor:'Minor',maj7:'Major 7',min7:'Minor 7',dominant7:'Dominant 7',add9:'Add 9',min9:'Minor 9',sus2:'Suspended 2',sus4:'Suspended 4',dim7:'Diminished 7',dorian:'Dorian',mixolydian:'Mixolydian',lydian:'Lydian',pentatonic:'Pentatonic',harmonic:'Harmonic minor',saw:'Sawtooth',pulse:'Pulse',triangle:'Triangle',sine:'Sine',lp12:'Low-pass / 12 dB',lp24:'Low-pass / 24 dB',hp:'High-pass',bp:'Band-pass',sampleHold:'Sample & hold',square:'Square',free:'Free running',cutoff:'Filter cutoff',pitch:'Pitch',vector:'Vector morph',amp:'Amplitude',pan:'Stereo pan',cascade:'Cascade',parallel:'Parallel',feedback:'Feedback loop',glass:'Glass',hollow:'Hollow',choir:'Choir',reed:'Reed',spectrum:'Spectrum',bell:'Bell' };
  const modelInfo = {
    dco:{name:'DCO',display:'DUAL DCO',description:'The ’80s chorus classic. Two steady oscillators, a velvet sub, and wide stereo warmth.'},
    vco:{name:'VCO',display:'TWIN VCO',description:'The big analogue voice. Detuned twin oscillators, a round sub, and unruly cross-modulation.'},
    sync:{name:'SYNC',display:'HARD SYNC',description:'The cutting lead. A slave oscillator resets to its master for that unmistakable sync growl.'},
    fm:{name:'FM',display:'FOUR-OP FM',description:'The glass and brass era. Four operators turn simple sine waves into bells, bite, and electric keys.'},
    vector:{name:'VECTOR',display:'SPECTRAL VECTOR',description:'The digital frontier. Six spectral tables with continuous morphing for slow, luminous movement.'}
  };
  let state, history = [], future = [], selectedStep = 0, transaction = null, transactionTarget = null;
  let autosaveTimer, exportAbort = null, importOperation = 0, transportOperation = 0, storageFailed = false;
  let keyboardBase = 48, keyVelocity = .85, fillHeld = false, midiAccess = null, midiBindings = new Map();
  const activeKeys = new Map(), held = new Set();
  let lastMeterTime = 0, phraseEvents = [], playingStep = -1, playingChord = -1;
  try { const saved = !hosted && localStorage.getItem('proof-project-v1'); state = saved ? S.parseProject(saved) : S.normalize(window.ProofPresets?.[0] || S.defaultState()); } catch (_) { state = S.defaultState(); storageFailed = true; }
  const engine = new window.ProofAudio(copy(state));
  function status(message) { $('status').textContent = message; }
  function get(path, source = state) { return path.split('.').reduce((o,k) => o?.[k], source); }
  function set(path, value, source = state) { const parts = path.split('.'); const last = parts.pop(); const parent = parts.reduce((o,k) => o[k], source); parent[last] = value; }
  function filename(suffix) { return (state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64) || 'leaven-recipe') + suffix; }
  function download(blob,name) { const url=URL.createObjectURL(blob), a=document.createElement('a'); a.href=url; a.download=name; document.body.append(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),30000); }
  function equal(a,b) { return JSON.stringify(a) === JSON.stringify(b); }
  function remember(previous) { if (equal(previous,state)) return; history.push(copy(previous)); if(history.length>64)history.shift(); future=[]; renderHistory(); }
  function finishTransaction() { if(transaction){remember(transaction);transaction=null;transactionTarget=null;} }
  function storageNotice() { $('storageNotice').hidden=!storageFailed; $('storageNotice').textContent='Browser recovery is unavailable. Save a project to keep this recipe.'; }
  function saveRecovery() { clearTimeout(autosaveTimer); if(hosted)return; autosaveTimer=setTimeout(()=>{try{localStorage.setItem('proof-project-v1',S.serialize(state));storageFailed=false;}catch(_){storageFailed=true;}storageNotice();},650); }
  function notifyState() { saveRecovery(); window.MusicLabHost?.notifyStateChange?.(); for(const fn of listeners){try{fn(copy(state));}catch(_){}} }
  function audioState() { const next=copy(state); if(fillHeld)next.patterns[next.selectedPattern].steps.forEach(x=>{if(x.on&&!x.tie)x.ratchet=Math.min(4,Math.max(2,x.ratchet));}); return next; }
  function changed({full=true,notify=true}={}) { state=S.normalize(state); engine.setState(audioState()); if(full)render(); else{renderControls();renderChordRack();renderSteps();drawDisplays();} if(notify)notifyState(); }
  function mutate(fn,message) { finishTransaction(); const previous=copy(state); fn(state); state=S.normalize(state); remember(previous); $('presetSelect').value=''; changed(); if(message)status(message); }
  function loadState(value) { const next=typeof value==='string'||value?.format ? S.parseProject(value) : S.normalize(value); finishTransaction(); cancelExport(); ++importOperation; const previous=copy(state); state=next; remember(previous); selectedStep=Math.min(selectedStep,state.patterns[state.selectedPattern].length-1); $('presetSelect').value=''; changed(); status('Loaded '+state.name+'.'); return copy(state); }
  function undo() { finishTransaction(); if(!history.length)return; future.push(copy(state)); state=history.pop(); changed(); $('presetSelect').value=''; status('Previous edit restored.'); }
  function redo() { finishTransaction(); if(!future.length)return; history.push(copy(state)); state=future.pop(); changed(); $('presetSelect').value=''; status('Edit reapplied.'); }
  function renderHistory(){ $('undoButton').disabled=!history.length; $('redoButton').disabled=!future.length; }
  const pct = v => Math.round(v*100)+'%', signed = v => (v>0?'+':'')+v;
  const seconds = v => v<1 ? Math.round(v*1000)+' ms' : Number(v.toFixed(2))+' s';
  const hz = v => v>=1000 ? Number((v/1000).toFixed(2))+' kHz' : Number(v.toFixed(2))+' Hz';
  function format(value,def) { if(def?.format)return def.format(Number(value)); if(typeof value==='number')return String(Number(value.toFixed(2))); return labels[value] || String(value); }
  function options(select,items) { select.replaceChildren(); for(const item of items){const pair=Array.isArray(item)?item:[item,labels[item]||item], o=document.createElement('option');o.value=pair[0];o.textContent=pair[1];select.append(o);} }
  function range(path,label,bounds,step=.01,formatFn=pct,extra={}) { return {path,label,type:'range',min:bounds[0],max:bounds[1],step,format:formatFn,...extra}; }
  function choice(path,label,items,extra={}) { return {path,label,type:'select',items,...extra}; }
  function createControls(container,defs) {
    const wrap=$(container); for(const def of defs){const label=document.createElement('label');label.className='control'; const top=document.createElement('span'), name=document.createElement('span');name.textContent=def.label;top.append(name);let output;
      if(def.type==='range'){output=document.createElement('output');top.append(output);}label.append(top);
      const input=document.createElement(def.type==='select'?'select':'input');if(def.type!=='select')input.type=def.type;input.dataset.path=def.path;input.id=def.id||def.path.replace(/[.{}]/g,'-');input.setAttribute('aria-label',def.label);if(def.title)input.title=def.title;
      if(def.type==='select')options(input,def.items);else if(def.type==='range'){input.min=def.min;input.max=def.max;input.step=def.step;output.htmlFor=input.id;}
      label.append(input);wrap.append(label);controls.set(input,{def,output,label});
    }
  }
  function buildControls() {
    options($('root'),Array.from({length:128},(_,n)=>[n,S.noteName(n)]));options($('scale'),Object.keys(S.SCALES));
    const r=S.RANGES;
    createControls('arpControls',[
      choice('arp.direction','DIRECTION',S.DIRECTIONS,{title:'The order in which chord notes are visited'}),choice('arp.division','CLOCK DIVISION',Object.keys(S.DIVISIONS)),range('arp.octaves','OCTAVES',r.arp.octaves,1,v=>v+' oct'),range('arp.gate','NOTE GATE',r.arp.gate,.01,pct),range('arp.transpose','TRANSPOSE',r.arp.transpose,1,v=>signed(v)+' st'),range('arp.repeat','REPEAT NOTE',r.arp.repeat,1,v=>v+'×'),range('arp.rotate','ROTATE ORDER',r.arp.rotate,1,signed),range('arp.spice','SPICE',r.arp.spice,.01,pct,{title:'Seeded note and velocity variation'}),choice('arp.fold','CYCLE FOLD',S.FOLDS),range('arp.foldEvery','FOLD EVERY',r.arp.foldEvery,1,v=>v+' cycles')
    ]);
    createControls('chordControls',[
      range('chords.{chord}.degree','SCALE DEGREE',r.chord.degree,1,v=>signed(v),{id:'chordDegree',title:'0 is the root; positive and negative values travel through the scale'}),choice('chords.{chord}.quality','CHORD TYPE',Object.keys(S.QUALITIES),{id:'chordQuality'}),range('chords.{chord}.inversion','INVERSION',r.chord.inversion,1,signed,{id:'chordInversion'}),range('chords.{chord}.spread','SPREAD',r.chord.spread,1,v=>v+' oct',{id:'chordSpread'}),choice('chords.{chord}.bars','HOLD FOR',[[1,'1 bar'],[2,'2 bars'],[4,'4 bars']],{id:'chordBars',numeric:true}),choice('chords.{chord}.enabled','SLOT ENABLED',[[true,'Enabled'],[false,'Disabled']],{id:'chordEnabled',boolean:true})
    ]);
    createControls('stepControls',[
      range('patterns.{bank}.steps.{step}.velocity','VELOCITY',r.step.velocity,.01,pct,{id:'stepVelocity'}),range('patterns.{bank}.steps.{step}.gate','GATE MULTIPLIER',r.step.gate,.01,v=>Number(v.toFixed(2))+'×',{id:'stepGate'}),range('patterns.{bank}.steps.{step}.probability','CHANCE',r.step.probability,.01,pct,{id:'stepProbability'}),range('patterns.{bank}.steps.{step}.ratchet','RATCHET',r.step.ratchet,1,v=>v+' hits',{id:'stepRatchet'}),range('patterns.{bank}.steps.{step}.offset','TIMING OFFSET',r.step.offset,.01,v=>signed(Math.round(v*100))+'%',{id:'stepOffset'}),range('patterns.{bank}.steps.{step}.octave','OCTAVE SHIFT',r.step.octave,1,v=>signed(v)+' oct',{id:'stepOctave'})
    ]);
    createControls('oscControls',[
      choice('synth.wave','WAVEFORM',S.ENUMS.wave,{models:['dco','vco','sync']}),range('synth.mix','OSCILLATOR BLEND',r.synth.mix,.01,pct),range('synth.sub','SUB OSCILLATOR',r.synth.sub,.01,pct),range('synth.detune','DETUNE',r.synth.detune,.01,pct),range('synth.pulseWidth','PULSE WIDTH',r.synth.pulseWidth,.01,pct,{models:['dco','vco','sync']}),range('synth.octave','VOICE OCTAVE',r.synth.octave,1,v=>signed(v)+' oct')
    ]);
    createControls('characterControls',[
      range('synth.sync','SYNC RATIO',r.synth.sync,.01,v=>Number(v.toFixed(2))+'×',{models:['sync']}),range('synth.crossmod','CROSS-MOD',r.synth.crossmod,.01,pct,{models:['vco']}),choice('synth.table','SPECTRAL TABLE',S.TABLES,{models:['vector']}),range('synth.vector','VECTOR MORPH',r.synth.vector,.01,pct,{models:['vector']}),range('synth.fmRatio','FM RATIO',r.synth.fmRatio,.01,v=>Number(v.toFixed(2))+'×',{models:['fm']}),range('synth.fmIndex','FM INDEX',r.synth.fmIndex,.01,v=>Number(v.toFixed(2)),{models:['fm']}),choice('synth.fmAlgorithm','FM ROUTING',S.ENUMS.fmAlgorithm,{models:['fm']}),range('synth.fmFeedback','FM FEEDBACK',r.synth.fmFeedback,.01,pct,{models:['fm']})
    ]);
    createControls('filterControls',[
      choice('synth.filter.type','FILTER TYPE',S.ENUMS.filterType),range('synth.filter.cutoff','CUTOFF',r.filter.cutoff,1,hz),range('synth.filter.resonance','RESONANCE',r.filter.resonance,.01,pct),range('synth.filter.envAmount','ENVELOPE DEPTH',r.filter.envAmount,.01,v=>signed(Number(v.toFixed(2)))+' oct'),range('synth.filter.keytrack','KEY TRACKING',r.filter.keytrack,.01,pct)
    ]);
    for(const [container,prefix] of [['ampControls','synth.amp'],['filterEnvControls','synth.filterEnv']])createControls(container,['attack','decay','sustain','release'].map(k=>range(prefix+'.'+k,k.toUpperCase(),r.envelope[k],k==='sustain'?.01:.001,k==='sustain'?pct:seconds)));
    createControls('toneControls',[range('synth.drive','CIRCUIT DRIVE',r.synth.drive,.01,pct),range('synth.velocity','VELOCITY RESPONSE',r.synth.velocity,.01,pct),range('synth.glide','PORTAMENTO',r.synth.glide,.001,seconds)]);
    createControls('lfoControls',[
      choice('synth.lfo.shape','LFO SHAPE',S.ENUMS.lfoShape),range('synth.lfo.rate','FREE RATE',r.lfo.rate,.01,hz),choice('synth.lfo.sync','TEMPO SYNC',S.ENUMS.lfoSync),range('synth.lfo.depth','MOD DEPTH',r.lfo.depth,.01,pct),choice('synth.lfo.target','DESTINATION',S.ENUMS.lfoTarget)
    ]);
    createControls('fxControls',[
      range('fx.chorus','CHORUS',r.fx.chorus,.01,pct),range('fx.chorusRate','CHORUS RATE',r.fx.chorusRate,.01,hz),range('fx.delay','DELAY MIX',r.fx.delay,.01,pct),choice('fx.delayDivision','DELAY TIME',S.ENUMS.delayDivision),range('fx.feedback','DELAY FEEDBACK',r.fx.feedback,.01,pct),range('fx.space','ROOM',r.fx.space,.01,pct),range('fx.width','STEREO WIDTH',r.fx.width,.01,pct),range('fx.volume','OUTPUT',r.fx.volume,.01,pct)
    ]);
    for(const model of S.MODELS){const b=document.createElement('button');b.textContent=modelInfo[model].name;b.dataset.model=model;b.title=modelInfo[model].description;b.addEventListener('click',()=>mutate(s=>{s.synth.model=model;},modelInfo[model].display+' engine selected.'));$('modelTabs').append(b);}
    let group;
    (window.ProofPresets||[]).forEach((preset,index)=>{if(!group||group.label!==preset.group){group=document.createElement('optgroup');group.label=preset.group||'Factory recipes';$('presetSelect').append(group);}const option=document.createElement('option');option.value=index;option.textContent=String(index+1).padStart(2,'0')+' / '+preset.name;group.append(option);});
  }
  function resolved(path) { return path.replace('{chord}',state.selectedChord).replace('{bank}',state.selectedPattern).replace('{step}',selectedStep); }
  function renderControls() {
    for(const [input,{def,output,label}] of controls){const path=resolved(def.path);input.dataset.path=path;const value=get(path);if(document.activeElement!==input)input.value=value;const inactive=def.models&&!def.models.includes(state.synth.model)||path==='synth.lfo.rate'&&state.synth.lfo.sync!=='free';input.disabled=!!inactive;label.classList.toggle('inactive',!!inactive);if(output)output.textContent=format(value,def);if(input.type==='range'){input.style.setProperty('--fill',((value-def.min)/(def.max-def.min)*100)+'%');input.setAttribute('aria-valuetext',format(value,def));}}
    for(const input of document.querySelectorAll('[data-path]')){if(controls.has(input))continue;const value=get(input.dataset.path);if(document.activeElement!==input){if(input.type==='checkbox')input.checked=!!value;else input.value=value;}if(input.type==='range')input.style.setProperty('--fill',((value-Number(input.min))/(Number(input.max)-Number(input.min))*100)+'%');}
    $('swingValue').textContent=pct(state.swing);$('tempo').min=S.RANGES.tempo[0];$('swing').max=S.RANGES.swing[1];
    $('patternName').value=state.patterns[state.selectedPattern].name;$('patternLength').value=state.patterns[state.selectedPattern].length;
    const step=state.patterns[state.selectedPattern].steps[selectedStep];$('stepIndex').textContent=String(selectedStep+1).padStart(2,'0');$('stepTie').checked=step.tie;$('stepProtect').checked=step.protect;$('stepToggle').setAttribute('aria-pressed',String(step.on));$('stepToggle').textContent=step.on?'On':'Off';
    const chord=state.chords[state.selectedChord];$('chordIndex').textContent=String(state.selectedChord+1).padStart(2,'0');$('chordName').textContent=S.chordName(state,chord);$('chordNotes').textContent=S.chordNotes(state,chord).map(S.noteName).join(' · ');
    $('heldSummary').textContent='HELD / '+(state.heldNotes.map(S.noteName).join(' ')||'NO NOTES');
    for(const b of $('modelTabs').children)b.setAttribute('aria-pressed',String(b.dataset.model===state.synth.model));$('modelDescription').textContent=modelInfo[state.synth.model].description;$('modelReadout').textContent=modelInfo[state.synth.model].display;
    $('importedNotice').hidden=!state.musicLabPattern;$('euclidPulses').max=state.patterns[state.selectedPattern].length;
  }
  function renderChordRack() {
    if(!$('chordRack').children.length)for(let i=0;i<8;i++){const b=document.createElement('button');b.className='chord-slot';b.dataset.chord=i;const top=document.createElement('span');top.className='slot-number';top.append(document.createTextNode(String(i+1).padStart(2,'0')));const light=document.createElement('i');light.className='slot-light';top.append(light);const name=document.createElement('strong');const length=document.createElement('span');length.className='slot-length';b.append(top,name,length);b.addEventListener('click',()=>selectChord(i));$('chordRack').append(b);}
    for(let i=0;i<8;i++){const b=$('chordRack').children[i],chord=state.chords[i];b.classList.toggle('selected',i===state.selectedChord);b.classList.toggle('off',!chord.enabled);b.classList.toggle('playing',i===playingChord&&engine.isPlaying);b.setAttribute('aria-pressed',String(i===state.selectedChord));b.setAttribute('aria-label','Chord '+(i+1)+', '+S.chordName(state,chord)+', '+(chord.enabled?'enabled':'disabled'));b.querySelector('strong').textContent=S.chordName(state,chord);b.querySelector('.slot-length').textContent=chord.enabled?chord.bars+' '+(chord.bars===1?'BAR':'BARS')+' / HOLD':'SLOT DISABLED';}
  }
  function selectChord(index){finishTransaction();state.selectedChord=index;changed();status('Chord '+(index+1)+' / '+S.chordName(state,state.chords[index])+'.');}
  function selectStep(index){finishTransaction();selectedStep=index;renderControls();renderSteps();}
  function renderSteps() {
    const pattern=state.patterns[state.selectedPattern];
    if(!$('steps').children.length)for(let i=0;i<16;i++){const b=document.createElement('button');b.className='step-cell';b.dataset.step=i;const num=document.createElement('span');num.className='step-number';num.textContent=String(i+1).padStart(2,'0');const note=document.createElement('span');note.className='step-note';const velocity=document.createElement('span');velocity.className='step-velocity';velocity.append(document.createElement('i'));const flags=document.createElement('span');flags.className='step-flags-readout';b.append(num,note,velocity,flags);b.addEventListener('click',()=>selectStep(i));b.addEventListener('dblclick',()=>mutate(s=>{s.patterns[s.selectedPattern].steps[i].on=!s.patterns[s.selectedPattern].steps[i].on;}));$('steps').append(b);}
    for(let i=0;i<16;i++){const b=$('steps').children[i],step=pattern.steps[i],event=phraseEvents.find(e=>e.step===i);b.classList.toggle('selected',i===selectedStep);b.classList.toggle('off',!step.on);b.classList.toggle('outside',i>=pattern.length);b.classList.toggle('playing',i===playingStep&&engine.isPlaying);b.setAttribute('aria-pressed',String(i===selectedStep));b.setAttribute('aria-label','Step '+(i+1)+', '+(step.on?'on':'off')+', velocity '+Math.round(step.velocity*100)+' percent'+(step.protect?', protected':''));b.querySelector('.step-note').textContent=i>=pattern.length?'—':event?S.noteName(event.note):step.tie?'TIE':step.on?'·':'OFF';b.querySelector('.step-velocity i').style.height=(step.velocity*100)+'%';b.querySelector('.step-flags-readout').textContent=(step.protect?'◆':'')+(step.tie?'⌒':step.ratchet>1?step.ratchet+'×':'');}
    if(!$('patternBanks').children.length)for(let i=0;i<4;i++){const b=document.createElement('button');b.dataset.bank=i;b.addEventListener('click',()=>mutate(s=>{s.selectedPattern=i;selectedStep=Math.min(selectedStep,s.patterns[i].length-1);},'Pattern bank '+String.fromCharCode(65+i)+'.'));$('patternBanks').append(b);}
    for(let i=0;i<4;i++){const b=$('patternBanks').children[i];b.textContent=String.fromCharCode(65+i);b.title=state.patterns[i].name;b.setAttribute('aria-pressed',String(i===state.selectedPattern));b.setAttribute('aria-label','Pattern bank '+String.fromCharCode(65+i)+', '+state.patterns[i].name);}
  }
  function render() { renderControls();renderHistory();drawDisplays();renderChordRack();renderSteps();renderTransport();storageNotice(); }
  // Resize bitmaps only when their dimensions change; clear before each identical redraw.
  const displayCanvases=new Map();
  function canvasContext(id,height) { let display=displayCanvases.get(id);if(!display){const canvas=$(id);display={canvas,ctx:canvas.getContext('2d')};displayCanvases.set(id,display);}const {canvas,ctx}=display,width=Math.max(1,canvas.clientWidth),ratio=Math.min(2,window.devicePixelRatio||1),pixelWidth=Math.round(width*ratio),pixelHeight=Math.round(height*ratio);if(canvas.width!==pixelWidth)canvas.width=pixelWidth;if(canvas.height!==pixelHeight)canvas.height=pixelHeight;ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.setTransform(ratio,0,0,ratio,0,0);return {ctx,width,height}; }
  function drawDisplays() {
    let length;try{length=Math.min(64,Math.max(4,arp.progressionLength(state)));phraseEvents=arp.events(state,{startBeat:0,lengthBeats:length});}catch(_){length=16;phraseEvents=[];}
    const notes=state.source==='held'?state.heldNotes:S.chordNotes(state,state.chords[state.selectedChord]);$('noteReadout').textContent=notes.map(S.noteName).join(' · ')||'PLAY A CHORD';
    $('phraseSummary').textContent=S.noteName(state.root).replace(/-?\d+$/,'')+' '+(labels[state.scale]||state.scale).toUpperCase()+' · '+(labels[state.arp.direction]||state.arp.direction).toUpperCase()+' · '+state.arp.division;
    $('phraseLength').textContent=Number((length/4).toFixed(2))+' BARS / '+state.patterns[state.selectedPattern].length+' STEPS';
    const {ctx,width,height}=canvasContext('phraseCanvas',95), low=Math.min(48,...phraseEvents.map(e=>e.note)),high=Math.max(84,...phraseEvents.map(e=>e.note)),span=Math.max(12,high-low),pad=8;
    ctx.strokeStyle='#53886b25';ctx.lineWidth=1;for(let y=12;y<height;y+=15){ctx.beginPath();ctx.moveTo(0,y+.5);ctx.lineTo(width,y+.5);ctx.stroke();}for(let beat=0;beat<length;beat+=4){const x=beat/length*width;ctx.beginPath();ctx.moveTo(x+.5,4);ctx.lineTo(x+.5,height-4);ctx.stroke();}
    for(const e of phraseEvents){const x=e.startBeat/length*width,y=height-pad-(e.note-low)/span*(height-2*pad),w=Math.max(2,Math.min(width-x,e.durationBeats/length*width-1));ctx.fillStyle='rgba(158,232,201,'+(.25+.7*e.velocity)+')';ctx.shadowColor='#91cbaa';ctx.shadowBlur=3;ctx.fillRect(x,y,w,3);ctx.shadowBlur=0;}
    drawEnvelope('ampCanvas',state.synth.amp);drawEnvelope('filterEnvCanvas',state.synth.filterEnv);drawFilter();
  }
  function drawEnvelope(id,env){const {ctx,width,height}=canvasContext(id,id==='ampCanvas'?72:65),padding=9,a=env.attack,d=env.decay,r=env.release,total=a+d+r+Math.max(.3,(a+d+r)*.2),sx=width-2*padding,sy=height-2*padding,hold=Math.max(.3,(a+d+r)*.2),points=[[padding,height-padding],[padding+a/total*sx,padding],[padding+(a+d)/total*sx,height-padding-env.sustain*sy],[padding+(a+d+hold)/total*sx,height-padding-env.sustain*sy],[width-padding,height-padding]];ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle='#dba74e';ctx.lineWidth=1.5;ctx.stroke();ctx.lineTo(width-padding,height);ctx.lineTo(padding,height);ctx.closePath();ctx.fillStyle='#d99b2720';ctx.fill();for(const p of points.slice(1,-1)){ctx.fillStyle='#f1c879';ctx.fillRect(p[0]-1.5,p[1]-1.5,3,3);} }
  function drawFilter(){const {ctx,width,height}=canvasContext('filterCanvas',75),f=state.synth.filter;ctx.strokeStyle='#756e4724';ctx.lineWidth=1;for(let x=10;x<width;x+=width/6){ctx.beginPath();ctx.moveTo(x,8);ctx.lineTo(x,height-8);ctx.stroke();}ctx.beginPath();for(let x=0;x<width;x++){const frequency=20*Math.pow(1000,x/width),ratio=frequency/f.cutoff;let gain;if(f.type==='hp')gain=ratio/Math.sqrt(1+ratio*ratio);else if(f.type==='bp')gain=2*ratio/(1+ratio*ratio);else gain=1/Math.sqrt(1+Math.pow(ratio,f.type==='lp24'?8:4));gain+=f.resonance*.45*Math.exp(-Math.pow(Math.log(Math.max(.001,ratio))*3,2));const y=height-10-Math.min(1.35,gain)*39;if(!x)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.strokeStyle='#a1d7b5';ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle='#708977';ctx.font='8px monospace';ctx.fillText('20 Hz',9,height-6);ctx.fillText('20 kHz',Math.max(9,width-45),height-6);}
  let lastTransport=null;
  function renderTransport(){const playing=!!engine.isPlaying;if(lastTransport===playing)return;lastTransport=playing;$('playButton').setAttribute('aria-pressed',String(playing));$('playLabel').textContent=playing?'Playing':'Play';$('playButton').firstElementChild.textContent=playing?'Ⅱ':'▶';$('transportLamp').classList.toggle('active',playing);$('transportStatus').textContent=playing?'PROOFING':'OVEN READY';}
  async function play(options={}) { finishTransaction(); const operation=++transportOperation;try{if(state.source==='held')for(const note of new Set(activeKeys.values()))engine.release(note);await engine.start(options);if(operation!==transportOperation){engine.stop();return;}renderTransport();status('The chord is rising.');}catch(error){if(operation===transportOperation)status('Audio could not start: '+error.message);} }
  function stop(){++transportOperation;engine.stop();playingStep=-1;playingChord=-1;renderTransport();renderSteps();renderChordRack();status('Stopped. Your recipe is ready.');}
  function panic(){++transportOperation;engine.panic();activeKeys.clear();held.clear();fillHeld=false;engine.setState(copy(state));renderKeyboardActivity();renderTransport();renderSteps();renderChordRack();status('All notes silenced.');}
  async function restart(){stop();await play({beat:0});}
  async function exportAudio(opts={}) { const snapshot=opts.state?S.normalize(opts.state):copy(state);return engine.renderWav({...opts,state:snapshot}); }
  function cancelExport(){exportAbort?.abort();exportAbort=null;document.body.classList.remove('is-exporting');$('wavButton').disabled=false;$('cancelExportButton').hidden=true;}
  async function exportWav(){cancelExport();const controller=new AbortController();exportAbort=controller;document.body.classList.add('is-exporting');$('wavButton').disabled=true;$('cancelExportButton').hidden=false;const name=filename('.wav'),scope=$('exportScope').value,bars=Math.min(16,Math.max(1,Number($('exportBars').value)||4));status('Printing stereo WAV… you can keep editing.');try{const result=await exportAudio({state:copy(state),bars,scope,signal:controller.signal});if(controller.signal.aborted||exportAbort!==controller)return;download(result.blob||result,name);status('Stereo WAV ready / '+bars+' '+(bars===1?'bar':'bars')+'.');}catch(error){if(!controller.signal.aborted)status('WAV render failed: '+error.message);}finally{if(exportAbort===controller)cancelExport();}}
  function exportMidi(){
    const bars=Math.min(16,Math.max(1,Number($('exportBars').value)||4)),length=bars*4,ticks=480,events=arp.events(copy(state),{startBeat:0,lengthBeats:length}),track=[];
    const vlq=n=>{n=Math.max(0,Math.round(n));const bytes=[n&127];while(n>>=7)bytes.unshift((n&127)|128);return bytes;};
    const tempo=Math.round(60000000/state.tempo);track.push(0,255,81,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255,0,255,88,4,4,2,24,8,0,192,81);
    const ordered=[];for(const event of events){if(event.velocity<=0||event.startBeat>=length)continue;const note=Math.max(0,Math.min(127,Math.round(event.note))),start=Math.max(0,Math.round(event.startBeat*ticks)),end=Math.max(start+1,Math.round(Math.min(length,event.startBeat+event.durationBeats)*ticks));ordered.push({time:start,on:true,note,velocity:Math.max(1,Math.round(event.velocity*127))},{time:end,on:false,note,velocity:0});}
    ordered.sort((a,b)=>a.time-b.time||Number(a.on)-Number(b.on)||a.note-b.note);let previous=0;for(const e of ordered){track.push(...vlq(e.time-previous),e.on?144:128,e.note,e.velocity);previous=e.time;}track.push(...vlq(Math.max(0,length*ticks-previous)),255,47,0);
    const u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],bytes=new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,...u32(track.length),...track]);download(new Blob([bytes],{type:'audio/midi'}),filename('.mid'));status('MIDI ready / '+events.length+' realized notes, '+bars+' bars.');
  }
  function readInput(input){const def=controls.get(input)?.def;if(input.type==='checkbox')return input.checked;if(def?.boolean)return input.value==='true';if(input.type==='range'||input.type==='number'||def?.numeric||input.dataset.path==='root')return Number(input.value);return input.value;}
  document.addEventListener('pointerdown',event=>{const input=event.target.closest('[data-path]');if(input&&!input.disabled){finishTransaction();transaction=copy(state);transactionTarget=input;} });
  document.addEventListener('focusin',event=>{if(event.target.matches('[data-path]')&&!transaction){transaction=copy(state);transactionTarget=event.target;}});
  document.addEventListener('input',event=>{const input=event.target;if(!input.matches('[data-path]')||input.disabled)return;if(transactionTarget!==input){finishTransaction();transaction=copy(state);transactionTarget=input;}const value=readInput(input);if(typeof value==='number'&&!Number.isFinite(value))return;set(input.dataset.path,value);$('presetSelect').value='';changed({full:false});});
  document.addEventListener('change',event=>{if(event.target.matches('[data-path]')){finishTransaction();renderControls();}});
  document.addEventListener('focusout',event=>{if(event.target===transactionTarget){finishTransaction();renderControls();}});
  $('patternName').addEventListener('change',()=>mutate(s=>{s.patterns[s.selectedPattern].name=$('patternName').value;},'Bank renamed.'));
  $('patternLength').addEventListener('change',()=>mutate(s=>{s.patterns[s.selectedPattern].length=Math.min(16,Math.max(1,Number($('patternLength').value)||16));selectedStep=Math.min(selectedStep,s.patterns[s.selectedPattern].length-1);},'Active pattern length changed.'));
  $('stepToggle').addEventListener('click',()=>mutate(s=>{const x=s.patterns[s.selectedPattern].steps[selectedStep];x.on=!x.on;}));
  for(const [id,key] of [['stepTie','tie'],['stepProtect','protect']])$(id).addEventListener('change',()=>mutate(s=>{s.patterns[s.selectedPattern].steps[selectedStep][key]=$(id).checked;}));
  $('copyBankButton').addEventListener('click',()=>mutate(s=>{const next=(s.selectedPattern+1)%4;s.patterns[next]=copy(s.patterns[s.selectedPattern]);s.patterns[next].name=s.patterns[s.selectedPattern].name+' copy';s.selectedPattern=next;},'Copied into the next bank.'));
  $('clearPatternButton').addEventListener('click',()=>mutate(s=>{s.patterns[s.selectedPattern].steps.forEach(x=>x.on=false);},'Steps cleared. Undo restores them.'));
  $('allStepsButton').addEventListener('click',()=>mutate(s=>{s.patterns[s.selectedPattern].steps.forEach(x=>x.on=true);},'All sixteen steps enabled.'));
  $('euclidButton').addEventListener('click',()=>mutate(s=>{const p=s.patterns[s.selectedPattern],pulses=Math.min(p.length,Math.max(0,Number($('euclidPulses').value)||0)),rhythm=S.euclidean(p.length,pulses,0);p.steps.forEach((x,i)=>{if(!x.protect)x.on=i<p.length&&rhythm[i];});},'Euclidean rhythm applied. Protected steps kept.'));
  $('mutateButton').addEventListener('click',()=>mutate(s=>{let seed=(s.seed^0x9e3779b9)>>>0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;};for(const x of s.patterns[s.selectedPattern].steps){if(x.protect)continue;x.on=random()>.14;x.velocity=.48+random()*.48;x.gate=.65+random()*.5;x.ratchet=random()>.88?2:1;x.probability=random()>.85?.7:1;x.offset=Math.round((random()-.5)*8)/100;x.octave=random()>.92?1:0;}s.seed=(seed+1)>>>0;},'A fresh variation. Protected steps kept.'));
  $('presetSelect').addEventListener('change',()=>{const preset=window.ProofPresets?.[Number($('presetSelect').value)];if($('presetSelect').value===''||!preset)return;const index=$('presetSelect').value;loadState(preset);$('presetSelect').value=index;$('presetDescription').textContent=preset.description||'Factory recipe / '+preset.group;status('Recipe '+(Number(index)+1)+' / '+preset.name+'.');});
  $('undoButton').addEventListener('click',undo);$('redoButton').addEventListener('click',redo);
  $('resetButton').addEventListener('click',()=>{loadState(S.defaultState());$('presetSelect').value='0';$('presetDescription').textContent=window.ProofPresets?.[0]?.description||'The original after-hours recipe.';status('Original recipe restored. Undo returns to your edits.');});
  $('saveButton').addEventListener('click',()=>{finishTransaction();download(new Blob([S.serialize(state)],{type:'application/json'}),filename('.proof.json'));status('Complete recipe saved.');});
  $('openButton').addEventListener('click',()=>{$('projectFile').value='';$('projectFile').click();});
  $('projectFile').addEventListener('change',async()=>{const file=$('projectFile').files[0];if(!file)return;const operation=++importOperation;if(file.size>1048576){status('Choose a project smaller than 1 MiB.');return;}try{const text=await file.text();if(operation!==importOperation)return;const loaded=S.parseProject(text);loadState(loaded);}catch(error){if(operation===importOperation)status('Project could not open: '+error.message);}});
  $('nativeArpButton').addEventListener('click',()=>mutate(s=>{delete s.musicLabPattern;},'Native arpeggiator restored. Undo brings back the imported notes.'));
  $('playButton').addEventListener('click',()=>engine.isPlaying?stop():play());$('stopButton').addEventListener('click',stop);$('restartButton').addEventListener('click',restart);$('panicButton').addEventListener('click',panic);
  $('auditionChordButton').addEventListener('click',async()=>{try{await engine.init();for(const note of S.chordNotes(state,state.chords[state.selectedChord]))await engine.trigger(note,.7,.8);status('Chord '+S.chordName(state,state.chords[state.selectedChord])+'.');}catch(error){status(error.message);}});
  $('wavButton').addEventListener('click',exportWav);$('midiExportButton').addEventListener('click',exportMidi);$('cancelExportButton').addEventListener('click',()=>{cancelExport();status('WAV render canceled.');});
  $('exportScope').addEventListener('change',()=>{$('exportBars').disabled=$('exportScope').value!=='pattern';});
  function setFill(on){if(fillHeld===on)return;fillHeld=on;engine.setState(audioState());$('fillButton').setAttribute('aria-pressed',String(on));$('fillButton').textContent=on?'Double-hit fill':'Hold to fill';}
  $('fillButton').addEventListener('pointerdown',event=>{event.preventDefault();$('fillButton').setPointerCapture(event.pointerId);setFill(true);});$('fillButton').addEventListener('pointerup',()=>setFill(false));$('fillButton').addEventListener('pointercancel',()=>setFill(false));$('fillButton').addEventListener('lostpointercapture',()=>setFill(false));$('fillButton').addEventListener('keydown',event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();setFill(true);}});$('fillButton').addEventListener('keyup',()=>setFill(false));$('fillButton').addEventListener('blur',()=>setFill(false));
  const keyMap=['a','w','s','e','d','f','t','g','y','h','u','j','k','o','l','p',';','\'',']'];
  function renderKeyboard(){const keyboard=$('keyboard');keyboard.replaceChildren();const white=[];for(let note=keyboardBase;note<=keyboardBase+24;note++){if(![1,3,6,8,10].includes(note%12))white.push(note);}for(let note=keyboardBase;note<=keyboardBase+24;note++){const black=[1,3,6,8,10].includes(note%12),button=document.createElement('button');button.className='piano-key'+(black?' black':'');button.dataset.note=note;button.setAttribute('aria-label',S.noteName(note));button.setAttribute('aria-pressed','false');if(black){const preceding=white.filter(n=>n<note).length;button.style.left=(preceding/white.length*100-2.15)+'%';}const label=document.createElement('span');label.textContent=keyMap[note-keyboardBase]?.toUpperCase()||'';if(!black&&note%12===0)button.append(document.createTextNode(S.noteName(note)));button.append(label);
      button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);keyDown('pointer-'+event.pointerId,note,keyVelocity);});button.addEventListener('pointerup',event=>keyUp('pointer-'+event.pointerId));button.addEventListener('pointercancel',event=>keyUp('pointer-'+event.pointerId));button.addEventListener('lostpointercapture',event=>keyUp('pointer-'+event.pointerId));button.addEventListener('keydown',event=>{if((event.key===' '||event.key==='Enter')&&!event.repeat){event.preventDefault();keyDown('focus-'+note,note,keyVelocity);}});button.addEventListener('keyup',event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();keyUp('focus-'+note);}});button.addEventListener('blur',()=>keyUp('focus-'+note));keyboard.append(button);
    }$('keyboardOctave').textContent=S.noteName(keyboardBase)+'—'+S.noteName(keyboardBase+24);renderKeyboardActivity();}
  function renderKeyboardActivity(){const live=new Set([...activeKeys.values()]);for(const key of $('keyboard').children){const active=live.has(Number(key.dataset.note));key.classList.toggle('active',active);key.setAttribute('aria-pressed',String(active));}}
  async function keyDown(source,note,velocity){if(activeKeys.has(source))return;const fresh=activeKeys.size===0;activeKeys.set(source,note);held.add(note);if(state.source==='held'){finishTransaction();const before=copy(state);if(fresh||!state.latch)state.heldNotes=[];state.heldNotes=Array.from(new Set([...state.heldNotes,...held])).sort((a,b)=>a-b);remember(before);changed();}if(state.source!=='held'||!engine.isPlaying){try{await engine.trigger(note,velocity,768);if(!activeKeys.has(source))engine.release(note);}catch(error){status('Audio could not start: '+error.message);}}
    renderKeyboardActivity();$('noteReadout').textContent=S.noteName(note)+' / '+pct(velocity);}
  function keyUp(source){const note=activeKeys.get(source);if(note===undefined)return;activeKeys.delete(source);if(![...activeKeys.values()].includes(note)){held.delete(note);engine.release(note);}if(state.source==='held'&&!state.latch){state.heldNotes=Array.from(held).sort((a,b)=>a-b);changed();}renderKeyboardActivity();}
  function releaseKeyboard(){for(const source of [...activeKeys.keys()])keyUp(source);setFill(false);}
  function shiftKeyboard(direction){releaseKeyboard();keyboardBase=Math.max(12,Math.min(96,keyboardBase+direction*12));renderKeyboard();status('Keyboard '+S.noteName(keyboardBase)+' to '+S.noteName(keyboardBase+24)+'.');}
  $('keyboardDown').addEventListener('click',()=>shiftKeyboard(-1));$('keyboardUp').addEventListener('click',()=>shiftKeyboard(1));$('keyVelocity').addEventListener('input',()=>{keyVelocity=Number($('keyVelocity').value);$('keyVelocityValue').textContent=pct(keyVelocity);$('keyVelocity').style.setProperty('--fill',((keyVelocity-.05)/.95*100)+'%');});
  function midiDisconnect(){for(const [input,fn]of midiBindings)if(input.onmidimessage===fn)input.onmidimessage=null;midiBindings.clear();for(const source of [...activeKeys.keys()])if(source.startsWith('midi-'))keyUp(source);}
  function attachMidi(){midiDisconnect();if(!midiAccess)return;for(const input of midiAccess.inputs.values()){if(input.state==='disconnected')continue;const fn=event=>{const [statusByte,note,velocity]=event.data,type=statusByte&240,key='midi-'+input.id+'-'+(statusByte&15)+'-'+note;if(type===144&&velocity>0)keyDown(key,note,velocity/127);else if(type===128||type===144&&velocity===0)keyUp(key);else if(type===176&&(note===120||note===123))releaseKeyboard();};input.onmidimessage=fn;midiBindings.set(input,fn);}$('midiStatus').textContent=midiBindings.size?midiBindings.size+' MIDI INPUT'+(midiBindings.size>1?'S':'')+' CONNECTED':'NO MIDI INPUTS / RECONNECT A DEVICE';$('midiButton').textContent=midiBindings.size?'Reconnect MIDI':'Connect MIDI';}
  $('midiButton').addEventListener('click',async()=>{if(!navigator.requestMIDIAccess){status('This browser does not provide Web MIDI. The computer and on-screen keys are ready.');$('midiStatus').textContent='WEB MIDI UNAVAILABLE';return;}try{if(midiAccess)midiAccess.onstatechange=null;midiDisconnect();midiAccess=await navigator.requestMIDIAccess({sysex:false});midiAccess.onstatechange=attachMidi;attachMidi();await engine.init();status(midiBindings.size?'MIDI connected. Choose held notes to arpeggiate your playing.':'Connect a MIDI keyboard; LEAVEN will detect it.');}catch(error){status('MIDI connection unavailable: '+error.message);}});
  document.addEventListener('keydown',event=>{const editing=event.target.closest('input,select,textarea,[contenteditable=true]'),dialog=$('helpDialog').open;if(event.key==='Escape'){panic();return;}if(dialog)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!editing){event.preventDefault();event.shiftKey?redo():undo();return;}if(editing||event.ctrlKey||event.metaKey||event.altKey)return;if(event.key===' '&&event.target.tagName!=='BUTTON'){event.preventDefault();if(!event.repeat)engine.isPlaying?stop():play();return;}if(event.key==='Home'){event.preventDefault();if(!event.repeat)restart();return;}if(event.repeat)return;const key=event.key.toLowerCase();if(key==='z'){event.preventDefault();shiftKeyboard(-1);}else if(key==='x'){event.preventDefault();shiftKeyboard(1);}else{const index=keyMap.indexOf(key);if(index>=0){event.preventDefault();keyDown('computer-'+event.code,keyboardBase+index,keyVelocity);}}});
  document.addEventListener('keyup',event=>keyUp('computer-'+event.code));window.addEventListener('blur',releaseKeyboard);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseKeyboard();});
  $('helpButton').addEventListener('click',()=>{$('helpDialog').showModal();});$('closeHelpButton').addEventListener('click',()=>{$('helpDialog').close();});$('helpDialog').addEventListener('click',event=>{if(event.target===$('helpDialog')){const r=$('helpDialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('helpDialog').close();}});
  const meterNodes=Object.fromEntries(['steps','chordRack','levelFill','levelReadout','voiceReadout','position'].map(id=>[id,$(id)]));
  function meterText(id,value){const node=meterNodes[id];if(node.textContent!==value)node.textContent=value;}
  let lastLevelWidth;
  function metersFrame(now){if(now-lastMeterTime>80){lastMeterTime=now;const meter=engine.getMeters()||{};const playing=!!engine.isPlaying;if(playing){playingStep=meter.step??-1;playingChord=meter.chord??-1;}else{playingStep=-1;playingChord=-1;}renderTransport();for(let i=0;i<16;i++){const b=meterNodes.steps.children[i],on=playing&&i===playingStep;if(b&&b.classList.contains('playing')!==on)b.classList.toggle('playing',on);}for(let i=0;i<8;i++){const b=meterNodes.chordRack.children[i],on=playing&&i===playingChord;if(b&&b.classList.contains('playing')!==on)b.classList.toggle('playing',on);}const rms=Math.max(0,Number(meter.rms)||0),db=rms>1e-5?20*Math.log10(rms):-Infinity;const levelWidth=Math.max(0,Math.min(100,(db+60)/60*100))+'%';if(levelWidth!==lastLevelWidth){meterNodes.levelFill.style.width=levelWidth;lastLevelWidth=levelWidth;}meterText('levelReadout',Number.isFinite(db)?Math.round(db)+' dB':'−∞ dB');meterText('voiceReadout',String(meter.voices||0).padStart(2,'0')+' VOICES');const beat=Math.max(0,Number(meter.beat)||0);meterText('position',String(Math.floor(beat/4)+1).padStart(2,'0')+' : '+String(Math.floor(beat%4)+1).padStart(2,'0'));const {ctx,width,height}=canvasContext('scopeCanvas',60),wave=meter.waveform;ctx.strokeStyle='#99d9b7';ctx.lineWidth=1;ctx.beginPath();if(wave&&wave.length){for(let i=0;i<wave.length;i++){const x=i/(wave.length-1)*width,y=height/2-Math.max(-1,Math.min(1,wave[i]))*height*.44;if(!i)ctx.moveTo(x,y);else ctx.lineTo(x,y);}}else{ctx.moveTo(0,height/2);ctx.lineTo(width,height/2);}ctx.stroke();}requestAnimationFrame(metersFrame);}
  buildControls();renderKeyboard();render();if(!storageFailed&&equal(state,S.normalize(window.ProofPresets?.[0]||S.defaultState()))){$('presetSelect').value='0';$('presetDescription').textContent=window.ProofPresets?.[0]?.description||'Warm circuits. Patient repetition. A little after-hours magic.';}
  let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawDisplays,100);});
  window.addEventListener('pagehide',()=>{releaseKeyboard();midiDisconnect();if(midiAccess)midiAccess.onstatechange=null;cancelExport();clearTimeout(autosaveTimer);if(!hosted){try{localStorage.setItem('proof-project-v1',S.serialize(state));}catch(_){}}engine.dispose();});
  window.ProofApp={getState:()=>copy(state),getProject:()=>JSON.parse(S.serialize(state)),loadState,applyState:loadState,engine,play,stop,panic,isPlaying:()=>!!engine.isPlaying,exportAudio,audioExport:{scopes:[{id:'pattern',label:'Arp phrase'},{id:'note',label:'Single note',usesBars:false},{id:'chord',label:'Current chord',usesBars:false}],defaultBars:4,maxBars:16},onStateChange(fn){listeners.add(fn);return()=>listeners.delete(fn);},selectStep,selectChord,clearImportedPattern(){mutate(s=>{delete s.musicLabPattern;},'Native arpeggiator restored.');}};
  window.dispatchEvent(new CustomEvent('musiclab:app-ready',{detail:{app:'proof'}}));requestAnimationFrame(metersFrame);
})();
