/* PROOF project vocabulary. Numeric values are seconds, Hz, beats or normalized controls. */
(function (global) {
  'use strict';
  const VERSION = '1.0.0', MAX_PROJECT_BYTES = 1024 * 1024;
  const SCALES = Object.freeze({ major: [0, 2, 4, 5, 7, 9, 11], minor: [0, 2, 3, 5, 7, 8, 10], dorian: [0, 2, 3, 5, 7, 9, 10], mixolydian: [0, 2, 4, 5, 7, 9, 10], lydian: [0, 2, 4, 6, 7, 9, 11], pentatonic: [0, 2, 4, 7, 9], harmonic: [0, 2, 3, 5, 7, 8, 11] });
  const QUALITIES = Object.freeze({ diatonic: [0, 2, 4], major: [0, 4, 7], minor: [0, 3, 7], maj7: [0, 4, 7, 11], min7: [0, 3, 7, 10], dominant7: [0, 4, 7, 10], add9: [0, 4, 7, 14], min9: [0, 3, 7, 10, 14], sus2: [0, 2, 7], sus4: [0, 5, 7], dim7: [0, 3, 6, 9] });
  const DIRECTIONS = Object.freeze(['up', 'down', 'updown', 'downup', 'outsidein', 'insideout', 'random', 'walk', 'skip', 'chord']);
  const DIVISIONS = Object.freeze({ '1/32': .125, '1/16': .25, '1/16T': 1 / 6, '1/8': .5, '1/8T': 1 / 3, '1/4': 1, '1/4T': 2 / 3 });
  const MODELS = Object.freeze(['dco', 'vco', 'sync', 'fm', 'vector']), TABLES = Object.freeze(['glass', 'hollow', 'choir', 'reed', 'spectrum', 'bell']), FOLDS = Object.freeze(['none', 'rise', 'fall', 'reverse', 'rotate', 'mirror']);
  const ENUMS = Object.freeze({ scale: Object.keys(SCALES), source: ['progression', 'held', 'single'], direction: DIRECTIONS, division: Object.keys(DIVISIONS), quality: Object.keys(QUALITIES), fold: FOLDS, model: MODELS, wave: ['saw', 'pulse', 'triangle', 'sine'], table: TABLES, fmAlgorithm: ['cascade', 'parallel', 'feedback'], filterType: ['lp12', 'lp24', 'hp', 'bp'], lfoShape: ['sine', 'triangle', 'saw', 'square', 'sampleHold'], lfoSync: ['free', '1/1', '1/2', '1/4', '1/8', '1/16', '1/4T', '1/8T', '1/16T'], lfoTarget: ['cutoff', 'pitch', 'pulse', 'vector', 'amp', 'pan'], delayDivision: ['1/32', '1/16', '1/16T', '1/8', '1/8T', '3/16', '1/4', '1/4T', '3/8', '1/2', '3/4', '1/1'] });
  const RANGES = Object.freeze({ tempo: [30, 240], swing: [0, .75], root: [0, 127], seed: [0, 4294967295], selectedChord: [0, 7], selectedPattern: [0, 3], arp: { octaves: [1, 4], gate: [.05, 1.5], transpose: [-36, 36], repeat: [1, 4], rotate: [-64, 64], spice: [0, 1], foldEvery: [1, 16] }, chord: { degree: [-7, 14], inversion: [-4, 4], spread: [0, 3] }, step: { velocity: [0, 1], gate: [.05, 2], probability: [0, 1], ratchet: [1, 4], offset: [-.45, .45], octave: [-2, 2] }, synth: { mix: [0, 1], sub: [0, 1], detune: [0, 1], pulseWidth: [.05, .95], sync: [1, 8], crossmod: [0, 1], vector: [0, 1], fmRatio: [.25, 16], fmIndex: [0, 20], fmFeedback: [0, .95], glide: [0, 2], octave: [-3, 3], velocity: [0, 1], drive: [0, 1] }, filter: { cutoff: [20, 20000], resonance: [0, .95], envAmount: [-5, 5], keytrack: [0, 1] }, envelope: { attack: [.001, 8], decay: [.001, 8], sustain: [0, 1], release: [.005, 12] }, lfo: { rate: [.02, 20], depth: [0, 1] }, fx: { chorus: [0, 1], chorusRate: [.05, 5], delay: [0, 1], feedback: [0, .85], space: [0, 1], width: [0, 1.5], volume: [0, 1] } });
  const object = x => x !== null && typeof x === 'object' && !Array.isArray(x);
  const copy = x => JSON.parse(JSON.stringify(x));
  const clamp = (x, range, fallback, integer = false) => { const v = typeof x === 'number' && Number.isFinite(x) ? Math.max(range[0], Math.min(range[1], x)) : fallback; return integer ? Math.round(v) : v; };
  const text = (x, fallback, max = 100) => typeof x === 'string' ? x.replace(/[\u0000-\u001f\u007f]/g, '').slice(0, max) : fallback;
  const choice = (x, values, fallback) => values.includes(x) ? x : fallback;
  const bool = (x, fallback) => typeof x === 'boolean' ? x : fallback;
  const step = () => ({ on: true, velocity: .8, gate: 1, probability: 1, ratchet: 1, offset: 0, octave: 0, tie: false, protect: false });
  function defaultState() {
    return { name: 'After-hours proof', tempo: 104, swing: .12, root: 57, scale: 'minor', source: 'progression', latch: true, selectedChord: 0, heldNotes: [57, 60, 64, 67], seed: 195936478,
      arp: { direction: 'updown', division: '1/16', octaves: 2, gate: .62, transpose: 0, repeat: 1, rotate: 0, spice: .06, fold: 'none', foldEvery: 4 },
      chords: Array.from({ length: 8 }, (_, i) => ({ degree: [0, 5, 2, 6][i] || 0, quality: ['min9', 'maj7', 'maj7', 'sus2'][i] || 'diatonic', inversion: 0, spread: 0, bars: 1, enabled: i < 4 })),
      selectedPattern: 0, patterns: Array.from({ length: 4 }, (_, i) => ({ name: String.fromCharCode(65 + i), length: 16, steps: Array.from({ length: 16 }, step) })),
      synth: { model: 'dco', wave: 'saw', mix: .5, sub: .18, detune: .12, pulseWidth: .45, sync: 1, crossmod: 0, vector: .35, table: 'glass', fmRatio: 2, fmIndex: 2.5, fmFeedback: .15, fmAlgorithm: 'cascade', glide: 0, octave: 0, velocity: .6, drive: .16,
        filter: { type: 'lp24', cutoff: 1800, resonance: .15, envAmount: 2, keytrack: .4 }, amp: { attack: .006, decay: .32, sustain: .45, release: .28 }, filterEnv: { attack: .002, decay: .4, sustain: .1, release: .22 }, lfo: { shape: 'sine', rate: .45, sync: 'free', depth: .15, target: 'cutoff', retrigger: false } },
      fx: { chorus: .4, chorusRate: .3, delay: .18, delayDivision: '3/16', feedback: .28, space: .15, width: .85, volume: .72 } };
  }
  function numbers(raw, defaults, ranges, integerKeys = []) { const result = {}; for (const key of Object.keys(ranges)) result[key] = clamp(raw[key], ranges[key], defaults[key], integerKeys.includes(key)); return result; }
  function byteLength(x) { return typeof TextEncoder === 'function' ? new TextEncoder().encode(x).length : encodeURIComponent(x).replace(/%[0-9A-F]{2}|./g, 'x').length; }
  function checkSize(x) { let json; try { json = typeof x === 'string' ? x : JSON.stringify(x); } catch (_) { throw new Error('The project must be a plain JSON object.'); } if (typeof json !== 'string' || json.length > MAX_PROJECT_BYTES || byteLength(json) > MAX_PROJECT_BYTES) throw new Error('LEAVEN projects must fit within 1 MiB.'); return json; }
  function fail(label) { throw new Error('Invalid ' + label + ' in this LEAVEN project.'); }
  function validNumber(x, range, label, integer = false) { if (typeof x !== 'number' || !Number.isFinite(x) || x < range[0] || x > range[1] || integer && !Number.isInteger(x)) fail(label); }
  function validText(x, label, max = 100) { if (typeof x !== 'string' || x.length > max || /[\u0000-\u001f\u007f]/.test(x)) fail(label); }
  function validBool(x, label) { if (typeof x !== 'boolean') fail(label); }
  function validChoice(x, values, label) { if (!values.includes(x)) fail(label); }
  function validNumbers(raw, ranges, label, integerKeys = []) { if (!object(raw)) fail(label); for (const key of Object.keys(ranges)) validNumber(raw[key], ranges[key], label + ' ' + key, integerKeys.includes(key)); }
  // Equivalent bounded fallback keeps unbundled offline source usable as well as built apps.
  function portablePattern(input) {
    if (global.MusicLabPatternSchema) return global.MusicLabPatternSchema.normalize(input);
    if (!object(input) || input.format !== 'musiclab-pattern' || input.version !== 1) fail('shared pattern');
    const id = (x, label) => { validText(x, label, 80); if (!x || ['__proto__', 'prototype', 'constructor'].includes(x)) fail(label); return x; };
    validNumber(input.lengthBeats, [.25, 256], 'shared pattern length');
    const voices = input.voices, notes = input.notes, length = input.lengthBeats;
    if (!Array.isArray(voices) || voices.length < 1 || voices.length > 64 || !Array.isArray(notes) || notes.length > 4096) fail('shared pattern notes');
    const voiceIds = new Set(), noteIds = new Set();
    const resultVoices = voices.map(v => { if (!object(v)) fail('shared voice'); const voiceId = id(v.id, 'shared voice ID'); if (voiceIds.has(voiceId)) fail('duplicate shared voice'); voiceIds.add(voiceId); const out = { id: voiceId, name: v.name === undefined ? voiceId : v.name }; validText(out.name, 'shared voice name', 100); if (v.pitch !== undefined) { validNumber(v.pitch, [0, 127], 'shared voice pitch', true); out.pitch = v.pitch; } return out; });
    const resultNotes = notes.map((n, i) => { if (!object(n)) fail('shared note'); const noteId = n.id === undefined ? 'n' + (i + 1) : id(n.id, 'shared note ID'); if (noteIds.has(noteId)) fail('duplicate shared note'); noteIds.add(noteId); validNumber(n.pitch, [0, 127], 'shared note pitch', true); validNumber(n.beat, [0, length], 'shared note beat'); validNumber(n.duration, [Number.MIN_VALUE, length], 'shared note duration'); if (n.beat >= length || n.beat + n.duration > length + 1e-8) fail('shared note bounds'); const voice = n.voice === undefined && voices.length === 1 ? voices[0].id : id(n.voice, 'shared note voice'); if (!voiceIds.has(voice)) fail('shared note voice'); const velocity = n.velocity === undefined ? .8 : n.velocity, probability = n.probability === undefined ? 1 : n.probability; validNumber(velocity, [0, 1], 'shared note velocity'); validNumber(probability, [0, 1], 'shared note probability'); return { id: noteId, pitch: n.pitch, beat: n.beat, duration: n.duration, velocity, voice, probability }; });
    const meter = input.meter === undefined ? [4, 4] : input.meter; if (!Array.isArray(meter) || meter.length !== 2 || !Number.isInteger(meter[0]) || meter[0] < 1 || meter[0] > 16 || ![1, 2, 4, 8, 16].includes(meter[1])) fail('shared meter');
    const tags = input.tags === undefined ? [] : input.tags; if (!Array.isArray(tags) || tags.length > 24) fail('shared tags'); tags.forEach(t => validText(t, 'shared tag', 40));
    const out = { format: 'musiclab-pattern', version: 1, name: input.name === undefined ? 'Untitled pattern' : input.name, sourceApp: input.sourceApp === undefined ? '' : input.sourceApp, kind: input.kind === undefined ? 'notes' : input.kind, tempo: input.tempo === undefined ? 120 : input.tempo, swing: input.swing === undefined ? 0 : input.swing, lengthBeats: length, meter: meter.slice(), voices: resultVoices, notes: resultNotes, tags: tags.slice() };
    validText(out.name, 'shared pattern name', 160); validText(out.sourceApp, 'shared source app', 80); validChoice(out.kind, ['notes', 'drums'], 'shared pattern kind'); validNumber(out.tempo, [20, 400], 'shared tempo'); validNumber(out.swing, [0, .75], 'shared swing'); if (input.seed !== undefined) { validNumber(input.seed, [0, 4294967295], 'shared seed', true); out.seed = input.seed; } checkSize(out); return out;
  }
  function normalizeOverlay(value) {
    if (!object(value) || !object(value.voiceMap)) fail('shared voice mapping');
    const pattern = portablePattern(value.pattern), voiceMap = {}, ids = pattern.voices.map(v => v.id);
    for (const key of Object.keys(value.voiceMap)) if (!ids.includes(key) || value.voiceMap[key] !== 'synth') fail('shared voice mapping');
    for (const voice of pattern.voices) { if (!Object.prototype.hasOwnProperty.call(value.voiceMap, voice.id) || value.voiceMap[voice.id] !== 'synth') fail('shared voice mapping'); voiceMap[voice.id] = 'synth'; }
    return { pattern, voiceMap };
  }
  function normalize(raw) {
    const d = defaultState(); raw = object(raw) ? raw : {};
    const a = object(raw.arp) ? raw.arp : {}, sy = object(raw.synth) ? raw.synth : {}, f = object(sy.filter) ? sy.filter : {}, l = object(sy.lfo) ? sy.lfo : {}, fx = object(raw.fx) ? raw.fx : {};
    const s = { name: text(raw.name, d.name), tempo: clamp(raw.tempo, RANGES.tempo, d.tempo), swing: clamp(raw.swing, RANGES.swing, d.swing), root: clamp(raw.root, RANGES.root, d.root, true), scale: choice(raw.scale, ENUMS.scale, d.scale), source: choice(raw.source, ENUMS.source, d.source), latch: bool(raw.latch, d.latch), selectedChord: clamp(raw.selectedChord, RANGES.selectedChord, 0, true), heldNotes: Array.isArray(raw.heldNotes) ? Array.from(new Set(raw.heldNotes.filter(n => typeof n === 'number' && Number.isFinite(n)).slice(0, 32).map(n => Math.round(Math.max(0, Math.min(127, n)))))).sort((x, y) => x - y) : d.heldNotes, seed: clamp(raw.seed, RANGES.seed, d.seed, true), arp: { ...numbers(a, d.arp, RANGES.arp, ['octaves', 'transpose', 'repeat', 'rotate', 'foldEvery']), direction: choice(a.direction, DIRECTIONS, d.arp.direction), division: choice(a.division, ENUMS.division, d.arp.division), fold: choice(a.fold, FOLDS, d.arp.fold) },
      chords: Array.from({ length: 8 }, (_, i) => { const c = object(raw.chords?.[i]) ? raw.chords[i] : {}; return { ...numbers(c, d.chords[i], RANGES.chord, ['degree', 'inversion', 'spread']), quality: choice(c.quality, ENUMS.quality, d.chords[i].quality), bars: choice(c.bars, [1, 2, 4], d.chords[i].bars), enabled: bool(c.enabled, d.chords[i].enabled) }; }), selectedPattern: clamp(raw.selectedPattern, RANGES.selectedPattern, 0, true),
      patterns: Array.from({ length: 4 }, (_, i) => { const p = object(raw.patterns?.[i]) ? raw.patterns[i] : {}; return { name: text(p.name, d.patterns[i].name, 24), length: clamp(p.length, [1, 16], 16, true), steps: Array.from({ length: 16 }, (_, k) => { const x = object(p.steps?.[k]) ? p.steps[k] : {}, defaults = step(); return { on: bool(x.on, defaults.on), ...numbers(x, defaults, RANGES.step, ['ratchet', 'octave']), tie: bool(x.tie, false), protect: bool(x.protect, false) }; }) }; }),
      synth: { ...numbers(sy, d.synth, RANGES.synth, ['octave']), model: choice(sy.model, MODELS, d.synth.model), wave: choice(sy.wave, ENUMS.wave, d.synth.wave), table: choice(sy.table, TABLES, d.synth.table), fmAlgorithm: choice(sy.fmAlgorithm, ENUMS.fmAlgorithm, d.synth.fmAlgorithm), filter: { ...numbers(f, d.synth.filter, RANGES.filter), type: choice(f.type, ENUMS.filterType, d.synth.filter.type) }, amp: numbers(object(sy.amp) ? sy.amp : {}, d.synth.amp, RANGES.envelope), filterEnv: numbers(object(sy.filterEnv) ? sy.filterEnv : {}, d.synth.filterEnv, RANGES.envelope), lfo: { ...numbers(l, d.synth.lfo, RANGES.lfo), shape: choice(l.shape, ENUMS.lfoShape, d.synth.lfo.shape), sync: choice(l.sync, ENUMS.lfoSync, d.synth.lfo.sync), target: choice(l.target, ENUMS.lfoTarget, d.synth.lfo.target), retrigger: bool(l.retrigger, false) } },
      fx: { ...numbers(fx, d.fx, RANGES.fx), delayDivision: choice(fx.delayDivision, ENUMS.delayDivision, d.fx.delayDivision) } };
    if (raw.musicLabPattern !== undefined) s.musicLabPattern = normalizeOverlay(raw.musicLabPattern);
    return s;
  }
  function validateState(s) {
    if (!object(s)) fail('state'); validText(s.name, 'project name');
    for (const k of ['tempo', 'swing', 'root', 'seed', 'selectedChord', 'selectedPattern']) validNumber(s[k], RANGES[k], k, ['root', 'seed', 'selectedChord', 'selectedPattern'].includes(k));
    validChoice(s.scale, ENUMS.scale, 'scale'); validChoice(s.source, ENUMS.source, 'note source'); validBool(s.latch, 'latch');
    if (!Array.isArray(s.heldNotes) || s.heldNotes.length > 32) fail('held notes'); s.heldNotes.forEach(n => validNumber(n, [0, 127], 'held note', true));
    validNumbers(s.arp, RANGES.arp, 'arp', ['octaves', 'transpose', 'repeat', 'rotate', 'foldEvery']); validChoice(s.arp.direction, DIRECTIONS, 'arp direction'); validChoice(s.arp.division, ENUMS.division, 'arp division'); validChoice(s.arp.fold, FOLDS, 'arp fold');
    if (!Array.isArray(s.chords) || s.chords.length !== 8) fail('eight chord slots'); s.chords.forEach(c => { validNumbers(c, RANGES.chord, 'chord', ['degree', 'inversion', 'spread']); validChoice(c.quality, ENUMS.quality, 'chord quality'); validChoice(c.bars, [1, 2, 4], 'chord bars'); validBool(c.enabled, 'chord enabled'); });
    if (!Array.isArray(s.patterns) || s.patterns.length !== 4) fail('four pattern banks'); s.patterns.forEach(p => { if (!object(p)) fail('pattern'); validText(p.name, 'pattern name', 24); validNumber(p.length, [1, 16], 'pattern length', true); if (!Array.isArray(p.steps) || p.steps.length !== 16) fail('sixteen steps'); p.steps.forEach(x => { validNumbers(x, RANGES.step, 'step', ['ratchet', 'octave']); validBool(x.on, 'step on'); validBool(x.tie, 'step tie'); validBool(x.protect, 'step protection'); }); });
    validNumbers(s.synth, RANGES.synth, 'synth', ['octave']); validChoice(s.synth.model, MODELS, 'oscillator model'); validChoice(s.synth.wave, ENUMS.wave, 'oscillator wave'); validChoice(s.synth.table, TABLES, 'spectral table'); validChoice(s.synth.fmAlgorithm, ENUMS.fmAlgorithm, 'FM algorithm'); validNumbers(s.synth.filter, RANGES.filter, 'filter'); validChoice(s.synth.filter.type, ENUMS.filterType, 'filter type'); validNumbers(s.synth.amp, RANGES.envelope, 'amp envelope'); validNumbers(s.synth.filterEnv, RANGES.envelope, 'filter envelope'); validNumbers(s.synth.lfo, RANGES.lfo, 'LFO'); validChoice(s.synth.lfo.shape, ENUMS.lfoShape, 'LFO shape'); validChoice(s.synth.lfo.sync, ENUMS.lfoSync, 'LFO clock'); validChoice(s.synth.lfo.target, ENUMS.lfoTarget, 'LFO target'); validBool(s.synth.lfo.retrigger, 'LFO retrigger'); validNumbers(s.fx, RANGES.fx, 'effect'); validChoice(s.fx.delayDivision, ENUMS.delayDivision, 'delay division');
    if (s.musicLabPattern !== undefined) normalizeOverlay(s.musicLabPattern);
  }
  function parseProject(input) {
    const json = checkSize(input); let value; try { value = typeof input === 'string' ? JSON.parse(json) : input; } catch (_) { throw new Error('This LEAVEN project is not valid JSON.'); }
    let state = value;
    if (object(value) && ('format' in value || 'state' in value)) { if (value.format !== 'proof-project' || (value.formatVersion === undefined ? value.version : value.formatVersion) !== 1 || value.version !== undefined && value.version !== 1) throw new Error('Choose a LEAVEN version 1 project.'); state = value.state; }
    validateState(state); return normalize(state);
  }
  function serialize(state) { const value = { format: 'proof-project', formatVersion: 1, appVersion: VERSION, state: normalize(state) }; const json = JSON.stringify(value, null, 2); checkSize(json); return json; }
  function noteName(midi) { const n = Math.round(Number(midi)); return Number.isFinite(n) ? ['C', 'C♯', 'D', 'D♯', 'E', 'F', 'F♯', 'G', 'G♯', 'A', 'A♯', 'B'][((n % 12) + 12) % 12] + (Math.floor(n / 12) - 1) : '—'; }
  function scaleNote(state, degree) { const scale = SCALES[state.scale] || SCALES.minor; return state.root + scale[((degree % scale.length) + scale.length) % scale.length] + 12 * Math.floor(degree / scale.length); }
  function chordNotes(state, chord) {
    if (typeof chord === 'number') chord = state.chords[chord]; chord = chord || state.chords[state.selectedChord || 0]; if (!chord) return [];
    const intervals = QUALITIES[chord.quality] || QUALITIES.diatonic, base = scaleNote(state, chord.degree || 0);
    let notes = intervals.map(interval => chord.quality === 'diatonic' ? scaleNote(state, (chord.degree || 0) + interval) : base + interval).sort((a, b) => a - b);
    let inversion = chord.inversion || 0; while (inversion > 0) { notes.push(notes.shift() + 12); notes.sort((a, b) => a - b); inversion--; } while (inversion < 0) { notes.unshift(notes.pop() - 12); notes.sort((a, b) => a - b); inversion++; }
    notes = notes.map((n, i) => Math.round(Math.max(0, Math.min(127, n + Math.floor(i / 2) * (chord.spread || 0) * 12)))); return Array.from(new Set(notes)).sort((a, b) => a - b);
  }
  function chordName(state, chord) { if (typeof chord === 'number') chord = state.chords[chord]; chord = chord || state.chords[state.selectedChord || 0]; if (!chord) return '—'; const degree = chord.degree || 0, root = scaleNote(state, degree), base = noteName(root).replace(/-?\d+$/, ''); let suffix = { diatonic: '', major: '', minor: 'm', maj7: 'maj7', min7: 'm7', dominant7: '7', add9: 'add9', min9: 'm9', sus2: 'sus2', sus4: 'sus4', dim7: '°7' }[chord.quality] || ''; if (chord.quality === 'diatonic') { const third = ((scaleNote(state, degree + 2) - root) % 12 + 12) % 12, fifth = ((scaleNote(state, degree + 4) - root) % 12 + 12) % 12; suffix = third === 3 ? fifth === 6 ? '°' : 'm' : fifth === 8 ? '+' : ''; } return base + suffix; }
  function euclidean(length, pulses, rotation = 0) { length = Math.max(1, Math.min(16, Math.round(Number(length) || 16))); pulses = Math.max(0, Math.min(length, Math.round(Number(pulses) || 0))); rotation = ((Math.round(Number(rotation) || 0) % length) + length) % length; return Array.from({ length }, (_, i) => (((i - rotation + length) % length) * pulses) % length < pulses); }
  global.ProofSchema = Object.freeze({ VERSION, MAX_PROJECT_BYTES, SCALES, QUALITIES, DIRECTIONS, DIVISIONS, MODELS, TABLES, FOLDS, ENUMS, RANGES, copy, defaultState, normalize, serialize, serializeProject: serialize, parseProject, noteName, chordName, chordNotes, step, euclidean });
})(typeof window === 'object' ? window : globalThis);
