(function () {
  'use strict';
  const S = window.LoomSchema, $ = id => document.getElementById(id), clone = value => S.copy(value);
  const effects = window.LoomEffectsCatalog, effectById = id => effects.find(f => f.id === id);
  const icons = {play:'<svg viewBox="0 0 12 14" aria-hidden="true"><path d="M2 1 11 7 2 13Z" fill="currentColor"/></svg>',pause:'<svg viewBox="0 0 12 14" aria-hidden="true"><path d="M2 1h3v12H2zm5 0h3v12H7z" fill="currentColor"/></svg>'};
  const escape = value => String(value == null ? '' : value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = (value, min, max) => Math.max(min, Math.min(max, Number(value) || 0));
  let recordFinishOperation = 0;
  let state, selectedClip = null, selectedSlot = null, history = [], future = [], lifecycle = 0, transportOperation = 0, recordPending = false, recordFinishing = false, transportPending = false, importOperation = 0, projectOperation = 0, loadOperations = new Map(), exportAbort = null, autosaveTimer, recovery = true;
  let recoveryWarned=false,recoveryUnavailable=false;
  let assetMap = {}, waveformCache = new Map(), fitInitial = true, drag = null, frameTrack = null, browserTrack = null, discoveryDone = false, customManifest = [], meterTime = 0;
  const frames = new Map(), armedBeforeRecord = new Map(), openedApps = new Map();
  try { recovery = localStorage.getItem('loom-recovery-enabled') !== '0'; const saved = recovery && localStorage.getItem('loom-session-v1'); state = saved ? S.parseProject(saved) : S.demoState(); } catch (_) { state = S.demoState(); recoveryUnavailable=true; }
  state = S.normalize(state);
  const engine = new window.LoomAudio(state);
  const host = new window.LoomInstrumentHost({ context: () => engine.context, getTrackInput: id => engine.getTrackInput(id), onStatus: (id, message, kind) => { if (id === frameTrack) $('instrumentHostStatus').textContent = message; if (kind === 'error') status(message); }, onStateChange: id => { scheduleSnapshot(id); } });
  function status(message) { $('status').textContent = message; }
  function track() { return state.tracks[state.selectedTrack]; }
  function clipLocation() { if (!selectedClip) return null; for (const t of state.tracks) { const c = t.clips.find(c => c.id === selectedClip); if (c) return {track:t, clip:c}; } return null; }
  function filename(suffix) { return (state.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 70) || 'loom-session') + suffix; }
  function download(blob, name) { const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = name; document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 30000); }
  function remember() { history.push(clone(state)); if (history.length > 40) history.shift(); future = []; renderHistory(); }
  function renderHistory() { $('undoButton').disabled = !history.length; $('redoButton').disabled = !future.length; }
  function decodeAssets() { const next = {}; for (const asset of state.assets) { next[asset.id] = assetMap[asset.id] || S.decodeAsset(asset); } assetMap = next; engine.setAssets(assetMap); }
  function changed(options = {}) { engine.setState(state); renderHistory(); if (options.arrangement) renderArrangement(); if (options.mixer) renderMixer(); if (options.rack) renderRack(); if (options.inspector) renderClipInspector(); scheduleAutosave(); }
  function recoveryInfo(message){$('recoveryStatus').hidden=!message;$('recoveryStatus').textContent=message||'';if(message&&!recoveryWarned){recoveryWarned=true;status(message);}}
  function scheduleAutosave(){clearTimeout(autosaveTimer);if(!recovery){recoveryInfo('Browser recovery is off. Save a project to keep this session.');return;}autosaveTimer=setTimeout(()=>{try{const serialized=S.serializeProject(state);if(serialized.length<8*1024*1024){localStorage.setItem('loom-session-v1',serialized);recoveryUnavailable=false;recoveryInfo('');}else{localStorage.removeItem('loom-session-v1');recoveryInfo('This session is too large for browser recovery. Save a project to keep your work.');}}catch(_){recoveryUnavailable=true;recoveryInfo('Browser recovery is unavailable or full. Save a project to keep this session.');}},1600);}
  const snapshotTimers = new Map();
  function scheduleSnapshot(id) { clearTimeout(snapshotTimers.get(id)); const generation = lifecycle; snapshotTimers.set(id, setTimeout(async () => { try { const snapshot = await host.snapshot(id); if (generation !== lifecycle) return; const t = state.tracks.find(t => t.id === id); if (t && t.instrument && snapshot) { t.instrument.snapshot = snapshot; scheduleAutosave(); } } catch (_) {} }, 900)); }
  async function snapshotAll() { for (const t of state.tracks) if (t.instrument && frames.has(t.id)) { try { const snapshot = await host.snapshot(t.id); if (snapshot) t.instrument.snapshot = snapshot; } catch (e) { status('The audio project is safe; one instrument could not provide its current settings. ' + e.message); } } }
  function snap(value) { const step = state.view.snap; return step ? Math.round(value / step) * step : Math.round(value * 1000) / 1000; }
  function selectedTrack(index, options = {}) { state.selectedTrack = index; if (!options.keepClip) selectedClip = null; if (selectedSlot !== null && !track().effects[selectedSlot]) selectedSlot = null; renderTrackHeaders(); renderLanes(); renderMixer(); renderRack(); renderClipInspector(); renderEffectEditor(); scheduleAutosave(); }
  function panLabel(value) { return Math.abs(value) < .01 ? 'C' : Math.round(Math.abs(value) * 100) + (value < 0 ? ' L' : ' R'); }
  function levelLabel(value) { return value <= .0001 ? '−∞ dB' : (20 * Math.log10(value)).toFixed(1) + ' dB'; }
  function effectArt(def, compact = false) {
    const c = def.color, a = def.accent, common = `fill="none" stroke-linecap="round" stroke-linejoin="round"`, g = compact ? '' : ' class="effect-motion"'; let drawing = '';
    if (def.visual === 'facets') drawing = `<path d="M15 94 74 10 142 93 204 32 236 103 15 94 112 52 74 10M74 10 112 52 142 93 204 32M112 52l124 51" stroke="${c}"/><path d="M15 94 142 93 112 52 15 94M142 93 204 32 236 103Z" fill="${c}" fill-opacity=".1" stroke="${a}"/>`;
    else if (def.visual === 'ribbons') drawing = Array.from({length:6},(_,i)=>`<path d="M5 ${25+i*12} C45 ${i%2?111:5},80 ${i%2?2:112},122 ${40+i*6}S200 ${i%2?8:109},245 ${22+i*13}" stroke="${i%2?a:c}" opacity="${.35+i*.11}"/>`).join('');
    else if (def.visual === 'embers') drawing = `<path d="M8 90h20l9-9 9 21 8-51 10 52 10-82 14 71 8-21 9 11 9-49 12 50 10-17 9 42 13-57 12 31 10-12 11 25 10-61 12 48h23" stroke="${c}"/><path d="M8 110h235" stroke="${a}" opacity=".4"/>` + Array.from({length:12},(_,i)=>`<circle cx="${17+i*20}" cy="${18+(i*31)%80}" r="${1.5+i%3}" stroke="${a}" fill="${a}" fill-opacity=".3"/>`).join('');
    else if (def.visual === 'ripples') drawing = Array.from({length:7},(_,i)=>`<path d="M3 ${20+i*14} Q60 ${i%2?70:0},125 ${20+i*14}T247 ${20+i*14}" stroke="${i%2?a:c}" opacity="${.35+i*.08}"/>`).join('');
    else if (def.visual === 'orbits') drawing = Array.from({length:5},(_,i)=>`<ellipse cx="125" cy="63" rx="${24+i*22}" ry="${12+i*10}" transform="rotate(${i*12-24} 125 63)" stroke="${i%2?a:c}" opacity="${1-i*.13}"/>`).join('') + `<circle cx="55" cy="41" r="5" fill="${a}" stroke="${a}"/><circle cx="204" cy="77" r="4" fill="${c}" stroke="${c}"/>`;
    else if (def.visual === 'vaults') drawing = Array.from({length:6},(_,i)=>`<path d="M${10+i*19} 115V${57+i*5} Q125 ${-35+i*19} ${240-i*19} ${57+i*5}V115" stroke="${i%2?a:c}" opacity="${.4+i*.1}"/>`).join('') + `<path d="M10 115h230" stroke="${a}"/>`;
    else if (def.visual === 'haloes') drawing = Array.from({length:5},(_,i)=>`<circle cx="${90+i*17}" cy="${71-i*8}" r="${19+i*7}" stroke="${i%2?a:c}" opacity="${.3+i*.16}"/>`).join('') + `<path d="M7 96Q80 33 127 85T243 40" stroke="${a}" opacity=".4"/>`;
    else drawing = `<path d="M8 100V25h23v75h18V43h23v57h18V25h23v75h18V43h23v57h18V25h23v75h18V43h23v57" stroke="${c}"/><path d="M8 69Q42 5 78 69T150 69T222 69" stroke="${a}" opacity=".8"/>`;
    return `<svg viewBox="0 0 250 125" aria-hidden="true"><g ${common} stroke-width="${compact?5:1.6}"${g}>${drawing}</g></svg>`;
  }
  function instrumentArt(id, color) { let p = ''; if (id === 'haze') p = Array.from({length:20},(_,i)=>`<rect x="${7+i*10}" y="${10+(i*17)%34}" width="7" height="${15+(i*13)%39}" fill="${color}" opacity="${.25+i%4*.15}"/>`).join(''); else if (id === 'bower') p = Array.from({length:4},(_,i)=>`<path d="M5 ${20+i*15}Q60 ${-15+i*16} 115 ${20+i*15}T225 ${20+i*15}"/>`).join(''); else if (id === 'ravel') p = Array.from({length:16},(_,i)=>`<path d="M${9+i*14} 10v60" opacity=".2"/><rect x="${11+i*14}" y="${20+(i*19)%26}" width="9" height="${8+i%4*9}" fill="${color}" fill-opacity=".35"/>`).join(''); else if (id === 'mire') p = `<path d="M0 55Q45 10 95 43T195 35T250 45M0 64Q45 20 95 52T195 44T250 54M0 73Q45 30 95 61T195 53T250 63"/><circle cx="140" cy="32" r="19" opacity=".3"/>`; else if (id === 'tine' || id === 'form') p = Array.from({length:7},(_,i)=>`<ellipse cx="116" cy="42" rx="${21+i*13}" ry="${6+i*4}" opacity="${1-i*.11}"/>`).join(''); else if (id === 'spool') p = `<circle cx="61" cy="40" r="30"/><circle cx="165" cy="40" r="30"/><circle cx="61" cy="40" r="8"/><circle cx="165" cy="40" r="8"/><path d="M61 10h104M61 70h104M61 40l21-21M165 40l-21 21"/>`; else p = Array.from({length:46},(_,i)=>`<path d="M${3+i*5} ${40-(i*17)%29}v${4+(i*19)%52}" opacity="${.3+i%4*.16}"/>`).join(''); return `<svg viewBox="0 0 230 82" aria-hidden="true"><g fill="none" stroke="${color}" stroke-width="1.5">${p}</g></svg>`; }
  function renderTrackHeaders() { $('trackHeaders').innerHTML = state.tracks.map((t,i)=>`<div class="track-header ${i===state.selectedTrack?'selected':''}" data-track="${i}" style="--track:${escape(t.color)}"><div class="track-name-row"><span class="track-number">${String(i+1).padStart(2,'0')}</span><span class="track-name">${escape(t.name)}</span><button class="track-arm" data-arm="${i}" aria-pressed="${t.armed}" aria-label="Arm track ${i+1} for recording"><i></i></button></div><div class="track-lower-row"><button class="instrument-chip" data-instrument="${i}" title="Choose or open this track's instrument">${escape(t.instrument ? t.instrument.name || t.instrument.id.toUpperCase() : '+ Load')}</button><button class="track-ms ${t.mute?'active':''}" data-mute="${i}" aria-pressed="${t.mute}" aria-label="Mute track ${i+1}">M</button><button class="track-ms ${t.solo?'active':''}" data-solo="${i}" aria-pressed="${t.solo}" aria-label="Solo track ${i+1}">S</button><span class="track-fx-dots">${t.effects.map(f=>`<i style="${f?'background:'+effectById(f.type).color:''}"></i>`).join('')}</span></div></div>`).join(''); }
  function timelineWidth() { return Math.max($('timelineScroll').clientWidth, state.lengthBars * 4 * state.view.zoom); }
  function renderArrangement() { renderTrackHeaders(); $('zoom').value = state.view.zoom; $('snap').value = state.view.snap; $('lengthBars').value = state.lengthBars; $('loopStart').value = state.loopStart / 4 + 1; $('loopEnd').value = state.loopEnd / 4 + 1; const width = timelineWidth(); $('timeline').style.width = width + 'px'; $('timeline').style.setProperty('--bar-width', state.view.zoom*4 + 'px'); $('timeline').style.setProperty('--beat-width', state.view.zoom + 'px'); $('ruler').innerHTML = Array.from({length:state.lengthBars},(_,i)=>`<span class="ruler-label" style="left:${i*4*state.view.zoom}px">${String(i+1).padStart(2,'0')}</span>`).join(''); $('loopStrip').innerHTML = state.loopEnabled ? `<div class="loop-region" style="left:${state.loopStart*state.view.zoom}px;width:${(state.loopEnd-state.loopStart)*state.view.zoom}px"></div>` : ''; renderLanes(); renderPlayhead(); }
  function renderLanes() { $('trackLanes').innerHTML = state.tracks.map((t,i)=>`<div class="track-lane ${i===state.selectedTrack?'selected':''}" data-lane="${i}" style="--track:${escape(t.color)}">${!t.clips.length?'<span class="lane-empty">IMPORT AUDIO OR RECORD A TAKE</span>':''}${t.clips.map(c=>`<div class="clip ${c.id===selectedClip?'selected':''}" data-clip="${escape(c.id)}" data-track="${i}" role="button" tabindex="0" aria-label="${escape(c.name)} on track ${i+1}, starts at beat ${c.start+1}, length ${c.length} beats. Arrow keys move; Shift arrows trim." style="left:${c.start*state.view.zoom}px;width:${Math.max(5,c.length*state.view.zoom)}px"><span class="clip-label">${escape(c.name)}${c.reverse?' ↶':''}${c.loop?' ⟳':''}</span><canvas aria-hidden="true"></canvas><i class="clip-edge left" data-edge="left"></i><i class="clip-edge right" data-edge="right"></i></div>`).join('')}</div>`).join(''); requestAnimationFrame(drawWaveforms); }
  function drawWaveforms() { for (const el of $('trackLanes').querySelectorAll('.clip')) { const found = state.tracks[Number(el.dataset.track)].clips.find(c=>c.id===el.dataset.clip), pcm = found && assetMap[found.assetId]; if (!found || !pcm) continue; const canvas = el.querySelector('canvas'), width = Math.max(1,Math.min(2400,Math.floor(el.clientWidth))), height = 32, dpr = Math.min(2,devicePixelRatio || 1); canvas.width = Math.min(8192,width*dpr); canvas.height = height*dpr; const ctx = canvas.getContext('2d'); ctx.scale(dpr,dpr); ctx.strokeStyle = state.tracks[Number(el.dataset.track)].color; ctx.lineWidth = 1; const duration = pcm.left.length / pcm.sampleRate, sourceSpan = Math.max(.0001,found.sourceEnd-found.sourceStart), secondsPerBeat = 60/state.tempo; ctx.beginPath(); const step = Math.max(1,Math.ceil(width/1200)); for (let x=0;x<width;x+=step) { let seconds = x/width * found.length * secondsPerBeat * found.rate; seconds += found.sourceOffset || 0; if (!found.loop && seconds >= sourceSpan) continue; seconds = found.loop ? seconds % sourceSpan : seconds; const position = found.reverse ? found.sourceEnd-seconds : found.sourceStart+seconds; const index = Math.max(0,Math.min(pcm.left.length-1,Math.floor(position*pcm.sampleRate))); const samples = Math.max(1,Math.ceil(pcm.sampleRate*found.length*secondsPerBeat*found.rate/width)); let peak = 0; for (let k=0;k<Math.min(96,samples);k++) { const n = Math.min(pcm.left.length-1,index+Math.floor(k*samples/Math.min(96,samples))); peak = Math.max(peak,Math.abs(pcm.left[n]),Math.abs(pcm.right[n])); } const fade = Math.min(1,(x/width*found.length)/Math.max(.0001,found.fadeIn),((1-x/width)*found.length)/Math.max(.0001,found.fadeOut)), amp = Math.min(1,peak*found.gain)*13*fade; ctx.moveTo(x,16-amp); ctx.lineTo(x,16+amp); } ctx.stroke(); } }
  function renderMixer() { $('mixer').innerHTML = state.tracks.map((t,i)=>`<div class="mixer-channel ${i===state.selectedTrack?'selected':''}" data-channel="${i}" style="--track:${escape(t.color)}"><span class="channel-number">${String(i+1).padStart(2,'0')}</span><div class="channel-name">${escape(t.name)}</div><div class="channel-pan"><label for="pan-${i}">PAN</label><input id="pan-${i}" data-mix="pan" data-track="${i}" type="range" min="-1" max="1" step="0.01" value="${t.pan}"><output>${panLabel(t.pan)}</output></div><div class="fader-wrap"><input class="channel-fader" id="level-${i}" data-mix="level" data-track="${i}" type="range" min="0" max="1.5" step="0.01" value="${t.level}" aria-label="Track ${i+1} level"><div class="channel-meter"><i id="meter-${i}"></i></div></div><output class="channel-db">${levelLabel(t.level)}</output><div class="channel-ms"><button data-mute="${i}" class="${t.mute?'active':''}" aria-pressed="${t.mute}" aria-label="Mute track ${i+1}">M</button><button data-solo="${i}" class="${t.solo?'active':''}" aria-pressed="${t.solo}" aria-label="Solo track ${i+1}">S</button><button data-arm="${i}" class="${t.armed?'active':''}" aria-pressed="${t.armed}" aria-label="Arm track ${i+1}">R</button></div><div class="channel-slots">${t.effects.map((f,s)=>`<button data-effect-track="${i}" data-effect-slot="${s}" title="Track ${i+1}, effect slot ${s+1}${f?': '+effectById(f.type).name:''}" style="${f?'--effect-color:'+effectById(f.type).color:''}">${f?effectById(f.type).name.slice(0,3):'+'}</button>`).join('')}</div></div>`).join(''); $('masterLevel').value=state.master.level; $('masterLevelValue').textContent=Math.round(state.master.level*100)+'%'; }
  function renderRack() { const t=track(); $('trackName').value=t.name;$('trackColor').value=t.color; $('rackTrack').textContent='TRACK '+String(state.selectedTrack+1).padStart(2,'0'); $('rack').innerHTML=t.effects.map((f,i)=>{const def=f&&effectById(f.type);return `<button class="rack-slot ${f?'':'empty'} ${selectedSlot===i?'selected':''}" data-slot="${i}" style="${def?'--effect-color:'+def.color:''}"><span class="slot-index">${i+1}</span>${def?`<span class="slot-tiny-art">${effectArt(def,true)}</span><span class="slot-name"><strong>${def.name}</strong><small>${escape(def.description)}</small></span>${f.params.bypass?'<span class="slot-bypass">BYPASSED</span>':'<span class="slot-arrow">↗</span>'}`:'<span class="slot-name">Add an effect</span><span class="slot-arrow">+</span>'}</button>`;}).join(''); $('trackInstrumentName').textContent=t.instrument ? t.instrument.name||t.instrument.id.toUpperCase() : 'No instrument loaded'; $('openInstrumentButton').hidden=!t.instrument; const browseLabel=t.instrument?'Replace instrument':'Choose instrument';if($('browseInstrumentButton').textContent!==browseLabel)$('browseInstrumentButton').textContent=browseLabel; $('instrumentLive').checked=t.instrumentLive; $('instrumentLive').disabled=!t.instrument; }
  function controlMarkup(key,label,value,options={}) { const attrs = options.min !== undefined ? `min="${options.min}" max="${options.max}" step="${options.step||.001}"` : ''; if (options.type==='checkbox') return `<div class="control check-control"><label><input data-clip-param="${key}" type="checkbox" ${value?'checked':''}>${label}</label></div>`; return `<div class="control"><label for="clip-${key}">${label}</label><input id="clip-${key}" data-clip-param="${key}" type="${options.type||'number'}" ${attrs} value="${escape(value)}" ${options.maxlength?'maxlength="'+options.maxlength+'"':''}></div>`; }
  function renderClipInspector() { const location = clipLocation(); $('clipInspector').hidden=!location; if (!location) { $('selectionSummary').textContent='Choose a clip to edit it, or load an instrument into a track.'; return; } const c=location.clip, asset=assetMap[c.assetId], duration=asset?asset.left.length/asset.sampleRate:120; $('selectionSummary').textContent=c.name+' · '+location.track.name+' · '+c.length.toFixed(2)+' beats'; $('clipControls').innerHTML=controlMarkup('name','CLIP NAME',c.name,{type:'text',maxlength:80})+controlMarkup('start','START (BEAT)',c.start+1,{min:1,max:state.lengthBars*4,step:.001})+controlMarkup('length','LENGTH (BEATS)',c.length,{min:.015625,max:state.lengthBars*4,step:.001})+controlMarkup('sourceStart','SOURCE IN (SEC)',c.sourceStart,{min:0,max:duration,step:.001})+controlMarkup('sourceEnd','SOURCE OUT (SEC)',c.sourceEnd,{min:0,max:duration,step:.001})+controlMarkup('rate','SPEED / PITCH',c.rate,{min:.125,max:8,step:.01})+controlMarkup('gain','CLIP LEVEL',c.gain,{min:0,max:2,step:.01})+controlMarkup('fadeIn','FADE IN (BEATS)',c.fadeIn,{min:0,max:c.length/2,step:.01})+controlMarkup('fadeOut','FADE OUT (BEATS)',c.fadeOut,{min:0,max:c.length/2,step:.01})+controlMarkup('reverse','Reverse',c.reverse,{type:'checkbox'})+controlMarkup('loop','Loop source',c.loop,{type:'checkbox'}); }
  function renderEffectEditor() { const slot=selectedSlot!==null&&track().effects[selectedSlot]; $('effectEditor').hidden=!slot; if(!slot)return; const def=effectById(slot.type); $('effectEditor').style.setProperty('--effect-color',def.color); $('effectEditor').innerHTML=`<div class="effect-editor-layout"><div class="effect-hero"><span class="eyebrow">INSERT ${selectedSlot+1} / TRACK ${String(state.selectedTrack+1).padStart(2,'0')}</span><h2>${def.name}</h2><p>${escape(def.subtitle)}</p><div class="effect-art">${effectArt(def)}</div><div class="effect-info">${escape(def.description)}</div></div><div class="effect-right"><div class="effect-toolbar"><span>${slot.params.bypass?'BYPASSED':'PROCESSING IN STEREO'}</span><div><button id="effectBypass" class="${slot.params.bypass?'bypassed':''}" aria-pressed="${slot.params.bypass}">Bypass</button><button id="effectReset">Reset</button><button id="effectUp" ${selectedSlot===0?'disabled':''}>Move ↑</button><button id="effectDown" ${selectedSlot===3?'disabled':''}>Move ↓</button><button id="effectReplace">Replace</button><button id="effectRemove">Remove</button></div></div><div class="effect-controls">${def.params.map(p=>p.type==='select'?`<div class="control"><label for="fx-${p.key}">${p.label}</label><select id="fx-${p.key}" data-effect-param="${p.key}">${p.options.map(o=>`<option value="${escape(o.value)}" ${o.value===slot.params[p.key]?'selected':''}>${escape(o.label)}</option>`).join('')}</select></div>`:`<div class="control"><label for="fx-${p.key}">${p.label}<output>${formatParam(p,slot.params[p.key])}</output></label>${effectRange(p,slot.params[p.key])}</div>`).join('')}</div></div></div>`; }
  function effectRange(p,value){const log=p.unit==='Hz'&&p.max/p.min>8;return `<input id="fx-${p.key}" data-effect-param="${p.key}" ${log?'data-log="true"':''} type="range" min="${log?0:p.min}" max="${log?1:p.max}" step="${log?.001:p.step}" value="${log?Math.log(value/p.min)/Math.log(p.max/p.min):value}">`;}
  function formatParam(p,value) { if (p.key==='mix'||['depth','spread','width','size','diffusion','pan','duty'].includes(p.key)) return Math.round(value*100)+'%'; if(p.unit==='Hz'&&value>=1000)return (value/1000).toFixed(value>=10000?1:2)+' kHz'; if(p.unit===':1')return Number(value).toFixed(1)+':1'; if(p.unit==='dB')return (value>0?'+':'')+Number(value).toFixed(1)+' dB'; const decimals=p.step>=1?0:p.step>=.1?1:2; return Number(value).toFixed(decimals)+(p.unit?' '+p.unit:''); }
  function renderTransport() { const m=engine.getMeters(), recording=!!m.recording; const playMode=m.playing?'pause':'play';if($('playButton').dataset.mode!==playMode){$('playButton').dataset.mode=playMode;$('playButton').innerHTML=(m.playing?icons.pause:icons.play)+`<span>${m.playing?'Pause':'Play'}</span>`;} $('playButton').setAttribute('aria-label',m.playing?'Pause':'Play');$('playButton').disabled=transportPending; $('recordButton').classList.toggle('recording',recording); const recordMode=recording?'recording':recordPending?'preparing':'ready';if($('recordButton').dataset.mode!==recordMode){$('recordButton').dataset.mode=recordMode;$('recordButton').innerHTML='<i></i><span>'+(recording?'Finish take':recordPending?'Preparing…':'Record')+'</span>';} $('recordButton').disabled=recordPending||recordFinishing; if(document.activeElement!==$('tempo'))$('tempo').value=state.tempo; $('loopButton').setAttribute('aria-pressed',state.loopEnabled); $('metronomeButton').setAttribute('aria-pressed',state.master.metronome); }
  function renderPlayhead() { const m=engine.getMeters(); $('playhead').style.left=(m.beat||0)*state.view.zoom+'px'; }
  function renderAll() { $('projectName').value=state.name; $('autosaveEnabled').checked=recovery; renderArrangement(); renderMixer(); renderRack(); renderClipInspector(); renderEffectEditor(); renderTransport(); renderHistory(); }
  function makeFrame(id) { let frame=frames.get(id); if(!frame){frame=document.createElement('iframe');frame.dataset.hostTrack=id;frame.title='Instrument editor for '+state.tracks.find(t=>t.id===id).name;frame.setAttribute('allow','autoplay');frame.hidden=true;$('instrumentFrames').append(frame);frames.set(id,frame);}return frame; }
  function showFrame(id) { if(frameTrack&&frameTrack!==id)engine.clearAudition(frameTrack);frameTrack=id;for(const [key,frame]of frames)frame.hidden=key!==id;$('instrumentBrowser').hidden=true;$('instrumentEditorBar').hidden=false;$('instrumentFrames').hidden=false;const t=state.tracks.find(t=>t.id===id);$('instrumentEditorName').textContent=t.instrument.name||t.instrument.id.toUpperCase();$('instrumentDialogTitle').textContent=t.name+' / instrument editor';engine.resumeAudition(id); }
  function closeInstrument() { if(frameTrack)engine.clearAudition(frameTrack);frameTrack=null;$('instrumentDialog').close(); }
  function instrumentOptions() { return [...(window.LoomInstrumentManifest||host.manifest||[]),...customManifest]; }
  function renderInstrumentBrowser() { const i=browserTrack===null?state.selectedTrack:browserTrack;$('instrumentDialogTitle').textContent='Choose a voice for track '+String(i+1).padStart(2,'0')+'.';$('instrumentGrid').innerHTML=instrumentOptions().map((app,index)=>`<button class="instrument-card" data-app="${index}" style="--app-color:${app.color||'#dce89b'}"><span class="eyebrow">${index<8?'MUSIC LAB / BUNDLED':'MUSIC LAB / DISCOVERED'}</span><h3>${escape(app.name||app.id.toUpperCase())}</h3><div class="instrument-art">${instrumentArt(app.id,app.color||'#dce89b')}</div><p>${escape(app.description||'A browser instrument from the Music Lab.')}</p><span class="instrument-open">LOAD INTO TRACK ${String(i+1).padStart(2,'0')} ↗</span></button>`).join(''); }
  async function discoverInstruments() { if(discoveryDone||location.protocol==='file:')return;discoveryDone=true;try{const hub=new URL('../index.html',location.href),response=await fetch(hub,{credentials:'same-origin'});if(!response.ok)return;const doc=new DOMParser().parseFromString(await response.text(),'text/html');const known=new Set(instrumentOptions().map(a=>a.id));for(const a of doc.querySelectorAll('.instrument .open-app')){const url=new URL(a.getAttribute('href'),hub);if(url.origin!==location.origin)continue;const match=url.pathname.match(/\/music\/([a-z0-9-]+)\/(?:index\.html)?$/i);if(!match||match[1]==='loom'||known.has(match[1]))continue;const id=match[1];known.add(id);const card=a.closest('.instrument');customManifest.push({id,name:card.querySelector('h2,h3')?.textContent?.trim()||id.toUpperCase(),url:url.href,color:'#b9ced7',description:'A newer Music Lab instrument. Editor-controlled transport until its host API is registered.'});}renderInstrumentBrowser();}catch(_){} }
  function openInstrumentBrowser(index=state.selectedTrack) { browserTrack=index;if(frameTrack)engine.clearAudition(frameTrack);frameTrack=null;$('instrumentBrowser').hidden=false;$('instrumentEditorBar').hidden=true;$('instrumentFrames').hidden=true;renderInstrumentBrowser();if(!$('instrumentDialog').open)$('instrumentDialog').showModal();discoverInstruments(); }
  async function ensureInstrument(t,{open=false,replace=false,descriptor=null}={}) { const id=t.id,operation=(loadOperations.get(id)||0)+1;loadOperations.set(id,operation);const generation=lifecycle;if(descriptor){if(replace){remember();if(frames.has(id)){host.unload(id);frames.get(id).remove();frames.delete(id);openedApps.delete(id);}t.instrument=clone(descriptor);changed({arrangement:true,rack:true});}else t.instrument=clone(descriptor);}if(!t.instrument)throw Error('Choose an instrument for '+t.name+' first.');await engine.init();if(generation!==lifecycle||operation!==loadOperations.get(id))return false;const frame=makeFrame(id),identity=t.instrument.html||t.instrument.url||t.instrument.id;if(open){showFrame(id);if(!$('instrumentDialog').open)$('instrumentDialog').showModal();$('instrumentHostStatus').textContent='Preparing the instrument and audio bridge…';}if(openedApps.get(id)!==identity){const result=await host.load(id,{id:t.instrument.id,name:t.instrument.name,url:t.instrument.url,html:t.instrument.html,state:t.instrument.snapshot},frame);if(generation!==lifecycle||operation!==loadOperations.get(id))return false;openedApps.set(id,identity);const capabilities=result&&result.capabilities;const transport=capabilities&&typeof capabilities==='object'?capabilities.transport:undefined;if(open)$('instrumentHostStatus').textContent=transport===false?'Editor-controlled transport · play the app, then Record its track.':'Instrument ready · output is routed through this track.';}else if(open)$('instrumentHostStatus').textContent=host.capabilities(id).transport?'Instrument ready · your previous settings are intact.':'Editor-controlled transport · play the app, then Record its track.';return true; }
  async function openExisting(index=state.selectedTrack) { selectedTrack(index);const t=track();if(!t.instrument){openInstrumentBrowser(index);return;}browserTrack=index;try{await ensureInstrument(t,{open:true});}catch(e){status(e.message);$('instrumentHostStatus').textContent=e.message;} }
  function clearAllFrames() { for(const id of frames.keys()){host.unload(id);frames.get(id).remove();engine.clearAudition(id);}frames.clear();openedApps.clear();loadOperations.clear();frameTrack=null; }
  function fireCommand(id,command,payload){const generation=lifecycle;return host.command(id,command,payload).catch(e=>{if(generation===lifecycle)status('Instrument '+command+': '+e.message);return false;});}
  async function transportStart() { if(transportPending)return;if(engine.getMeters().playing){await stop();return;}const operation=++transportOperation,generation=lifecycle;transportPending=true;renderTransport();try{await engine.init();const live=state.tracks.filter(t=>t.instrument&&t.instrumentLive);await Promise.all(live.map(async t=>{const ready=await ensureInstrument(t);if(ready)await host.command(t.id,'prepare');}));if(operation!==transportOperation||generation!==lifecycle)return;await host.setTempo(state.tempo);if(operation!==transportOperation||generation!==lifecycle)return;const started=await engine.play();if(!started||operation!==transportOperation||generation!==lifecycle)return;for(const t of live)fireCommand(t.id,'start');status('Eight threads in motion. The committee is delighted.');}catch(e){if(operation===transportOperation)status(e.message);}finally{if(operation===transportOperation){transportPending=false;renderTransport();}} }
  async function stop() { ++transportOperation;transportPending=false;engine.stop();for(const t of state.tracks)if(t.instrument&&frames.has(t.id))fireCommand(t.id,'stop');if(engine.getMeters().recording)await finishRecording();else{recordPending=false;status('Stopped. The threads are considering their next move.');}renderTransport(); }
  function panic(message='Silence. Pending recordings have been discarded.') { ++lifecycle;++recordFinishOperation;++importOperation;++projectOperation;++transportOperation;for(const [id,op]of loadOperations)loadOperations.set(id,op+1);recordPending=false;transportPending=false;recordFinishing=false;engine.panic();for(const t of state.tracks)if(t.instrument&&frames.has(t.id))fireCommand(t.id,'panic');for(const id of armedBeforeRecord.keys())engine.clearAudition(id);armedBeforeRecord.clear();renderTransport();status(message); }
  async function startRecording() { if(recordPending||recordFinishing)return;if(engine.getMeters().recording){await stop();return;}const source=$('recordSource').value,operation=++transportOperation,generation=lifecycle;recordPending=true;renderTransport();try{await engine.init();if(operation!==transportOperation||generation!==lifecycle)return;const used=state.assets.reduce((total,a)=>total+a.frames*a.channels*2,0),budgetBytes=Math.max(0,64*1024*1024-used);if(budgetBytes<48000*4)throw Error('This project has reached its audio memory limit. Start a new session or remove unused audio.');if(source==='microphone'){if(track().clips.length>=128)throw Error('This track has reached its 128-clip limit. Remove a clip before recording.');const started=await engine.startMicrophoneRecording(track().id,{maxSeconds:Math.min(120,(256-(engine.getMeters().beat||0))*60/state.tempo),budgetBytes,startTransport:true});if(started&&operation===transportOperation&&generation===lifecycle)status('Recording your microphone without monitoring it. Stop finishes the take; Panic discards it.');return;}let armed=state.tracks.filter(t=>t.armed&&t.instrument);if(!armed.length&&track().instrument){remember();track().armed=true;armed=[track()];renderTrackHeaders();renderMixer();}if(!armed.length)throw Error('Choose an instrument, then arm its track before recording.');if(armed.some(t=>t.clips.length>=128))throw Error('An armed track has reached its 128-clip limit. Remove a clip or disarm it before recording.');await Promise.all(armed.map(async t=>{if(await ensureInstrument(t))await host.command(t.id,'prepare');}));if(operation!==transportOperation||generation!==lifecycle)return;await host.setTempo(state.tempo);if(operation!==transportOperation||generation!==lifecycle)return;for(const t of armed){armedBeforeRecord.set(t.id,t.instrumentLive);engine.resumeAudition(t.id);}const started=await engine.startRecording(armed.map(t=>t.id),{maxSeconds:Math.min(120,(256-(engine.getMeters().beat||0))*60/state.tempo),budgetBytes,startTransport:true});if(!started||operation!==transportOperation||generation!==lifecycle)return;for(const t of armed)fireCommand(t.id,'start');status('Recording '+armed.map(t=>t.name).join(', ')+'. Stop turns the performance into editable clips.');}catch(e){if(operation===transportOperation){engine.cancelRecording();for(const id of armedBeforeRecord.keys())engine.clearAudition(id);armedBeforeRecord.clear();status(e.message);}}finally{if(operation===transportOperation){recordPending=false;renderTransport();}} }
  async function finishRecording(limited=false){
    if(recordFinishing)return;recordFinishing=true;recordPending=false;const generation=lifecycle,operation=++recordFinishOperation;renderTransport();
    try{
      const takes=await engine.stopRecording();if(generation!==lifecycle||operation!==recordFinishOperation)return;
      if(!takes||!takes.length){status('That take was empty. Play an instrument and try again.');return;}
      const snapshots=await Promise.all(takes.map(async take=>{const t=state.tracks.find(t=>t.id===take.trackId);if(!t?.instrument||!frames.has(t.id))return null;try{return await host.snapshot(t.id);}catch(_){return null;}}));
      if(generation!==lifecycle||operation!==recordFinishOperation)return;
      remember();for(let i=0;i<takes.length;i++){
        const take=takes[i];if(!take.frames||take.frames<128)continue;const t=state.tracks.find(t=>t.id===take.trackId);if(!t)continue;
        if(t.clips.length>=128){status(t.name+' has reached its clip limit. Remove a clip before recording again.');continue;}
        const asset=S.encodeAsset({left:take.left,right:take.right,sampleRate:take.sampleRate,name:t.name+' — take '+(t.clips.length+1)});state.assets.push(asset);
        const length=take.frames/take.sampleRate*state.tempo/60,start=Math.max(0,take.startBeat||0);state.lengthBars=Math.max(state.lengthBars,Math.min(64,Math.ceil((start+length)/4)));
        const c={id:S.uid('clip'),name:asset.name,assetId:asset.id,start,length:Math.max(.015625,Math.min(length,state.lengthBars*4-start)),sourceStart:0,sourceEnd:take.frames/take.sampleRate,sourceOffset:0,rate:1,reverse:false,loop:false,gain:1,fadeIn:.01,fadeOut:.03};
        t.clips.push(c);selectedClip=c.id;state.selectedTrack=state.tracks.indexOf(t);if(t.instrument&&snapshots[i])t.instrument.snapshot=snapshots[i];
      }
      state=S.normalize(state);decodeAssets();changed({arrangement:true,mixer:true,rack:true,inspector:true});status(limited?'The recording limit was reached. Your complete take is in the arrangement.':'Take printed. Move, trim, split, or add effects to the new clip.');
    }catch(e){if(generation===lifecycle)status(e.message);}
    finally{if(operation===recordFinishOperation){for(const id of armedBeforeRecord.keys())if(id!==frameTrack)engine.clearAudition(id);armedBeforeRecord.clear();recordFinishing=false;renderTransport();}}
  }
  engine.onRecordingLimit=()=>{engine.stop();for(const t of state.tracks)if(t.instrument&&frames.has(t.id))fireCommand(t.id,'stop');finishRecording(true);};
  async function replaceState(next,{message='Project opened.',undo=false}={}) { const old=state;++lifecycle;++projectOperation;++importOperation;++transportOperation;exportAbort?.abort();panic('');if(!undo)remember();clearAllFrames();if($('instrumentDialog').open)closeInstrument();state=S.normalize(next);host.setTempo(state.tempo);selectedClip=null;selectedSlot=null;assetMap={};decodeAssets();engine.setState(state);engine.seek(0);renderAll();scheduleAutosave();status(message); }
  function historyState(next,message){
    const previous=state,normalized=S.normalize(next),playing=engine.getMeters().playing;const identity=t=>t.instrument&&(t.instrument.html||t.instrument.url||t.instrument.id);
    ++lifecycle;++importOperation;++projectOperation;++transportOperation;exportAbort?.abort();transportPending=false;if(recordPending){engine.cancelRecording();recordPending=false;}
    for(let i=0;i<8;i++){
      const old=previous.tracks[i],t=normalized.tracks[i];
      if(identity(old)===identity(t)&&t.instrument){if(old.instrument.snapshot)t.instrument.snapshot=clone(old.instrument.snapshot);}
      else if(frames.has(old.id)){host.unload(old.id);frames.get(old.id).remove();frames.delete(old.id);openedApps.delete(old.id);engine.clearAudition(old.id);loadOperations.set(old.id,(loadOperations.get(old.id)||0)+1);if(frameTrack===old.id){frameTrack=null;$('instrumentDialog').close();}}
      if(playing&&frames.has(t.id)&&old.instrumentLive&&!t.instrumentLive)fireCommand(t.id,'stop');
    }
    state=normalized;host.setTempo(state.tempo);decodeAssets();engine.setState(state);if(!clipLocation())selectedClip=null;if(selectedSlot!==null&&!track().effects[selectedSlot])selectedSlot=null;renderAll();scheduleAutosave();status(message);
    if(playing){const generation=lifecycle;for(let i=0;i<8;i++){const t=state.tracks[i];if(t.instrument&&t.instrumentLive&&!previous.tracks[i].instrumentLive){ensureInstrument(t).then(async ready=>{if(ready&&generation===lifecycle){await host.command(t.id,'prepare');if(generation===lifecycle&&engine.getMeters().playing)fireCommand(t.id,'start');}}).catch(e=>status(e.message));}}}
  }
  function undo(){if(recordFinishing){status('Finishing this take. Undo will be available in a moment.');return;}if(!history.length)return;const next=history.pop();future.push(clone(state));historyState(next,'The previous tangle has returned.');}
  function redo(){if(recordFinishing){status('Finishing this take. Redo will be available in a moment.');return;}if(!future.length)return;const next=future.pop();history.push(clone(state));historyState(next,'The next tangle has returned.');}
  function removeClip() { const location=clipLocation();if(!location)return;remember();location.track.clips=location.track.clips.filter(c=>c.id!==selectedClip);selectedClip=null;state=S.pruneAssets(state);decodeAssets();changed({arrangement:true,inspector:true});status('Clip removed. Undo will bring it back.'); }
  function duplicateClip() { const location=clipLocation();if(!location)return;if(location.track.clips.length>=128){status('This track has reached its 128-clip limit.');return;}const c=location.clip,start=snap(c.start+c.length);if(start>=state.lengthBars*4){status('Increase the session length to make room for a duplicate.');return;}remember();const copy={...clone(c),id:S.uid('clip'),start,length:Math.min(c.length,state.lengthBars*4-start),name:c.name+' copy'};location.track.clips.push(copy);selectedClip=copy.id;changed({arrangement:true,inspector:true});status('A second piece, just beside the first.'); }
  function splitClip() { const location=clipLocation();if(!location)return;const c=location.clip,point=snap(engine.getMeters().beat||0);if(point<=c.start+.015625||point>=c.start+c.length-.015625){status('Move the playhead inside the selected clip, then split.');return;}if(location.track.clips.length>=128){status('This track has reached its 128-clip limit.');return;}remember();const leftLength=point-c.start,rawOffset=(c.sourceOffset||0)+leftLength*60/state.tempo*c.rate,offset=c.loop?rawOffset%Math.max(.000001,c.sourceEnd-c.sourceStart):rawOffset,right={...clone(c),id:S.uid('clip'),start:point,length:c.length-leftLength,sourceOffset:offset,fadeIn:0,name:c.name+' / II'};c.length=leftLength;c.fadeOut=0;location.track.clips.push(right);selectedClip=right.id;changed({arrangement:true,inspector:true});status('One sound, now in two agreeable pieces.'); }
  async function importAudio(file) { if(!file)return;if(file.size>64*1024*1024){status('Choose an audio file smaller than 64 MB. A clip can hold up to two minutes.');return;}const generation=lifecycle,operation=++importOperation,target=track().id;status('Decoding audio locally…');try{const context=await engine.init(),bytes=await file.arrayBuffer();if(generation!==lifecycle||operation!==importOperation)return;const audio=await context.decodeAudioData(bytes);if(generation!==lifecycle||operation!==importOperation)return;const framesCount=Math.min(audio.length,Math.floor(audio.sampleRate*120)),left=new Float32Array(audio.getChannelData(0).subarray(0,framesCount)),right=new Float32Array(audio.getChannelData(Math.min(1,audio.numberOfChannels-1)).subarray(0,framesCount));const asset=S.encodeAsset({left,right,sampleRate:audio.sampleRate,name:file.name.replace(/\.[^.]+$/,'')||'Imported audio'}),t=state.tracks.find(t=>t.id===target);if(t.clips.length>=128)throw Error('This track has reached its 128-clip limit.');const used=state.assets.reduce((sum,a)=>sum+a.frames*a.channels*2,0);if(used+asset.frames*asset.channels*2>64*1024*1024)throw Error('This audio would exceed the project’s 64 MB audio budget.');const start=Math.min(state.lengthBars*4-.015625,Math.max(0,snap(engine.getMeters().beat||0))),duration=framesCount/audio.sampleRate;remember();state.lengthBars=Math.max(state.lengthBars,Math.min(64,Math.ceil((start+duration*state.tempo/60)/4)));state.assets.push(asset);const c={id:S.uid('clip'),name:asset.name,assetId:asset.id,start,length:Math.min(duration*state.tempo/60,state.lengthBars*4-start),sourceStart:0,sourceEnd:duration,sourceOffset:0,rate:1,reverse:false,loop:false,gain:1,fadeIn:.01,fadeOut:.03};t.clips.push(c);state.selectedTrack=state.tracks.indexOf(t);selectedClip=c.id;decodeAssets();changed({arrangement:true,mixer:true,rack:true,inspector:true});status(file.name+' is in the arrangement'+(audio.length>framesCount?' (first two minutes retained).':'.')+(duration*state.tempo/60>c.length+.001?' The full source is retained; the visible clip ends at the 64-bar session limit.':''));}catch(e){if(generation===lifecycle&&operation===importOperation)status('Audio import: '+e.message);} }
  async function saveProject() { const generation=lifecycle,operation=++projectOperation;status('Gathering the instruments’ settings…');$('saveButton').disabled=true;try{if(engine.getMeters().recording)await stop();await snapshotAll();if(generation!==lifecycle||operation!==projectOperation)return;download(new Blob([S.serializeProject(state)],{type:'application/json'}),filename('.loom.json'));status('Project saved, including audio and instrument settings.');}catch(e){if(generation===lifecycle)status(e.message);}finally{$('saveButton').disabled=false;} }
  async function openProject(file) { if(!file)return;if(file.size>256*1024*1024){status('Choose a LOOM project smaller than 256 MB.');return;}const generation=lifecycle,operation=++projectOperation;status('Reading the project…');try{const next=S.parseProject(await file.text());if(generation!==lifecycle||operation!==projectOperation)return;await replaceState(next,{message:'Project opened. All eight threads remember.'});}catch(e){if(generation===lifecycle&&operation===projectOperation)status(e.message);} }
  function openEffects(slot,index=state.selectedTrack) { selectedTrack(index,{keepClip:true});selectedSlot=slot;$('effectGrid').innerHTML=effects.map(def=>`<button class="effect-choice" data-add-effect="${def.id}" style="--effect-color:${def.color}"><div class="effect-art">${effectArt(def)}</div><h3>${def.name}</h3><p>${escape(def.description)}</p><span class="effect-type">INSERT ${slot+1} / TRACK ${String(index+1).padStart(2,'0')} ↗</span></button>`).join('');$('effectDialog').showModal(); }
  function selectEffect(slot,index=state.selectedTrack) { selectedTrack(index,{keepClip:true});selectedSlot=slot;if(!track().effects[slot]){openEffects(slot,index);return;}renderRack();renderEffectEditor();$('effectEditor').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'nearest'}); }
  function changeEffect(action) { const t=track(),slot=t.effects[selectedSlot];if(!slot)return;remember();if(action==='bypass')slot.params.bypass=!slot.params.bypass;if(action==='reset')slot.params=clone(effectById(slot.type).defaults);if(action==='remove'){t.effects[selectedSlot]=null;selectedSlot=null;}if(action==='up'&&selectedSlot>0){[t.effects[selectedSlot-1],t.effects[selectedSlot]]=[slot,t.effects[selectedSlot-1]];selectedSlot--;}if(action==='down'&&selectedSlot<3){[t.effects[selectedSlot+1],t.effects[selectedSlot]]=[slot,t.effects[selectedSlot+1]];selectedSlot++;}changed({arrangement:true,mixer:true,rack:true});renderEffectEditor(); }
  const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1));return c>>>0;});
  function canceledError(){const error=new Error('Render canceled.');error.name='AbortError';return error;}
  async function crc32(bytes,signal){let c=0xffffffff;for(let start=0;start<bytes.length;start+=262144){if(signal?.aborted)throw canceledError();const end=Math.min(bytes.length,start+262144);for(let i=start;i<end;i++)c=crcTable[(c^bytes[i])&255]^(c>>>8);await new Promise(resolve=>setTimeout(resolve,0));}return(c^0xffffffff)>>>0;}
  async function zipStored(files,signal,onProgress){const encoder=new TextEncoder(),parts=[],directory=[];let offset=0;for(let i=0;i<files.length;i++){if(signal?.aborted)throw canceledError();const file=files[i],data=new Uint8Array(await file.blob.arrayBuffer()),name=encoder.encode(file.name),crc=await crc32(data,signal),local=new Uint8Array(30+name.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,0x5c21,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);local.set(name,30);parts.push(local,data);const central=new Uint8Array(46+name.length),c=new DataView(central.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint16(14,0x5c21,true);c.setUint32(16,crc,true);c.setUint32(20,data.length,true);c.setUint32(24,data.length,true);c.setUint16(28,name.length,true);c.setUint32(42,offset,true);central.set(name,46);directory.push(central);offset+=local.length+data.length;onProgress?.((i+1)/files.length);}if(signal?.aborted)throw canceledError();const centralSize=directory.reduce((n,a)=>n+a.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);return new Blob([...parts,...directory,end],{type:'application/zip'});}
  async function renderExport() { if(exportAbort)return;const generation=lifecycle,controller=new AbortController();exportAbort=controller;$('renderButton').disabled=true;$('cancelExport').hidden=false;$('closeExport').disabled=true;$('exportProgress').hidden=false;$('exportProgress').value=0;const mode=$('exportMode').value,range=$('exportRange').value,tail=Number($('exportTail').value),exportState=clone(state),startBeat=range==='loop'?state.loopStart:0,endBeat=range==='loop'?state.loopEnd:state.lengthBars*4,ids=mode==='all'?state.tracks.map(t=>t.id):[mode==='stem'?track().id:null];$('exportSummary').textContent='Rendering '+(mode==='all'?'eight stems':'stereo audio')+'…';try{const files=[];for(let i=0;i<ids.length;i++){const blob=await engine.renderWav(exportState,assetMap,{startBeat,endBeat,tailSeconds:tail,trackId:ids[i],signal:controller.signal,onProgress:p=>{$('exportProgress').value=(i+p)/ids.length*(mode==='all'?.9:1);}});if(generation!==lifecycle||controller.signal.aborted)return;const t=ids[i]&&exportState.tracks.find(t=>t.id===ids[i]);files.push({blob,name:filename(t?'-'+String(exportState.tracks.indexOf(t)+1).padStart(2,'0')+'-'+t.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.wav':'-mix.wav')});}if(mode==='all'){$('exportSummary').textContent='Packing eight stems into one ZIP…';const zip=await zipStored(files,controller.signal,p=>{$('exportProgress').value=.9+p*.1;});if(generation!==lifecycle||controller.signal.aborted)return;download(zip,filename('-eight-stems.zip'));}else download(files[0].blob,files[0].name);$('exportSummary').textContent=mode==='all'?'Eight stereo stems downloaded in one ZIP.':'Stereo WAV downloaded.';status('The tangle has become a '+(mode==='all'?'bundle of eight stems.':'stereo WAV.'));}catch(e){$('exportSummary').textContent=e.name==='AbortError'?'Render canceled.':e.message;status(e.name==='AbortError'?'WAV render canceled.':e.message);}finally{if(exportAbort===controller)exportAbort=null;$('renderButton').disabled=false;$('cancelExport').hidden=true;$('closeExport').disabled=false;} }
  function selectClipElement(el) { const i=Number(el.dataset.track);state.selectedTrack=i;selectedClip=el.dataset.clip;for(const c of $('trackLanes').querySelectorAll('.clip'))c.classList.toggle('selected',c===el);for(const lane of $('trackLanes').querySelectorAll('.track-lane'))lane.classList.toggle('selected',Number(lane.dataset.lane)===i);renderTrackHeaders();renderMixer();renderRack();renderClipInspector();renderEffectEditor(); }
  $('trackLanes').addEventListener('pointerdown',e=>{const el=e.target.closest('.clip');if(!el){const lane=e.target.closest('[data-lane]');if(lane){selectedTrack(Number(lane.dataset.lane));engine.seek(snap((e.clientX-$('timeline').getBoundingClientRect().left)/state.view.zoom));renderPlayhead();}return;}if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();selectClipElement(el);const c=clipLocation().clip;drag={pointer:e.pointerId,element:el,original:clone(c),trackIndex:state.selectedTrack,startX:e.clientX,startY:e.clientY,mode:e.target.dataset.edge||'move',remembered:false};el.setPointerCapture(e.pointerId);});
  $('trackLanes').addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;const dx=e.clientX-drag.startX;if(!drag.remembered&&Math.abs(dx)<3&&Math.abs(e.clientY-drag.startY)<7)return;if(!drag.remembered){remember();drag.remembered=true;}const c=clipLocation().clip,o=drag.original,delta=snap(dx/state.view.zoom),min=1/64,secondsPerBeat=60/state.tempo;if(drag.mode==='move'){c.start=num(snap(o.start+delta),0,state.lengthBars*4-o.length);const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-lane]');if(target){drag.targetIndex=Number(target.dataset.lane);if(drag.element.parentElement!==target)target.append(drag.element);}}else if(drag.mode==='right'){c.length=num(snap(o.length+delta),min,state.lengthBars*4-o.start);c.fadeIn=Math.min(o.fadeIn,c.length/2);c.fadeOut=Math.min(o.fadeOut,c.length/2);}else{const first=o.loop?0:o.start-Math.min(o.start,(o.sourceOffset||0)/secondsPerBeat/o.rate),next=num(snap(o.start+delta),first,o.start+o.length-min);c.start=next;c.length=o.start+o.length-next;c.sourceOffset=(o.sourceOffset||0)+(next-o.start)*secondsPerBeat*o.rate;if(c.loop){const span=Math.max(.000001,c.sourceEnd-c.sourceStart);c.sourceOffset=((c.sourceOffset%span)+span)%span;}else c.sourceOffset=Math.max(0,c.sourceOffset);c.fadeIn=Math.min(o.fadeIn,c.length/2);c.fadeOut=Math.min(o.fadeOut,c.length/2);}drag.element.style.left=c.start*state.view.zoom+'px';drag.element.style.width=Math.max(5,c.length*state.view.zoom)+'px';engine.setState(state);renderClipInspector();});
  function finishDrag(e) { if(!drag||e.pointerId!==drag.pointer)return;const completed=drag;drag=null;if(completed.remembered&&completed.mode==='move'&&completed.targetIndex!==undefined&&completed.targetIndex!==completed.trackIndex){const source=state.tracks[completed.trackIndex],target=state.tracks[completed.targetIndex],c=source.clips.find(c=>c.id===selectedClip);if(target.clips.length>=128){Object.assign(c,completed.original);status('That track has reached its clip limit.');}else{source.clips=source.clips.filter(c=>c.id!==selectedClip);target.clips.push(c);state.selectedTrack=completed.targetIndex;}}changed({arrangement:true,mixer:true,rack:true,inspector:true}); }
  $('trackLanes').addEventListener('pointerup',finishDrag);$('trackLanes').addEventListener('pointercancel',e=>{if(drag&&e.pointerId===drag.pointer){const c=clipLocation()?.clip;if(c)Object.assign(c,drag.original);drag=null;changed({arrangement:true,inspector:true});}});
  $('trackLanes').addEventListener('keydown',e=>{const el=e.target.closest('.clip');if(!el)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();selectClipElement(el);if(e.key==='Enter'||e.key===' ')return;remember();const c=clipLocation().clip,step=state.view.snap||.0625;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){const sign=e.key==='ArrowLeft'?-1:1;if(e.shiftKey)c.length=num(c.length+sign*step,1/64,state.lengthBars*4-c.start);else c.start=num(c.start+sign*step,0,state.lengthBars*4-c.length);}else{const target=state.selectedTrack+(e.key==='ArrowUp'?-1:1);if(target>=0&&target<8&&state.tracks[target].clips.length<128){const t=track();t.clips=t.clips.filter(a=>a.id!==c.id);state.tracks[target].clips.push(c);state.selectedTrack=target;}}changed({arrangement:true,mixer:true,rack:true,inspector:true});requestAnimationFrame(()=>{for(const item of $('trackLanes').querySelectorAll('[data-clip]'))if(item.dataset.clip===selectedClip)item.focus();});}});
  const activeRanges=new WeakSet();
  document.addEventListener('pointerdown',e=>{if(e.target.matches('input[type=range]')&&e.target.id!=='zoom'){remember();activeRanges.add(e.target);}});
  document.addEventListener('keydown',e=>{if(e.target.matches('input[type=range]')&&e.target.id!=='zoom'&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key)&&!activeRanges.has(e.target)){remember();activeRanges.add(e.target);}});
  document.addEventListener('change',e=>{if(e.target.matches('input[type=range]'))activeRanges.delete(e.target);});
  document.addEventListener('keyup',e=>{if(e.target.matches('input[type=range]'))activeRanges.delete(e.target);});
  document.addEventListener('click',e=>{
    const arm=e.target.closest('[data-arm]'),mute=e.target.closest('[data-mute]'),solo=e.target.closest('[data-solo]');
    if(arm||mute||solo){const el=arm||mute||solo,key=arm?'armed':mute?'mute':'solo',i=Number(el.dataset[arm?'arm':mute?'mute':'solo']);remember();state.tracks[i][key]=!state.tracks[i][key];changed({arrangement:true,mixer:true});return;}
    const instrument=e.target.closest('[data-instrument]');if(instrument){openExisting(Number(instrument.dataset.instrument));return;}
    const fx=e.target.closest('[data-effect-track]');if(fx){selectEffect(Number(fx.dataset.effectSlot),Number(fx.dataset.effectTrack));return;}
    const header=e.target.closest('.track-header');if(header){selectedTrack(Number(header.dataset.track));return;}
    const channel=e.target.closest('[data-channel]');if(channel&&!e.target.closest('input,button')){selectedTrack(Number(channel.dataset.channel));return;}
    const slot=e.target.closest('[data-slot]');if(slot){selectEffect(Number(slot.dataset.slot));return;}
    const add=e.target.closest('[data-add-effect]');if(add){remember();track().effects[selectedSlot]={type:add.dataset.addEffect,params:clone(effectById(add.dataset.addEffect).defaults)};$('effectDialog').close();changed({arrangement:true,mixer:true,rack:true});renderEffectEditor();$('effectEditor').scrollIntoView({block:'nearest',behavior:'smooth'});return;}
    const app=e.target.closest('[data-app]');if(app){const descriptor=instrumentOptions()[Number(app.dataset.app)],index=browserTrack??state.selectedTrack;selectedTrack(index);ensureInstrument(track(),{open:true,replace:true,descriptor:{id:descriptor.id,name:descriptor.name,url:descriptor.url}}).catch(e=>status(e.message));return;}
    const effectActions={effectBypass:'bypass',effectReset:'reset',effectUp:'up',effectDown:'down',effectRemove:'remove'};if(effectActions[e.target.id]){changeEffect(effectActions[e.target.id]);return;}if(e.target.id==='effectReplace')openEffects(selectedSlot);
  });
  document.addEventListener('input',e=>{const input=e.target;if(input.dataset.mix){if(!activeRanges.has(input)){remember();activeRanges.add(input);}const t=state.tracks[Number(input.dataset.track)],key=input.dataset.mix;t[key]=Number(input.value);if(key==='pan')input.nextElementSibling.textContent=panLabel(t.pan);else input.closest('.mixer-channel').querySelector('.channel-db').textContent=levelLabel(t.level);changed();}if(input.dataset.effectParam&&input.type==='range'){if(!activeRanges.has(input)&&input.type==='range'){remember();activeRanges.add(input);}const slot=track().effects[selectedSlot],p=effectById(slot.type).params.find(p=>p.key===input.dataset.effectParam);slot.params[p.key]=p.type==='select'?input.value:Number(input.value);if(input.dataset.log==='true')slot.params[p.key]=p.min*Math.pow(p.max/p.min,Number(input.value));if(p.type==='range')input.closest('.control').querySelector('output').textContent=formatParam(p,slot.params[p.key]);changed();const graphic=$('effectEditor').querySelector('.effect-art');if(graphic)graphic.style.filter=`drop-shadow(0 0 ${2+slot.params.mix*7}px ${effectById(slot.type).color}22)`;} });
  document.addEventListener('change',e=>{if(e.target.dataset.effectParam&&e.target.tagName==='SELECT'){remember();track().effects[selectedSlot].params[e.target.dataset.effectParam]=e.target.value;changed();}});
  $('clipControls').addEventListener('change',e=>{const key=e.target.dataset.clipParam,location=clipLocation();if(!key||!location)return;remember();const c=location.clip,asset=assetMap[c.assetId],duration=asset.left.length/asset.sampleRate,value=e.target.type==='checkbox'?e.target.checked:e.target.type==='text'?e.target.value:Number(e.target.value);if(key==='name')c.name=value.trim().slice(0,80)||'Untitled clip';else if(key==='start')c.start=num(value-1,0,state.lengthBars*4-c.length);else if(key==='length'){c.length=num(value,1/64,state.lengthBars*4-c.start);c.fadeIn=Math.min(c.fadeIn,c.length/2);c.fadeOut=Math.min(c.fadeOut,c.length/2);}else if(key==='sourceStart'){c.sourceStart=num(value,0,c.sourceEnd-1/asset.sampleRate);c.sourceOffset=0;}else if(key==='sourceEnd'){c.sourceEnd=num(value,c.sourceStart+1/asset.sampleRate,duration);c.sourceOffset=0;}else if(key==='rate')c.rate=num(value,.125,8);else if(key==='gain')c.gain=num(value,0,2);else if(key==='fadeIn'||key==='fadeOut')c[key]=num(value,0,c.length/2);else c[key]=value;changed({arrangement:true,inspector:true});});
  $('ruler').addEventListener('pointerdown',e=>{engine.seek(num(snap((e.clientX-$('timeline').getBoundingClientRect().left)/state.view.zoom),0,state.lengthBars*4));renderPlayhead();});
  $('playButton').addEventListener('click',transportStart);$('stopButton').addEventListener('click',stop);$('panicButton').addEventListener('click',()=>panic());$('recordButton').addEventListener('click',startRecording);
  $('tempo').addEventListener('change',()=>{remember();state.tempo=num($('tempo').value,40,240);$('tempo').value=state.tempo;host.setTempo(state.tempo);changed({arrangement:true});renderTransport();});
  $('loopButton').addEventListener('click',()=>{remember();state.loopEnabled=!state.loopEnabled;changed({arrangement:true});renderTransport();});
  $('metronomeButton').addEventListener('click',()=>{remember();state.master.metronome=!state.master.metronome;changed();renderTransport();});
  $('projectName').addEventListener('change',()=>{remember();state.name=$('projectName').value.trim().slice(0,80)||'Untitled tangle';changed();});
  $('undoButton').addEventListener('click',undo);$('redoButton').addEventListener('click',redo);$('saveButton').addEventListener('click',saveProject);
  $('openButton').addEventListener('click',()=>{$('projectFile').value='';$('projectFile').click();});$('projectFile').addEventListener('change',()=>openProject($('projectFile').files[0]));
  $('newButton').addEventListener('click',()=>replaceState(S.defaultState(),{message:'Eight empty tracks. A wonderfully unreasonable beginning.'}));
  $('starterButton').addEventListener('click',()=>replaceState(S.demoState(),{message:'The pocket orchestra has returned. Press Play.'}));
  $('importButton').addEventListener('click',()=>{$('audioFile').value='';$('audioFile').click();});$('audioFile').addEventListener('change',()=>importAudio($('audioFile').files[0]));
  $('splitButton').addEventListener('click',splitClip);$('duplicateButton').addEventListener('click',duplicateClip);$('deleteClipButton').addEventListener('click',removeClip);
  $('zoom').addEventListener('input',()=>{fitInitial=false;state.view.zoom=Number($('zoom').value);renderArrangement();scheduleAutosave();});
  function fitTimeline() { state.view.zoom=Math.max(5,Math.min(100,$('timelineScroll').clientWidth/(state.lengthBars*4)));renderArrangement();scheduleAutosave(); }
  $('fitButton').addEventListener('click',()=>{fitInitial=true;fitTimeline();});$('snap').addEventListener('change',()=>{state.view.snap=Number($('snap').value);scheduleAutosave();});
  $('lengthBars').addEventListener('change',()=>{remember();state.lengthBars=Math.round(num($('lengthBars').value,1,64));state=S.normalize(state);changed({arrangement:true,inspector:true});if(fitInitial)fitTimeline();});
  $('loopStart').addEventListener('change',()=>{remember();state.loopStart=num((Number($('loopStart').value)-1)*4,0,state.loopEnd-.25);changed({arrangement:true});});$('loopEnd').addEventListener('change',()=>{remember();state.loopEnd=num((Number($('loopEnd').value)-1)*4,state.loopStart+.25,state.lengthBars*4);changed({arrangement:true});});
  $('masterLevel').addEventListener('input',()=>{if(!activeRanges.has($('masterLevel'))){remember();activeRanges.add($('masterLevel'));}state.master.level=Number($('masterLevel').value);$('masterLevelValue').textContent=Math.round(state.master.level*100)+'%';changed();});
  $('browseInstrumentButton').addEventListener('click',()=>openInstrumentBrowser());$('openInstrumentButton').addEventListener('click',()=>openExisting());$('closeInstrument').addEventListener('click',closeInstrument);$('instrumentDialog').addEventListener('cancel',()=>{if(frameTrack)engine.clearAudition(frameTrack);frameTrack=null;});
  $('instrumentBackButton').addEventListener('click',()=>openInstrumentBrowser(browserTrack??state.selectedTrack));
  $('unloadInstrumentButton').addEventListener('click',()=>{const id=frameTrack,t=state.tracks.find(t=>t.id===id);if(!t)return;remember();host.unload(id);engine.clearAudition(id);frames.get(id)?.remove();frames.delete(id);openedApps.delete(id);loadOperations.set(id,(loadOperations.get(id)||0)+1);t.instrument=null;t.instrumentLive=false;frameTrack=null;changed({arrangement:true,rack:true});openInstrumentBrowser(state.tracks.indexOf(t));status('Instrument unloaded. Its recorded clips remain in the arrangement.');});
  $('trackName').addEventListener('change',()=>{remember();track().name=$('trackName').value.trim().slice(0,80)||'Track '+(state.selectedTrack+1);changed({arrangement:true,mixer:true,rack:true});});$('trackColor').addEventListener('change',()=>{remember();track().color=$('trackColor').value;changed({arrangement:true,mixer:true,rack:true});});
  $('instrumentLive').addEventListener('change',()=>{remember();track().instrumentLive=$('instrumentLive').checked;changed();if(engine.getMeters().playing&&track().instrument){if(track().instrumentLive){const t=track(),generation=lifecycle;ensureInstrument(t).then(async ready=>{if(ready&&generation===lifecycle&&t.instrumentLive&&engine.getMeters().playing){await host.command(t.id,'prepare');if(generation===lifecycle&&t.instrumentLive&&engine.getMeters().playing)fireCommand(t.id,'start');}}).catch(e=>status(e.message));}else fireCommand(track().id,'stop');}});
  $('uploadAppButton').addEventListener('click',()=>{$('appFile').value='';$('appFile').click();});$('appFile').addEventListener('change',async()=>{const file=$('appFile').files[0];if(!file)return;if(file.size>4*1024*1024){status('Choose a self-contained instrument HTML smaller than 4 MB.');return;}const generation=lifecycle;try{const html=await file.text();if(generation!==lifecycle)return;const id='custom-'+S.uid('app').slice(-24).replace(/[^a-z0-9_-]/gi,'');selectedTrack(browserTrack??state.selectedTrack);await ensureInstrument(track(),{open:true,replace:true,descriptor:{id,name:file.name.replace(/\.html?$/i,''),html}});}catch(e){status(e.message);}});
  $('loadAppUrlButton').addEventListener('click',()=>{try{const url=new URL($('customAppUrl').value,location.href);if(location.protocol==='file:'||url.origin!==location.origin||!['http:','https:'].includes(url.protocol))throw Error('Choose an instrument URL on this same site. For offline apps, upload its HTML.');selectedTrack(browserTrack??state.selectedTrack);const id='custom-'+S.uid('app').slice(-24).replace(/[^a-z0-9_-]/gi,'');ensureInstrument(track(),{open:true,replace:true,descriptor:{id,name:url.pathname.split('/').filter(Boolean).pop()||'New instrument',url:url.href}}).catch(e=>status(e.message));}catch(e){status(e.message);}});
  $('closeEffect').addEventListener('click',()=>$('effectDialog').close());$('exportButton').addEventListener('click',()=>{$('exportSummary').textContent='Stereo PCM WAV · 48 kHz · 16 bit';$('exportDialog').showModal();});$('closeExport').addEventListener('click',()=>$('exportDialog').close());$('renderButton').addEventListener('click',renderExport);$('cancelExport').addEventListener('click',()=>exportAbort?.abort());$('exportDialog').addEventListener('cancel',e=>{if(exportAbort){e.preventDefault();exportAbort.abort();}});
  const showHelp=()=>$('helpDialog').showModal();$('helpButton').addEventListener('click',showHelp);$('footerHelp').addEventListener('click',showHelp);$('closeHelp').addEventListener('click',()=>$('helpDialog').close());
  $('autosaveEnabled').addEventListener('change',()=>{recovery=$('autosaveEnabled').checked;try{localStorage.setItem('loom-recovery-enabled',recovery?'1':'0');if(!recovery)localStorage.removeItem('loom-session-v1');}catch(_){}scheduleAutosave();status(recovery?'Browser recovery enabled when storage is available. Save a project to keep large sessions.':'Browser recovery disabled. Save projects to keep your work.');});
  document.addEventListener('keydown',e=>{const dialog=document.querySelector('dialog[open]'),editing=e.target.closest('input,select,textarea,[contenteditable=true]'),nativeButton=e.target.closest('button,a');if(dialog)return;if(editing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return;}if(e.key==='Escape'){e.preventDefault();panic();return;}if(e.code==='Space'&&!e.repeat&&!nativeButton&&!e.target.closest('.clip')){e.preventDefault();transportStart();return;}if(nativeButton)return;if((e.key==='Delete'||e.key==='Backspace')&&selectedClip){e.preventDefault();removeClip();}if(!e.ctrlKey&&!e.metaKey&&selectedClip){if(e.key.toLowerCase()==='d'){e.preventDefault();duplicateClip();}if(e.key.toLowerCase()==='s'){e.preventDefault();splitClip();}}});
  function animate(now) { if(now-meterTime>45){meterTime=now;const m=engine.getMeters(),beat=m.beat||0,bar=Math.floor(beat/4)+1,quarter=Math.floor(beat%4)+1,tick=Math.floor((beat%1)*1000);$('clock').textContent=String(bar).padStart(2,'0')+' : '+String(quarter).padStart(2,'0')+' : '+String(tick).padStart(3,'0');$('clockMode').textContent=m.recording?'RECORDING / '+(m.recordSeconds||0).toFixed(1)+' SECONDS':m.playing?'PLAYING / '+(m.mode||'WEB AUDIO').toUpperCase():'STOPPED / READY FOR TROUBLE';$('playhead').style.left=beat*state.view.zoom+'px';const master=m.master||{},level=Math.max(master.rmsLeft||0,master.rmsRight||0,master.rms||0);$('masterLeft').style.width=Math.min(100,Math.sqrt(master.rmsLeft||master.rms||0)*140)+'%';$('masterRight').style.width=Math.min(100,Math.sqrt(master.rmsRight||master.rms||0)*140)+'%';$('masterDb').textContent=level>1e-5?(20*Math.log10(level)).toFixed(0)+' dB':'−∞';for(let i=0;i<8;i++){const el=$('meter-'+i);if(el)el.style.height=Math.min(100,Math.sqrt(m.tracks?.[i]?.rms||0)*135)+'%';}if($('playButton').dataset.playing!==String(m.playing)){$('playButton').dataset.playing=String(m.playing);renderTransport();}}requestAnimationFrame(animate); }
  host.setTempo(state.tempo);decodeAssets();renderAll();if(recoveryUnavailable)recoveryInfo('Browser recovery is unavailable. Save a project to keep this session.');requestAnimationFrame(()=>{fitTimeline();requestAnimationFrame(animate);});let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(fitInitial)fitTimeline();else renderArrangement();},100);});
  if(location.protocol==='file:'){const home='https://calebhaines.github.io/sidequest-prototypes/music/';$('musicHome').href=home;$('downloadHtml').href=home+'loom/index.html';$('downloadSource').href=home+'loom/LOOM-source.zip';$('downloadApi').href='https://github.com/calebhaines/sidequest-prototypes/blob/main/loom/HOSTING.md';}
  window.addEventListener('pagehide',()=>{engine.panic();host.dispose();});
  window.LoomApp=Object.freeze({getState:()=>clone(state),loadState:next=>replaceState(next,{message:'Session loaded.'}),get engine(){return engine;},get host(){return host;},get assets(){return assetMap;},selectTrack:index=>selectedTrack(num(index,0,7)),get selectedClip(){return selectedClip;}});
})();
