/* GLAZE · a vocal finishing station. All processing is local. */
(function (scope) {
  'use strict';
  const range = (key, label, min, max, step, value, unit = '') => ({ key, label, type: 'range', min, max, step, default: value, unit });
  const select = (key, label, value, options) => ({ key, label, type: 'select', default: value, options: options.map(([value, label]) => ({ value, label })) });
  const switcher = (key, value) => select(key, 'Stage', value, [['on', 'On'], ['off', 'Off']]);
  const rhythmic = [['1/32', '1/32 note'], ['1/16', '1/16 note'], ['1/8', '1/8 note'], ['1/8.', 'Dotted eighth'], ['1/4', 'Quarter note'], ['1/4.', 'Dotted quarter'], ['1/2', 'Half note'], ['1', 'One bar'], ['2', 'Two bars']];
  const params = [
    switcher('clean', 'on'), range('input', 'Input trim', -18, 24, .1, 0, 'dB'), range('highpass', 'Low cut', 20, 400, 1, 75, 'Hz'), range('gate', 'Gate threshold', -90, -12, 1, -70, 'dB'), range('gateRange', 'Gate reduction', 0, 60, .1, 45, 'dB'), range('gateRelease', 'Gate release', 20, 1000, 1, 180, 'ms'),
    switcher('deess', 'on'), range('deessFreq', 'Sibilance frequency', 2500, 11000, 1, 6500, 'Hz'), range('deessThreshold', 'De-ess threshold', -60, -3, .1, -24, 'dB'), range('deessAmount', 'De-ess strength', 0, 1, .01, .45, '%'),
    switcher('compressor', 'on'), range('threshold', 'Threshold', -48, 0, .1, -18, 'dB'), range('ratio', 'Ratio', 1, 20, .1, 3, ':1'), range('attack', 'Attack', .2, 80, .1, 5, 'ms'), range('release', 'Release', 20, 1200, 1, 120, 'ms'), range('makeup', 'Makeup gain', 0, 18, .1, 2, 'dB'),
    switcher('eq', 'on'), range('body', 'Body', -15, 15, .1, 0, 'dB'), range('bodyFreq', 'Body frequency', 100, 600, 1, 220, 'Hz'), range('mud', 'Low-middle', -15, 15, .1, -1, 'dB'), range('mudFreq', 'Low-middle frequency', 180, 1200, 1, 420, 'Hz'), range('presence', 'Presence', -15, 15, .1, 1, 'dB'), range('presenceFreq', 'Presence frequency', 1200, 7000, 1, 3200, 'Hz'), range('air', 'Air', -15, 15, .1, 1.5, 'dB'),
    select('saturation', 'Colour', 'off', [['off', 'Off'], ['warm', 'Warm glaze'], ['edge', 'Hard caramel'], ['fold', 'Folded sugar']]), range('drive', 'Drive', 0, 30, .1, 3, 'dB'), range('satMix', 'Colour blend', 0, 1, .01, .25, '%'),
    select('pitch', 'Pitch mode', 'off', [['off', 'Off'], ['shift', 'Transpose'], ['correct', 'Scale correction']]), range('semitones', 'Transpose', -24, 24, 1, 0, 'st'), range('fine', 'Fine tune', -100, 100, 1, 0, 'cent'), select('key', 'Root note', 'C', ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'].map(note => [note, note])), select('scale', 'Scale', 'chromatic', [['chromatic', 'Chromatic'], ['major', 'Major'], ['minor', 'Minor'], ['pentatonic', 'Pentatonic'], ['harmonic-minor', 'Harmonic minor']]), range('speed', 'Correction strength', 0, 1, .01, .65, '%'), range('pitchWindow', 'Pitch window', 20, 100, 1, 50, 'ms'), range('pitchMix', 'Pitch blend', 0, 1, .01, 1, '%'),
    switcher('harmony', 'off'), range('harmonyA', 'Harmony A interval', -24, 24, 1, 7, 'st'), range('harmonyB', 'Harmony B interval', -24, 24, 1, 12, 'st'), range('harmonyMix', 'Harmony blend', 0, 1, .01, .3, '%'), range('harmonyWidth', 'Harmony width', 0, 1, .01, .7, '%'),
    switcher('doubler', 'off'), range('doubleAmount', 'Double blend', 0, 1, .01, .3, '%'), range('doubleSpread', 'Double width', 0, 1, .01, .8, '%'), range('doubleTime', 'Double time', 8, 45, 1, 18, 'ms'), range('doubleDetune', 'Double drift', 0, 25, .1, 7, 'cent'),
    select('vowel', 'Vowel shape', 'off', [['off', 'Off'], ['ah', 'Ah'], ['eh', 'Eh'], ['ee', 'Ee'], ['oh', 'Oh'], ['oo', 'Oo']]), range('formant', 'Vowel shift', -12, 12, .1, 0, 'st'), range('vowelMix', 'Vowel blend', 0, 1, .01, .5, '%'),
    select('robot', 'Robot mode', 'off', [['off', 'Off'], ['ring', 'Ring modulation'], ['vocoder', 'Twelve-band vocoder']]), select('carrier', 'Vocoder carrier', 'saw', [['saw', 'Saw'], ['square', 'Square'], ['pulse', 'Narrow pulse']]), range('carrierNote', 'Carrier MIDI note', 24, 84, 1, 45, ''), select('carrierChord', 'Carrier chord', 'single', [['single', 'Single note'], ['fifth', 'Root + fifth'], ['minor', 'Minor triad'], ['major', 'Major triad']]), range('robotMix', 'Robot blend', 0, 1, .01, .65, '%'), range('robotFreq', 'Ring frequency', 20, 2000, 1, 120, 'Hz'),
    switcher('chop', 'off'), select('chopDivision', 'Chop cycle', '1/16', rhythmic), range('chopDepth', 'Chop depth', 0, 1, .01, 1, '%'), range('chopDuty', 'Open length', .05, .95, .01, .5, '%'), range('chopSmooth', 'Chop smoothing', .2, 40, .1, 3, 'ms'),
    switcher('delay', 'off'), select('delayClock', 'Delay clock', 'sync', [['sync', 'Follow session tempo'], ['free', 'Milliseconds']]), select('delayDivision', 'Delay division', '1/8.', rhythmic.filter(item => item[0] !== '2')), range('delayTime', 'Delay time', 20, 2000, 1, 375, 'ms'), range('delayFeedback', 'Feedback', 0, .88, .01, .35, '%'), range('delayTone', 'Repeat tone', 500, 14000, 1, 5500, 'Hz'), range('delayWidth', 'Repeat width', 0, 1, .01, .85, '%'), range('delayMix', 'Delay blend', 0, 1, .01, .15, '%'), range('delayDuck', 'Delay ducking', 0, 1, .01, .5, '%'),
    switcher('reverb', 'off'), range('reverbSize', 'Room size', 0, 1, .01, .45, '%'), range('reverbDecay', 'Decay', .2, 10, .1, 2.4, 's'), range('predelay', 'Pre-delay', 0, 150, 1, 18, 'ms'), range('reverbTone', 'Reverb tone', 800, 14000, 1, 6500, 'Hz'), range('reverbWidth', 'Reverb width', 0, 1, .01, .8, '%'), range('reverbMix', 'Reverb blend', 0, 1, .01, .18, '%'), range('reverbDuck', 'Reverb ducking', 0, 1, .01, .5, '%'),
    switcher('guard', 'on'), range('ceiling', 'Peak ceiling', -12, 0, .1, -.5, 'dB'), range('output', 'Output trim', -24, 12, .1, 0, 'dB')
  ];
  const group = (id, label, shortLabel, enableKey, description, keys, basicKeys) => ({ id, label, shortLabel, enableKey, description, keys, basicKeys });
  scope.LoomVocalCatalog = {
    id: 'glaze', name: 'GLAZE', subtitle: 'A finishing station for every voice in the room.', color: '#d4a0bd', accent: '#ffdccd', visual: 'glaze', panel: 'vocal',
    description: 'Clean, contain, tune, thicken, distort, chop, and send a voice into a room it has no business occupying. One insert. Every stage has its own switch.',
    params, defaults: Object.assign(Object.fromEntries(params.map(p => [p.key, p.default])), { mix: 1, bypass: false }),
    groups: [
      group('clean', '01 · Prep & cleanup', 'Cleanup', 'clean', 'Input trim is always active. Low cut and the gentle gate belong to this stage.', ['input', 'highpass', 'gate', 'gateRange', 'gateRelease'], ['input', 'highpass', 'gate']),
      group('deess', '02 · Tame the hiss', 'De-ess', 'deess', 'Reduce sharp sibilance without lowering the whole word.', ['deessFreq', 'deessThreshold', 'deessAmount'], ['deessAmount']),
      group('compressor', '03 · Hold the voice', 'Dynamics', 'compressor', 'Control uneven phrases. Attack and release decide how firmly.', ['threshold', 'ratio', 'attack', 'release', 'makeup'], ['threshold', 'ratio']),
      group('eq', '04 · Tone & air', 'Tone', 'eq', 'Body below, clarity above, and somewhere to put the boxiness.', ['body', 'bodyFreq', 'mud', 'mudFreq', 'presence', 'presenceFreq', 'air'], ['body', 'presence', 'air']),
      group('saturation', '05 · Caramelisation', 'Colour', 'saturation', 'A little warmth, a pointed edge, or thoroughly folded sugar.', ['drive', 'satMix'], ['drive', 'satMix']),
      group('pitch', '06 · Tune & transpose', 'Pitch', 'pitch', 'Scale correction suits one pitched voice. Transpose is a creative grain shifter; pitch windows add audible delay.', ['semitones', 'fine', 'key', 'scale', 'speed', 'pitchWindow', 'pitchMix'], ['semitones', 'key', 'scale', 'speed', 'pitchWindow']),
      group('harmony', '07 · Extra mouths', 'Harmony', 'harmony', 'Two fixed-interval voices, spread to either side. They use the shared pitch window.', ['harmonyA', 'harmonyB', 'harmonyMix', 'harmonyWidth'], ['harmonyA', 'harmonyB', 'harmonyMix']),
      group('doubler', '08 · Double service', 'Double', 'doubler', 'Short drifting copies widen a lead without another take.', ['doubleAmount', 'doubleSpread', 'doubleTime', 'doubleDetune'], ['doubleAmount', 'doubleSpread']),
      group('vowel', '09 · Shape the mouth', 'Vowel', 'vowel', 'Three resonators colour vowels. Vowel shift moves their resonances; it is an expressive filter.', ['formant', 'vowelMix'], ['formant', 'vowelMix']),
      group('robot', '10 · Kitchen intercom', 'Robot', 'robot', 'A ringing carrier or a voice-shaped synthesizer. The carrier can sing a chord.', ['carrier', 'carrierNote', 'carrierChord', 'robotMix', 'robotFreq'], ['carrierNote', 'robotFreq', 'robotMix']),
      group('chop', '11 · Cut the phrase', 'Chop', 'chop', 'Tempo-locked cuts. Soften their edges or leave the knife marks.', ['chopDivision', 'chopDepth', 'chopDuty', 'chopSmooth'], ['chopDivision', 'chopDepth']),
      group('delay', '12 · Repeat the order', 'Delay', 'delay', 'Stereo repeats duck behind your words. Follow the clock or pick a time.', ['delayClock', 'delayDivision', 'delayTime', 'delayFeedback', 'delayTone', 'delayWidth', 'delayMix', 'delayDuck'], ['delayClock', 'delayDivision', 'delayTime', 'delayFeedback', 'delayMix']),
      group('reverb', '13 · Room for dessert', 'Reverb', 'reverb', 'A room, a hall, or a suspiciously long corridor. Ducking keeps the lead clear.', ['reverbSize', 'reverbDecay', 'predelay', 'reverbTone', 'reverbWidth', 'reverbMix', 'reverbDuck'], ['reverbDecay', 'reverbMix']),
      group('output', '14 · Plate & pass', 'Peak guard', 'guard', 'Peak guard catches excess level. Output trim and dry / wet are always active.', ['ceiling', 'output', 'mix'], ['output', 'mix'])
    ],
    presets: [
      { id: 'first-service', name: 'First service · clean lead', description: 'A practical lead strip: low cut, light de-essing, even phrases, and a breath of air. Pitch processing stays off.', params: {} },
      { id: 'close-quarters', name: 'Close quarters · intimate', description: 'Firm, close vocals with a soft room tucked underneath.', params: { highpass: 95, threshold: -22, ratio: 4, attack: 8, makeup: 3, mud: -2.5, air: 2, reverb: 'on', reverbDecay: .8, reverbMix: .07, predelay: 9, reverbDuck: .7 } },
      { id: 'spoken-menu', name: 'Spoken menu · narration', description: 'Controlled speech with a little presence. No doubling, pitch window, or long ambience.', params: { highpass: 100, deessAmount: .6, threshold: -24, ratio: 4.5, attack: 3, release: 160, makeup: 3, presence: 2.5, air: 0, gate: -58, gateRange: 16, gateRelease: 240 } },
      { id: 'silver-service', name: 'Silver service · polished', description: 'Bright lead vocals, a discreet double, and ducked rhythmic repeats.', params: { highpass: 90, deessAmount: .6, threshold: -21, ratio: 4, makeup: 3, presence: 2, air: 3, doubler: 'on', doubleAmount: .12, doubleDetune: 4, delay: 'on', delayMix: .1, delayFeedback: .28, reverb: 'on', reverbDecay: 1.8, reverbMix: .12 } },
      { id: 'room-temperature', name: 'Room temperature · natural', description: 'A gentle finishing pass with a small room. The singer stays in front.', params: { highpass: 60, gate: -80, ratio: 2, attack: 18, threshold: -20, makeup: 1, mud: 0, presence: .5, air: 1, reverb: 'on', reverbDecay: 1.2, reverbSize: .25, reverbMix: .1 } },
      { id: 'locked-glaze', name: 'Set glaze · hard tuning', description: 'Strong A-minor correction, a wide double, and tight repeats. Designed for a single sung line; pitch processing adds delay.', params: { pitch: 'correct', key: 'A', scale: 'minor', speed: 1, pitchWindow: 40, threshold: -24, ratio: 5, makeup: 3, doubler: 'on', doubleAmount: .2, delay: 'on', delayDivision: '1/8', delayMix: .12, reverb: 'on', reverbMix: .1 } },
      { id: 'upper-shelf', name: 'Upper shelf · octave choir', description: 'A fifth and an octave gather around the original voice. Fixed intervals, no choir required.', params: { harmony: 'on', harmonyA: 7, harmonyB: 12, harmonyMix: .4, harmonyWidth: 1, doubler: 'on', doubleAmount: .15, reverb: 'on', reverbDecay: 3.8, reverbMix: .24, reverbDuck: .65 } },
      { id: 'heavy-syrup', name: 'Heavy syrup · low creature', description: 'An octave-down voice, dark resonant vowels, and a little burnt edge.', params: { pitch: 'shift', semitones: -12, pitchWindow: 70, vowel: 'oh', formant: -4, vowelMix: .3, saturation: 'warm', drive: 8, satMix: .35, air: -4, reverb: 'on', reverbDecay: 2.8, reverbTone: 2500, reverbMix: .14, output: -3 } },
      { id: 'sugar-glass', name: 'Sugar glass · bright creature', description: 'A lifted voice with narrow vowel colour and short, glassy repeats.', params: { pitch: 'shift', semitones: 7, pitchWindow: 35, vowel: 'ee', formant: 4, vowelMix: .35, doubler: 'on', doubleAmount: .3, doubleDetune: 12, delay: 'on', delayDivision: '1/16', delayFeedback: .4, delayMix: .18, output: -2 } },
      { id: 'burnt-caramel', name: 'Burnt caramel · grit', description: 'A forward, compressed voice with a hard edge. The blend keeps some human underneath.', params: { threshold: -26, ratio: 6, makeup: 4, saturation: 'edge', drive: 16, satMix: .55, presence: 3, air: -2, delay: 'on', delayClock: 'free', delayTime: 95, delayFeedback: .13, delayMix: .12, output: -5 } },
      { id: 'intercom-choir', name: 'Intercom choir · vocoder', description: 'An A-minor synth chord borrows the singer’s articulation. Choose a carrier note in the full pantry.', params: { robot: 'vocoder', carrier: 'saw', carrierNote: 45, carrierChord: 'minor', robotMix: 1, eq: 'off', reverb: 'on', reverbDecay: 2.6, reverbMix: .18, delay: 'on', delayDivision: '1/8', delayMix: .13, output: -3 } },
      { id: 'broken-ticket', name: 'Broken ticket · chopped', description: 'Fast rhythmic cuts, narrow ring modulation, and repeats that refuse to read the order once.', params: { robot: 'ring', robotFreq: 180, robotMix: .4, chop: 'on', chopDivision: '1/32', chopDepth: .9, chopDuty: .35, chopSmooth: .8, delay: 'on', delayDivision: '1/8.', delayFeedback: .58, delayMix: .28, saturation: 'fold', drive: 7, satMix: .18, output: -3 } },
      { id: 'cold-storage', name: 'Cold storage · endless hall', description: 'A voice at the end of a long corridor. Ducked ambience keeps new phrases visible.', params: { doubler: 'on', doubleAmount: .28, doubleSpread: 1, reverb: 'on', reverbSize: .9, reverbDecay: 8, predelay: 65, reverbMix: .48, reverbDuck: .8, delay: 'on', delayDivision: '1/2', delayFeedback: .64, delayMix: .24, delayDuck: .75, output: -3 } },
      { id: 'staff-radio', name: 'Staff radio · narrow & odd', description: 'A thin, nasal voice with a ring of machinery and a very small room.', params: { highpass: 280, body: -12, mud: 4, mudFreq: 900, presence: 4, air: -12, vowel: 'eh', formant: 2, vowelMix: .5, saturation: 'warm', drive: 12, satMix: .45, robot: 'ring', robotFreq: 35, robotMix: .15, reverb: 'on', reverbDecay: .4, reverbMix: .08, output: -4 } }
    ]
  };
  for (const g of scope.LoomVocalCatalog.groups) g.optional = !['clean', 'deess', 'compressor', 'eq', 'output'].includes(g.id);
  scope.LoomVocalCatalog.groups.find(g => g.id === 'clean').alwaysKeys = ['input'];
  scope.LoomVocalCatalog.groups.find(g => g.id === 'output').alwaysKeys = ['output', 'mix'];
})(typeof window === 'undefined' ? globalThis : window);
