/* STEAM's drawing desk. Every mark is part of the sound. */
(() => {
  'use strict';
  const S=window.HazeSchema,P=window.HazePresets,$=id=>document.getElementById(id),canvas=$('score-canvas'),ctx=canvas.getContext('2d'),envCanvas=$('envelope-canvas'),envCtx=envCanvas.getContext('2d');
  let state=S.copy(P[0].state),history=[],tool='brush',selected={x:0,y:0},paint=null,layout=null,uiGeneration=0,persistTimer=null,storageUnavailable=false,capturePending=false,playPending=false,captureOperation=0,playOperation=0,exportPending=false,paintDirty=true,editRevision=0,importOperation=0;
  // Display-only focus never enters a saved score or its Undo history.
  let detailView=false,detailColumn=0,detailBand=0;
  try{const saved=localStorage.getItem('haze-project-v1');if(saved)state=S.parseProject(saved);}catch{storageUnavailable=true;}
  const engine=new window.HazeAudio(state),controls=new Map();
  const status=(message)=>{$('status').textContent=message;};
  function persist(){clearTimeout(persistTimer);persistTimer=setTimeout(()=>{if(storageUnavailable)return;try{localStorage.setItem('haze-project-v1',S.serializeProject(state));}catch{storageUnavailable=true;status('Browser storage is unavailable. Save a project to keep this recipe.');}},350);}
  function remember(snapshot=state){history.push(S.copy(snapshot));if(history.length>40)history.shift();$('undo-button').disabled=!history.length;}
  function changed({custom=true}={}){editRevision++;if(custom)state.name='Your own extraction recipe';engine.setState(state);paintDirty=true;renderCounts();persist();}
  function applyState(next,{undo=true,message='A new recipe is on the line.'}={}){if(undo)remember();uiGeneration++;captureOperation++;playOperation++;playPending=false;engine.panic();state=S.normalize(next);engine.setState(state);capturePending=false;renderControls();renderTransport();paintDirty=true;persist();status(message);}
  function renderCounts(){const count=state.score.reduce((n,row)=>n+row.filter(v=>v>0).length,0);$('score-count').textContent=`${count} PAINTED CELLS`;const legacyNames={'The sky has mislaid its notes':'The extraction fan knows a tune','Stairs for a passing cloud':'Steps under the heat lamp','A velvet weather warning':'After-hours extraction','Glass, pretending to be rain':'Glassware in the dishwasher','The mirror owes us a song':'The recipe reads backwards','A committee of violet moths':'The hood committee','The clock has swallowed noon':'The timer refuses service','An entirely imaginary sky':'An empty prep sheet'};const match=P.find(p=>p.name===(legacyNames[state.name]||state.name));$('preset').value=match?match.id:'custom';$('preset-description').textContent=match?match.description:'Your own notes, prepared for continuous extraction.';}
  function option(select,value,text){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}
  for(const p of P)option($('preset'),p.id,p.name);option($('preset'),'custom','Your own extraction recipe');
  for(const s of S.SCALES)option($('scale'),s.id,s.name);for(const d of S.DIRECTIONS)option($('direction'),d.id,d.name);for(const d of S.DIVISIONS)option($('echo-division'),d,d);
  for(let m=24;m<=72;m++)option($('root'),m,S.noteName(m));
  const specs=[
    ['synthesis-controls','stretch','Stretch',.5,1.8,.01,v=>v.toFixed(2)+'×'],['synthesis-controls','color','Colour',0,1,.01,v=>Math.round(v*100)+'%'],['synthesis-controls','drift','Drift',0,1,.01,v=>Math.round(v*100)+'%'],['synthesis-controls','blur','Blur',0,1,.01,v=>Math.round(v*100)+'%'],['synthesis-controls','cutoff','Low-pass filter',200,18000,1,v=>v>=1000?(v/1000).toFixed(1)+' kHz':Math.round(v)+' Hz','log'],['synthesis-controls','drive','Saturation',0,1,.01,v=>Math.round(v*100)+'%'],
    ['envelope-controls','attack','Attack',2,1200,1,v=>Math.round(v)+' ms','log'],['envelope-controls','release','Release',10,5000,1,v=>v>=1000?(v/1000).toFixed(2)+' s':Math.round(v)+' ms','log'],['space-controls','spread','Stereo spread',0,1,.01,v=>Math.round(v*100)+'%'],['space-controls','echo','Echo level',0,1,.01,v=>Math.round(v*100)+'%'],['space-controls','feedback','Echo feedback',0,.82,.01,v=>Math.round(v*100)+'%'],['space-controls','room','Room level',0,1,.01,v=>Math.round(v*100)+'%'],['output-controls','volume','Output level',0,1,.01,v=>Math.round(v*100)+'%']
  ];
  for(const [container,key,label,min,max,step,format,curve]of specs){const wrap=document.createElement('div');wrap.className='control';const l=document.createElement('label'),o=document.createElement('output'),input=document.createElement('input');l.textContent=label;l.htmlFor=`control-${key}`;input.type='range';input.id=l.htmlFor;input.min=curve==='log'?0:min;input.max=curve==='log'?1000:max;input.step=curve==='log'?1:step;o.htmlFor=input.id;wrap.append(l,o,input);$(container).append(wrap);const decode=v=>curve==='log'?min*Math.pow(max/min,Number(v)/1000):Number(v),encode=v=>curve==='log'?Math.log(v/min)/Math.log(max/min)*1000:v;let before=null;
    input.addEventListener('pointerdown',()=>{before=S.copy(state);});input.addEventListener('focus',()=>{before=S.copy(state);});input.addEventListener('input',()=>{if(!before)before=S.copy(state);state[key]=decode(input.value);o.textContent=format(state[key]);input.style.setProperty('--fill',((Number(input.value)-Number(input.min))/(Number(input.max)-Number(input.min))*100)+'%');changed();if(['root','scale','stretch'].includes(key))renderTuning();if(key==='attack'||key==='release')drawEnvelope();});input.addEventListener('change',()=>{if(before){remember(before);before=S.copy(state);}});controls.set(key,{input,output:o,format,encode});
  }
  function renderTuning(){renderCell();paintDirty=true;const low=window.HazeDSP.frequencyForBand(state,0),high=window.HazeDSP.frequencyForBand(state,23);$('frequency-range').textContent=`${Math.round(low)} Hz — ${high>1000?(high/1000).toFixed(1)+' kHz':Math.round(high)+' Hz'}`;$('tuning-note').textContent=state.scale==='harmonic'?'One fundamental, twenty-four harmonic bands.':'Twenty-four tuned bands, each with an overtone.';}
  function renderControls(){for(const [key,c]of controls){c.input.value=c.encode(state[key]);c.output.textContent=c.format(state[key]);c.input.style.setProperty('--fill',((Number(c.input.value)-Number(c.input.min))/(Number(c.input.max)-Number(c.input.min))*100)+'%');}for(const key of ['tempo','bars','root','scale','direction'])$(key).value=state[key];$('echo-division').value=state.echoDivision;$('freeze-button').setAttribute('aria-pressed',String(state.freeze));renderCounts();renderTuning();renderCell();drawEnvelope();$('undo-button').disabled=!history.length;}
  function renderTransport(){const playing=engine.isPlaying;$('play-button').disabled=playPending;$('play-button').querySelector('span').textContent=playing?'Stop':'Play';$('play-button').querySelector('use').setAttribute('href',playing?'#i-stop':'#i-play');$('capture-button').classList.toggle('recording',engine.isRecording);$('capture-button').querySelector('span').textContent=engine.isRecording?'Finish':'Capture';$('capture-button').disabled=capturePending;$('status-dot').classList.toggle('active',playing||engine.isRecording);}
  for(const key of ['tempo','bars','root','scale','direction'])$(key).addEventListener('change',()=>{remember();if(key==='tempo')state.tempo=Math.min(240,Math.max(40,Number($('tempo').value)||88));else state[key]=['root','bars'].includes(key)?Number($(key).value):$(key).value;changed();renderControls();});
  $('echo-division').addEventListener('change',()=>{remember();state.echoDivision=$('echo-division').value;changed();});
  $('preset').addEventListener('change',()=>{const p=P.find(p=>p.id===$('preset').value);if(p)applyState(p.state,{message:p.description});});
  async function togglePlay(){if(engine.isPlaying||playPending){playOperation++;playPending=false;engine.stop();status('The fan is resting. Its echoes may take a moment.');renderTransport();return;}const generation=uiGeneration,operation=++playOperation;playPending=true;renderTransport();status('Starting the extraction system…');try{const started=await engine.start();if(started&&generation===uiGeneration&&operation===playOperation)status('The extraction fan is singing. Paint while it passes.');}catch(e){if(generation===uiGeneration&&operation===playOperation)status(e.message);}finally{if(operation===playOperation){playPending=false;renderTransport();}}}

  $('play-button').addEventListener('click',togglePlay);
  function panic(){uiGeneration++;captureOperation++;playOperation++;playPending=false;engine.panic();capturePending=false;paintDirty=true;status('All sound stopped. Live capture discarded.');renderTransport();}
  $('panic-button').addEventListener('click',panic);
  $('freeze-button').addEventListener('click',()=>{remember();state.position=engine.getMeters().position;state.freeze=!state.freeze;changed({custom:false});renderControls();status(state.freeze?'Spectrum held. The current recipe is staying put.':'The extraction cycle is moving again.');});
  function setTool(next){tool=next;$('brush-button').setAttribute('aria-pressed',String(tool==='brush'));$('erase-button').setAttribute('aria-pressed',String(tool==='erase'));canvas.style.cursor=tool==='erase'?'cell':'crosshair';}
  $('brush-button').addEventListener('click',()=>setTool('brush'));$('erase-button').addEventListener('click',()=>setTool('erase'));
  $('brush-intensity').addEventListener('input',()=>{$('brush-intensity-value').textContent=Math.round(Number($('brush-intensity').value)*100)+'%';$('brush-intensity').style.setProperty('--fill',Number($('brush-intensity').value)*100+'%');});
  function bandPitch(band){const f=window.HazeDSP.frequencyForBand(state,band),midi=69+12*Math.log2(f/440),note=S.noteName(Math.round(midi)),cents=Math.round((midi-Math.round(midi))*100),detune=Math.abs(cents)>=3?` ${cents>0?'+':''}${cents}¢`:'';return {frequency:f,note,text:`${note}${detune} · ${f>=1000?(f/1000).toFixed(2)+' kHz':Math.round(f)+' Hz'}`};}
  function renderCell(){const pitch=bandPitch(selected.y);$('cell-column').value=selected.x+1;$('cell-band').value=selected.y+1;$('cell-intensity').value=Number(state.score[selected.y][selected.x].toFixed(3));$('selected-cell-summary').textContent=`Column ${selected.x+1} · Band ${selected.y+1}`;$('selected-pitch').textContent=pitch.text;canvas.setAttribute('aria-label',`Spectral score${detailView?', enlarged detail view':''}. Selected column ${selected.x+1}, band ${selected.y+1}, ${pitch.text}, intensity ${Math.round(state.score[selected.y][selected.x]*100)} percent. Arrow keys move, Enter paints, Delete erases.`);}
  function syncDetailWindow(){if(!detailView)return;detailColumn=Math.floor(selected.x/8)*8;detailBand=Math.floor(selected.y/8)*8;$('detail-time').value=detailColumn;$('detail-pitch').value=detailBand;}
  function selectCell(x,y){selected={x:Math.min(31,Math.max(0,Math.round(Number(x)||0))),y:Math.min(23,Math.max(0,Math.round(Number(y)||0)))};syncDetailWindow();renderCell();paintDirty=true;}
  $('detail-view-button').addEventListener('click',()=>{detailView=!detailView;$('detail-view-button').setAttribute('aria-pressed',String(detailView));$('detail-view-button').textContent=detailView?'Full score':'Detail view';$('detail-navigation').hidden=!detailView;syncDetailWindow();renderCell();paintDirty=true;});
  $('detail-time').addEventListener('change',()=>{detailColumn=Number($('detail-time').value);selected.x=detailColumn+selected.x%8;renderCell();paintDirty=true;});
  $('detail-pitch').addEventListener('change',()=>{detailBand=Number($('detail-pitch').value);selected.y=detailBand+selected.y%8;renderCell();paintDirty=true;});
  if(window.matchMedia('(max-width:650px)').matches)document.querySelector('.cell-editor').open=true;
  function locate(e){if(!layout)return null;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x<layout.x||x>layout.x+layout.w||y<layout.y||y>layout.y+layout.h)return null;return {x:layout.columnStart+Math.min(layout.columns-1,Math.floor((x-layout.x)/layout.w*layout.columns)),y:layout.bandStart+layout.bands-1-Math.min(layout.bands-1,Math.floor((y-layout.y)/layout.h*layout.bands))};}
  function brushAt(x,y,erase=tool==='erase'){const radius=Number($('brush-size').value)-1,intensity=Number($('brush-intensity').value);for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){const xx=x+dx,yy=y+dy;if(xx<0||xx>31||yy<0||yy>23||dx*dx+dy*dy>radius*radius+.1)continue;state.score[yy][xx]=erase?0:Math.max(state.score[yy][xx],intensity*(radius?1-Math.hypot(dx,dy)/(radius+1):1));}selected={x,y};renderCell();changed();}
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;const cell=locate(e);if(!cell)return;e.preventDefault();remember();canvas.setPointerCapture(e.pointerId);paint={pointer:e.pointerId,last:cell,erase:tool==='erase'||e.altKey};brushAt(cell.x,cell.y,paint.erase);});
  canvas.addEventListener('pointermove',e=>{if(!paint||paint.pointer!==e.pointerId)return;const cell=locate(e);if(!cell)return;const last=paint.last,steps=Math.max(Math.abs(cell.x-last.x),Math.abs(cell.y-last.y));for(let n=1;n<=Math.max(1,steps);n++)brushAt(Math.round(last.x+(cell.x-last.x)*n/Math.max(1,steps)),Math.round(last.y+(cell.y-last.y)*n/Math.max(1,steps)),paint.erase);paint.last=cell;});
  const finishPaint=()=>{paint=null;};canvas.addEventListener('pointerup',finishPaint);canvas.addEventListener('pointercancel',finishPaint);canvas.addEventListener('lostpointercapture',finishPaint);
  canvas.addEventListener('keydown',e=>{const k=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' ','Delete','Backspace'].includes(k)){e.preventDefault();e.stopPropagation();}if(k==='ArrowLeft')selectCell(selected.x-1,selected.y);if(k==='ArrowRight')selectCell(selected.x+1,selected.y);if(k==='ArrowUp')selectCell(selected.x,selected.y+1);if(k==='ArrowDown')selectCell(selected.x,selected.y-1);if(k==='Enter'||k===' '){remember();brushAt(selected.x,selected.y);}if(k==='Delete'||k==='Backspace'){remember();brushAt(selected.x,selected.y,true);}});
  for(const id of ['cell-column','cell-band'])$(id).addEventListener('change',()=>selectCell(Number($('cell-column').value)-1,Number($('cell-band').value)-1));
  $('set-cell-button').addEventListener('click',()=>{remember();state.score[selected.y][selected.x]=Math.min(1,Math.max(0,Number($('cell-intensity').value)||0));changed();renderCell();status(`Column ${selected.x+1}, band ${selected.y+1} updated.`);});
  $('seek-button').addEventListener('click',()=>{remember();state.position=selected.x+.5;engine.setPosition(state.position);changed({custom:false});status(`Scanning column ${selected.x+1}${state.freeze?' · frozen':''}.`);});
  function undo(){if(!history.length)return;const previous=history.pop();applyState(previous,{undo:false,message:'The previous recipe has returned.'});$('undo-button').disabled=!history.length;}
  $('undo-button').addEventListener('click',undo);
  $('clear-button').addEventListener('click',()=>{remember();state.score=Array.from({length:24},()=>Array(32).fill(0));changed();renderCell();status('The grid is empty. Draw a spectrum to begin.');});
  $('evolve-button').addEventListener('click',()=>{remember();const a=S.copy(state.score);for(let y=0;y<24;y++)for(let x=0;x<32;x++){if(a[y][x]>.01&&Math.random()<.2){const yy=Math.max(0,Math.min(23,y+(Math.random()<.5?-1:1)));state.score[y][x]*=.65;state.score[yy][(x+1)%32]=Math.max(state.score[yy][(x+1)%32],a[y][x]*.8);}if(Math.random()<.025)state.score[y][x]*=.65;}changed();renderCell();status('The recipe has developed a few new opinions.');});
  $('random-button').addEventListener('click',()=>{remember();state.score=Array.from({length:24},()=>Array(32).fill(0));let row=Math.floor(Math.random()*6);for(let x=0;x<32;x++){if(x%2===0){row=Math.min(16,Math.max(0,row+[-2,-1,0,1,2][Math.floor(Math.random()*5)]));state.score[row][x]=.45+Math.random()*.5;if(Math.random()<.55)state.score[row][(x+1)%32]=state.score[row][x]*.5;}if(x%8<5)state.score[3+Math.floor(x/8)*2][x]=Math.max(state.score[3+Math.floor(x/8)*2][x],.2);}changed();renderCell();status('New recipe. The ventilation approves provisionally.');});
  function filename(suffix){return (state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'haze')+suffix;}
  const hasScore=()=>state.score.some(row=>row.some(value=>value>0));
  async function importAudio({pcm,sampleRate,name='Shared sample',options={}}={}){
    if(options.target!==undefined&&options.target!=='score')throw Error('Choose the Spectral score target.');
    if(hasScore()&&options.replace!==true)throw Error('The spectral score already contains notes. Confirm replacement before importing.');
    const operation=++importOperation,generation=uiGeneration,revision=editRevision,snapshot=S.copy(state),signal=options.signal,isCurrent=()=>operation===importOperation&&generation===uiGeneration&&revision===editRevision;
    const result=await window.HazeAudio.analyzeAudio(pcm,sampleRate,snapshot,{signal,isCurrent});
    if(signal?.aborted||!isCurrent())throw new DOMException('Audio analysis cancelled because the score changed.','AbortError');
    remember();state.score=result.score;state.name=('Spectral study: '+String(name).replace(/[\u0000-\u001f\u007f]/g,'').trim()).slice(0,100);changed({custom:false});renderControls();status(`Analyzed ${result.seconds.toFixed(2)} seconds into an editable spectral score. Tuning and effects are preserved.`);
    return {target:'score',name:state.name,seconds:result.seconds,mode:'analysis'};
  }
  async function exportAudio({scope='score',bars=1,tailSeconds=0,signal}={}){
    if(scope!=='score')throw Error('Choose the Current score export.');
    const snapshot=S.copy(state),cycles=Math.min(16,Math.max(1,Math.round(Number(bars)||1))),name=(snapshot.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'haze')+'.wav';
    const blob=await engine.renderWav(cycles,tailSeconds,{signal,state:snapshot});return {blob,sampleRate:48000,name,tempo:snapshot.tempo,sourceApp:'haze',bars:cycles};
  }
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
  $('save-button').addEventListener('click',()=>{download(new Blob([S.serializeProject(state)],{type:'application/json'}),filename('.haze.json'));status('The whole recipe, saved in a project file.');});
  $('open-button').addEventListener('click',()=>{$('project-file').value='';$('project-file').click();});
  $('project-file').addEventListener('change',async()=>{const file=$('project-file').files[0];if(!file)return;const generation=uiGeneration;try{if(file.size>1024*1024)throw Error('Choose a STEAM project smaller than 1 MB.');const next=S.parseProject(await file.text());if(generation!==uiGeneration)return;applyState(next,{message:'Project opened. The extraction recipe is restored.'});}catch(e){if(generation===uiGeneration)status(e.message);}});
  async function finishCapture(limit=false){if(capturePending)return;const generation=uiGeneration,operation=++captureOperation;capturePending=true;renderTransport();try{const blob=await engine.stopRecording();if(generation!==uiGeneration||operation!==captureOperation)return;if(blob){download(blob,filename('-capture.wav'));status(limit?'Three-minute capture limit reached. Your recording is downloaded.':'Your live performance is captured.');}else status('Capture was empty. Play a little sound, then try again.');}catch(e){if(generation===uiGeneration&&operation===captureOperation)status(e.message);}finally{if(operation===captureOperation){capturePending=false;renderTransport();}}}
  $('capture-button').addEventListener('click',async()=>{if(capturePending)return;if(engine.isRecording){await finishCapture();return;}const generation=uiGeneration,operation=++captureOperation;capturePending=true;renderTransport();try{const started=await engine.startRecording();if(started&&generation===uiGeneration&&operation===captureOperation)status('Capturing the live stereo output. Press Finish to download.');}catch(e){if(generation===uiGeneration&&operation===captureOperation)status(e.message);}finally{if(operation===captureOperation){capturePending=false;renderTransport();}}});
  engine.onRecordingLimit=()=>finishCapture(true);
  $('export-button').addEventListener('click',async()=>{if(exportPending)return;exportPending=true;$('export-button').disabled=true;const name=filename('-render.wav');status('Rendering this spectral recipe to stereo WAV…');try{const blob=await engine.renderWav(Number($('export-bars').value),3);download(blob,name);status('Stereo WAV downloaded, with room for the echoes.');}catch(e){status(e.message);}finally{exportPending=false;$('export-button').disabled=false;}});
  $('help-button').addEventListener('click',()=>$('help-dialog').showModal());$('help-close').addEventListener('click',()=>$('help-dialog').close());$('help-dialog').addEventListener('click',e=>{if(e.target===$('help-dialog')){const r=$('help-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('help-dialog').close();}});
  if(location.protocol==='file:'){const home='https://calebhaines.github.io/sidequest-prototypes/music/';$('music-home').href=home;$('download-html').href=home+'haze/index.html';$('download-source').href=home+'haze/HAZE-source.zip';}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('help-dialog').open)return;panic();return;}if($('help-dialog').open)return;const editing=e.target.matches('input,select,textarea,[contenteditable]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!editing){e.preventDefault();undo();return;}if(e.code==='Space'&&!editing&&!e.repeat&&e.target!==canvas){e.preventDefault();togglePlay();}});
  function sizeCanvas(c,context){const r=c.getBoundingClientRect(),dpr=Math.min(3,window.devicePixelRatio||1),w=Math.max(1,Math.round(r.width*dpr)),h=Math.max(1,Math.round(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h;context.setTransform(dpr,0,0,dpr,0,0);return true;}context.setTransform(dpr,0,0,dpr,0,0);return false;}
  function drawScore(){
    sizeCanvas(canvas,ctx);const w=canvas.getBoundingClientRect().width,h=canvas.getBoundingClientRect().height;ctx.clearRect(0,0,w,h);
    layout={x:43,y:15,w:w-49,h:h-35,columns:detailView?8:32,bands:detailView?8:24,columnStart:detailView?detailColumn:0,bandStart:detailView?detailBand:0};
    const l=layout,cw=l.w/l.columns,ch=l.h/l.bands;ctx.font='9px "Haze Sans"';ctx.textBaseline='middle';ctx.fillStyle='#a0b5bc';ctx.textAlign='right';
    for(let row=0;row<l.bands;row++){const y=l.bandStart+row;if(!detailView&&row%3!==0)continue;const pitch=bandPitch(y);ctx.fillText(state.scale==='harmonic'?(y+1)+'×':pitch.note,l.x-7,l.y+(l.bands-1-row+.5)*ch);}
    ctx.textAlign='center';ctx.fillStyle='#a6b7b9';for(let col=0;col<l.columns;col++){const x=l.columnStart+col;if(!detailView&&x%4!==0)continue;ctx.fillText(String(x+1).padStart(2,'0'),l.x+(col+.5)*cw,h-8);}
    ctx.fillStyle='#0f191d';ctx.fillRect(l.x,l.y,l.w,l.h);
    const position=engine.getMeters().position,activeColumn=Math.floor(position),isActive=engine.isPlaying||state.freeze;
    for(let row=0;row<l.bands;row++)for(let col=0;col<l.columns;col++){
      const y=l.bandStart+row,x=l.columnStart+col,v=state.score[y][x],xx=l.x+col*cw+1,yy=l.y+(l.bands-1-row)*ch+1;
      ctx.fillStyle=x%4===0?'#233337':'#19272c';ctx.fillRect(xx,yy,Math.max(1,cw-1.5),Math.max(1,ch-1.5));
      if(v>.001){const hue=30+(y/23)*135,light=32+v*35;ctx.fillStyle=`hsla(${hue},${42+v*21}%,${light}%,${.45+v*.54})`;ctx.fillRect(xx,yy,Math.max(1,cw-1.5),Math.max(1,ch-1.5));if(isActive&&x===activeColumn){ctx.fillStyle='#f0f7e933';ctx.fillRect(xx,yy,Math.max(1,cw-1.5),Math.max(1,ch-1.5));}}
    }
    const px=l.x+(position-l.columnStart)/l.columns*l.w;
    if(isActive&&px>=l.x&&px<=l.x+l.w){const g=ctx.createLinearGradient(px-14,0,px+5,0);g.addColorStop(0,'#ddf6e900');g.addColorStop(1,'#ddf6e926');ctx.fillStyle=g;ctx.fillRect(Math.max(l.x,px-14),l.y,Math.min(19,l.x+l.w-Math.max(l.x,px-14)),l.h);ctx.strokeStyle='#effce9';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(px,l.y);ctx.lineTo(px,l.y+l.h);ctx.stroke();ctx.fillStyle='#b7dac6';ctx.beginPath();ctx.moveTo(px-4,l.y-8);ctx.lineTo(px+4,l.y-8);ctx.lineTo(px,l.y-2);ctx.fill();}
    if(selected.x>=l.columnStart&&selected.x<l.columnStart+l.columns&&selected.y>=l.bandStart&&selected.y<l.bandStart+l.bands){ctx.strokeStyle='#f7eed0';ctx.lineWidth=1.5;ctx.strokeRect(l.x+(selected.x-l.columnStart)*cw+.5,l.y+(l.bands-1-selected.y+l.bandStart)*ch+.5,Math.max(1,cw-1),Math.max(1,ch-1));}
  }
  function drawEnvelope(){sizeCanvas(envCanvas,envCtx);const r=envCanvas.getBoundingClientRect(),w=r.width,h=r.height;envCtx.clearRect(0,0,w,h);const total=state.attack+state.release+250,ax=12+(w-24)*state.attack/total,sx=ax+(w-24)*250/total,bottom=h-13,top=13;envCtx.strokeStyle='#333537';envCtx.lineWidth=1;envCtx.beginPath();envCtx.moveTo(10,bottom);envCtx.lineTo(w-10,bottom);envCtx.stroke();const g=envCtx.createLinearGradient(0,top,0,bottom);g.addColorStop(0,'#ff8d4525');g.addColorStop(1,'#ff8d4500');envCtx.beginPath();envCtx.moveTo(12,bottom);envCtx.quadraticCurveTo(12,top,ax,top);envCtx.lineTo(sx,top);envCtx.bezierCurveTo(sx+(w-sx)*.14,h*.72,w-30,bottom,w-12,bottom);envCtx.lineTo(12,bottom);envCtx.fillStyle=g;envCtx.fill();envCtx.beginPath();envCtx.moveTo(12,bottom);envCtx.quadraticCurveTo(12,top,ax,top);envCtx.lineTo(sx,top);envCtx.bezierCurveTo(sx+(w-sx)*.14,h*.72,w-30,bottom,w-12,bottom);envCtx.strokeStyle='#ff8d45';envCtx.lineWidth=1.5;envCtx.stroke();envCtx.fillStyle='#7f878a';envCtx.font='7px "Haze Sans"';envCtx.fillText('ATTACK',12,h-1);envCtx.textAlign='right';envCtx.fillText('RELEASE',w-12,h-1);envCtx.textAlign='left';}
  let lastFrame=0;function animate(now){if(now-lastFrame>31){lastFrame=now;const meters=engine.getMeters();if(paintDirty||engine.isPlaying||state.freeze){drawScore();paintDirty=false;}const db=meters.rms>1e-5?Math.max(-90,20*Math.log10(meters.rms)):-Infinity;$('output-db').innerHTML=(Number.isFinite(db)?db.toFixed(1):'−∞')+' <small>dB</small>';const meterWidth=v=>Math.min(100,Math.max(0,((v>1e-5?20*Math.log10(v):-90)+60)/60*100));$('meter-left').style.width=meterWidth(meters.rmsLeft||0)+'%';$('meter-right').style.width=meterWidth(meters.rmsRight||0)+'%';$('scan-position').textContent=`${String(Math.min(32,Math.floor(meters.position)+1)).padStart(2,'0')} / 32`;$('audio-mode').textContent=engine.mode==='idle'?'AUDIO ASLEEP':engine.mode==='worklet'?'AUDIOWORKLET · STEREO':'STANDALONE AUDIO · STEREO';if(engine.isRecording)$('capture-button').querySelector('span').textContent=`Finish ${Math.floor(meters.recordSeconds)}s`; }requestAnimationFrame(animate);}
  document.querySelector('.sound-bench').addEventListener('toggle',()=>{paintDirty=true;drawEnvelope();});
  const observer=new ResizeObserver(()=>{paintDirty=true;drawEnvelope();});observer.observe(canvas);observer.observe(envCanvas);window.addEventListener('resize',()=>{paintDirty=true;drawEnvelope();});document.fonts?.ready.then(()=>{paintDirty=true;drawEnvelope();});
  Object.defineProperty(window,'HazeApp',{value:Object.freeze({get state(){return S.copy(state);},get engine(){return engine;},getState:()=>S.copy(state),loadState:(s)=>applyState(s),selectCell,importAudio,exportAudio,get audioImport(){return {mode:'analysis',description:'Analyze audio into an editable spectral score.',maxSeconds:20,channels:1,decks:1,targets:[{id:'score',name:'Spectral score',occupied:hasScore(),assetName:hasScore()?state.name:''}]};},get audioExport(){return {scopes:[{id:'score',label:'Current score'}],defaultBars:1};}}),writable:false});
  renderControls();renderTransport();if(storageUnavailable)status('Browser storage is unavailable. Save a project to keep this recipe.');requestAnimationFrame(animate);
})();
