/* STEAM: the same bounded additive synthesizer in the worklet, fallback, and WAV renderer. */
(() => {
  'use strict';
  function createDSP(){
    const TAU=Math.PI*2,clamp=(v,a,b,d)=>Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;
    const scales={pentatonic:[0,3,5,7,10],minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],chromatic:[0,1,2,3,4,5,6,7,8,9,10,11]};
    function frequencyForBand(s,row){const root=440*Math.pow(2,(s.root-69)/12);if(s.scale==='harmonic')return root*Math.pow(row+1,s.stretch);const a=scales[s.scale]||scales.pentatonic,degree=a[row%a.length]+12*Math.floor(row/a.length);return root*Math.pow(2,degree*s.stretch/12);}
    function sanitize(r){const d={tempo:88,bars:2,direction:'forward',freeze:false,position:0,root:45,scale:'pentatonic',stretch:1,color:.26,drift:.15,blur:.15,attack:35,release:420,cutoff:9500,drive:.12,spread:.82,volume:.66,echo:.25,echoDivision:'3/16',feedback:.38,room:.28};const s=Object.assign({},d);for(const[k,a,b]of[['tempo',40,240],['stretch',.5,1.8],['color',0,1],['drift',0,1],['blur',0,1],['attack',2,1200],['release',10,5000],['cutoff',200,18000],['drive',0,1],['spread',0,1],['volume',0,1],['echo',0,1],['feedback',0,.82],['room',0,1],['position',0,31.999],['root',24,72]])s[k]=clamp(r?.[k],a,b,d[k]);s.bars=[1,2,4,8].includes(r?.bars)?r.bars:2;s.direction=['forward','reverse','pingpong'].includes(r?.direction)?r.direction:'forward';s.scale=Object.keys(scales).concat('harmonic').includes(r?.scale)?r.scale:'pentatonic';s.freeze=r?.freeze===true;s.echoDivision=['1/16','1/8','3/16','1/4','3/8','1/2'].includes(r?.echoDivision)?r.echoDivision:'3/16';s.score=Array.from({length:24},(_,y)=>Array.from({length:32},(_,x)=>clamp(r?.score?.[y]?.[x],0,1,0)));return s;}
    class Core{
      constructor(state,sampleRate=48000){this.sampleRate=clamp(sampleRate,8000,192000,48000);this.running=false;this.externalNotes=false;this.positionEvents=[];this.noteEvents=[];this.noteGates=[];this.cancellations=[];this.frame=0;this.position=0;this.travel=0;this.env=new Float64Array(24);this.phase=new Float64Array(48);this.freq=new Float64Array(24);this.targets=new Float64Array(24);this.leftPans=new Float64Array(24);this.rightPans=new Float64Array(24);this.filterL=0;this.filterR=0;const n=Math.ceil(this.sampleRate*4);this.delayL=new Float32Array(n);this.delayR=new Float32Array(n);this.roomL=new Float32Array(Math.ceil(this.sampleRate*1.3));this.roomR=new Float32Array(this.roomL.length);this.delayHead=0;this.roomHead=0;this.meters={peak:0,rms:0,position:0,spectrum:Array(24).fill(0)};this.setState(state);this.setPosition(this.state.position);}
      setState(raw){const old=this.state;this.state=sanitize(raw);for(let y=0;y<24;y++)this.freq[y]=frequencyForBand(this.state,y);if(old&&Math.abs(old.position-this.state.position)>.0001)this.setPosition(this.state.position);else if(old&&old.direction!==this.state.direction)this.setPosition(this.position);}
      setPosition(p){this.position=clamp(p,0,31.999,0);this.travel=this.state.direction==='reverse'?32-this.position:this.position;}
      scheduleNote(row,velocity,frame,durationFrames,source='native'){if(this.cancellations.some(c=>(!c.source||c.source===source)&&frame>=c.frame))return false;if(this.noteEvents.length>=8192)throw new Error('The note queue is full.');this.externalNotes=true;const event={row:Math.min(23,Math.max(0,Math.round(row))),velocity:Math.min(1,Math.max(0,velocity)),frame:Math.max(this.frame,Math.round(frame)),durationFrames:Math.max(1,Math.round(durationFrames)),source};let at=this.noteEvents.findIndex(e=>e.frame>event.frame);if(at<0)at=this.noteEvents.length;this.noteEvents.splice(at,0,event);}
      stopNotes(source,frame=this.frame){frame=Math.max(this.frame,Math.round(Number.isFinite(frame)?frame:this.frame));if(frame>this.frame){this.noteEvents=this.noteEvents.filter(e=>(source&&e.source!==source)||e.frame<frame);if(this.cancellations.length>=256)throw new Error('The cancellation queue is full.');this.cancellations.push({source,frame});this.cancellations.sort((a,b)=>a.frame-b.frame);return;}this.cancellations=source?this.cancellations.filter(c=>c.source!==source):[];this.noteEvents=source?this.noteEvents.filter(e=>e.source!==source):[];this.noteGates=source?this.noteGates.filter(e=>e.source!==source):[];if(!this.noteEvents.length&&!this.noteGates.length){this.externalNotes=false;this.targets.fill(0);}else this.updateTargets();}
      clearPositions(){this.positionEvents=[];}
      schedulePosition(position,frame){if(this.positionEvents.length>=8192)throw new Error('The position queue is full.');const event={position,frame:Math.max(this.frame,Math.round(frame))};let at=this.positionEvents.findIndex(e=>e.frame>event.frame);if(at<0)at=this.positionEvents.length;this.positionEvents.splice(at,0,event);}
      start(){this.running=true;}
      stop(){this.running=false;this.positionEvents=[];this.cancellations=[];}
      panic(){this.stopNotes();this.positionEvents=[];this.running=false;this.env.fill(0);this.targets.fill(0);this.phase.fill(0);this.delayL.fill(0);this.delayR.fill(0);this.roomL.fill(0);this.roomR.fill(0);this.filterL=this.filterR=0;this.meters={peak:0,rms:0,position:this.position,spectrum:Array(24).fill(0)};}
      updateTargets(){const s=this.state,p=this.position,base=Math.floor(p),f=p-base,blur=s.blur;
        const read=(y,x)=>s.score[Math.max(0,Math.min(23,y))][(x+32)%32];let total=0;
        for(let y=0;y<24;y++){let a=read(y,base)*(1-f)+read(y,base+1)*f;const t=(read(y,base-1)+read(y,base+2))*.5;const b=(read(y-1,base)*(1-f)+read(y-1,base+1)*f+read(y+1,base)*(1-f)+read(y+1,base+1)*f)*.5;a=a*(1-blur*.65)+t*blur*.25+b*blur*.4;if(this.externalNotes){a=this.running?a:0;for(const gate of this.noteGates)if(gate.row===y)a=Math.min(1,a+gate.velocity);}this.targets[y]=this.externalNotes?a:this.running?a:0;total+=a;const pan=((y/23)*2-1)*s.spread;this.leftPans[y]=Math.sqrt((1-pan)*.5);this.rightPans[y]=Math.sqrt((1+pan)*.5);}this.gain=.38/Math.sqrt(Math.max(1,total));}
      processBlock(left,right){const s=this.state,sr=this.sampleRate,len=Math.min(left.length,right.length),attack=1-Math.exp(-1/(s.attack*.001*sr)),release=1-Math.exp(-1/(s.release*.001*sr));const filter=1-Math.exp(-TAU*Math.min(s.cutoff,sr*.43)/sr),drive=1+s.drive*5,driveNorm=1/Math.sqrt(drive),div=s.echoDivision.split('/').map(Number),delay=Math.min(this.delayL.length-2,Math.round(sr*(60/s.tempo)*4*div[0]/div[1])),advance=32*s.tempo/(s.bars*240*sr);let peak=0,power=0,powerL=0,powerR=0;
        for(let i=0;i<len;i++){while(this.cancellations.length&&this.cancellations[0].frame<=this.frame){const cancel=this.cancellations.shift();this.stopNotes(cancel.source);}while(this.positionEvents.length&&this.positionEvents[0].frame<=this.frame)this.setPosition(this.positionEvents.shift().position);let notesChanged=false;while(this.noteEvents.length&&this.noteEvents[0].frame<=this.frame){const event=this.noteEvents.shift();if(this.noteGates.length>=128)this.noteGates.shift();this.noteGates.push({...event,endFrame:event.frame+event.durationFrames});notesChanged=true;}for(let n=this.noteGates.length-1;n>=0;n--)if(this.noteGates[n].endFrame<=this.frame){this.noteGates.splice(n,1);notesChanged=true;}if(notesChanged||(i&15)===0)this.updateTargets();let l=0,r=0;const seconds=this.frame/sr;
          for(let y=0;y<24;y++){const goal=this.targets[y];this.env[y]+=(goal-this.env[y])*(goal>this.env[y]?attack:release);if(this.env[y]<1e-6)continue;const drift=1+Math.sin(seconds*(.17+y*.013)*TAU+y*2.399)*s.drift*.008;const freq=Math.min(sr*.43,this.freq[y]*drift),overtone=freq*(2+s.color*.045*s.stretch);this.phase[y*2]=(this.phase[y*2]+TAU*freq/sr)%TAU;this.phase[y*2+1]=(this.phase[y*2+1]+TAU*Math.min(sr*.43,overtone)/sr)%TAU;const sample=(Math.sin(this.phase[y*2])+Math.sin(this.phase[y*2+1])*s.color*.55)*this.env[y]*this.gain;l+=sample*this.leftPans[y];r+=sample*this.rightPans[y];}
          this.filterL+=(l-this.filterL)*filter;this.filterR+=(r-this.filterR)*filter;l=Math.tanh(this.filterL*drive)*driveNorm;r=Math.tanh(this.filterR*drive)*driveNorm;
          const di=(this.delayHead-delay+this.delayL.length)%this.delayL.length,dl=this.delayL[di],dr=this.delayR[di];this.delayL[this.delayHead]=l+dr*s.feedback;this.delayR[this.delayHead]=r+dl*s.feedback;this.delayHead=(this.delayHead+1)%this.delayL.length;
          let roomL=0,roomR=0;for(const t of [.073,.113,.179,.293]){const ri=(this.roomHead-Math.floor(t*sr)+this.roomL.length)%this.roomL.length;roomL+=this.roomL[ri]*.19;roomR+=this.roomR[(ri+Math.floor(sr*.009))%this.roomR.length]*.19;}this.roomL[this.roomHead]=l+roomR*.48;this.roomR[this.roomHead]=r+roomL*.48;this.roomHead=(this.roomHead+1)%this.roomL.length;
          l=.98*Math.tanh((l+dl*s.echo+roomL*s.room)*s.volume*1.5);r=.98*Math.tanh((r+dr*s.echo+roomR*s.room)*s.volume*1.5);if(!Number.isFinite(l))l=0;if(!Number.isFinite(r))r=0;left[i]=l;right[i]=r;peak=Math.max(peak,Math.abs(l),Math.abs(r));power+=l*l+r*r;powerL+=l*l;powerR+=r*r;
          if(this.running&&!s.freeze){this.travel+=advance;if(s.direction==='pingpong'){const p=this.travel%64;this.position=p<32?p:63.999-p;}else if(s.direction==='reverse')this.position=(32-(this.travel%32))%32;else this.position=this.travel%32;}this.frame++;
        }this.meters={peak,rms:Math.sqrt(power/Math.max(1,len*2)),rmsLeft:Math.sqrt(powerL/Math.max(1,len)),rmsRight:Math.sqrt(powerR/Math.max(1,len)),position:this.position,spectrum:Array.from(this.env)};return this.meters;
      }
    }
    return {Core,frequencyForBand};
  }
  const DSP=createDSP();window.HazeDSP=Object.freeze(DSP);
  const processor=`const DSP=(${createDSP.toString()})();class HazeProcessor extends AudioWorkletProcessor{constructor(o){super();this.core=new DSP.Core(o.processorOptions.state,sampleRate);this.core.frame=currentFrame;this.record=false;this.recordId=0;this.frames=0;this.blocks=0;this.port.onmessage=e=>{const m=e.data;if(m.type==='state')this.core.setState(m.state);else if(m.type==='start')this.core.start();else if(m.type==='stop')this.core.stop();else if(m.type==='panic'){this.core.panic();this.record=false;}else if(m.type==='clearPositions')this.core.clearPositions();else if(m.type==='position'){if(Number.isFinite(m.frame))this.core.schedulePosition(m.position,m.frame);else this.core.setPosition(m.position);}else if(m.type==='note')this.core.scheduleNote(m.row,m.velocity,m.frame,m.durationFrames,m.source);else if(m.type==='stopNotes')this.core.stopNotes(m.source,m.frame);else if(m.type==='recordStart'){this.record=true;this.recordId=m.id;this.frames=0;}else if(m.type==='recordStop'){this.record=false;this.port.postMessage({type:'recordStopped',id:m.id});}};}process(inputs,outputs){const out=outputs[0];if(!out||out.length<2)return true;const m=this.core.processBlock(out[0],out[1]);if(this.record){const remain=sampleRate*180-this.frames,count=Math.min(out[0].length,remain);if(count>0){const l=out[0].slice(0,count),r=out[1].slice(0,count);this.port.postMessage({type:'recordChunk',id:this.recordId,left:l,right:r},[l.buffer,r.buffer]);this.frames+=count;}if(this.frames>=sampleRate*180){this.record=false;this.port.postMessage({type:'recordLimit',id:this.recordId});}}if(++this.blocks%12===0)this.port.postMessage({type:'meters',meters:m});return true;}}registerProcessor('haze-sky',HazeProcessor);`;
  function wav(chunks,sampleRate,frames){const buffer=new ArrayBuffer(44+frames*4),v=new DataView(buffer),put=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};put(0,'RIFF');v.setUint32(4,36+frames*4,true);put(8,'WAVE');put(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);put(36,'data');v.setUint32(40,frames*4,true);let at=44;for(const c of chunks)for(let i=0;i<c.left.length;i++){for(const x of [c.left[i],c.right[i]]){const q=Math.min(1,Math.max(-1,Number.isFinite(x)?x:0));v.setInt16(at,Math.round(q*(q<0?32768:32767)),true);at+=2;}}return new Blob([buffer],{type:'audio/wav'});}
  function checkOperation(signal,isCurrent){if(signal?.aborted||isCurrent&& !isCurrent())throw new DOMException('Audio operation cancelled.','AbortError');}
  const yieldTask=()=>new Promise(resolve=>setTimeout(resolve,0));
  function fft(real,imag){const n=real.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){const r=real[i],q=imag[i];real[i]=real[j];imag[i]=imag[j];real[j]=r;imag[j]=q;}}for(let size=2;size<=n;size<<=1){const angle=-2*Math.PI/size,stepR=Math.cos(angle),stepI=Math.sin(angle);for(let start=0;start<n;start+=size){let wr=1,wi=0;for(let j=0;j<size/2;j++){const a=start+j,b=a+size/2,tr=wr*real[b]-wi*imag[b],ti=wr*imag[b]+wi*real[b];real[b]=real[a]-tr;imag[b]=imag[a]-ti;real[a]+=tr;imag[a]+=ti;const next=wr*stepR-wi*stepI;wi=wr*stepI+wi*stepR;wr=next;}}}}
  // Analysis produces an editable score, rather than replacing the additive
  // engine with a sample player. Each column owns its audio interval, so a
  // transient cannot paint cells in a neighboring silent interval.
  async function analyzeAudio(pcm,sampleRate,settings,{signal,isCurrent}={}){
    checkOperation(signal,isCurrent);
    if(!ArrayBuffer.isView(pcm)||Object.prototype.toString.call(pcm)!=='[object Float32Array]'||pcm.length<64||pcm.length%2)throw Error('Choose stereo audio with complete left/right sample pairs.');
    if(!Number.isFinite(sampleRate)||sampleRate<8000||sampleRate>192000)throw Error('The audio sample rate must be between 8 and 192 kHz.');
    const frames=pcm.length/2,seconds=frames/sampleRate;if(seconds>20+.5/sampleRate)throw Error('STEAM analyzes up to 20 seconds. Trim the sample before importing.');
    const input=new Float32Array(pcm);let midPower=0,leftPower=0,rightPower=0;
    for(let i=0;i<frames;i++){const l=input[i*2],r=input[i*2+1];if(!Number.isFinite(l)||!Number.isFinite(r))throw Error('The sample contains invalid audio values.');const m=(l+r)*.5;midPower+=m*m;leftPower+=l*l;rightPower+=r*r;if((i&131071)===131071){await yieldTask();checkOperation(signal,isCurrent);}}
    // Keep anti-phase stereo material audible when a conventional mono
    // downmix would cancel almost completely.
    const channel=midPower<Math.max(leftPower,rightPower)*.01?(leftPower>=rightPower?0:1):-1,rate=Math.min(48000,sampleRate),length=Math.max(1,Math.floor(seconds*rate)),mono=new Float32Array(length),ratio=sampleRate/rate;
    for(let i=0;i<length;i++){const from=Math.floor(i*ratio),to=Math.min(frames,Math.max(from+1,Math.floor((i+1)*ratio)));let sum=0;for(let j=from;j<to;j++)sum+=channel<0?(input[j*2]+input[j*2+1])*.5:input[j*2+channel];mono[i]=sum/(to-from);if((i&131071)===131071){await yieldTask();checkOperation(signal,isCurrent);}}
    const state=window.HazeSchema.normalize(settings),frequencies=Array.from({length:24},(_,row)=>DSP.frequencyForBand(state,row)),edges=[0];for(let y=1;y<24;y++)edges.push(Math.min(rate/2,Math.sqrt(frequencies[y-1]*frequencies[y])));edges.push(rate/2);
    const score=Array.from({length:24},()=>Array(32).fill(0));let peak=0;
    for(let column=0;column<32;column++){
      checkOperation(signal,isCurrent);const from=Math.floor(column*length/32),to=Math.floor((column+1)*length/32),count=to-from;if(!count)continue;
      let n=256;while(n<count&&n<32768)n<<=1;const real=new Float64Array(n),imag=new Float64Array(n),offset=Math.floor((from+to-n)/2);let mean=0;for(let i=from;i<to;i++)mean+=mono[i];mean/=count;
      for(let i=0;i<n;i++){const at=offset+i;if(at>=from&&at<to)real[i]=(mono[at]-mean)*(.5-.5*Math.cos(2*Math.PI*i/(n-1)));}fft(real,imag);
      const resolution=rate/n;for(let row=0;row<24;row++){const low=edges[row],high=edges[row+1];if(high<=low)continue;let power=0,weight=0;const first=Math.max(1,Math.floor(low/resolution-.5)),last=Math.min(n/2-1,Math.ceil(high/resolution+.5));for(let bin=first;bin<=last;bin++){const overlap=Math.max(0,Math.min(high,(bin+.5)*resolution)-Math.max(low,(bin-.5)*resolution))/resolution;if(overlap){power+=(real[bin]*real[bin]+imag[bin]*imag[bin])*overlap;weight+=overlap;}}const value=Math.sqrt(power/Math.max(.0001,weight))/n;score[row][column]=value;peak=Math.max(peak,value);}
      if(column%2===1){await yieldTask();checkOperation(signal,isCurrent);}
    }
    if(peak<1e-9)throw Error('The sample has no audible spectral energy to paint.');
    for(const row of score)for(let x=0;x<32;x++){const value=row[x]/peak;row[x]=value>.025?Math.min(.95,Math.pow((value-.025)/.975,.72)*.95):0;}
    checkOperation(signal,isCurrent);return {score,seconds,sampleRate:rate};
  }
  class HazeAudio{
    constructor(state){this.state=window.HazeSchema.normalize(state);this.context=null;this.node=null;this.core=null;this.mode='idle';this.isPlaying=false;this.isRecording=false;this._generation=0;this._startRequest=0;this._recordRequest=0;this._recordId=0;this._recordStopId=0;this._chunks=[];this._recordFrames=0;this._meters={peak:0,rms:0,position:this.state.position,spectrum:Array(24).fill(0)};}
    async init(){if(this._init)return this._init;this._init=(async()=>{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('This browser does not support Web Audio.');this.context=new AC({latencyHint:'interactive'});if(this.context.audioWorklet&&window.AudioWorkletNode){let url;try{url=URL.createObjectURL(new Blob([processor],{type:'application/javascript'}));await this.context.audioWorklet.addModule(url);this.node=new AudioWorkletNode(this.context,'haze-sky',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2],processorOptions:{state:this.state}});this.node.port.onmessage=e=>this._message(e.data);this.mode='worklet';}catch{this.node=null;}finally{if(url)URL.revokeObjectURL(url);}}
      if(!this.node){this.core=new DSP.Core(this.state,this.context.sampleRate);this.node=this.context.createScriptProcessor(1024,0,2);this.node.onaudioprocess=e=>{const l=e.outputBuffer.getChannelData(0),r=e.outputBuffer.getChannelData(1);this.core.frame=Math.round(e.playbackTime*this.context.sampleRate);this._meters=this.core.processBlock(l,r);if(this.isRecording){const n=Math.min(l.length,this.context.sampleRate*180-this._recordFrames);if(n>0){this._chunks.push({left:l.slice(0,n),right:r.slice(0,n)});this._recordFrames+=n;}if(this._recordFrames>=this.context.sampleRate*180){this.isRecording=false;this.onRecordingLimit?.();}}};this.mode='fallback';}this.node.connect(this.context.destination);this._send({type:'state',state:this.state});return this;})().catch(e=>{this._init=null;throw e;});return this._init;}
    _message(m){if(m.type==='meters')this._meters=m.meters;else if(m.type==='recordChunk'&&m.id===this._recordId){this._chunks.push({left:m.left,right:m.right});this._recordFrames+=m.left.length;}else if(m.type==='recordLimit'&&m.id===this._recordId){this.isRecording=false;this.onRecordingLimit?.();}else if(m.type==='recordStopped'&&this._recordStopped?.id===m.id){this._recordStopped.resolve();this._recordStopped=null;}}
    _send(m){if(this.mode==='worklet'){this.node.port.postMessage(m);return;}if(!this.core)return;if(m.type==='state')this.core.setState(m.state);else if(m.type==='start')this.core.start();else if(m.type==='stop')this.core.stop();else if(m.type==='panic')this.core.panic();else if(m.type==='clearPositions')this.core.clearPositions();else if(m.type==='position'){if(Number.isFinite(m.frame))this.core.schedulePosition(m.position,m.frame);else this.core.setPosition(m.position);}else if(m.type==='note')this.core.scheduleNote(m.row,m.velocity,m.frame,m.durationFrames,m.source);else if(m.type==='stopNotes')this.core.stopNotes(m.source,m.frame);}
    setState(s){this.state=window.HazeSchema.normalize(s);this._send({type:'state',state:this.state});}
    setPosition(p){this.state.position=Math.min(31.999,Math.max(0,Number(p)||0));this._meters.position=this.state.position;this._send({type:'position',position:this.state.position});}
    async start(){const generation=this._generation,request=++this._startRequest;await this.init();if(generation!==this._generation||request!==this._startRequest)return false;await this.context.resume();if(generation!==this._generation||request!==this._startRequest)return false;this.isPlaying=true;this._send({type:'start'});return true;}
    stop(){this._startRequest++;this.isPlaying=false;this._send({type:'stop'});}
    panic(){this._generation++;this._startRequest++;this._recordRequest++;this._recordId++;this.isPlaying=false;this.isRecording=false;this._chunks=[];this._recordFrames=0;this._send({type:'panic'});if(this._recordStopped){this._recordStopped.resolve();this._recordStopped=null;}this._meters={peak:0,rms:0,position:this._meters.position,spectrum:Array(24).fill(0)};}
    scheduleNote({voiceId='0',velocity=.8,when,durationSeconds=.25,source='loom'}={}){if(!this.context||!this.node)throw new Error('Prepare the instrument before scheduling notes.');const row=Number(voiceId);if(!Number.isInteger(row)||row<0||row>23)throw new Error('Choose one of STEAM’s twenty-four tuned bands.');this._send({type:'note',row,velocity,frame:Math.round(Math.max(this.context.currentTime,Number(when)||this.context.currentTime)*this.context.sampleRate),durationFrames:Math.max(1,Math.round(durationSeconds*this.context.sampleRate)),source});return true;}
    stopNotes({source,when}={}){this._send({type:'stopNotes',source,frame:this.context?Math.round(Math.max(this.context.currentTime,Number.isFinite(when)?when:this.context.currentTime)*this.context.sampleRate):undefined});}
    clearClockPositions(){this._send({type:'clearPositions'});}
    seekBeat(beat,{when}={}){const beats=this.state.bars*4,p=((Number(beat)||0)%beats+beats)%beats,position=p/beats*32;if(this.context&&Number.isFinite(when)&&when>this.context.currentTime)this._send({type:'position',position,frame:Math.round(when*this.context.sampleRate)});else this.setPosition(position);}
    async renderNotes({events,tempo=120,lengthBeats=4,tailSeconds=3,signal,state=this.state}={}){checkOperation(signal);const snapshot=window.HazeSchema.normalize(state);snapshot.tempo=tempo;const sr=48000,body=lengthBeats*60/tempo,tail=Math.min(30,Math.max(0,Number(tailSeconds)||0));if(!Number.isFinite(body)||body<=0||body+tail>180)throw new Error('Pattern render must be between zero and 180 seconds.');const core=new DSP.Core(snapshot,sr),frames=Math.ceil((body+tail)*sr),chunks=[];for(const e of events)core.scheduleNote(Number(e.voiceId??0),e.velocity,Math.round(e.startBeat*60/tempo*sr),Math.round(e.durationBeats*60/tempo*sr));for(let at=0;at<frames;){checkOperation(signal);const n=Math.min(1024,frames-at),left=new Float32Array(n),right=new Float32Array(n);core.processBlock(left,right);chunks.push({left,right});at+=n;if(chunks.length%80===0)await yieldTask();}checkOperation(signal);return{blob:wav(chunks,sr,frames),sampleRate:sr,tempo,sourceApp:'haze'};}
    getMeters(){return Object.assign({},this._meters,{recordSeconds:this.context?this._recordFrames/this.context.sampleRate:0,mode:this.mode});}
    async startRecording(){if(this.isRecording||this._stopPromise)return false;const generation=this._generation,request=++this._recordRequest;await this.init();if(generation!==this._generation||request!==this._recordRequest)return false;await this.context.resume();if(generation!==this._generation||request!==this._recordRequest)return false;this._chunks=[];this._recordFrames=0;this._recordId++;this.isRecording=true;if(this.mode==='worklet')this.node.port.postMessage({type:'recordStart',id:this._recordId});return true;}
    stopRecording(){if(this._stopPromise)return this._stopPromise;this._stopPromise=this._finishRecording().finally(()=>{this._stopPromise=null;});return this._stopPromise;}
    async _finishRecording(){const generation=this._generation;this._recordRequest++;this.isRecording=false;if(this.mode==='worklet'){await new Promise(resolve=>{const id=++this._recordStopId;this._recordStopped={id,resolve};this.node.port.postMessage({type:'recordStop',id});});}if(generation!==this._generation)return null;const chunks=this._chunks,frames=this._recordFrames;this._chunks=[];this._recordFrames=0;if(!frames)return null;return wav(chunks,this.context.sampleRate,frames);}
    async renderWav(bars=this.state.bars,tailSeconds=3,{signal,state=this.state}={}){checkOperation(signal);const s=window.HazeSchema.normalize(state),sr=48000,cycles=Math.min(16,Math.max(1,Math.round(Number(bars)||s.bars))),tail=Math.min(30,Math.max(0,Number(tailSeconds)||0)),main=Math.round(cycles*240/s.tempo*sr),total=main+Math.round(tail*sr),core=new DSP.Core(s,sr),chunks=[];core.start();for(let at=0;at<total;){checkOperation(signal);if(at===main)core.stop();const count=Math.min(1024,total-at,at<main?main-at:total-at),left=new Float32Array(count),right=new Float32Array(count);core.processBlock(left,right);chunks.push({left,right});at+=count;if(chunks.length%80===0)await yieldTask();}checkOperation(signal);return wav(chunks,sr,total);}
  }
  HazeAudio.analyzeAudio=analyzeAudio;
  window.HazeAudio=HazeAudio;
})();
