/* HAZE: the same bounded additive synthesizer in the worklet, fallback, and WAV renderer. */
(() => {
  'use strict';
  function createDSP(){
    const TAU=Math.PI*2,clamp=(v,a,b,d)=>Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;
    const scales={pentatonic:[0,3,5,7,10],minor:[0,2,3,5,7,8,10],major:[0,2,4,5,7,9,11],chromatic:[0,1,2,3,4,5,6,7,8,9,10,11]};
    function frequencyForBand(s,row){const root=440*Math.pow(2,(s.root-69)/12);if(s.scale==='harmonic')return root*Math.pow(row+1,s.stretch);const a=scales[s.scale]||scales.pentatonic,degree=a[row%a.length]+12*Math.floor(row/a.length);return root*Math.pow(2,degree*s.stretch/12);}
    function sanitize(r){const d={tempo:88,bars:2,direction:'forward',freeze:false,position:0,root:45,scale:'pentatonic',stretch:1,color:.26,drift:.15,blur:.15,attack:35,release:420,cutoff:9500,drive:.12,spread:.82,volume:.66,echo:.25,echoDivision:'3/16',feedback:.38,room:.28};const s=Object.assign({},d);for(const[k,a,b]of[['tempo',40,180],['stretch',.5,1.8],['color',0,1],['drift',0,1],['blur',0,1],['attack',2,1200],['release',10,5000],['cutoff',200,18000],['drive',0,1],['spread',0,1],['volume',0,1],['echo',0,1],['feedback',0,.82],['room',0,1],['position',0,31.999],['root',24,72]])s[k]=clamp(r?.[k],a,b,d[k]);s.bars=[1,2,4,8].includes(r?.bars)?r.bars:2;s.direction=['forward','reverse','pingpong'].includes(r?.direction)?r.direction:'forward';s.scale=Object.keys(scales).concat('harmonic').includes(r?.scale)?r.scale:'pentatonic';s.freeze=r?.freeze===true;s.echoDivision=['1/16','1/8','3/16','1/4','3/8','1/2'].includes(r?.echoDivision)?r.echoDivision:'3/16';s.score=Array.from({length:24},(_,y)=>Array.from({length:32},(_,x)=>clamp(r?.score?.[y]?.[x],0,1,0)));return s;}
    class Core{
      constructor(state,sampleRate=48000){this.sampleRate=clamp(sampleRate,8000,192000,48000);this.running=false;this.frame=0;this.position=0;this.travel=0;this.env=new Float64Array(24);this.phase=new Float64Array(48);this.freq=new Float64Array(24);this.targets=new Float64Array(24);this.leftPans=new Float64Array(24);this.rightPans=new Float64Array(24);this.filterL=0;this.filterR=0;const n=Math.ceil(this.sampleRate*4);this.delayL=new Float32Array(n);this.delayR=new Float32Array(n);this.roomL=new Float32Array(Math.ceil(this.sampleRate*1.3));this.roomR=new Float32Array(this.roomL.length);this.delayHead=0;this.roomHead=0;this.meters={peak:0,rms:0,position:0,spectrum:Array(24).fill(0)};this.setState(state);this.setPosition(this.state.position);}
      setState(raw){const old=this.state;this.state=sanitize(raw);for(let y=0;y<24;y++)this.freq[y]=frequencyForBand(this.state,y);if(old&&Math.abs(old.position-this.state.position)>.0001)this.setPosition(this.state.position);else if(old&&old.direction!==this.state.direction)this.setPosition(this.position);}
      setPosition(p){this.position=clamp(p,0,31.999,0);this.travel=this.state.direction==='reverse'?32-this.position:this.position;}
      start(){this.running=true;}
      stop(){this.running=false;}
      panic(){this.running=false;this.env.fill(0);this.targets.fill(0);this.phase.fill(0);this.delayL.fill(0);this.delayR.fill(0);this.roomL.fill(0);this.roomR.fill(0);this.filterL=this.filterR=0;this.meters={peak:0,rms:0,position:this.position,spectrum:Array(24).fill(0)};}
      updateTargets(){const s=this.state,p=this.position,base=Math.floor(p),f=p-base,blur=s.blur;
        const read=(y,x)=>s.score[Math.max(0,Math.min(23,y))][(x+32)%32];let total=0;
        for(let y=0;y<24;y++){let a=read(y,base)*(1-f)+read(y,base+1)*f;const t=(read(y,base-1)+read(y,base+2))*.5;const b=(read(y-1,base)*(1-f)+read(y-1,base+1)*f+read(y+1,base)*(1-f)+read(y+1,base+1)*f)*.5;a=a*(1-blur*.65)+t*blur*.25+b*blur*.4;this.targets[y]=this.running?a:0;total+=a;const pan=((y/23)*2-1)*s.spread;this.leftPans[y]=Math.sqrt((1-pan)*.5);this.rightPans[y]=Math.sqrt((1+pan)*.5);}this.gain=.38/Math.sqrt(Math.max(1,total));}
      processBlock(left,right){const s=this.state,sr=this.sampleRate,len=Math.min(left.length,right.length),attack=1-Math.exp(-1/(s.attack*.001*sr)),release=1-Math.exp(-1/(s.release*.001*sr));const filter=1-Math.exp(-TAU*Math.min(s.cutoff,sr*.43)/sr),drive=1+s.drive*5,driveNorm=1/Math.sqrt(drive),div=s.echoDivision.split('/').map(Number),delay=Math.min(this.delayL.length-2,Math.round(sr*(60/s.tempo)*4*div[0]/div[1])),advance=32*s.tempo/(s.bars*240*sr);let peak=0,power=0,powerL=0,powerR=0;
        for(let i=0;i<len;i++){if((i&15)===0)this.updateTargets();let l=0,r=0;const seconds=this.frame/sr;
          for(let y=0;y<24;y++){const goal=this.targets[y];this.env[y]+=(goal-this.env[y])*(goal>this.env[y]?attack:release);if(this.env[y]<1e-6)continue;const drift=1+Math.sin(seconds*(.17+y*.013)*TAU+y*2.399)*s.drift*.008;const freq=Math.min(sr*.43,this.freq[y]*drift),overtone=freq*(2+s.color*.045*s.stretch);this.phase[y*2]=(this.phase[y*2]+TAU*freq/sr)%TAU;this.phase[y*2+1]=(this.phase[y*2+1]+TAU*Math.min(sr*.43,overtone)/sr)%TAU;const sample=(Math.sin(this.phase[y*2])+Math.sin(this.phase[y*2+1])*s.color*.55)*this.env[y]*this.gain;l+=sample*this.leftPans[y];r+=sample*this.rightPans[y];}
          this.filterL+=(l-this.filterL)*filter;this.filterR+=(r-this.filterR)*filter;l=Math.tanh(this.filterL*drive)*driveNorm;r=Math.tanh(this.filterR*drive)*driveNorm;
          const di=(this.delayHead-delay+this.delayL.length)%this.delayL.length,dl=this.delayL[di],dr=this.delayR[di];this.delayL[this.delayHead]=l+dr*s.feedback;this.delayR[this.delayHead]=r+dl*s.feedback;this.delayHead=(this.delayHead+1)%this.delayL.length;
          let roomL=0,roomR=0;for(const t of [.073,.113,.179,.293]){const ri=(this.roomHead-Math.floor(t*sr)+this.roomL.length)%this.roomL.length;roomL+=this.roomL[ri]*.19;roomR+=this.roomR[(ri+Math.floor(sr*.009))%this.roomR.length]*.19;}this.roomL[this.roomHead]=l+roomR*.48;this.roomR[this.roomHead]=r+roomL*.48;this.roomHead=(this.roomHead+1)%this.roomL.length;
          l=.98*Math.tanh((l+dl*s.echo+roomL*s.room)*s.volume*1.5);r=.98*Math.tanh((r+dr*s.echo+roomR*s.room)*s.volume*1.5);if(!Number.isFinite(l))l=0;if(!Number.isFinite(r))r=0;left[i]=l;right[i]=r;peak=Math.max(peak,Math.abs(l),Math.abs(r));power+=l*l+r*r;powerL+=l*l;powerR+=r*r;
          if(this.running&&!s.freeze){this.travel+=advance;if(s.direction==='pingpong'){const p=this.travel%64;this.position=p<32?p:63.999-p;}else if(s.direction==='reverse')this.position=(32-(this.travel%32))%32;else this.position=this.travel%32;}this.frame++;
        }this.meters={peak,rms:Math.sqrt(power/Math.max(1,len*2)),rmsLeft:Math.sqrt(powerL/Math.max(1,len)),rmsRight:Math.sqrt(powerR/Math.max(1,len)),position:this.position,spectrum:Array.from(this.env)};return this.meters;
      }
    }
    return {Core,frequencyForBand};
  }
  const DSP=createDSP();window.HazeDSP=Object.freeze(DSP);
  const processor=`const DSP=(${createDSP.toString()})();class HazeProcessor extends AudioWorkletProcessor{constructor(o){super();this.core=new DSP.Core(o.processorOptions.state,sampleRate);this.record=false;this.recordId=0;this.frames=0;this.blocks=0;this.port.onmessage=e=>{const m=e.data;if(m.type==='state')this.core.setState(m.state);else if(m.type==='start')this.core.start();else if(m.type==='stop')this.core.stop();else if(m.type==='panic'){this.core.panic();this.record=false;}else if(m.type==='position')this.core.setPosition(m.position);else if(m.type==='recordStart'){this.record=true;this.recordId=m.id;this.frames=0;}else if(m.type==='recordStop'){this.record=false;this.port.postMessage({type:'recordStopped',id:m.id});}};}process(inputs,outputs){const out=outputs[0];if(!out||out.length<2)return true;const m=this.core.processBlock(out[0],out[1]);if(this.record){const remain=sampleRate*180-this.frames,count=Math.min(out[0].length,remain);if(count>0){const l=out[0].slice(0,count),r=out[1].slice(0,count);this.port.postMessage({type:'recordChunk',id:this.recordId,left:l,right:r},[l.buffer,r.buffer]);this.frames+=count;}if(this.frames>=sampleRate*180){this.record=false;this.port.postMessage({type:'recordLimit',id:this.recordId});}}if(++this.blocks%12===0)this.port.postMessage({type:'meters',meters:m});return true;}}registerProcessor('haze-sky',HazeProcessor);`;
  function wav(chunks,sampleRate,frames){const buffer=new ArrayBuffer(44+frames*4),v=new DataView(buffer),put=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};put(0,'RIFF');v.setUint32(4,36+frames*4,true);put(8,'WAVE');put(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,2,true);v.setUint32(24,sampleRate,true);v.setUint32(28,sampleRate*4,true);v.setUint16(32,4,true);v.setUint16(34,16,true);put(36,'data');v.setUint32(40,frames*4,true);let at=44;for(const c of chunks)for(let i=0;i<c.left.length;i++){for(const x of [c.left[i],c.right[i]]){const q=Math.min(1,Math.max(-1,Number.isFinite(x)?x:0));v.setInt16(at,Math.round(q*(q<0?32768:32767)),true);at+=2;}}return new Blob([buffer],{type:'audio/wav'});}
  class HazeAudio{
    constructor(state){this.state=window.HazeSchema.normalize(state);this.context=null;this.node=null;this.core=null;this.mode='idle';this.isPlaying=false;this.isRecording=false;this._generation=0;this._startRequest=0;this._recordRequest=0;this._recordId=0;this._recordStopId=0;this._chunks=[];this._recordFrames=0;this._meters={peak:0,rms:0,position:this.state.position,spectrum:Array(24).fill(0)};}
    async init(){if(this._init)return this._init;this._init=(async()=>{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('This browser does not support Web Audio.');this.context=new AC({latencyHint:'interactive'});if(this.context.audioWorklet&&window.AudioWorkletNode){let url;try{url=URL.createObjectURL(new Blob([processor],{type:'application/javascript'}));await this.context.audioWorklet.addModule(url);this.node=new AudioWorkletNode(this.context,'haze-sky',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2],processorOptions:{state:this.state}});this.node.port.onmessage=e=>this._message(e.data);this.mode='worklet';}catch{this.node=null;}finally{if(url)URL.revokeObjectURL(url);}}
      if(!this.node){this.core=new DSP.Core(this.state,this.context.sampleRate);this.node=this.context.createScriptProcessor(1024,0,2);this.node.onaudioprocess=e=>{const l=e.outputBuffer.getChannelData(0),r=e.outputBuffer.getChannelData(1);this._meters=this.core.processBlock(l,r);if(this.isRecording){const n=Math.min(l.length,this.context.sampleRate*180-this._recordFrames);if(n>0){this._chunks.push({left:l.slice(0,n),right:r.slice(0,n)});this._recordFrames+=n;}if(this._recordFrames>=this.context.sampleRate*180){this.isRecording=false;this.onRecordingLimit?.();}}};this.mode='fallback';}this.node.connect(this.context.destination);this._send({type:'state',state:this.state});return this;})().catch(e=>{this._init=null;throw e;});return this._init;}
    _message(m){if(m.type==='meters')this._meters=m.meters;else if(m.type==='recordChunk'&&m.id===this._recordId){this._chunks.push({left:m.left,right:m.right});this._recordFrames+=m.left.length;}else if(m.type==='recordLimit'&&m.id===this._recordId){this.isRecording=false;this.onRecordingLimit?.();}else if(m.type==='recordStopped'&&this._recordStopped?.id===m.id){this._recordStopped.resolve();this._recordStopped=null;}}
    _send(m){if(this.mode==='worklet'){this.node.port.postMessage(m);return;}if(!this.core)return;if(m.type==='state')this.core.setState(m.state);else if(m.type==='start')this.core.start();else if(m.type==='stop')this.core.stop();else if(m.type==='panic')this.core.panic();else if(m.type==='position')this.core.setPosition(m.position);}
    setState(s){this.state=window.HazeSchema.normalize(s);this._send({type:'state',state:this.state});}
    setPosition(p){this.state.position=Math.min(31.999,Math.max(0,Number(p)||0));this._meters.position=this.state.position;this._send({type:'position',position:this.state.position});}
    async start(){const generation=this._generation,request=++this._startRequest;await this.init();if(generation!==this._generation||request!==this._startRequest)return false;await this.context.resume();if(generation!==this._generation||request!==this._startRequest)return false;this.isPlaying=true;this._send({type:'start'});return true;}
    stop(){this._startRequest++;this.isPlaying=false;this._send({type:'stop'});}
    panic(){this._generation++;this._startRequest++;this._recordRequest++;this._recordId++;this.isPlaying=false;this.isRecording=false;this._chunks=[];this._recordFrames=0;this._send({type:'panic'});if(this._recordStopped){this._recordStopped.resolve();this._recordStopped=null;}this._meters={peak:0,rms:0,position:this._meters.position,spectrum:Array(24).fill(0)};}
    getMeters(){return Object.assign({},this._meters,{recordSeconds:this.context?this._recordFrames/this.context.sampleRate:0,mode:this.mode});}
    async startRecording(){if(this.isRecording||this._stopPromise)return false;const generation=this._generation,request=++this._recordRequest;await this.init();if(generation!==this._generation||request!==this._recordRequest)return false;await this.context.resume();if(generation!==this._generation||request!==this._recordRequest)return false;this._chunks=[];this._recordFrames=0;this._recordId++;this.isRecording=true;if(this.mode==='worklet')this.node.port.postMessage({type:'recordStart',id:this._recordId});return true;}
    stopRecording(){if(this._stopPromise)return this._stopPromise;this._stopPromise=this._finishRecording().finally(()=>{this._stopPromise=null;});return this._stopPromise;}
    async _finishRecording(){const generation=this._generation;this._recordRequest++;this.isRecording=false;if(this.mode==='worklet'){await new Promise(resolve=>{const id=++this._recordStopId;this._recordStopped={id,resolve};this.node.port.postMessage({type:'recordStop',id});});}if(generation!==this._generation)return null;const chunks=this._chunks,frames=this._recordFrames;this._chunks=[];this._recordFrames=0;if(!frames)return null;return wav(chunks,this.context.sampleRate,frames);}
    async renderWav(bars=this.state.bars,tailSeconds=3){const s=window.HazeSchema.normalize(this.state),sr=48000,cycles=Math.min(16,Math.max(1,Math.round(Number(bars)||s.bars))),tail=Math.min(10,Math.max(0,Number(tailSeconds)||0)),main=Math.round(cycles*240/s.tempo*sr),total=main+Math.round(tail*sr),core=new DSP.Core(s,sr),chunks=[];core.start();for(let at=0;at<total;){if(at===main)core.stop();const count=Math.min(1024,total-at,at<main?main-at:total-at),left=new Float32Array(count),right=new Float32Array(count);core.processBlock(left,right);chunks.push({left,right});at+=count;if(chunks.length%80===0)await new Promise(r=>setTimeout(r,0));}return wav(chunks,sr,total);}
  }
  window.HazeAudio=HazeAudio;
})();
