(function () {
  'use strict';
  const S=window.MarinadeSchema, Sources=window.MarinadeSources, Analysis=window.MarinadeAnalysis;
  const sequence=window.MarinadeSequence||window.createMarinadeSequence(), $=id=>document.getElementById(id), copy=value=>S.copy(value);
  const hosted=window.parent!==window||!!window.MusicLabHost, controls=new Map(), listeners=new Set();
  const presets=window.MarinadePresets?.list||[], catalog=Sources.catalog||[];
  const names={lp:'Low-pass',hp:'High-pass',bp:'Band-pass',pingpong:'Back & forth',loop:'Loop',oneShot:'Play once',free:'Free running',sampleHold:'Sample & hold',morph:'Spectral blend',pitchBlend:'Pitch blend',position:'Source position',formant:'Formant shift',cutoff:'Filter cutoff',pan:'Stereo pan',single:'Single note',major:'Major',minor:'Minor',fifth:'Open fifth',sus2:'Suspended 2',dorian:'Dorian',pentatonic:'Pentatonic',chromatic:'Chromatic',sine:'Sine',triangle:'Triangle',saw:'Saw',square:'Square'};
  let state,history=[],future=[],transaction=null,transactionTarget=null,selectedStep=0;
  let stateRevision=0,importOperation=0,transportOperation=0,displayOperation=0,presetOperation=0,autosaveTimer,storageFailed=false,exportAbort=null,importCommit=Promise.resolve();
  const sourceOperations=[0,0];
  let keyboardBase=48,keyVelocity=.85,midiAccess=null,lastMeterTime=0,playingStep=-1,visualModels=null;
  const activeKeys=new Map(),midiBindings=new Map(),previews=new Map(),sourceDisplayCache=new Map();
  function sourceDisplay(ref){const key=ref.kind==='factory'?'factory:'+ref.id:ref.data;let cached=sourceDisplayCache.get(key);if(cached)return cached;const audio=Sources.resolve(ref),pcm=audio.pcm[0],bins=Math.min(2048,pcm.length),low=new Float32Array(bins),high=new Float32Array(bins);for(let i=0;i<pcm.length;i++){const bin=Math.min(bins-1,Math.floor(i/pcm.length*bins)),value=pcm[i];low[bin]=Math.min(low[bin],value);high[bin]=Math.max(high[bin],value);}cached={audio,low,high,bins};if(sourceDisplayCache.size>=4)sourceDisplayCache.delete(sourceDisplayCache.keys().next().value);sourceDisplayCache.set(key,cached);return cached;}
  const initial=presets[0]?.state||S.defaultState();
  try { const saved=!hosted&&localStorage.getItem('marinade-project-v1');state=saved?S.parseProject(saved):S.normalize(initial); } catch(_){state=S.normalize(initial);storageFailed=true;}
  const engine=new window.MarinadeAudio(copy(state));
  const pct=v=>Math.round(v*100)+'%',signed=v=>(v>0?'+':'')+Number(v.toFixed(2)),seconds=v=>v<1?Math.round(v*1000)+' ms':Number(v.toFixed(2))+' s',hz=v=>v>=1000?Number((v/1000).toFixed(2))+' kHz':Number(v.toFixed(2))+' Hz';
  const get=(path,source=state)=>path.split('.').reduce((o,k)=>o?.[k],source);
  function set(path,value,source=state){const parts=path.split('.'),last=parts.pop();parts.reduce((o,k)=>o[k],source)[last]=value;}
  const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
  function status(message){$('status').textContent=message;}
  function filename(suffix){return(state.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'marinade-recipe')+suffix;}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function renderHistory(){$('undoButton').disabled=!history.length;$('redoButton').disabled=!future.length;}
  function remember(previous){if(equal(previous,state))return;history.push(copy(previous));if(history.length>40)history.shift();future=[];renderHistory();}
  function finishTransaction(){if(transaction){remember(transaction);transaction=null;transactionTarget=null;}}
  function storageNotice(){$('storageNotice').hidden=!storageFailed;$('storageNotice').textContent='Browser recovery is unavailable or full. Save project to keep your ingredients and recipe.';}
  function saveRecovery(){clearTimeout(autosaveTimer);if(hosted)return;autosaveTimer=setTimeout(()=>{try{localStorage.setItem('marinade-project-v1',S.serialize(state));storageFailed=false;}catch(_){storageFailed=true;}storageNotice();},850);}
  function notifyState(){saveRecovery();window.MusicLabHost?.notifyStateChange?.();for(const fn of listeners){try{fn(copy(state));}catch(_){}}}
  async function updateEngine(){const revision=++stateRevision;try{await engine.setState(copy(state));if(revision===stateRevision){visualModels=engine.models||visualModels;drawDisplays();}}catch(error){if(revision===stateRevision&&error.name!=='AbortError')status('Spectral analysis: '+error.message);}}
  function changed({notify=true,full=true}={}){state=S.normalize(state);const update=updateEngine();if(full)render();else{renderControls();renderSteps();drawDisplays();}if(notify)notifyState();return update;}
  function mutate(fn,message){finishTransaction();const previous=copy(state);fn(state);state=S.normalize(state);remember(previous);$('presetSelect').value='';changed();if(message)status(message);}
  async function applyState(value,{notify=true}={}){finishTransaction();state=S.normalize(typeof value==='function'?value(copy(state)):value);await changed({notify});return copy(state);}
  async function setTempo(value){const number=Number(value);if(!Number.isFinite(number)||number<20||number>400)throw new Error('Choose a tempo from 20 to 400 BPM.');state.tempo=number;await changed({full:false});return state.tempo;}
  async function loadState(value){const next=S.parseProject(value);finishTransaction();++importOperation;++transportOperation;cancelExport();releaseKeyboard();stopPreviews();engine.stop();engine.panic();const previous=copy(state);state=next;selectedStep=Math.min(selectedStep,state.sequence.length-1);remember(previous);$('presetSelect').value='';await changed();status('Loaded '+state.name+'.');return copy(state);}
  async function undo(){finishTransaction();if(!history.length)return;future.push(copy(state));state=history.pop();++importOperation;releaseKeyboard();stopPreviews();await changed();$('presetSelect').value='';status('Previous edit restored, ingredients included.');}
  async function redo(){finishTransaction();if(!future.length)return;history.push(copy(state));state=future.pop();++importOperation;releaseKeyboard();stopPreviews();await changed();$('presetSelect').value='';status('Edit reapplied.');}
  function optionList(select,items){select.replaceChildren();for(const item of items){const pair=Array.isArray(item)?item:[item,names[item]||item],o=document.createElement('option');o.value=pair[0];o.textContent=pair[1];select.append(o);}}
  const range=(path,label,bounds,step=.01,format=pct,extra={})=>({path,label,type:'range',min:bounds[0],max:bounds[1],step,format,...extra});
  const choice=(path,label,items,extra={})=>({path,label,type:'select',items,...extra});
  function createControls(container,defs){for(const def of defs){const label=document.createElement('label');label.className='control';const top=document.createElement('span'),name=document.createElement('span');name.textContent=def.label;top.append(name);let output;if(def.type==='range'){output=document.createElement('output');top.append(output);}label.append(top);const input=document.createElement(def.type==='select'?'select':'input');if(def.type!=='select')input.type=def.type;input.dataset.path=def.path;input.id=def.id||def.path.replace(/[.{}]/g,'-');input.setAttribute('aria-label',def.label);if(def.title)input.title=def.title;if(def.type==='select')optionList(input,def.items);else{input.min=def.min;input.max=def.max;input.step=def.step;output.htmlFor=input.id;}label.append(input);$(container).append(label);controls.set(input,{def,output,label});}}
  function buildControls(){
    for(let bay=0;bay<2;bay++){const letter=bay?'B':'A',prefix='samples.'+bay;const custom=document.createElement('option');custom.value='';custom.textContent='Your imported ingredient';custom.disabled=true;$('factory'+letter).append(custom);let group;for(const entry of catalog){if(!group||group.label!==entry.family){group=document.createElement('optgroup');group.label=entry.family;$('factory'+letter).append(group);}const option=document.createElement('option');option.value=entry.id;option.textContent=entry.name;group.append(option);}createControls('sourceControls'+letter,[range(prefix+'.trimStart','TRIM START',[0,.999],.001,pct),range(prefix+'.trimEnd','TRIM END',[.001,1],.001,pct),choice(prefix+'.rootNote','SOURCE ROOT',Array.from({length:128},(_,n)=>[n,S.noteName(n)]),{numeric:true,title:'The original pitch of this ingredient. Tune it here before playing.'}),range(prefix+'.position','FREEZE POSITION',[0,1],.001,pct,{title:'The spectral frame at which scanning starts; enable Freeze to hold it.'}),choice(prefix+'.freeze','SPECTRUM',[[false,'Scan the sample'],[true,'Freeze this moment']],{boolean:true}),range(prefix+'.gain','SOURCE GAIN',[0,2],.01,v=>Number(v.toFixed(2))+'×'),choice(prefix+'.reverse','DIRECTION',[[false,'Forward'],[true,'Reverse']],{boolean:true})]);}
    createControls('pathControls',[choice('morphPath.enabled','PATH MOVEMENT',[[true,'Follow the drawing'],[false,'Keep blend still']],{boolean:true}),range('morphPath.beats','PATH DURATION',[1,32],1,v=>v+' beats'),range('morphPath.depth','PATH DEPTH',[0,1]),range('synth.scanRate','SCAN SPEED',[-2,2],.01,v=>signed(v)+'×',{title:'Negative values reverse the scan; zero holds the selected positions.'})]);
    createControls('morphControls',[range('synth.pitchBlend','PITCH BLEND',[0,1],.001,v=>Math.round((1-v)*100)+' A / '+Math.round(v*100)+' B',{title:'Interpolate the frequencies independently from their amplitudes.'}),range('synth.texture','NOISE TEXTURE',[0,1],.01,pct,{title:'Rebuild the residual breath, friction, and noise of the source pair.'}),range('synth.textureBlend','TEXTURE BLEND',[0,1],.01,v=>Math.round((1-v)*100)+' A / '+Math.round(v*100)+' B',{title:'Choose which ingredient supplies the breath, friction, and noise.'}),range('synth.transient','ATTACK DETAIL',[0,1],.01,pct,{title:'Blend in the original first 180 ms for recognizable strikes and consonants.'}),range('synth.transientBlend','ATTACK BLEND',[0,1],.01,v=>Math.round((1-v)*100)+' A / '+Math.round(v*100)+' B',{title:'Choose which ingredient supplies the original strike or consonant.'}),range('synth.formantShift','FORMANT SHIFT',[-24,24],.1,v=>signed(v)+' st',{title:'Move the spectral envelope without transposing the played note.'}),choice('synth.formantLock','FORMANT TRACKING',[[true,'Keep the vowel shape'],[false,'Follow note pitch']],{boolean:true}),range('synth.inharmonic','CROOKED PARTIALS',[0,1],.01,pct,{title:'Spread partials away from tuned harmonics toward metallic intervals.'}),range('synth.smear','SPECTRAL SMEAR',[0,1],.01,pct,{title:'Smooth neighbouring spectral lanes into a softer ingredient.'}),range('synth.spread','PARTIAL SPREAD',[0,1],.01,pct,{title:'Spread reconstructed harmonics across the stereo field.'}),choice('synth.scanMode','SCAN MODE',['pingpong','loop','oneShot'])]);
    for(const [container,prefix] of [['ampControls','synth.amp'],['filterEnvControls','synth.filterEnv']])createControls(container,['attack','decay','sustain','release'].map(k=>range(prefix+'.'+k,k.toUpperCase(),k==='sustain'?[0,1]:k==='release'?[.005,12]:[.001,8],k==='sustain'?.01:.001,k==='sustain'?pct:seconds)));
    createControls('filterControls',[choice('synth.filter.type','FILTER',['lp','hp','bp']),range('synth.filter.cutoff','CUTOFF',[20,20000],1,hz),range('synth.filter.resonance','RESONANCE',[0,.85]),range('synth.filter.envAmount','ENVELOPE DEPTH',[-5,5],.01,v=>signed(v)+' oct'),range('synth.filter.keytrack','KEY TRACKING',[0,1])]);
    createControls('lfoControls',[choice('synth.lfo.shape','LFO SHAPE',['sine','triangle','saw','square','sampleHold']),range('synth.lfo.rate','FREE RATE',[.02,20],.01,hz),choice('synth.lfo.sync','TEMPO SYNC',['free','1/1','1/2','1/4','1/8','1/16','1/8T','1/16T']),range('synth.lfo.depth','MOD DEPTH',[0,1]),choice('synth.lfo.target','DESTINATION',['morph','pitchBlend','position','formant','cutoff','pan']),choice('synth.lfo.retrigger','LFO PHASE',[[false,'Continuous motion'],[true,'Restart each note']],{boolean:true})]);
    createControls('fxControls',[range('fx.drive','DRIVE',[0,1]),range('fx.chorus','CHORUS',[0,1]),range('fx.delay','DELAY',[0,1]),choice('fx.delayDivision','DELAY TIME',['1/32','1/16','1/8','3/16','1/4','3/8','1/2','1/1']),range('fx.feedback','DELAY FEEDBACK',[0,.85]),range('fx.space','ROOM',[0,1]),range('fx.width','STEREO WIDTH',[0,1.5],.01,v=>Number(v.toFixed(2))+'×'),range('fx.volume','OUTPUT',[0,1])]);
    createControls('sequenceControls',[range('sequence.transpose','PATTERN TRANSPOSE',[-36,36],1,v=>signed(v)+' st'),range('sequence.gate','PATTERN NOTE GATE',[.05,2],.01,pct)]);
    createControls('stepControls',[choice('sequence.steps.{step}.note','NOTE',Array.from({length:128},(_,n)=>[n,S.noteName(n)]),{numeric:true,id:'stepNote'}),choice('sequence.steps.{step}.chord','CHORD',['single','major','minor','fifth','sus2'],{id:'stepChord'}),range('sequence.steps.{step}.velocity','VELOCITY',[0,1],.01,pct,{id:'stepVelocity'}),range('sequence.steps.{step}.gate','GATE',[.05,2],.01,v=>Number(v.toFixed(2))+'×',{id:'stepGate'}),range('sequence.steps.{step}.probability','CHANCE',[0,1],.01,pct,{id:'stepProbability'}),range('sequence.steps.{step}.ratchet','RATCHET',[1,4],1,v=>v+' hits',{id:'stepRatchet'}),range('sequence.steps.{step}.offset','TIMING OFFSET',[-.45,.45],.01,v=>signed(Math.round(v*100))+'%',{id:'stepOffset'})]);
    optionList($('root'),Array.from({length:128},(_,n)=>[n,S.noteName(n)]));optionList($('scale'),['major','minor','dorian','pentatonic','chromatic']);optionList($('division'),['1/32','1/16','1/16T','1/8','1/8T','1/4']);
    presets.forEach((preset,index)=>{const option=document.createElement('option');option.value=preset.id||String(index);option.textContent=String(index+1).padStart(2,'0')+' / '+preset.name;$('presetSelect').append(option);});$('tempo').min=20;$('tempo').max=400;
  }
  function renderControls(){for(const [input,{def,output,label}]of controls){const path=def.path.replace('{step}',selectedStep);input.dataset.path=path;const value=get(path);if(document.activeElement!==input)input.value=String(value);const inactive=path==='synth.lfo.rate'&&state.synth.lfo.sync!=='free';input.disabled=inactive;label.classList.toggle('inactive',inactive);if(output)output.textContent=def.format(Number(value));if(input.type==='range'){input.style.setProperty('--fill',((value-def.min)/(def.max-def.min)*100)+'%');input.setAttribute('aria-valuetext',def.format(Number(value)));}}for(const input of document.querySelectorAll('[data-path]')){if(controls.has(input))continue;const value=get(input.dataset.path);if(document.activeElement!==input)input.value=value;if(input.type==='range')input.style.setProperty('--fill',((value-Number(input.min))/(Number(input.max)-Number(input.min))*100)+'%');}$('swingValue').textContent=pct(state.swing);$('patternLength').value=state.sequence.length;$('stepIndex').textContent=String(selectedStep+1).padStart(2,'0');const step=state.sequence.steps[selectedStep];$('stepToggle').textContent=step.on?'On':'Off';$('stepToggle').setAttribute('aria-pressed',String(step.on));$('stepProtect').checked=step.protect;$('importedNotice').hidden=!state.musicLabPattern;$('pathDuration').textContent=state.morphPath.beats+' BEATS';
    state.samples.forEach((sample,index)=>{const letter=index?'B':'A',entry=sample.ref.kind==='factory'?catalog.find(x=>x.id===sample.ref.id):null;$('sourceName'+letter).textContent=entry?.name||sample.ref.name||'Imported ingredient';$('sourceKind'+letter).textContent=entry?'FACTORY SOURCE':'IMPORTED AUDIO';$('sourceNote'+letter).textContent=entry?.description||'Your ingredient. Mono spectral analysis; polyphonic stereo result.';let duration=sample.ref.frames/sample.ref.sampleRate;if(entry)duration=entry.seconds;$('sourceDuration'+letter).textContent=Number.isFinite(duration)?duration.toFixed(2)+' s / '+S.noteName(sample.rootNote):S.noteName(sample.rootNote);if(document.activeElement!==$('factory'+letter)){$('factory'+letter).value=entry?.id||'';}});
  }
  function renderSteps(){if(!$('steps').children.length)for(let i=0;i<16;i++){const button=document.createElement('button');button.className='step-cell';button.dataset.step=i;const num=document.createElement('span');num.className='step-number';num.textContent=String(i+1).padStart(2,'0');const note=document.createElement('span');note.className='step-note';const velocity=document.createElement('span');velocity.className='step-velocity';velocity.append(document.createElement('i'));const flags=document.createElement('span');flags.className='step-flags';button.append(num,note,velocity,flags);button.addEventListener('click',()=>{finishTransaction();selectedStep=i;renderControls();renderSteps();});button.addEventListener('dblclick',()=>mutate(s=>s.sequence.steps[i].on=!s.sequence.steps[i].on));$('steps').append(button);}for(let i=0;i<16;i++){const button=$('steps').children[i],step=state.sequence.steps[i];button.classList.toggle('selected',i===selectedStep);button.classList.toggle('off',!step.on);button.classList.toggle('outside',i>=state.sequence.length);button.classList.toggle('playing',engine.isPlaying&&i===playingStep);button.setAttribute('aria-pressed',String(i===selectedStep));button.setAttribute('aria-label','Step '+(i+1)+', '+S.noteName(step.note)+', '+(step.on?'on':'off')+', '+Math.round(step.velocity*100)+' percent velocity'+(step.protect?', protected':''));button.querySelector('.step-note').textContent=i>=state.sequence.length?'—':step.on?S.noteName(step.note):'OFF';button.querySelector('.step-velocity i').style.height=step.velocity*100+'%';button.querySelector('.step-flags').textContent=(step.protect?'◆':'')+(step.ratchet>1?step.ratchet+'×':step.chord!=='single'?'♫':'');}}
  function renderTransport(){const playing=!!engine.isPlaying;$('playButton').setAttribute('aria-pressed',String(playing));$('playLabel').textContent=playing?'Playing':'Play';$('transportLamp').classList.toggle('active',playing);$('transportStatus').textContent=playing?'INFUSING':'READY TO INFUSE';}
  function render(){renderControls();renderSteps();renderHistory();renderTransport();storageNotice();drawDisplays();}
  function canvas(id){const element=$(id),ratio=Math.min(2,window.devicePixelRatio||1),width=Math.max(1,element.clientWidth),height=Math.max(1,element.clientHeight);element.width=Math.round(width*ratio);element.height=Math.round(height*ratio);const ctx=element.getContext('2d');ctx.scale(ratio,ratio);return{ctx,width,height};}
  function drawWave(index){const letter=index?'B':'A',{ctx,width,height}=canvas('wave'+letter),sample=state.samples[index];let cached;try{cached=sourceDisplay(sample.ref);}catch(_){return;}const top=height*.5,colour=index?'#81cec2':'#f3946f';ctx.fillStyle=index?'#81cec213':'#f3946f13';ctx.fillRect(sample.trimStart*width,0,(sample.trimEnd-sample.trimStart)*width,height);ctx.strokeStyle=index?'#81cec225':'#f3946f25';ctx.beginPath();ctx.moveTo(0,top);ctx.lineTo(width,top);ctx.stroke();ctx.strokeStyle=colour;ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<width;x++){const start=Math.floor(x/width*cached.bins),end=Math.min(cached.bins,Math.max(start+1,Math.floor((x+1)/width*cached.bins)));let low=0,high=0;for(let p=start;p<end;p++){low=Math.min(low,cached.low[p]);high=Math.max(high,cached.high[p]);}ctx.moveTo(x,top-high*height*.42);ctx.lineTo(x,top-low*height*.42);}ctx.stroke();ctx.fillStyle='#07151bb9';ctx.fillRect(0,0,sample.trimStart*width,height);ctx.fillRect(sample.trimEnd*width,0,(1-sample.trimEnd)*width,height);const position=sample.trimStart+(sample.trimEnd-sample.trimStart)*(sample.reverse?1-sample.position:sample.position),x=position*width;ctx.strokeStyle='#dfecb8';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x,3);ctx.lineTo(x,height-3);ctx.stroke();ctx.setLineDash([]);}
  function drawPath(meter={}){const{ctx,width,height}=canvas('pathCanvas'),pad=8;ctx.strokeStyle='#42645355';ctx.lineWidth=1;for(let i=0;i<=4;i++){const x=pad+i*(width-pad*2)/4;ctx.beginPath();ctx.moveTo(x,pad);ctx.lineTo(x,height-pad);ctx.stroke();const y=pad+i*(height-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(width-pad,y);ctx.stroke();}const points=state.morphPath.points;ctx.beginPath();points.forEach((value,index)=>{const x=pad+index/15*(width-2*pad),y=pad+(1-value)*(height-2*pad);index?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle=state.morphPath.enabled?'#d5ed83':'#748870';ctx.lineWidth=2;ctx.shadowColor='#d5ed83';ctx.shadowBlur=state.morphPath.enabled?5:0;ctx.stroke();ctx.shadowBlur=0;ctx.lineTo(width-pad,height-pad);ctx.lineTo(pad,height-pad);ctx.closePath();ctx.fillStyle='#bfd97612';ctx.fill();for(let i=0;i<16;i++){ctx.fillStyle='#cee699';ctx.fillRect(pad+i/15*(width-2*pad)-1.5,pad+(1-points[i])*(height-2*pad)-1.5,3,3);}ctx.fillStyle='#75948d';ctx.font='8px monospace';ctx.fillText('B',3,10);ctx.fillText('A',3,height-3);if((engine.isPlaying||meter.voices)&&state.morphPath.enabled){const phase=Number.isFinite(meter.pathPhase)?meter.pathPhase:((Number(meter.beat)||0)%state.morphPath.beats)/state.morphPath.beats,x=pad+phase*(width-2*pad);ctx.strokeStyle='#e0f2ad55';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();ctx.setLineDash([]);}}
  function drawSpectrum(meter={}){const{ctx,width,height}=canvas('spectrumCanvas'),models=engine.models||visualModels,blend=Number.isFinite(meter.morph)&&meter.voices?meter.morph:state.synth.morph;ctx.strokeStyle='#71a96d1b';ctx.lineWidth=1;for(let i=1;i<6;i++){const y=i/6*(height-17);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}for(let i=0;i<8;i++){const x=i/8*width;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height-14);ctx.stroke();}if(models?.length===2){const amplitudes=models.map((model,index)=>{const pos=(meter.voices&&Number.isFinite(meter.scanPositions?.[index])?meter.scanPositions[index]:state.samples[index].position),frame=Math.min(model.frames-1,Math.max(0,Math.round(pos*(model.frames-1))));return Array.from({length:model.lanes},(_,lane)=>Number(model.amplitudes[frame*model.lanes+lane])||0);}),lanes=Math.min(amplitudes[0].length,amplitudes[1].length),mid=meter.voices&&meter.spectrum?.length===lanes?Array.from(meter.spectrum):amplitudes[0].map((v,i)=>v*(1-blend)+amplitudes[1][i]*blend),max=Math.max(.015,...amplitudes.flat(),...mid);const y=v=>height-20-Math.log(1+v/max*30)/Math.log(31)*(height-34);const draw=(values,colour,fill=false)=>{ctx.beginPath();for(let i=0;i<lanes;i++){const x=i/(lanes-1)*width;i?ctx.lineTo(x,y(values[i])):ctx.moveTo(x,y(values[i]));}ctx.strokeStyle=colour;ctx.lineWidth=fill?1.8:1;ctx.globalAlpha=fill?1:.45;ctx.stroke();if(fill){ctx.lineTo(width,height-20);ctx.lineTo(0,height-20);ctx.closePath();const gradient=ctx.createLinearGradient(0,0,0,height);gradient.addColorStop(0,'#d5ed833f');gradient.addColorStop(1,'#d5ed8300');ctx.fillStyle=gradient;ctx.fill();}ctx.globalAlpha=1;};draw(amplitudes[0],'#f3946f');draw(amplitudes[1],'#81cec2');ctx.shadowColor='#d5ed83';ctx.shadowBlur=5;draw(mid,'#d5ed83',true);ctx.shadowBlur=0;}else{ctx.fillStyle='#7c9c80';ctx.font='10px monospace';ctx.fillText('ANALYSING THE INGREDIENTS…',9,height*.5);}ctx.fillStyle='#72977c';ctx.font='8px monospace';ctx.fillText('LOW',1,height-2);ctx.fillText('HARMONIC SPECTRUM',Math.max(30,width/2-43),height-2);ctx.fillText('HIGH',width-21,height-2);$('fusionReadout').textContent='A '+Math.round((1-blend)*100)+' : '+Math.round(blend*100)+' B';}
  function drawEnvelope(){const{ctx,width,height}=canvas('ampCanvas'),env=state.synth.amp,pad=7,total=env.attack+env.decay+env.release+.5,points=[[pad,height-pad],[pad+env.attack/total*(width-pad*2),pad],[pad+(env.attack+env.decay)/total*(width-pad*2),height-pad-env.sustain*(height-pad*2)],[pad+(env.attack+env.decay+.5)/total*(width-pad*2),height-pad-env.sustain*(height-pad*2)],[width-pad,height-pad]];ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle='#a9cba1';ctx.lineWidth=1.5;ctx.stroke();ctx.lineTo(width-pad,height);ctx.lineTo(pad,height);ctx.closePath();ctx.fillStyle='#9ebe8b17';ctx.fill();}
  function drawDisplays(){drawWave(0);drawWave(1);drawSpectrum();drawPath();drawEnvelope();}
  async function refreshAnalysis(){const operation=++displayOperation;try{const models=await Analysis.prepare(copy(state));if(operation===displayOperation){visualModels=models;drawDisplays();}}catch(error){if(operation===displayOperation&&error.name!=='AbortError')status('Spectral analysis: '+error.message);}}
  async function play(options={}){finishTransaction();const operation=++transportOperation;try{await engine.start(options);if(operation!==transportOperation){engine.stop();return;}renderTransport();status('The ingredients are getting acquainted.');}catch(error){if(operation===transportOperation)status('Audio could not start: '+error.message);}}
  function stop(){++transportOperation;engine.stop();stopPreviews();playingStep=-1;renderTransport();renderSteps();status('Stopped. The flavour stays.');}
  function panic(){++transportOperation;releaseKeyboard();stopPreviews();engine.panic();renderTransport();renderSteps();status('All notes silenced.');}
  async function restart(){stop();await play({beat:0});}
  function chordNotes(){const offsets={minor9:[0,3,7,10,14],major7:[0,4,7,11],sus2:[0,2,7,12],fifth:[0,7,12]}[$('chordType').value]||[0,3,7];return offsets.map(n=>Math.max(0,Math.min(127,state.root+n)));}
  async function exportAudio(options={}){const snapshot=options.state?S.normalize(options.state):copy(state);return engine.renderWav({...options,state:snapshot,chordNotes:options.chordNotes||chordNotes()});}
  function cancelExport(){exportAbort?.abort();exportAbort=null;document.body.classList.remove('is-exporting');$('wavButton').disabled=false;$('cancelExportButton').hidden=true;}
  async function exportWav(){cancelExport();const controller=new AbortController();exportAbort=controller;document.body.classList.add('is-exporting');$('wavButton').disabled=true;$('cancelExportButton').hidden=false;const name=filename('.wav'),scope=$('exportScope').value,bars=Math.min(16,Math.max(1,Number($('exportBars').value)||4));status('Printing stereo WAV… your live recipe remains playable.');try{const result=await exportAudio({state:copy(state),scope,bars,signal:controller.signal});if(controller.signal.aborted||exportAbort!==controller)return;download(result.blob||result,name);status('Stereo WAV bottled and ready.');}catch(error){if(!controller.signal.aborted)status('WAV render failed: '+error.message);}finally{if(exportAbort===controller)cancelExport();}}
  function stopPreviews(){for(const preview of previews.values()){try{preview.source.stop();}catch(_){}try{preview.source.disconnect();preview.gain.disconnect();}catch(_){}$('audition'+preview.letter).textContent='▶ Hear '+preview.letter;}previews.clear();}
  async function audition(index){const letter=index?'B':'A';if(previews.has(index)){const p=previews.get(index);p.source.stop();return;}try{await engine.init();const audio=sourceDisplay(state.samples[index].ref).audio,ctx=engine.context,sample=state.samples[index],first=Math.floor(sample.trimStart*audio.pcm[0].length),last=Math.max(first+1,Math.ceil(sample.trimEnd*audio.pcm[0].length)),length=last-first,buffer=ctx.createBuffer(1,length,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=audio.pcm[0][sample.reverse?last-1-i:first+i];const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=buffer;gain.gain.value=sample.gain*.45;source.connect(gain);gain.connect(ctx.destination);previews.set(index,{source,gain,letter});$('audition'+letter).textContent='■ Stop '+letter;source.onended=()=>{if(previews.get(index)?.source===source){previews.delete(index);$('audition'+letter).textContent='▶ Hear '+letter;}source.disconnect();gain.disconnect();};source.start();status('Original ingredient '+letter+' / '+audio.name+'.');}catch(error){status('Source audition unavailable: '+error.message);}}
  function abortCheck(signal){if(signal?.aborted)throw new DOMException('Audio import cancelled.','AbortError');}
  function splitPCM(payload){const pcm=payload?.pcm,rate=Number(payload?.sampleRate);if(!Number.isFinite(rate)||rate<8000||rate>192000)throw new Error('Choose audio with a sample rate between 8 and 192 kHz.');const typed=value=>Object.prototype.toString.call(value)==='[object Float32Array]'||Object.prototype.toString.call(value)==='[object Float64Array]';let planar;if(Array.isArray(pcm)){if(pcm.length<1||pcm.length>2||pcm.some(c=>!typed(c)))throw new Error('Provide one or two floating-point audio channels.');planar=pcm;}else{if(!typed(pcm))throw new Error('Provide floating-point audio samples.');const channels=payload.channels===1?1:2;if(pcm.length%channels)throw new Error('Audio must contain complete stereo frames.');const frames=pcm.length/channels;planar=Array.from({length:channels},()=>new Float32Array(frames));for(let i=0;i<frames;i++)for(let c=0;c<channels;c++)planar[c][i]=pcm[i*channels+c];}const frames=planar[0].length;if(!Number.isInteger(frames)||frames<1||frames/rate>20.00001||planar.some(c=>c.length!==frames))throw new Error('Choose a sample up to 20 seconds with matching audio channels.');for(const channel of planar)for(const value of channel)if(!Number.isFinite(value)||Math.abs(value)>16)throw new Error('The audio contains invalid sample values.');return{pcm:planar,sampleRate:rate,name:String(payload.name||'Imported ingredient').slice(0,120)};}
  async function importAudio(payload,extra={}){const options={...(payload?.options||{}),...extra},signal=options.signal||payload?.signal,target=options.target,index=target==='a'?0:target==='b'?1:-1;if(index<0)throw new Error('Choose Source A or Source B as the destination.');if(!options.replace)throw new Error('Choose Replace to put this sample into '+(index?'Source B':'Source A')+'.');abortCheck(signal);const audio=splitPCM(payload),ref=Sources.encodeAudio(audio),operation=++sourceOperations[index],projectOperation=importOperation,originalRef=copy(state.samples[index].ref),letter=index?'B':'A';$('sourceBay'+letter).classList.add('busy');status('Analysing ingredient '+letter+'…');try{const candidate=copy(state);candidate.samples[index]={...candidate.samples[index],ref,trimStart:0,trimEnd:1,position:.15,freeze:false,reverse:false};await Analysis.prepare(candidate,{signal});abortCheck(signal);const commit=importCommit.then(async()=>{abortCheck(signal);if(operation!==sourceOperations[index]||projectOperation!==importOperation||!equal(state.samples[index].ref,originalRef))throw new DOMException('A newer ingredient replaced this import.','AbortError');finishTransaction();const next=copy(state);next.samples[index]=candidate.samples[index];try{await engine.setState(next);abortCheck(signal);if(operation!==sourceOperations[index]||projectOperation!==importOperation||!equal(state.samples[index].ref,originalRef))throw new DOMException('A newer ingredient replaced this import.','AbortError');}catch(error){await engine.setState(copy(state));throw error;}const previous=copy(state);state={...copy(state),samples:state.samples.map((bay,i)=>i===index?copy(candidate.samples[index]):copy(bay))};remember(previous);$('presetSelect').value='';await changed();visualModels=engine.models||visualModels;render();status('Ingredient '+letter+' / '+ref.name+' imported. Save project includes its audio.');return{target,name:ref.name,sampleRate:ref.sampleRate,frames:ref.frames,channels:1};});importCommit=commit.catch(()=>{});return await commit;}finally{if(operation===sourceOperations[index])$('sourceBay'+letter).classList.remove('busy');}}
  async function importFile(file,index){if(!file)return;const operation=++sourceOperations[index],projectOperation=importOperation;if(file.size>64*1024*1024){status('Choose an audio file smaller than 64 MB.');return;}try{await engine.init();const bytes=await file.arrayBuffer();if(operation!==sourceOperations[index]||projectOperation!==importOperation)throw new DOMException('A newer source operation replaced this file.','AbortError');const decoded=await engine.context.decodeAudioData(bytes);if(operation!==sourceOperations[index]||projectOperation!==importOperation)throw new DOMException('A newer source operation replaced this file.','AbortError');const pcm=Array.from({length:Math.min(2,decoded.numberOfChannels)},(_,c)=>decoded.getChannelData(c));await importAudio({pcm,sampleRate:decoded.sampleRate,name:file.name.replace(/\.[^.]+$/,'')},{target:index?'b':'a',replace:true});}catch(error){if(error.name!=='AbortError')status('Audio import failed: '+error.message);}}
  function readInput(input){const def=controls.get(input)?.def;if(def?.boolean)return input.value==='true';if(input.type==='range'||input.type==='number'||def?.numeric||input.dataset.path==='root')return Number(input.value);return input.value;}
  document.addEventListener('pointerdown',event=>{const input=event.target.closest('[data-path]');if(input&&!input.disabled){finishTransaction();transaction=copy(state);transactionTarget=input;}});
  document.addEventListener('focusin',event=>{if(event.target.matches('[data-path]')&&!transaction){transaction=copy(state);transactionTarget=event.target;}});
  document.addEventListener('input',event=>{const input=event.target;if(!input.matches('[data-path]')||input.disabled)return;if(transactionTarget!==input){finishTransaction();transaction=copy(state);transactionTarget=input;}const value=readInput(input);if(typeof value==='number'&&!Number.isFinite(value))return;const path=input.dataset.path;if(path.endsWith('.trimStart')){const i=Number(path.split('.')[1]);set(path,Math.min(value,state.samples[i].trimEnd-.001));}else if(path.endsWith('.trimEnd')){const i=Number(path.split('.')[1]);set(path,Math.max(value,state.samples[i].trimStart+.001));}else set(path,value);$('presetSelect').value='';changed({full:false});});
  document.addEventListener('change',event=>{if(event.target.matches('[data-path]')){finishTransaction();renderControls();}});document.addEventListener('focusout',event=>{if(event.target===transactionTarget){finishTransaction();renderControls();}});
  $('patternLength').addEventListener('change',()=>mutate(s=>{s.sequence.length=Math.max(1,Math.min(16,Number($('patternLength').value)||16));selectedStep=Math.min(selectedStep,s.sequence.length-1);},'Pattern length changed.'));
  $('stepToggle').addEventListener('click',()=>mutate(s=>s.sequence.steps[selectedStep].on=!s.sequence.steps[selectedStep].on));$('stepProtect').addEventListener('change',()=>mutate(s=>s.sequence.steps[selectedStep].protect=$('stepProtect').checked));
  $('clearPatternButton').addEventListener('click',()=>mutate(s=>{s.sequence.steps.forEach(step=>step.on=false);delete s.musicLabPattern;},'Pattern cleared. Undo restores every note.'));
  $('allStepsButton').addEventListener('click',()=>mutate(s=>{s.sequence.steps.forEach(step=>step.on=true);delete s.musicLabPattern;},'All sixteen steps enabled.'));
  $('mutateButton').addEventListener('click',()=>mutate(s=>{let seed=(s.seed^0x9e3779b9)>>>0;const random=()=>{seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;return(seed>>>0)/4294967296;},scale=S.SCALES[s.scale]||[0,2,3,5,7,8,10];for(const step of s.sequence.steps){if(step.protect)continue;step.note=Math.max(0,Math.min(127,s.root+scale[Math.floor(random()*scale.length)]+(random()>.7?12:0)));step.on=random()>.15;step.velocity=.48+random()*.47;step.ratchet=random()>.89?2:1;step.probability=random()>.87?.72:1;step.gate=.65+random()*.5;}s.seed=(seed+1)>>>0;delete s.musicLabPattern;},'A little seasoning. Protected steps kept.'));
  $('recipeButton').addEventListener('click',()=>mutate(s=>{const recipe=$('noteRecipe').value,notes={minor:[0,7,12,3,10,7,14,12],major:[0,7,12,4,11,7,16,14],pentatonic:[0,3,5,7,10,12,15,17],chord:[0,3,7,10,12,10,7,3],bass:[-24,-12,-24,-17,-24,-14,-12,-17]}[recipe]||[0,3,7];s.sequence.steps.forEach((step,i)=>{if(step.protect)return;step.note=Math.max(0,Math.min(127,s.root+notes[i%notes.length]));step.on=true;step.chord='single';step.ratchet=1;step.velocity=i%4===0?.9:.65;});delete s.musicLabPattern;},'Note recipe applied. Protected steps kept.'));
  $('presetSelect').addEventListener('change',async()=>{const operation=++presetOperation,id=$('presetSelect').value,preset=presets.find((p,i)=>(p.id||String(i))===id);if(!preset)return;try{await loadState(preset.state);if(operation!==presetOperation)return;$('presetSelect').value=id;$('presetDescription').textContent=preset.description;status('Recipe / '+preset.name+'.');}catch(error){status('Recipe could not load: '+error.message);}});
  $('undoButton').addEventListener('click',undo);$('redoButton').addEventListener('click',redo);$('resetButton').addEventListener('click',()=>loadState(S.defaultState()).catch(error=>status(error.message)));
  $('saveButton').addEventListener('click',()=>{finishTransaction();download(new Blob([S.serialize(state)],{type:'application/json'}),filename('.marinade.json'));status('Saved project with both ingredients.');});$('openButton').addEventListener('click',()=>$('projectFile').click());$('projectFile').addEventListener('change',async()=>{const file=$('projectFile').files[0];$('projectFile').value='';if(!file)return;if(file.size>16*1024*1024){status('Choose a MARINADE project smaller than 16 MB.');return;}try{await loadState(await file.text());}catch(error){status('Project could not open: '+error.message);}});
  for(let i=0;i<2;i++){const letter=i?'B':'A';$('load'+letter).addEventListener('click',()=>$('sourceFile'+letter).click());$('sourceFile'+letter).addEventListener('change',()=>{const file=$('sourceFile'+letter).files[0];$('sourceFile'+letter).value='';importFile(file,i);});$('audition'+letter).addEventListener('click',()=>audition(i));$('factory'+letter).addEventListener('change',()=>{const entry=catalog.find(x=>x.id===$('factory'+letter).value);if(!entry)return;++sourceOperations[i];$('sourceBay'+letter).classList.remove('busy');stopPreviews();mutate(s=>{s.samples[i]={...s.samples[i],ref:{kind:'factory',id:entry.id},rootNote:entry.rootNote,trimStart:0,trimEnd:1,position:.15};},'Ingredient '+letter+' / '+entry.name+'.');refreshAnalysis();});const bay=$('sourceBay'+letter);bay.addEventListener('dragover',event=>{event.preventDefault();bay.classList.add('drag-over');if(event.dataTransfer)event.dataTransfer.dropEffect='copy';});bay.addEventListener('dragleave',event=>{if(!bay.contains(event.relatedTarget))bay.classList.remove('drag-over');});bay.addEventListener('drop',event=>{event.preventDefault();bay.classList.remove('drag-over');importFile(event.dataTransfer?.files?.[0],i);});}
  $('swapButton').addEventListener('click',()=>{++importOperation;stopPreviews();mutate(s=>{s.samples.reverse();s.synth.morph=1-s.synth.morph;s.synth.pitchBlend=1-s.synth.pitchBlend;s.synth.textureBlend=1-s.synth.textureBlend;s.synth.transientBlend=1-s.synth.transientBlend;s.morphPath.points=s.morphPath.points.map(v=>1-v);},'Ingredients swapped. All four source balances reversed.');refreshAnalysis();});
  let drawing=null,pathFocus=0;
  function pathPoint(event){const rect=$('pathCanvas').getBoundingClientRect(),x=Math.max(0,Math.min(1,(event.clientX-rect.left-8)/(rect.width-16))),y=Math.max(0,Math.min(1,1-(event.clientY-rect.top-8)/(rect.height-16)));return{index:Math.round(x*15),value:y};}
  function paintPath(event){const next=pathPoint(event),last=drawing.last;if(last&&next.index!==last.index){const lo=Math.min(last.index,next.index),hi=Math.max(last.index,next.index);for(let i=lo;i<=hi;i++)state.morphPath.points[i]=last.value+(next.value-last.value)*(i-last.index)/(next.index-last.index);}state.morphPath.points[next.index]=next.value;state.morphPath.enabled=true;drawing.last=next;pathFocus=next.index;changed({full:false});}
  $('pathCanvas').addEventListener('pointerdown',event=>{event.preventDefault();finishTransaction();drawing={before:copy(state),last:null,pointer:event.pointerId};$('pathCanvas').setPointerCapture(event.pointerId);paintPath(event);});$('pathCanvas').addEventListener('pointermove',event=>{if(drawing&&event.pointerId===drawing.pointer)paintPath(event);});function finishDrawing(){if(!drawing)return;remember(drawing.before);drawing=null;notifyState();status('Morph movement drawn. Undo restores the previous path.');}for(const type of ['pointerup','pointercancel','lostpointercapture'])$('pathCanvas').addEventListener(type,finishDrawing);
  $('pathCanvas').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();if(event.key==='ArrowLeft'||event.key==='ArrowRight'){pathFocus=Math.max(0,Math.min(15,pathFocus+(event.key==='ArrowLeft'?-1:1)));status('Morph path point '+(pathFocus+1)+' / '+pct(state.morphPath.points[pathFocus])+'.');}else mutate(s=>{s.morphPath.points[pathFocus]=Math.max(0,Math.min(1,s.morphPath.points[pathFocus]+(event.key==='ArrowUp'?.05:-.05)));s.morphPath.enabled=true;});});
  $('resetPathButton').addEventListener('click',()=>mutate(s=>{s.morphPath.points=Array.from({length:16},()=>.5);},'Morph path reset to a steady blend.'));
  $('playButton').addEventListener('click',()=>engine.isPlaying?stop():play());$('stopButton').addEventListener('click',stop);$('restartButton').addEventListener('click',restart);$('panicButton').addEventListener('click',panic);$('chordButton').addEventListener('click',async()=>{try{await engine.init();for(const note of chordNotes())await engine.trigger(note,.7,1.2,'chord-audition');status('A chord of the new flavour.');}catch(error){status(error.message);}});$('wavButton').addEventListener('click',exportWav);$('cancelExportButton').addEventListener('click',()=>{cancelExport();status('WAV render cancelled.');});$('exportScope').addEventListener('change',()=>{$('exportBars').disabled=$('exportScope').value!=='pattern';});
  const keyMap=['a','w','s','e','d','f','t','g','y','h','u','j','k','o','l','p',';','\'',']'];
  function renderKeyboard(){const keyboard=$('keyboard');keyboard.replaceChildren();const white=[];for(let note=keyboardBase;note<=keyboardBase+24;note++)if(![1,3,6,8,10].includes(note%12))white.push(note);for(let note=keyboardBase;note<=keyboardBase+24;note++){const black=[1,3,6,8,10].includes(note%12),button=document.createElement('button');button.className='piano-key '+(black?'black':'white');button.dataset.note=note;button.setAttribute('aria-label',S.noteName(note));button.setAttribute('aria-pressed','false');if(black)button.style.left=(white.filter(n=>n<note).length/white.length*100-2.2)+'%';const label=document.createElement('span');label.textContent=keyMap[note-keyboardBase]?.toUpperCase()||'';if(!black&&note%12===0)button.append(document.createTextNode(S.noteName(note)));button.append(label);button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);keyDown('pointer-'+event.pointerId,note,keyVelocity);});for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,event=>keyUp('pointer-'+event.pointerId));button.addEventListener('keydown',event=>{if((event.key===' '||event.key==='Enter')&&!event.repeat){event.preventDefault();keyDown('focus-'+note,note,keyVelocity);}});button.addEventListener('keyup',event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();keyUp('focus-'+note);}});button.addEventListener('blur',()=>keyUp('focus-'+note));keyboard.append(button);}$('keyboardOctave').textContent=S.noteName(keyboardBase)+'—'+S.noteName(keyboardBase+24);renderKeyboardActivity();}
  function renderKeyboardActivity(){const live=new Set([...activeKeys.values()].map(k=>k.note));for(const key of $('keyboard').children){const active=live.has(Number(key.dataset.note));key.classList.toggle('active',active);key.setAttribute('aria-pressed',String(active));}}
  async function keyDown(source,note,velocity){if(activeKeys.has(source))return;const entry={note,source:'key:'+source,operation:transportOperation};activeKeys.set(source,entry);renderKeyboardActivity();try{await engine.trigger(note,velocity,768,entry.source);if(activeKeys.get(source)!==entry)engine.release(note,entry.source);}catch(error){if(activeKeys.get(source)===entry){activeKeys.delete(source);renderKeyboardActivity();}status('Audio could not start: '+error.message);}}
  function keyUp(source){const entry=activeKeys.get(source);if(!entry)return;activeKeys.delete(source);engine.release(entry.note,entry.source);renderKeyboardActivity();}
  function releaseKeyboard(){for(const source of [...activeKeys.keys()])keyUp(source);}
  function shiftKeyboard(direction){releaseKeyboard();keyboardBase=Math.max(12,Math.min(96,keyboardBase+direction*12));renderKeyboard();status('Keyboard '+S.noteName(keyboardBase)+' to '+S.noteName(keyboardBase+24)+'.');}
  $('keyboardDown').addEventListener('click',()=>shiftKeyboard(-1));$('keyboardUp').addEventListener('click',()=>shiftKeyboard(1));$('keyVelocity').addEventListener('input',()=>{keyVelocity=Number($('keyVelocity').value);$('keyVelocityValue').textContent=pct(keyVelocity);$('keyVelocity').style.setProperty('--fill',(keyVelocity-.05)/.95*100+'%');});
  function midiDisconnect(){for(const [input,fn]of midiBindings)if(input.onmidimessage===fn)input.onmidimessage=null;midiBindings.clear();for(const source of [...activeKeys.keys()])if(source.startsWith('midi-'))keyUp(source);}
  function attachMidi(){midiDisconnect();if(!midiAccess)return;for(const input of midiAccess.inputs.values()){if(input.state==='disconnected')continue;const fn=event=>{const [byte,note,velocity]=event.data,type=byte&240,key='midi-'+input.id+'-'+(byte&15)+'-'+note;if(type===144&&velocity>0)keyDown(key,note,velocity/127);else if(type===128||type===144&&velocity===0)keyUp(key);else if(type===176&&(note===120||note===123)){for(const source of [...activeKeys.keys()])if(source.startsWith('midi-'+input.id+'-'+(byte&15)+'-'))keyUp(source);}};input.onmidimessage=fn;midiBindings.set(input,fn);}$('midiStatus').textContent=midiBindings.size?midiBindings.size+' MIDI INPUT'+(midiBindings.size>1?'S':'')+' CONNECTED':'NO MIDI INPUTS / RECONNECT A DEVICE';$('midiButton').textContent=midiBindings.size?'Reconnect MIDI':'Connect MIDI';}
  $('midiButton').addEventListener('click',async()=>{if(!navigator.requestMIDIAccess){$('midiStatus').textContent='WEB MIDI UNAVAILABLE';status('This browser does not provide Web MIDI. Computer and on-screen keys are ready.');return;}try{if(midiAccess)midiAccess.onstatechange=null;midiDisconnect();midiAccess=await navigator.requestMIDIAccess({sysex:false});midiAccess.onstatechange=attachMidi;attachMidi();await engine.init();status(midiBindings.size?'MIDI connected. Play the infusion.':'Connect a MIDI keyboard; MARINADE will detect it.');}catch(error){status('MIDI unavailable: '+error.message);}});
  document.addEventListener('keydown',event=>{const editing=event.target.closest('input,select,textarea,[contenteditable=true]');if(event.key==='Escape'){panic();return;}if($('helpDialog').open)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!editing){event.preventDefault();event.shiftKey?redo():undo();return;}if(editing||event.ctrlKey||event.metaKey||event.altKey)return;if(event.target===$('pathCanvas'))return;if(event.key===' '&&event.target.tagName!=='BUTTON'){event.preventDefault();if(!event.repeat)engine.isPlaying?stop():play();return;}if(event.key==='Home'){event.preventDefault();if(!event.repeat)restart();return;}if(event.repeat)return;const key=event.key.toLowerCase();if(key==='z'){event.preventDefault();shiftKeyboard(-1);}else if(key==='x'){event.preventDefault();shiftKeyboard(1);}else{const index=keyMap.indexOf(key);if(index>=0){event.preventDefault();keyDown('computer-'+event.code,keyboardBase+index,keyVelocity);}}});document.addEventListener('keyup',event=>keyUp('computer-'+event.code));window.addEventListener('blur',releaseKeyboard);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseKeyboard();});
  $('nativePatternButton').addEventListener('click',()=>mutate(s=>{delete s.musicLabPattern;},'Native sequence restored.'));
  $('helpButton').addEventListener('click',()=>$('helpDialog').showModal());$('closeHelpButton').addEventListener('click',()=>$('helpDialog').close());$('helpDialog').addEventListener('click',event=>{if(event.target!==$('helpDialog'))return;const rect=$('helpDialog').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)$('helpDialog').close();});
  function meterFrame(now){if(now-lastMeterTime>85){lastMeterTime=now;const meter=engine.getMeters()||{},playing=!!engine.isPlaying;playingStep=playing?(meter.step??-1):-1;renderTransport();for(let i=0;i<16;i++)$('steps').children[i]?.classList.toggle('playing',playing&&i===playingStep);const rms=Math.max(0,Number(meter.rms)||0),db=rms>1e-5?20*Math.log10(rms):-Infinity;$('levelFill').style.width=Math.max(0,Math.min(100,(db+60)/60*100))+'%';$('levelReadout').textContent=Number.isFinite(db)?Math.round(db)+' dB':'−∞ dB';$('voiceReadout').textContent=String(meter.voices||0)+' VOICES';const beat=Math.max(0,Number(meter.beat)||0);$('position').textContent=String(Math.floor(beat/4)+1).padStart(2,'0')+' : '+String(Math.floor(beat%4)+1).padStart(2,'0');drawSpectrum(meter);drawPath(meter);}requestAnimationFrame(meterFrame);}
  buildControls();renderKeyboard();render();if(equal(state,S.normalize(initial))&&presets.length){$('presetSelect').value=presets[0].id||'0';$('presetDescription').textContent=presets[0].description;}
  updateEngine();refreshAnalysis();let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(drawDisplays,100);});
  window.addEventListener('pagehide',()=>{++importOperation;releaseKeyboard();stopPreviews();midiDisconnect();if(midiAccess)midiAccess.onstatechange=null;cancelExport();clearTimeout(autosaveTimer);if(!hosted){try{localStorage.setItem('marinade-project-v1',S.serialize(state));}catch(_){}}engine.dispose();});
  window.MarinadeApp={getState:()=>copy(state),getProject:()=>JSON.parse(S.serialize(state)),loadState,applyState,setTempo,engine,play,stop,panic,isPlaying:()=>!!engine.isPlaying,exportAudio,audioExport:{scopes:[{id:'pattern',label:'Current pattern'},{id:'note',label:'Single note',usesBars:false},{id:'chord',label:'Current chord',usesBars:false}],defaultBars:4,maxBars:16},get audioImport(){return{targets:[{id:'a',name:'Source A',occupied:true},{id:'b',name:'Source B',occupied:true}],maxSeconds:20,channels:1,mode:'analysis',description:'Replace either ingredient with up to 20 seconds of audio. Stereo is analysed as mono; the reconstructed instrument plays in stereo.'};},importAudio,onStateChange(fn){listeners.add(fn);return()=>listeners.delete(fn);},selectStep(index){selectedStep=Math.max(0,Math.min(15,Number(index)||0));renderControls();renderSteps();},clearImportedPattern(){mutate(s=>{delete s.musicLabPattern;},'Native sequence restored.');}};
  window.dispatchEvent(new CustomEvent('musiclab:app-ready',{detail:{app:'marinade'}}));requestAnimationFrame(meterFrame);
})();
