/* MARINADE — phase-continuous spectral resynthesis shared by live and offline playback. */
(function(global){
  'use strict';
  function createMarinadeDSP(){
    'use strict';
    const TAU=Math.PI*2,MAX_VOICES=16,MAX_PARTIALS=36,MAX_QUEUE=16384,CONTROL=128,PARTIAL_BUDGET=288;
    const clamp=(v,a,b,d=a)=>Number.isFinite(v)?Math.min(b,Math.max(a,v)):d;
    const clone=x=>{const state={...(x||{})};if(Array.isArray(state.samples))state.samples=state.samples.map(bay=>{const ref={...(bay.ref||{})};delete ref.data;return{...bay,ref};});return JSON.parse(JSON.stringify(state));},frac=x=>x-Math.floor(x);
    const hash=n=>{n=Math.imul(n^(n>>>16),0x7feb352d);n=Math.imul(n^(n>>>15),0x846ca68b);return(n^(n>>>16))>>>0;};
    const soft=x=>{x=clamp(x,-4,4,0);const q=x*x;return x*(27+q)/(27+9*q);};
    const sequence=typeof createMarinadeSequence==='function'?createMarinadeSequence():null;
    const beatDivision=d=>({'1/32':.125,'1/16':.25,'1/16T':1/6,'1/8':.5,'1/8T':1/3,'1/4':1,'1/4T':2/3,'3/4':3,'1/2':2,'1/1':4,'1bar':4,'2bar':8,'4bar':16,'3/16':.75,'3/8':1.5})[d]||.5;
    function envConfig(e,sr){e=e||{};return{attack:1/(clamp(e.attack,.001,12,.012)*sr),decay:Math.exp(-6.9/(clamp(e.decay,.001,15,.7)*sr)),sustain:clamp(e.sustain,0,1,.7),release:Math.exp(-6.9/(clamp(e.release,.005,20,.6)*sr))};}
    function config(state,sr){const s=state.synth||{},l=s.lfo||{},fx=state.fx||{},m=state.morphPath||{},f=s.filter||{};
      return{blend:clamp(s.morph,0,1,.5),pitchBlend:clamp(s.pitchBlend,0,1,.5),texture:clamp(s.texture,0,1,.15),textureBlend:clamp(s.textureBlend,0,1,.5),transientBlend:clamp(s.transientBlend,0,1,.5),transient:clamp(s.transient,0,1,.2),formantShift:clamp(s.formantShift,-24,24,0),formantLock:typeof s.formantLock==='boolean'?+s.formantLock:clamp(s.formantLock,0,1,1),inharmonic:clamp(s.inharmonic,0,1,.08),smear:clamp(s.smear,0,1,.2),spread:clamp(s.spread,0,1,.55),scanMode:s.scanMode||'pingpong',scanRate:clamp(s.scanRate,-2,2,.5),lfoShape:l.shape||'sine',lfoRate:l.sync&&l.sync!=='free'?clamp(state.tempo,20,400,96)/(60*beatDivision(l.sync)):clamp(l.rate,.02,20,.3),lfoDepth:clamp(l.depth,0,1,.12),lfoTarget:l.target||'morph',retrigger:!!l.retrigger,amp:envConfig(s.amp,sr),filterEnv:envConfig(s.filterEnv,sr),cutoff:clamp(f.cutoff,20,sr*.43,9500),resonance:clamp(f.resonance,0,.85,.1),envAmount:clamp(f.envAmount,-5,5,1),keytrack:clamp(f.keytrack,0,1,.25),filterType:f.type||'lp',drive:clamp(fx.drive,0,1,.1),chorus:clamp(fx.chorus,0,1,.22),delay:clamp(fx.delay,0,1,.16),delayFrames:clamp(beatDivision(fx.delayDivision||'3/16')*60/clamp(state.tempo,20,400,96)*sr,16,sr*12),feedback:clamp(fx.feedback,0,.85,.3),space:clamp(fx.space,0,1,.28),width:clamp(fx.width,0,1.5,1),volume:clamp(fx.volume,0,1,.7),pathEnabled:!!m.enabled,pathBeats:clamp(m.beats,1,32,4),pathDepth:clamp(m.depth,0,1,.65)};
    }
    function lfo(phase,shape,seed){if(shape==='triangle')return 1-4*Math.abs(phase-.5);if(shape==='saw')return phase*2-1;if(shape==='square')return phase<.5?1:-1;if(shape==='sampleHold'||shape==='hold')return hash(seed)/2147483648-1;return Math.sin(TAU*phase);}
    function interp(model,array,frame,lane,stride){const f=clamp(frame,0,model.frames-1,0),a=Math.floor(f),b=Math.min(model.frames-1,a+1),x=f-a;return array[a*stride+lane]+(array[b*stride+lane]-array[a*stride+lane])*(x);}
    function envelopeAt(model,frame,freq,anchorFrequency,anchorLane){const first=model.laneFrequencies[0],last=model.laneFrequencies[model.lanes-1],lane=clamp(anchorLane+Math.log(Math.max(1,freq)/Math.max(1,anchorFrequency))/Math.log(last/first)*(model.lanes-1),0,model.lanes-1,0),a=Math.floor(lane),b=Math.min(model.lanes-1,a+1),data=model.envelope||model.amplitudes;return interp(model,data,frame,a,model.lanes)*(1-(lane-a))+interp(model,data,frame,b,model.lanes)*(lane-a);}
    class Core{
      constructor(sr,state,models){this.sr=clamp(sr,8000,192000,48000);this.frame=0;this.playing=false;this.clockPlaying=false;this.originBeat=0;this.originFrame=0;this.tempo=108;this.voices=[];this.tails=[];this.jobs=[];this.controls=[];this.fences=new Map();this.serial=0;this.models=null;this.lanes=[];this.nextCycle=0;this.lfoPhase=0;this.lfoCycle=0;this.chorusAt=0;this.chorusPhase=0;this.chorusL=new Float32Array(Math.ceil(this.sr*.055));this.chorusR=new Float32Array(this.chorusL.length);this.delayAt=0;this.delayL=new Float32Array(Math.ceil(this.sr*12)+2);this.delayR=new Float32Array(this.delayL.length);this.delayToneL=0;this.delayToneR=0;this.room=[.0297,.0371,.0411,.0437,.0309,.0353,.0397,.0451].map((seconds,i)=>({data:new Float32Array(Math.round(this.sr*seconds)+(i%2)),at:0,tone:0}));this.dcL=0;this.dcR=0;this.dcInL=0;this.dcInR=0;this.toneL=0;this.toneR=0;this.peak=0;this.rms=0;this.waveform=new Float32Array(128);this.waveAt=0;this.spectrum=new Float32Array(72);this.scanPosition=0;this.scanPositions=[0,0];this.pathPhase=0;this.morphPosition=.5;this.step=-1;this.setState(state||{});if(models)this.setModels(models);}
      setModels(models){if(!Array.isArray(models)||models.length!==2||models.some(m=>!m||m.lanes!==72||m.frames<2||!m.amplitudes||!m.frequencies))throw new Error('MARINADE needs two analyzed source models.');this.models=models;const [a,b]=models,usedA=new Set(),usedB=new Set(),pairs=[],candidates=Array.from({length:72},(_,i)=>({i,weight:a.laneWeight[i]||0})).sort((x,y)=>y.weight-x.weight||x.i-y.i),floorA=Math.max(...a.laneWeight)*.0008,floorB=Math.max(...b.laneWeight)*.0008;
        for(const candidate of candidates){const i=candidate.i;if(candidate.weight<=Math.max(1e-8,floorA))continue;let counterpart=-1,score=-Infinity;for(let j=Math.max(0,i-2);j<=Math.min(71,i+2);j++){if(usedB.has(j)||b.laneWeight[j]<=Math.max(1e-8,floorB))continue;const weight=b.laneWeight[j]/(1+Math.abs(j-i)*.8);if(weight>score){score=weight;counterpart=j;}}usedA.add(i);if(counterpart>=0)usedB.add(counterpart);pairs.push({a:i,b:counterpart,display:i,weight:candidate.weight+(counterpart>=0?b.laneWeight[counterpart]:0)});}
        for(let j=0;j<72;j++)if(!usedB.has(j)&&b.laneWeight[j]>Math.max(1e-8,floorB))pairs.push({a:-1,b:j,display:j,weight:b.laneWeight[j]});pairs.sort((x,y)=>y.weight-x.weight||x.display-y.display);this.partials=pairs.slice(0,MAX_PARTIALS);this.lanes=this.partials.map(x=>x.display);for(const v of this.voices)v.refresh=true;}
      setAnalysis(models){this.setModels(models);}
      setState(state){const beat=this.playing?this.beatAt(this.frame):this.originBeat;this.state=clone(state);this.tempo=clamp(state.tempo,20,400,108);this.target=config(this.state,this.sr);if(!this.params)this.params={...this.target};if(this.playing){this.originBeat=beat;this.originFrame=this.frame;this.jobs=this.jobs.filter(x=>x.source!=='marinade-phrase');this._setCursor(beat);}for(const v of this.voices)v.refresh=true;}
      beatAt(frame){return this.originBeat+(frame-this.originFrame)*this.tempo/(60*this.sr);}
      _frameAt(beat){return Math.round(this.originFrame+(beat-this.originBeat)*60/this.tempo*this.sr);}
      _insert(queue,event,cap){if(queue.length>=cap)throw new Error('MARINADE’s scheduled event queue is full.');let lo=0,hi=queue.length;while(lo<hi){const m=(lo+hi)>>>1;if(queue[m].frame<event.frame||(queue[m].frame===event.frame&&(queue[m].note??0)<=(event.note??0)))lo=m+1;else hi=m;}queue.splice(lo,0,event);}
      _setCursor(beat){this.phraseLength=this.state.musicLabPattern?.pattern?.lengthBeats||(sequence?sequence.patternLength(this.state):4);this.nextCycle=Math.floor(Math.max(0,beat)/this.phraseLength);this.cycleEvents=null;this.cycleCursor=0;}
      start({beat=0,frame=this.frame}={}){if(!Number.isFinite(beat)||beat<0||beat>1e6||!Number.isFinite(frame)||frame<0)throw new Error('Provide a valid start beat and timestamp.');const job={type:'start',beat,frame:Math.max(this.frame,Math.round(frame))};if(job.frame>this.frame)this._insert(this.controls,job,256);else this._start(job);}
      _start(job){this.stopNotes({source:'marinade-phrase',frame:this.frame});this.fences.delete('marinade-phrase');this.originBeat=job.beat;this.originFrame=job.frame;this.playing=true;this._setCursor(job.beat);}
      stop(){this.originBeat=this.beatAt(this.frame);this.originFrame=this.frame;this.playing=false;this.clockPlaying=false;this.controls=this.controls.filter(j=>j.type!=='start'&&j.type!=='transport');this.stopNotes({source:'marinade-phrase',frame:this.frame});this.step=-1;}
      panic(){this.playing=false;this.clockPlaying=false;this.jobs.length=this.controls.length=this.voices.length=this.tails.length=0;this.fences.clear();this.chorusL.fill(0);this.chorusR.fill(0);this.delayL.fill(0);this.delayR.fill(0);for(const r of this.room){r.data.fill(0);r.tone=0;}this.delayToneL=this.delayToneR=this.dcL=this.dcR=this.dcInL=this.dcInR=this.toneL=this.toneR=this.peak=this.rms=0;this.waveform.fill(0);this.spectrum.fill(0);this.step=-1;}
      scheduleNote({note=60,velocity=.85,frame=this.frame,duration=.4,source='marinade-live',step=-1}={}){if(!Number.isFinite(note)||note<0||note>127||!Number.isFinite(velocity)||velocity<0||velocity>1||!Number.isFinite(frame)||frame<0||!Number.isFinite(duration)||duration<=0||duration>768)throw new Error('Invalid MARINADE note or timestamp.');if(typeof source!=='string'||!source||source.length>200)throw new Error('Provide a valid MARINADE note source.');const at=Math.max(this.frame,Math.round(frame)),fence=this.fences.get(source),all=this.fences.get('*');if((fence&&this.frame<fence.frame&&at>=fence.frame)||(all&&this.frame<all.frame&&at>=all.frame))return false;if(!velocity)return true;this._insert(this.jobs,{note,velocity,frame:at,duration:Math.max(1,Math.round(duration*this.sr)),source,step},MAX_QUEUE);return true;}
      stopNotes({source,frame=this.frame}={}){if(source!==undefined&&(typeof source!=='string'||!source||source.length>200))throw new Error('Provide a valid MARINADE cancellation source.');if(!Number.isFinite(frame)||frame<0)throw new Error('Provide a valid MARINADE cancellation timestamp.');const at=Math.max(this.frame,Math.round(frame));this.jobs=this.jobs.filter(e=>(source&&e.source!==source)||e.frame<at);if(at>this.frame){if(this.fences.size>=256&&!this.fences.has(source||'*'))throw new Error('Too many pending MARINADE cancellation sources.');this.fences.set(source||'*',{frame:at});this._insert(this.controls,{type:'cancel',source,frame:at},256);}else for(const v of this.voices)if(!source||v.source===source)this._release(v);}
      setTransport(clock={}){const frame=Number.isFinite(clock.frame)?clock.frame:Number.isFinite(clock.when)?Math.round(clock.when*this.sr):this.frame,beat=clock.absoluteBeat??clock.beat;if(!Number.isFinite(beat)||!Number.isFinite(clock.tempo)||!Number.isFinite(frame))throw new Error('Provide a finite MARINADE transport beat and tempo.');const job={type:'transport',frame:Math.max(this.frame,Math.round(frame)),beat:clamp(beat,0,1e6),tempo:clamp(clock.tempo,20,400),playing:!!clock.playing,revision:clock.revision};if(job.frame>this.frame){this.controls=this.controls.filter(j=>j.type!=='transport'||j.frame<job.frame);this._insert(this.controls,job,256);}else this._transport(job);}
      _transport(job){const seek=this.clockRevision!==job.revision||Math.abs(this.beatAt(job.frame)-job.beat)>.03;this.clockRevision=job.revision;this.tempo=job.tempo;this.clockPlaying=job.playing;if(!job.playing){this.stop();this.originBeat=job.beat;this.originFrame=job.frame;return;}if(this.playing&&seek)this._start(job);else{this.originBeat=job.beat;this.originFrame=job.frame;}this.target=config({...this.state,tempo:this.tempo},this.sr);}
      _sequence(){if(!this.playing||!sequence)return;const beat=this.beatAt(this.frame),ahead=32*this.tempo/(60*this.sr);let count=0;while(count++<MAX_QUEUE){if(!this.cycleEvents){const startBeat=this.nextCycle*this.phraseLength;this.cycleEvents=sequence.events(this.state,{startBeat,lengthBeats:this.phraseLength});this.cycleCursor=0;}if(this.cycleCursor>=this.cycleEvents.length){if((this.nextCycle+1)*this.phraseLength>beat+ahead)break;this.nextCycle++;this.cycleEvents=null;continue;}const e=this.cycleEvents[this.cycleCursor],at=e.startBeat??e.beat;if(at>beat+ahead)break;this.cycleCursor++;if(at>=this.originBeat-1e-8)this.scheduleNote({note:e.note??e.pitch,velocity:e.velocity,frame:this._frameAt(at),duration:(e.durationBeats??e.duration)*60/this.tempo,source:'marinade-phrase',step:e.step??-1});}}
      _release(v){if(v.stage<3)v.stage=3;if(v.filterStage<3)v.filterStage=3;}
      _note(e){if(!this.models)return;if(this.voices.length>=MAX_VOICES){let steal=0,score=Infinity;for(let i=0;i<this.voices.length;i++){const v=this.voices[i],s=v.env+(v.stage>=3?-2:0);if(s<score){score=s;steal=i;}}const old=this.voices.splice(steal,1)[0];if(this.tails.length>=8)this.tails.shift();this.tails.push({l:old.lastL||0,r:old.lastR||0,remaining:64});}const count=MAX_PARTIALS,seed=hash((this.state.seed||628317)^Math.imul(Math.round(e.note),9781)),v={note:e.note,source:e.source,born:this.frame,end:this.frame+e.duration,stage:0,env:0,filterStage:0,filterEnv:0,ic1L:0,ic2L:0,ic1R:0,ic2R:0,a1:1,a2:0,a3:0,k:2,velocity:e.velocity,seed,noiseSeed:seed||1,lfoPhase:0,lfoCycle:0,lastL:0,lastR:0,refresh:true,cos:new Float64Array(count),sin:new Float64Array(count),rotC:new Float64Array(count),rotS:new Float64Array(count),amp:new Float32Array(count),ampStep:new Float32Array(count),quality:new Float32Array(count),qualityStep:new Float32Array(count),panL:new Float32Array(count),panR:new Float32Array(count),noiseLow:new Float64Array(6),noiseHigh:new Float64Array(6),noiseGain:new Float32Array(6),noiseC1:new Float32Array(6),noiseC2:new Float32Array(6)};for(let i=0;i<count;i++){const phase=hash(seed^Math.imul(this.lanes[i]??i,9173))/4294967296*TAU;v.cos[i]=Math.cos(phase);v.sin[i]=Math.sin(phase);v.quality[i]=1;}const edges=[25,180,500,1200,3000,6500,11025];for(let b=0;b<6;b++){v.noiseC1[b]=1-Math.exp(-TAU*Math.min(this.sr*.43,edges[b+1])/this.sr);v.noiseC2[b]=1-Math.exp(-TAU*edges[b]/this.sr);}this.voices.push(v);if(e.step>=0)this.step=e.step;}
      _path(beat){const points=this.state.morphPath?.points||[];if(points.length<2)return .5;const phase=frac(beat/this.params.pathBeats),pos=phase*(points.length-1),a=Math.floor(pos);return points[a]+(points[Math.min(points.length-1,a+1)]-points[a])*(pos-a);}
      _scan(bay,model,elapsed,p,lf){let position=clamp(bay.position+(p.lfoTarget==='position'?lf*p.lfoDepth*.45:0),0,1,0);if(bay.freeze)return position;const t=elapsed*p.scanRate/Math.max(.05,model.duration)+position;if(p.scanMode==='oneShot')return clamp(t,0,1,0);if(p.scanMode==='pingpong'){const at=frac(t/2)*2;return at<=1?at:2-at;}return frac(t);}
      _voiceControl(v,p){const [a,b]=this.models,elapsed=(this.frame-v.born)/this.sr,phase=p.retrigger?v.lfoPhase:this.lfoPhase,lf=lfo(phase,p.lfoShape,(this.state.seed||1)^(p.retrigger?v.lfoCycle:this.lfoCycle)),pathBeat=(this.playing||this.clockPlaying)?this.beatAt(this.frame):elapsed*this.tempo/60;let blend=p.blend;if(p.pathEnabled)blend+=(this._path(pathBeat)-.5)*p.pathDepth;if(p.lfoTarget==='morph')blend+=lf*p.lfoDepth;blend=clamp(blend,0,1,.5);const positionA=this._scan(this.state.samples[0],a,elapsed,p,lf),positionB=this._scan(this.state.samples[1],b,elapsed,p,lf),frameA=positionA*(a.frames-1),frameB=positionB*(b.frames-1),pitchBlend=clamp(p.pitchBlend+(p.lfoTarget==='pitchBlend'?lf*p.lfoDepth:0),0,1,.5),noteFactor=Math.pow(2,(v.note-69)/12)*440,formant=Math.pow(2,(p.formantShift+(p.lfoTarget==='formant'?lf*p.lfoDepth*12:0))/12);let ampSum=0;
        const blurred=(model,frame,lane)=>{const own=interp(model,model.amplitudes,frame,lane,model.lanes);if(!p.smear)return own;const side=(interp(model,model.amplitudes,frame,Math.max(0,lane-1),model.lanes)+interp(model,model.amplitudes,frame,Math.min(model.lanes-1,lane+1),model.lanes))*.5;return own*(1-p.smear*.65)+side*p.smear*.65;};
        for(let i=0;i<this.lanes.length;i++){const part=this.partials[i],lane=part.display,laneA=part.a,laneB=part.b,presentA=laneA>=0,presentB=laneB>=0,realFA=presentA?interp(a,a.frequencies,frameA,laneA,a.lanes):0,realFB=presentB?interp(b,b.frequencies,frameB,laneB,b.lanes):0,fA=presentA?realFA:realFB/b.rootFrequency*a.rootFrequency,fB=presentB?realFB:realFA/a.rootFrequency*b.rootFrequency,ratioA=fA/a.rootFrequency,ratioB=fB/b.rootFrequency,frequency=Math.exp(Math.log(Math.max(.01,ratioA))*(1-pitchBlend)+Math.log(Math.max(.01,ratioB))*pitchBlend)*noteFactor*Math.pow(2,(hash(lane^937)/4294967296-.5)*p.inharmonic*.16),amA=presentA?blurred(a,frameA,laneA):0,amB=presentB?blurred(b,frameB,laneB):0;let level=amA*(1-blend)+amB*blend;
          if(p.formantLock||p.formantShift||p.lfoTarget==='formant'){const transferred=(model,frame,sourceFrequency,sourceLane,original)=>{if(sourceLane<0)return 0;const query=(sourceFrequency*(1-p.formantLock)+frequency*p.formantLock)/formant,own=interp(model,model.envelope||model.amplitudes,frame,sourceLane,model.lanes),shifted=envelopeAt(model,frame,query,sourceFrequency,sourceLane),ratio=clamp(shifted/Math.max(1e-6,own),.25,3,1);return original*ratio;};level=transferred(a,frameA,fA,laneA,amA)*(1-blend)+transferred(b,frameB,fB,laneB,amB)*blend;}
          if(frequency>this.sr*.43||frequency<8)level=0;level=clamp(level,0,2,0);const angle=TAU*clamp(frequency,0,this.sr*.43)/this.sr;v.rotC[i]=Math.cos(angle);v.rotS[i]=Math.sin(angle);const magnitude=Math.sqrt(v.cos[i]*v.cos[i]+v.sin[i]*v.sin[i]);if(magnitude>1e-8){v.cos[i]/=magnitude;v.sin[i]/=magnitude;}v.ampStep[i]=(level-v.amp[i])/CONTROL;v.qualityStep[i]=((i<Math.max(18,Math.floor(PARTIAL_BUDGET/Math.max(1,this.voices.length)))?1:0)-v.quality[i])/CONTROL;let pan=(hash(lane^621)/4294967296-.5)*p.spread*1.8;if(p.lfoTarget==='pan')pan=clamp(pan+lf*p.lfoDepth*.9,-.95,.95,0);v.panL[i]=Math.sqrt(.5*(1-pan));v.panR[i]=Math.sqrt(.5*(1+pan));ampSum+=level;this.spectrum[lane]=Math.max(this.spectrum[lane],level*v.env);}
        v.partialGain=ampSum>1.8?1.8/ampSum:1;for(let band=0;band<6;band++)v.noiseGain[band]=(interp(a,a.texture,frameA,band,6)*(1-p.textureBlend)+interp(b,b.texture,frameB,band,6)*p.textureBlend)*p.texture*1.7;v.transientRatioA=noteFactor/a.rootFrequency;v.transientRatioB=noteFactor/b.rootFrequency;v.blend=blend;v.refresh=false;this.scanPosition=positionA*(1-blend)+positionB*blend;this.scanPositions[0]=positionA;this.scanPositions[1]=positionB;this.pathPhase=frac(pathBeat/p.pathBeats);this.morphPosition=blend;
        const cutoff=clamp(p.cutoff*Math.pow(2,p.envAmount*v.filterEnv+(v.note-60)*p.keytrack/12+(p.lfoTarget==='cutoff'?lf*p.lfoDepth*4:0)),20,this.sr*.42,9500),g=Math.tan(Math.PI*cutoff/this.sr);v.k=2-p.resonance*1.85;v.a1=1/(1+g*(g+v.k));v.a2=g*v.a1;v.a3=g*v.a2;
      }
      _filter(v,l,r,type){const zL=l-v.ic2L,bpL=v.a1*v.ic1L+v.a2*zL,lpL=v.ic2L+v.a2*v.ic1L+v.a3*zL,zR=r-v.ic2R,bpR=v.a1*v.ic1R+v.a2*zR,lpR=v.ic2R+v.a2*v.ic1R+v.a3*zR;v.ic1L=2*bpL-v.ic1L;v.ic2L=2*lpL-v.ic2L;v.ic1R=2*bpR-v.ic1R;v.ic2R=2*lpR-v.ic2R;if(type==='hp'){v.filteredL=l-v.k*bpL-lpL;v.filteredR=r-v.k*bpR-lpR;}else if(type==='bp'){const g=Math.sqrt(v.k);v.filteredL=bpL*g;v.filteredR=bpR*g;}else{v.filteredL=lpL;v.filteredR=lpR;}}
      _transient(model,elapsed,ratio){const pos=elapsed*model.sampleRate*ratio,at=Math.floor(pos);return at<model.transient.length-1?model.transient[at]+(model.transient[at+1]-model.transient[at])*(pos-at):0;}
      _read(buffer,delay,index){let pos=index-delay;while(pos<0)pos+=buffer.length;const i=Math.floor(pos)%buffer.length,j=(i+1)%buffer.length;return buffer[i]+(buffer[j]-buffer[i])*(pos-Math.floor(pos));}
      processBlock(left,right){if(!left||!right||left.length!==right.length)throw new Error('MARINADE needs equally sized stereo output channels.');let square=0,peak=0;const sr=this.sr,p=this.params,smoothing=1-Math.exp(-CONTROL/(sr*.015));const numeric=['blend','pitchBlend','texture','textureBlend','transient','transientBlend','formantShift','formantLock','inharmonic','smear','spread','scanRate','lfoRate','lfoDepth','drive','chorus','delay','delayFrames','feedback','space','width','volume','cutoff','resonance','envAmount','keytrack','pathDepth'];
        for(let i=0;i<left.length;i++,this.frame++){
          while(this.controls.length&&this.controls[0].frame<=this.frame){const j=this.controls.shift();if(j.type==='start')this._start(j);else if(j.type==='transport')this._transport(j);else{for(const v of this.voices)if(!j.source||v.source===j.source)this._release(v);this.fences.delete(j.source||'*');}}
          if(this.playing&&((this.frame&31)===0||this.frame===this.originFrame))this._sequence();while(this.jobs.length&&this.jobs[0].frame<=this.frame)this._note(this.jobs.shift());
          if((this.frame&(CONTROL-1))===0){const t=this.target;for(const key of numeric)p[key]+=(t[key]-p[key])*smoothing;p.amp=t.amp;p.filterEnv=t.filterEnv;p.filterType=t.filterType;p.scanMode=t.scanMode;p.lfoTarget=t.lfoTarget;p.lfoShape=t.lfoShape;p.retrigger=t.retrigger;p.pathEnabled=t.pathEnabled;p.pathBeats=t.pathBeats;this.spectrum.fill(0);}
          let dryL=0,dryR=0;
          for(let j=this.voices.length-1;j>=0;j--){const v=this.voices[j];if(this.frame>=v.end)this._release(v);if(v.stage===0){v.env+=p.amp.attack;if(v.env>=1){v.env=1;v.stage=1;}}else if(v.stage===1){v.env=p.amp.sustain+(v.env-p.amp.sustain)*p.amp.decay;if(Math.abs(v.env-p.amp.sustain)<.0001)v.stage=2;}else if(v.stage===2)v.env+=(p.amp.sustain-v.env)*.002;else{v.env*=p.amp.release;if(v.env<.00001){this.voices.splice(j,1);continue;}}
            if(v.filterStage===0){v.filterEnv+=p.filterEnv.attack;if(v.filterEnv>=1){v.filterEnv=1;v.filterStage=1;}}else if(v.filterStage===1){v.filterEnv=p.filterEnv.sustain+(v.filterEnv-p.filterEnv.sustain)*p.filterEnv.decay;if(Math.abs(v.filterEnv-p.filterEnv.sustain)<.0001)v.filterStage=2;}else if(v.filterStage===2)v.filterEnv+=(p.filterEnv.sustain-v.filterEnv)*.002;else v.filterEnv*=p.filterEnv.release;
            if(v.refresh||((this.frame-v.born)&(CONTROL-1))===0)this._voiceControl(v,p);let l=0,r=0;for(let k=0;k<this.lanes.length;k++){v.amp[k]+=v.ampStep[k];v.quality[k]+=v.qualityStep[k];if(v.quality[k]<.00001&&v.qualityStep[k]<=0)continue;const value=v.sin[k]*v.amp[k]*v.quality[k],cos=v.cos[k],sin=v.sin[k];v.cos[k]=cos*v.rotC[k]-sin*v.rotS[k];v.sin[k]=sin*v.rotC[k]+cos*v.rotS[k];l+=value*v.panL[k];r+=value*v.panR[k];}l*=v.partialGain;r*=v.partialGain;
            v.noiseSeed^=v.noiseSeed<<13;v.noiseSeed^=v.noiseSeed>>>17;v.noiseSeed^=v.noiseSeed<<5;const noise=(v.noiseSeed>>>0)/2147483648-1;let texture=0;for(let band=0;band<6;band++){v.noiseLow[band]+=(noise-v.noiseLow[band])*v.noiseC1[band];v.noiseHigh[band]+=(noise-v.noiseHigh[band])*v.noiseC2[band];texture+=(v.noiseLow[band]-v.noiseHigh[band])*v.noiseGain[band];}l+=texture*.707;r+=texture*.707;
            if(p.transient&&this.frame-v.born<sr*.18){const elapsed=(this.frame-v.born)/sr,tr=(this._transient(this.models[0],elapsed,v.transientRatioA)*(1-p.transientBlend)+this._transient(this.models[1],elapsed,v.transientRatioB)*p.transientBlend)*p.transient*(1-elapsed/.18);l+=tr*.707;r+=tr*.707;}
            const gain=v.env*v.velocity;this._filter(v,l,r,p.filterType);v.lastL=v.filteredL*gain;v.lastR=v.filteredR*gain;dryL+=v.lastL;dryR+=v.lastR;const next=v.lfoPhase+p.lfoRate/sr;if(next>=1)v.lfoCycle++;v.lfoPhase=frac(next);
          }
          for(let j=this.tails.length-1;j>=0;j--){const t=this.tails[j],gain=t.remaining/64;dryL+=t.l*gain;dryR+=t.r*gain;if(--t.remaining<=0)this.tails.splice(j,1);}const next=this.lfoPhase+p.lfoRate/sr;if(next>=1)this.lfoCycle++;this.lfoPhase=frac(next);
          this.chorusL[this.chorusAt]=dryL;this.chorusR[this.chorusAt]=dryR;const chorusL=this._read(this.chorusR,sr*(.016+.004*Math.sin(TAU*this.chorusPhase)),this.chorusAt),chorusR=this._read(this.chorusL,sr*(.019+.004*Math.sin(TAU*this.chorusPhase+1.9)),this.chorusAt);this.chorusAt=(this.chorusAt+1)%this.chorusL.length;this.chorusPhase=frac(this.chorusPhase+.23/sr);let outL=soft((dryL*(1-p.chorus*.25)+chorusL*p.chorus*.48)*(1+p.drive*5))/(1+p.drive),outR=soft((dryR*(1-p.chorus*.25)+chorusR*p.chorus*.48)*(1+p.drive*5))/(1+p.drive),dl=this._read(this.delayL,p.delayFrames,this.delayAt),dr=this._read(this.delayR,p.delayFrames*1.006,this.delayAt);this.delayToneL+=(dl-this.delayToneL)*.19;this.delayToneR+=(dr-this.delayToneR)*.19;this.delayL[this.delayAt]=soft(outL*p.delay+this.delayToneR*p.feedback);this.delayR[this.delayAt]=soft(outR*p.delay+this.delayToneL*p.feedback);this.delayAt=(this.delayAt+1)%this.delayL.length;outL+=dl*.72;outR+=dr*.72;let roomL=0,roomR=0;for(let j=0;j<8;j++){const re=this.room[j],value=re.data[re.at];re.tone+=(value-re.tone)*.22;re.data[re.at]=soft((j<4?outL:outR)*p.space*.22+re.tone*.74);re.at=(re.at+1)%re.data.length;if(j<4)roomL+=value;else roomR+=value;}outL+=roomL*.38;outR+=roomR*.38;const mid=(outL+outR)*.5,side=(outL-outR)*.5*p.width;outL=(mid+side)*p.volume*.7;outR=(mid-side)*p.volume*.7;const dcL=outL-this.dcInL+this.dcL*.9985,dcR=outR-this.dcInR+this.dcR*.9985;this.dcInL=outL;this.dcInR=outR;this.dcL=Number.isFinite(dcL)?dcL:0;this.dcR=Number.isFinite(dcR)?dcR:0;const finalL=soft(this.dcL)*.98,finalR=soft(this.dcR)*.98;left[i]=finalL;right[i]=finalR;square+=finalL*finalL+finalR*finalR;peak=Math.max(peak,Math.abs(finalL),Math.abs(finalR));if((this.frame&7)===0){this.waveform[this.waveAt]=(finalL+finalR)*.5;this.waveAt=(this.waveAt+1)&127;}
        }this.rms=left.length?Math.sqrt(square/(left.length*2)):0;this.peak=peak;
      }
      getMeters(){const waveform=new Float32Array(128);for(let i=0;i<128;i++)waveform[i]=this.waveform[(this.waveAt+i)&127];return{rms:this.rms,peak:this.peak,voices:this.voices.length,beat:(this.playing||this.clockPlaying)?this.beatAt(this.frame):this.originBeat,step:this.playing?this.step:-1,waveform,spectrum:new Float32Array(this.spectrum),scan:this.scanPosition,scanPositions:[...this.scanPositions],pathPhase:this.pathPhase,morph:this.morphPosition};}
    }
    return{Core,MAX_VOICES,MAX_PARTIALS,MAX_QUEUE,CONTROL,PARTIAL_BUDGET};
  }
  global.createMarinadeDSP=createMarinadeDSP;global.MarinadeDSP=createMarinadeDSP();
  const DSP=global.MarinadeDSP;
  function processorState(state){const out={...state};if(Array.isArray(out.samples))out.samples=out.samples.map(bay=>{const ref={...(bay.ref||{})};delete ref.data;return{...bay,ref};});return out;}
  const emptyMeters=()=>({rms:0,peak:0,voices:0,beat:0,step:-1,chord:-1,waveform:new Float32Array(128)});
  function normalized(state){return global.MarinadeSchema?global.MarinadeSchema.normalize(state):JSON.parse(JSON.stringify(state||{}));}
  function finite(value,label,min,max){if(!Number.isFinite(value)||value<min||value>max)throw new Error(label+' is outside the supported range.');return value;}
  function cancelled(signal){if(signal?.aborted)throw new DOMException('Audio export cancelled.','AbortError');}
  function wavBlob(chunks,frames,sr) {
    const bytes=new ArrayBuffer(44+frames*4),v=new DataView(bytes);let at=0;const tag=s=>{for(let i=0;i<s.length;i++)v.setUint8(at++,s.charCodeAt(i));};
    tag('RIFF');v.setUint32(at,36+frames*4,true);at+=4;tag('WAVE');tag('fmt ');v.setUint32(at,16,true);at+=4;v.setUint16(at,1,true);at+=2;v.setUint16(at,2,true);at+=2;v.setUint32(at,sr,true);at+=4;v.setUint32(at,sr*4,true);at+=4;v.setUint16(at,4,true);at+=2;v.setUint16(at,16,true);at+=2;tag('data');v.setUint32(at,frames*4,true);at+=4;
    for(const pcm of chunks)for(let i=0;i<pcm.length;i++){const x=Math.max(-1,Math.min(1,pcm[i]));v.setInt16(at,Math.round(x*(x<0?32768:32767)),true);at+=2;}return new Blob([bytes],{type:'audio/wav'});
  }
  function processorSource() {
    return `${global.createMarinadeSequence.toString()}\n${createMarinadeDSP.toString()}\nconst DSP=createMarinadeDSP();class MarinadeProcessor extends AudioWorkletProcessor { constructor(options){super();this.core=new DSP.Core(sampleRate,options.processorOptions.state,options.processorOptions.models);this.core.frame=currentFrame;this.blocks=0;this.port.onmessage=e=>{const m=e.data;try{if(m.type==='models')this.core.setModels(m.models);else if(m.type==='state')this.core.setState(m.state);else if(m.type==='start')this.core.start(m.options);else if(m.type==='stop')this.core.stop();else if(m.type==='panic')this.core.panic();else if(m.type==='note')this.core.scheduleNote(m.options);else if(m.type==='cancel')this.core.stopNotes(m.options);else if(m.type==='transport')this.core.setTransport(m.clock);}catch(error){this.port.postMessage({type:'error',message:error.message});}};} process(inputs,outputs){const out=outputs[0];if(!out||!out[0])return true;this.core.processBlock(out[0],out[1]||out[0]);if(++this.blocks%12===0)this.port.postMessage({type:'meters',meters:this.core.getMeters()});return true;}}registerProcessor('marinade-polyphonic',MarinadeProcessor);`;
  }
  class MarinadeAudio {
    constructor(state) {
      this.state=normalized(state);this.models=null;this._modelSignature=null;this._stateRevision=0;this._preparePromise=null;this.context=null;this.node=null;this.core=null;this.mode='idle';this.isPlaying=false;this.meters=emptyMeters();this._initPromise=null;this._generation=0;this._disposed=false;this._keyTokens=new Map();this._keySequence=0;this._ownsContext=true;
    }
    async init() {
      if(this._disposed)throw new Error('This MARINADE engine has been closed.');
      if(this.node&&this.context?.state!=='closed')return this;
      if(this.context?.state==='closed'){this.node?.disconnect();this.node=null;this.core=null;this.context=null;this._initPromise=null;this._ownsContext=true;this.mode='idle';this.isPlaying=false;this.meters=emptyMeters();}
      if(this._initPromise)return this._initPromise;
      this._initPromise=(async()=>{
        const Context=global.AudioContext||global.webkitAudioContext;if(!Context)throw new Error('This browser does not support Web Audio.');
        // GALLEY supplies a child facade; closing it never closes the studio’s context.
        if(global.MusicLabHost?.createAudioContext){this.context=global.MusicLabHost.createAudioContext();this._ownsContext=true;}
        else if(global.MusicLabHost?.context){this.context=global.MusicLabHost.context;this._ownsContext=false;}
        else this.context=new Context({latencyHint:'interactive'});
        const ctx=this.context,resumePromise=ctx.resume();await this._ensureModels();await resumePromise;let url;
        if(ctx.audioWorklet&&global.AudioWorkletNode&&typeof global.createMarinadeSequence==='function'){
          try{url=URL.createObjectURL(new Blob([processorSource()],{type:'text/javascript'}));await ctx.audioWorklet.addModule(url);if(this._disposed)throw new Error('This MARINADE engine has been closed.');this.node=new global.AudioWorkletNode(ctx,'marinade-polyphonic',{numberOfInputs:0,numberOfOutputs:1,outputChannelCount:[2],processorOptions:{state:processorState(this.state),models:this.models}});this.mode='worklet';this.node.port.onmessage=e=>{if(e.data.type==='meters')this.meters=e.data.meters;else if(e.data.type==='error')this.onStatus?.(e.data.message);};}
          catch(error){if(this._disposed)throw error;this.node=null;this.onStatus?.('Using the compatible audio engine.');}
          finally{if(url)URL.revokeObjectURL(url);}
        }
        if(!this.node){if(!ctx.createScriptProcessor)throw new Error('This browser cannot run MARINADE’s audio engine.');this.core=new DSP.Core(ctx.sampleRate,this.state,this.models);this.core.frame=Math.round(ctx.currentTime*ctx.sampleRate);this.node=ctx.createScriptProcessor(1024,0,2);this.mode='fallback';this.node.onaudioprocess=e=>{if(this._disposed)return;const at=Math.round((Number.isFinite(e.playbackTime)?e.playbackTime:ctx.currentTime)*ctx.sampleRate);if(at>this.core.frame)this.core.frame=at;this.core.processBlock(e.outputBuffer.getChannelData(0),e.outputBuffer.getChannelData(1));this.meters=this.core.getMeters();};}
        if(this._disposed)throw new Error('This MARINADE engine has been closed.');await this._ensureModels();this._send('models',{models:this.models});this._send('state',{state:this.state});this.node.connect(ctx.destination);return this;
      })().catch(error=>{this._initPromise=null;this.node?.disconnect();this.node=null;if(this._ownsContext)this.context?.close().catch(()=>{});this.context=null;this.core=null;throw error;});return this._initPromise;
    }
    _send(type,data={}) {
      if(!this.node)return;if(type==='state')data={...data,state:processorState(data.state)};if(this.mode==='worklet'){this.node.port.postMessage({type,...data});return;}
      const c=this.core;if(type==='models')c.setModels(data.models);else if(type==='state')c.setState(data.state);else if(type==='start')c.start(data.options);else if(type==='stop')c.stop();else if(type==='panic')c.panic();else if(type==='note')c.scheduleNote(data.options);else if(type==='cancel')c.stopNotes(data.options);else if(type==='transport')c.setTransport(data.clock);
    }
    _sameSources(a,b){return !!a&&!!b&&a.length===b.length&&a.every((entry,i)=>entry.length===b[i].length&&entry.every((value,j)=>value===b[i][j]));}
    async _ensureModels(){while(!this.models||!this._sameSources(this._modelSignature,global.MarinadeAnalysis.sourceSignature(this.state)))await this.setState(this.state);return this.models;}
    async setState(state){if(this._disposed)throw new Error('This MARINADE engine has been closed.');const snapshot=normalized(state),signature=global.MarinadeAnalysis.sourceSignature(snapshot),revision=++this._stateRevision;this.state=snapshot;if(!this.models||!this._sameSources(this._modelSignature,signature)){let job=this._preparePromise;if(!job||!this._sameSources(job.signature,signature)){job={signature,promise:global.MarinadeAnalysis.prepare(snapshot)};this._preparePromise=job;}const models=await job.promise;if(this._disposed||revision!==this._stateRevision)return this.state;this.models=models;this._modelSignature=signature;if(this._preparePromise===job)this._preparePromise=null;this._send('models',{models});}if(revision===this._stateRevision)this._send('state',{state:snapshot});return this.state;}
    getModels(){return this.models;}
    async start({when,beat=0}={}) {
      finite(beat,'Start beat',0,1000000);if(when!==undefined)finite(when,'Start time',0,Number.MAX_SAFE_INTEGER);
      const generation=++this._generation;await this.init();if(generation!==this._generation||this._disposed)return false;await this.context.resume();if(generation!==this._generation||this._disposed)return false;
      this.isPlaying=true;this._send('start',{options:{beat,frame:Math.round(Math.max(this.context.currentTime,when??this.context.currentTime)*this.context.sampleRate)}});return true;
    }
    stop(){this._generation++;this.isPlaying=false;this._send('stop');this.meters=Object.assign({},this.meters,{step:-1});}
    panic(){this._generation++;this._keyTokens.clear();this.isPlaying=false;this._send('panic');this.meters=emptyMeters();}
    async trigger(note,velocity=.85,duration=768,source){finite(note,'Pitch',0,127);finite(velocity,'Velocity',0,1);finite(duration,'Gate',.000001,768);source=source||'marinade-key-'+note;if(typeof source!=='string'||!source||source.length>200)throw new Error('Provide a valid note source.');const token=++this._keySequence;this._keyTokens.set(source,token);const generation=this._generation;await this.init();if(this._keyTokens.get(source)!==token||generation!==this._generation||this._disposed)return false;await this.context.resume();if(this._keyTokens.get(source)!==token||generation!==this._generation||this._disposed)return false;return this.scheduleNote({note,velocity,durationSeconds:duration,source});}
    release(note,source){source=source||'marinade-key-'+note;this._keyTokens.delete(source);this.stopNotes({source});}
    scheduleNote({voiceId='synth',note=60,velocity=.85,when,durationSeconds=.4,source='marinade-live'}={}) {
      if(!this.node||!this.context||this.context.state==='closed')throw new Error('Prepare MARINADE before scheduling notes.');if(!['synth','0','auto'].includes(String(voiceId)))throw new Error('Choose MARINADE’s synth voice.');finite(note,'Pitch',0,127);finite(velocity,'Velocity',0,1);finite(durationSeconds,'Gate',.000001,768);if(when!==undefined)finite(when,'Start time',0,Number.MAX_SAFE_INTEGER);if(typeof source!=='string'||!source||source.length>200)throw new Error('Provide a valid note source.');
      this._send('note',{options:{note,velocity,frame:Math.round(Math.max(this.context.currentTime,when??this.context.currentTime)*this.context.sampleRate),duration:durationSeconds,source}});return true;
    }
    stopNotes({source,when}={}) {
      if(source!==undefined&&(typeof source!=='string'||!source||source.length>200))throw new Error('Provide a valid cancellation source.');if(when!==undefined)finite(when,'Cancellation time',0,Number.MAX_SAFE_INTEGER);if(!this.context||!this.node)return;
      this._send('cancel',{options:{source,frame:Math.round(Math.max(this.context.currentTime,when??this.context.currentTime)*this.context.sampleRate)}});
    }
    followTransport(clock={}) {
      if(!this.context||!this.node)return;const beat=clock.absoluteBeat??clock.beat,when=clock.when??clock.contextTime??this.context.currentTime;finite(beat,'Transport beat',0,1000000);finite(clock.tempo,'Transport tempo',20,400);finite(when,'Transport time',0,Number.MAX_SAFE_INTEGER);
      if(!clock.playing)this.isPlaying=false;this._send('transport',{clock:{beat,absoluteBeat:beat,tempo:clock.tempo,playing:!!clock.playing,revision:clock.revision,frame:Math.round(Math.max(this.context.currentTime,when)*this.context.sampleRate)}});
    }
    getMeters(){const m=this.core?this.core.getMeters():this.meters;return {...m,waveform:new Float32Array(m.waveform||128)};}
    async renderWav({state=this.state,bars=4,tailSeconds=2,scope='pattern',signal,chordNotes}={}) {
      cancelled(signal);const snapshot=normalized(state);finite(bars,'Bars',1,16);if(!Number.isInteger(bars))throw new Error('Choose a whole number of bars.');if(!['pattern','note','chord'].includes(scope))throw new Error('Choose an audio export scope.');
      const tempo=snapshot.tempo,lengthBeats=scope==='pattern'?bars*4:Math.min(4,Math.max(1,tempo/60));let events;
      if(scope==='pattern')events=global.createMarinadeSequence().events(snapshot,{startBeat:0,lengthBeats});
      else{const notes=scope==='note'?[snapshot.root]:chordNotes||[snapshot.root,snapshot.root+(snapshot.scale==='major'?4:3),snapshot.root+7].filter(n=>n<=127);if(!Array.isArray(notes)||!notes.length||notes.length>16||notes.some(n=>!Number.isInteger(n)||n<0||n>127))throw new Error('Choose valid chord notes.');events=notes.map(note=>({note,velocity:.85,startBeat:0,durationBeats:lengthBeats,voiceId:'synth'}));}
      return this.renderNotes({state:snapshot,events,tempo,lengthBeats,tailSeconds,signal,name:snapshot.name+'-'+scope});
    }
    async renderNotes({state=this.state,events,tempo,lengthBeats,tailSeconds=2,signal,name,includePCM=false}={}) {
      cancelled(signal);const snapshot=normalized(state);tempo=tempo??snapshot.tempo;finite(tempo,'Render tempo',20,400);finite(lengthBeats,'Phrase length',.000001,1024);finite(tailSeconds,'Tail',0,30);
      if(!Array.isArray(events)||events.length>DSP.MAX_QUEUE)throw new Error('Provide a bounded list of notes to print.');const body=lengthBeats*60/tempo;if(body+tailSeconds>120)throw new Error('Audio exports can be at most 120 seconds including the tail.');
      snapshot.tempo=tempo;const models=await global.MarinadeAnalysis.prepare(snapshot,{signal});cancelled(signal);const sr=48000,core=new DSP.Core(sr,snapshot,models),frames=Math.max(1,Math.ceil((body+tailSeconds)*sr)),chunks=[],renderPCM=includePCM?new Float32Array(frames*2):null;
      for(const e of events){finite(e.note??e.pitch,'Rendered pitch',0,127);finite(e.velocity??.8,'Rendered velocity',0,1);finite(e.startBeat??e.beat,'Rendered note start',0,lengthBeats);finite(e.durationBeats??e.duration,'Rendered note duration',.000001,1024);if((e.startBeat??e.beat)>=lengthBeats)continue;
        core.scheduleNote({note:e.note??e.pitch,velocity:e.velocity??.8,frame:Math.round((e.startBeat??e.beat)*60/tempo*sr),duration:Math.min((e.durationBeats??e.duration)*60/tempo,768),source:'marinade-render'});
      }
      core.stopNotes({source:'marinade-render',frame:Math.round(body*sr)});
      let at=0,blocks=0;const fadeFrames=Math.min(Math.round(sr*.02),Math.max(1,Math.floor(frames/2)));
      while(at<frames){cancelled(signal);const count=Math.min(2048,frames-at),left=new Float32Array(count),right=new Float32Array(count),pcm=renderPCM?renderPCM.subarray(at*2,(at+count)*2):new Float32Array(count*2);core.processBlock(left,right);
        for(let i=0;i<count;i++){const fade=Math.min(1,(frames-at-i-1)/fadeFrames);pcm[i*2]=left[i]*Math.max(0,fade);pcm[i*2+1]=right[i]*Math.max(0,fade);}chunks.push(pcm);at+=count;if(++blocks%2===0)await new Promise(resolve=>setTimeout(resolve,0));}
      cancelled(signal);return {blob:wavBlob(chunks,frames,sr),sampleRate:sr,channels:2,name:(name||snapshot.name||'MARINADE').replace(/[^\w -]/g,'').trim()||'MARINADE',tempo,sourceApp:'marinade',...(renderPCM?{pcm:renderPCM}:{})};
    }
    dispose(){if(this._disposed)return;this.panic();this._disposed=true;this.node?.disconnect();if(this.node&&this.mode==='fallback')this.node.onaudioprocess=null;if(this.node&&this.mode==='worklet'){this.node.port.onmessage=null;this.node.port.close?.();}if(this._ownsContext)this.context?.close().catch(()=>{});this.node=null;this.core=null;}
  }
  MarinadeAudio.wavBlob=wavBlob;MarinadeAudio.processorSource=processorSource;global.MarinadeAudio=MarinadeAudio;
})(typeof window!=='undefined'?window:globalThis);
