// Original stories for the two new browser prototypes. Feature names match
// new-worlds.js; the engine owns progression, dialogue actions, and effects.
export const NEW_STORIES = {
  lynch: {
    title: 'A room with your name',
    weapon: 'flash',
    currency: 'tokens',
    enemy: 'Uninvited shape',
    objective: 'Answer the telephone awake. Enter the stage and the pine grove dreaming. Bring the three clues to Dale.',
    intro: 'Mercy Falls has saved a room for you. The reservation is in your handwriting, dated tomorrow. Your sister June disappeared here thirteen years ago; this morning her voice called your number. Find the message at the ringing telephone, the name behind the red curtain, and the person in the black pines. Some things can only be found while dreaming.',
    lore: 'Mercy Falls is a paper mill town built beside a road that washed away. Its diner stays open for the night shift, although the mill closed years ago. Everyone remembers June. Nobody agrees on whether she ever lived here. At the motel, room 6 is always ready and never rented.',
    advice: 'E speaks to people and investigates places. Q changes between waking and dreaming; the town will remember you differently. Space flashes your camera to repel uninvited shapes. You can finish this story without harming one. Follow the diamond or explore with M.',
    examine: 'The ordinary object has been waiting for you. It becomes less ordinary when you look away.',
    rumor: 'At 2:17 every morning, the diner receives one order for a cup of coffee and two empty chairs. Alma always brings the coffee.',
    resolution: 'Dale lays three things on the counter: June’s message, a playbill with your name, and the key from the pines. The town has been rehearsing an explanation for thirteen years. There is enough evidence to end the rehearsal. There is not enough evidence to make it painless. What will you let Mercy Falls remember?',
    reward: 'Let the town remember June',
    rewardItem: 'June’s brass room key',
    bounty: 65,
    rank: 'A familiar stranger',
    killsNeeded: 0,
    phaseNames: { waking: 'Waking · Mercy Falls', dream: 'Dreaming · The other Mercy Falls' },
    clueNames: {
      'june-message': 'June’s message: “I left. You did not make me leave.”',
      'missing-playbill': 'A playbill credits you with a part you never performed.',
      'room-six-key': 'Room 6’s key was buried beneath the black pines.',
      'double-account': 'Your double remembers staying when you remember running.',
    },
    npcs: [
      {
        name: 'Dale Mercer', role: 'guide',
        intro: '“You’re early,” says Dale, checking a stopped wristwatch. He used to inspect lost mail. Now he inspects the town’s explanations. “June sent you something. Three places have been trying to deliver it. Take your time. Hurry is how we lose the important parts.”',
        waking: 'Dale warms his hands around a cup that gives off no steam. “A person can be missing without being yours to find. Keep that possibility in your pocket.”',
        dream: 'Dale’s reflection watches you from the coffee. “In here, an answer is sometimes a room. Please leave the door open when you go.”',
        completed: 'Dale finally winds his watch. For the first time, it makes a sound. “Whatever comes next, it will be next.”',
        endingText: {
          remember: 'Dale folds June’s statement into the town ledger. “A fact does not make a feeling disappear. It gives the feeling somewhere to stand.” The shapes have quieted.',
          stay: 'Dale sets a second cup beside yours. “I will watch the waking side. You watch this one.” The dream no longer pushes you away.',
          silence: 'Dale accepts the blank tape without touching it. “We have done this before,” he says. “I had hoped this time we would remember doing it.”',
        },
        topics: [
          { label: 'How do I find the three clues?', text: '“The public telephone is north of the diner. Answer it awake. The theatre stage is northeast; its curtain opens in dreams. Follow that dream farther northeast into the black pines. Bring what you learn here. I can restore your health whenever you need a rest.”', dream: '“You are already on the right side for the curtain and the pines. The telephone needs a waking ear. Q will take you across; E will let you listen.”' },
          { label: 'What happened to June?', text: '“The road washed out the night she left. People find that easier to remember than the argument before it. I will not tell you which part belongs to you.”', dream: '“The road did not wash out. It forgot where it was going. I understand the distinction. I cannot help you with it.”' },
          { label: 'Why are you still here?', text: '“A letter came back marked RETURN TO SENDER. I have been trying to find the sender. It was addressed to me.”', completed: '“There are still letters to deliver. A few of them might reach someone now.”' },
        ],
      },
      {
        name: 'Alma Vale', role: 'merchant',
        intro: 'Alma has lined up six slices of cherry pie. Five have been paid for. “If you are asking about June, you can sit. If you are asking about the sixth slice, I will need a minute.”',
        waking: '“June worked the morning shift. She wore a yellow coat. I know because I mended the cuff.” Alma’s own cuff is yellow beneath her apron.',
        dream: 'Alma serves an empty plate. “Your usual. You have been eating around this for years.”',
        completed: 'Alma changes the board from YESTERDAY’S SPECIAL to TODAY’S. She keeps the sixth slice.',
        endingText: { remember: 'Alma pins a photograph of June beside the menu. “She was a person. We can begin there.”', stay: 'Alma places a warm slice in front of the empty chair. “At last. Someone remembered the order.”', silence: 'Alma clears all six plates. “Only five customers,” she says, too quickly.' },
        topics: [
          { label: 'Tell me about the night June left', text: '“She asked me which road went east. Then she asked which one nobody watched. I drew two different lines on the same napkin.”', dream: '“You asked me to keep her here. I said a diner is not a cage. Then I locked the back door. I think that was a different Alma.”' },
          { label: 'Who orders the extra coffee?', text: '“Someone who tips in motel keys. It is poor currency, but it is an excellent conversation starter.”', dream: '“The chair orders it. The chair has better manners than most customers.”' },
          { label: 'What keeps a town alive?', text: '“Somebody opens the door in the morning. Somebody else comes through it. You would be surprised how much rests on those two decisions.”', completed: '“The mill workers came in today. First time in years. None of them said a word. I put fresh coffee on.”' },
        ],
      },
      {
        name: 'Vivian Bell', role: 'ranger',
        intro: 'Vivian sews a hem at the theatre entrance. There is no fabric in her hands. “We start when everybody is seated. We have been one person short for a very long time.”',
        waking: '“There is no performance tonight,” Vivian says. The ticket reads EVERY NIGHT.',
        dream: 'Vivian’s needle passes through the dark. “There you are. Your understudy has become difficult.”',
        completed: 'Vivian rolls up the unused tickets. “The silence after a show belongs to the audience. You may take yours home.”',
        endingText: { remember: 'Vivian opens the curtains onto an empty stage. “We can perform something else now.”', stay: 'Vivian leaves a seat in the front row. Your name is stitched into it.', silence: 'Vivian begins repairing the same invisible hem. “The next performance will explain everything.”' },
        topics: [
          { label: 'What is behind the curtain?', text: '“A room pretending to be a stage. Come back dreaming. The room is less shy then.”', dream: '“Your part is the person who came back. Nobody has written your next line. I consider that promising.”' },
          { label: 'Did June perform here?', text: '“She played the sister. She objected that she was already a sister. We never settled whether that qualified her.”', dream: '“She walked offstage before the ending. Some people called it a mistake. Some called it the only honest line.”' },
          { label: 'Why is my name on the playbill?', text: '“The printer says you ordered it. The printer died in spring. Those facts do not cooperate.”', completed: '“I took your name down. You can put it back if you want a new part.”' },
        ],
      },
      {
        name: 'Owen Pike', role: 'clerk',
        intro: 'Owen presses the motel bell with one finger. It rings from upstairs. “Welcome back. Please do not correct me. It makes the booking system nervous.”',
        waking: '“Room 6 is reserved. I cannot say for whom. The name changes when I read it aloud.”',
        dream: 'Owen holds a key with no teeth. “The room is outside tonight. Try the pines.”',
        completed: 'Owen’s register has finally dried. He turns to a clean page and asks how long you plan to stay.',
        endingText: { remember: 'Owen writes JUNE CHECKED OUT in the old register. He underlines OUT only once.', stay: 'Owen gives you room 6. The key is warm. “Two occupants,” he says. “No extra charge.”', silence: 'Owen turns the register backward to the first page. Your reservation is there again.' },
        topics: [
          { label: 'Show me the old guest register', text: 'June signed in thirteen years ago. Your name appears below hers in fresh ink. Owen blots it. More ink rises. “This is why we stopped offering pens.”', dream: 'The dates count down toward the night of the washout. The last entry says CHECK OUT WHEN READY. “I did not write that,” Owen says.' },
          { label: 'Did someone leave a suitcase?', text: '“Out back. Whoever owned it packed one shoe, a birthday card, and a weather report. They were prepared for a particular kind of journey.”' },
          { label: 'What is in room 6?', text: '“I clean it every morning. The bed is made every evening. I do not know who is doing my job before I arrive.”', dream: '“A person waiting for an apology. I suggest asking what you are apologising for before you promise one.”' },
        ],
      },
      {
        name: 'Elsie Reed', role: 'operator',
        intro: 'Elsie has disconnected the switchboard. Calls keep arriving. “Please hold,” she tells the silence. To you: “I meant that literally. Some voices need a hand.”',
        waking: '“June called the morning after the washout. I logged the call. I also logged that she never called. Both entries are mine.”',
        dream: 'Elsie wears the headset backward. “The future keeps asking to speak to the past. Neither will accept the charges.”',
        completed: 'For the first time, the switchboard has one steady light. Elsie listens without making a note.',
        endingText: { remember: 'Elsie connects June’s recording to every speaker in town. Nobody interrupts it.', stay: 'Elsie opens a line between the diner and the dream. “Visiting hours,” she says, “are whatever you need.”', silence: 'Elsie cuts the wire. The telephone keeps ringing. She cannot meet your eyes.' },
        topics: [
          { label: 'Who is calling the public telephone?', text: '“June. Or someone borrowing the part of her that wanted to leave. Answer while you are awake. In a dream, it only repeats what you already think.”', dream: '“Wake up to answer. You cannot hear another person while you are doing all of their talking.”' },
          { label: 'Can you prove she survived?', text: '“I can prove a call arrived. I can prove I heard her voice. I cannot prove why I hid the log. That is the piece I keep avoiding.”' },
          { label: 'What did she say to you?', text: '“Do not tell them where I went. Tell them I went.” Elsie moves an unplugged cable from one socket to another. “I did neither. I told myself those were the same.”', completed: '“I have stopped translating people into whatever the town can tolerate. It is harder work than I expected.”' },
        ],
      },
      {
        name: 'The double', role: 'double', clue: 'double-account',
        intro: 'Someone with your face stands very still. Their coat is dry despite the rain. “I took care of it,” they say. They appear disappointed that this does not reassure you.',
        waking: 'Your double speaks with your voice a little too slowly. “You remember leaving. I remember being left. One of us is using a convenient word.”',
        dream: 'Your double’s shadow points toward you. “June left because she wanted a life. You turned that into a disappearance because it gave you a job to do.”',
        completed: 'Your double looks less like you. For a moment, they look like somebody you could forgive.',
        endingText: { remember: 'The double puts down their camera. “I can be a memory now.” Their edges soften, and they stop following you.', stay: 'The double steps aside. There is room for both of you on the path.', silence: 'The double smiles exactly when you do. From somewhere behind them comes a camera flash.' },
        topics: [
          { label: 'Did I cause June to disappear?', text: '“You argued. She left. The road washed out. Your mind made one sentence out of three events. It has been an expensive sentence.”', dream: '“You gave her a reason to leave. You did not take away her reasons to live. She deserves those back.”' },
          { label: 'What did you take care of?', text: '“I kept the room ready. Somebody had to. You kept driving past the turnoff.”', dream: '“The part of you that could not wait became me. Do not mistake a useful arrangement for a true account.”' },
          { label: 'Can you come with me?', text: '“I already do. I would prefer to be invited.”', completed: '“Ask me again tomorrow. We have not had a tomorrow before.”' },
        ],
      },
    ],
    landmarks: [
      {
        name: 'Ringing telephone', phase: 'waking', clue: 'june-message', item: 'June’s recorded message',
        text: 'The receiver is warm. June’s voice arrives through a storm: “I left. You did not make me leave. I wanted to be someone you had not already decided I was.” A pause. “I miss the diner. I do not miss the room.” The recording ends with a bus door opening. You keep the message.',
        wrongPhaseText: 'The telephone rings inside your chest. When you lift the receiver, your own voice says the things you expected June to say. This is not her message. Wake with Q, then answer again.',
        completed: 'The telephone is quiet. For once, nobody owes it an answer.',
      },
      {
        name: 'Red-curtain stage', phase: 'dream', clue: 'missing-playbill', item: 'An unfinished playbill',
        text: 'The curtain parts. Two chairs face one another in a motel room. A playbill names you as THE PERSON WHO CAME BACK and June as THE PERSON WHO LEFT. Below them is a blank line: ENDING BY ______. On the second chair, a yellow coat has been carefully folded. There is no body inside it.',
        wrongPhaseText: 'The stage is bare, and the curtain will not move. A ticket seller’s sign reads: CLOSED UNTIL YOU CLOSE YOUR EYES. Enter the dream with Q and investigate again.',
        completed: 'The chairs have turned toward the audience. The blank line is still there. It belongs to you now.',
      },
      {
        name: 'Black pine grove', phase: 'dream', clue: 'room-six-key', item: 'Room 6’s brass key',
        text: 'Between the black pines stands a door without a wall. Beneath it lies room 6’s key. Someone inside asks, “Are you looking for your sister, or for the person you were before she left?” You take the key. The door stays shut. For the first time, you understand that opening it and finding June may be different things.',
        wrongPhaseText: 'The pines are ordinary trees. There is a rectangle of dry ground where no sunlight reaches. Whatever was here is on the other side of sleep. Press Q to enter the dream.',
        completed: 'A path has appeared where the door stood. You cannot see its end, which feels like an improvement.',
      },
    ],
    endings: [
      {
        id: 'remember', label: 'Broadcast June’s message. Let her leave.', reward: 65, item: 'June’s brass room key',
        text: 'Elsie plays the message over the old mill speakers. Alma listens with her apron in both hands. Vivian opens the stage curtains. Nobody claims to understand everything. June’s place in the town becomes a life she chose, rather than an ending you invented. Somewhere far away, a bus reaches its stop.',
        worldConsequence: 'Mercy Falls wakes. The uninvited shapes become peaceful, and the townspeople begin remembering June as a person who left.',
        enemyDisposition: 'peaceful', phase: 'waking',
      },
      {
        id: 'stay', label: 'Keep the dream’s door open. Give the waiting a home.', reward: 65, item: 'The key to both Mercy Falls',
        text: 'You ask Dale to keep the waking diner open. In the dream, you place the second cup on the table and wait without deciding who must arrive. The double sits beside you. For once, the town does not ask anybody to play June. It makes space for what is still unknown.',
        worldConsequence: 'The town remains dreaming. The shapes stop attacking, and its people can visit their other selves without pretending the dream proves what happened.',
        enemyDisposition: 'peaceful', phase: 'dream',
      },
      {
        id: 'silence', label: 'Erase the recording. Give Mercy Falls its old story.', reward: 85, item: 'A blank cassette',
        text: 'You record silence over June’s voice. Dale signs the old report. The mill whistles although its machines are gone. Everyone thanks you for bringing them certainty. At the motel, Owen prepares room 6. The reservation is in your handwriting, dated tomorrow.',
        worldConsequence: 'The town returns to waking, but its uninvited shapes remain hostile. The missing-person story begins again, and the extra payment buys no explanation.',
        enemyDisposition: 'hostile', phase: 'waking',
      },
    ],
  },
  shinobi: {
    title: 'The ember beneath the seal',
    weapon: 'kunai',
    currency: 'ryō',
    enemy: 'Rogue shinobi',
    objective: 'Train at the northern grounds, recover the scroll at Bamboo crossing, and open the watchtower seal. Defeat two rogues or learn Sora’s peaceful passphrase.',
    intro: 'You are a new genin of the Village Hidden in the Reeds. A mission scroll vanished before the morning briefing. Your rival Kaito believes it names the shinobi who betrayed his clan. Mentor Ren has ordered you to recover it before the border patrol does. Learn to shape your chakra, search the bamboo crossing, then open the old watchtower seal. What you return matters as much as whether you return.',
    lore: 'The Hidden Reeds shelters three clans around a spring that never freezes. The Ash clan shapes fire; the Reed clan carries messages through water; the Bell clan makes wind carry a blade. The village calls their pact the Threefold Oath. Its elders teach loyalty first. Its grave markers tell you to ask loyalty to whom.',
    advice: 'Space throws a kunai. 1 casts Ember Release; 2 makes a Shadow Clone that draws attacks; 3 uses Substitution to escape danger. All three jutsus are available now, and chakra returns over time. E speaks, investigates, and completes the three trials. Ask Sora about the watchtower passphrase for a route that needs no rogue defeats. Your jutsus and your decisions both matter.',
    examine: 'You place two fingers against the mark. Chakra answers from somewhere beyond the stone. An old oath remembers its witnesses.',
    rumor: 'The bamboo bends toward the west even when the wind blows east. Aya says it listens to runners. Nori says it listens to people worth following.',
    resolution: 'The scroll contains no enemy roster. It is a mission ledger: village leaders sent Kaito’s clan beyond the border to preserve a treaty, then called their deaths desertion. Ren knew part of it. Sora kept the seal. Kaito waits for you to say whether loyalty can survive the truth. The scroll is yours to place.',
    reward: 'Read the ledger before the whole village',
    rewardItem: 'Threefold Oath headband',
    bounty: 75,
    rank: 'Genin · ember recruit',
    killsNeeded: 2,
    peacefulRouteClue: 'watchtower-password',
    clueNames: {
      'watchtower-password': 'Sora’s passphrase: “A village is everyone who must come home.” The watchtower guards stand down; rogue defeats are optional.',
      'aya-tracks': 'Aya’s tracks lead to Bamboo crossing. The scroll carrier avoided the watchtower patrol.',
      'kaito-oath': 'Kaito’s brother carried a return token from the village when he died.',
      'chakra-form': 'Elemental trial: steady your breath, shape your chakra, and release it without anger.',
      'mission-scroll': 'The recovered mission scroll contains an erased mission ledger.',
      'broken-seal': 'The watchtower seal confirms the ledger was altered by village authority.',
    },
    npcs: [
      {
        name: 'Ren', role: 'guide',
        intro: 'Ren adjusts your forehead protector until its knot sits level. “A genin can finish a mission by obeying. A shinobi must also understand what they have done. Bring the scroll home. Do not let Kaito face this alone.”',
        completed: 'Ren bows to you before giving his next instruction. “You made a decision I would have been afraid to make at your rank.”',
        endingText: { truth: 'Ren removes his council insignia. “I will testify. A teacher who asks for courage must bring some of his own.”', exile: 'Ren places two travel packs at the gate. “You are leaving my command. You are not leaving my care.”', order: 'Ren files the scroll behind a new seal. “The village is safe,” he says. He does not say whether that is enough.' },
        topics: [
          { label: 'Give me a mission briefing', text: '“Train north of here. The scroll was last seen at the bamboo crossing to the southwest. The sealed watchtower is northeast. You can clear two rogues, or ask Sora for the old passphrase and go through without a fight. Press M to read the map.”' },
          { label: 'Teach me chakra control', text: '“1 releases fire. 2 shapes a shadow clone that draws attacks. 3 uses substitution to slip away from danger. All three are yours already. Chakra recovers when you give it a moment. Running out is an instruction to think, not an instruction to be braver.”' },
          { label: 'What do you know about Kaito’s clan?', text: '“Their last order did not come through me. I told myself that meant it was not my responsibility. I have been teaching you better than I lived.”', completed: '“The names are in our memorial now. Whatever the council says, I will teach them to the next class.”' },
          { label: 'What makes someone a shinobi?', text: '“Not a bloodline. Not a technique. Someone has to carry a promise through danger. The difficult part is knowing which promises deserve the journey.”' },
        ],
      },
      {
        name: 'Mako', role: 'merchant',
        intro: 'Mako stacks paper charms beside rice balls. “One keeps evil away. One keeps hunger away. Only one comes with a guarantee.”',
        completed: 'Mako has added a second bench outside the shop. “People have things to say now. They should be able to sit while saying them.”',
        endingText: { truth: 'Mako offers food to the families waiting for the council hearing. “The village finally has an appetite for something useful.”', exile: 'Mako tucks extra rice balls into your pack. “A border is a poor reason to go hungry.”', order: 'Mako closes the shop early. Behind the counter, one unsigned memorial charm remains.' },
        topics: [
          { label: 'Which clan are you from?', text: '“None that will admit it. My mother made wind charms. My father fixed water pumps. The council could not decide which box to put me in, so I opened a shop.”' },
          { label: 'What does the village think of Kaito?', text: '“People like a survivor while he is grateful. They become uncomfortable when he wants an answer. I give him breakfast either way.”' },
          { label: 'Any advice for a new genin?', text: '“Your supplies are replaceable. Your teammates are not. If somebody tells you a person is an acceptable loss, ask what they are accepting for themselves.”', completed: '“You brought more back than a scroll. I wish the academy gave credit for that.”' },
        ],
      },
      {
        name: 'Aya', role: 'ranger', clue: 'aya-tracks',
        intro: 'Aya balances on the fence, reading the grass below. “Three sets of footprints. One person running. One person following. One person trying to look like two. We have an interesting morning.”',
        completed: 'Aya has taken the patrol notices down. She still watches the road, but she leaves the gate open.',
        endingText: { truth: 'Aya volunteers to find the families named in the ledger. “There is a difference between tracking a person and bringing them home.”', exile: 'Aya points out an unwatched road. “The report will say I did not see you. That is almost true.”', order: 'Aya folds the patrol order in half. “I know how to obey. I am still learning when.”' },
        topics: [
          { label: 'Where did the scroll carrier go?', text: '“Southwest, into the bamboo crossing. Look for the loose bridge rope. Whoever hid the scroll knew we would search the watchtower first.”' },
          { label: 'Can I avoid a fight?', text: '“The rogues are former village shinobi guarding an old promise. Ask Elder Sora for the watchtower passphrase. Say it properly, and there is no need to prove yourself by hurting them.”' },
          { label: 'Teach me about the Reed clan', text: '“We send messages through running water. The current repeats a lie just as faithfully as the truth. A useful technique requires an honest messenger.”', completed: '“I sent the news downstream. The villages will hear what happened. This time, so will the families.”' },
        ],
      },
      {
        name: 'Nori', role: 'quartermaster',
        intro: 'Nori checks the seal on a crate of practice kunai. “Count them before you leave. Count your teammates when you return. We have been doing those in the wrong order.”',
        completed: 'Nori replaces the casualty column in the mission book with PEOPLE TO BRING HOME.',
        endingText: { truth: 'Nori writes the erased names into the supply ledger. “Dead shinobi leave belongings. Someone should know who to give them to.”', exile: 'Nori marks your packs TRAINING SUPPLIES. “I can lose two crates. I cannot lose another team.”', order: 'Nori signs the new inventory. He leaves the casualty column blank.' },
        topics: [
          { label: 'What is hidden in the training supplies?', text: '“A chakra-binding cord and an old field manual. Take what you need. Equipment that sits in a crate is very good at protecting a crate.”' },
          { label: 'Who supplied the last border mission?', text: '“I did. Seven return tokens. Seven people expected to come back. The record now says the tokens were never issued. I have excellent handwriting; I recognise my own numbers.”' },
          { label: 'Why do you never go on missions?', text: '“I lost one hand making sure a bridge stayed up. The people who crossed it call that retirement. I call this the rest of the same mission.”', completed: '“A quartermaster can mend more than equipment. Sometimes a record needs its missing pieces.”' },
        ],
      },
      {
        name: 'Sora', role: 'elder',
        intro: 'Sora sits beneath the watchtower’s old oath plaque. “You came looking for permission. I hope you will also look for a reason.”',
        completed: 'Sora rises from the plaque for the first time in years. The stone behind her is lighter than the rest.',
        endingText: { truth: 'Sora hands over the council’s seal. “I called silence protection. You have given it its proper name.”', exile: 'Sora removes your names from the gate register. “A village may fail the people it is meant to shelter. Take care of each other until ours remembers.”', order: 'Sora presses a new seal onto the ledger. Her hand shakes. “Another generation,” she says, “might be ready.”' },
        topics: [
          { label: 'Teach me the watchtower passphrase', text: '“A village is everyone who must come home.” Sora speaks each word as if it hurts. “The guards recognise the Threefold Oath. Carry it to the tower, and they will stand down. You can complete your mission without defeating the rogues.”', clue: 'watchtower-password' },
          { label: 'Why is the watchtower sealed?', text: '“A seal keeps something safe from the outside. It also prevents the outside from learning what it is keeping. I used that distinction for too long.”' },
          { label: 'What happened to the Ash clan?', text: '“We purchased peace with a mission we did not expect them to survive. Then we purchased our own comfort by calling them deserters. Their children were left to pay for both.”', completed: '“Your generation has inherited the result. It does not have to inherit our excuses.”' },
        ],
      },
      {
        name: 'Kaito', role: 'rival', clue: 'kaito-oath',
        intro: 'Kaito’s practice blade has split its wooden target. “Ren says we are rivals so we will improve. I would settle for knowing which direction I am meant to improve in.”',
        completed: 'Kaito puts his blade down when he sees you. This is the first conversation where he has done that.',
        endingText: { truth: 'Kaito ties his brother’s return token beneath his headband. “They will say his name. Then I will decide what to do with mine.”', exile: 'Kaito waits at the gate with one pack. “I meant to go alone. I am glad you are bad at following orders.”', order: 'Kaito hears the council’s account without answering. “You completed the mission,” he says. “I hope that is what you wanted.”' },
        topics: [
          { label: 'Do you want revenge?', text: '“I want someone to say my brother did not run away. Every time they refuse, revenge begins to sound like an answer. I know it is not the same thing.”' },
          { label: 'Tell me about your brother', text: '“He made fire birds to amuse the academy kids. His last message had a village return token tied to it. Deserters do not carry a promise to come home.”' },
          { label: 'Will you trust me with the scroll?', text: '“I do not trust the council. That is different from not trusting you. Bring me the truth before you bring anybody my obedience.”', completed: '“We were taught to compete. I think we might be better at standing beside one another.”' },
          { label: 'Teach me an Ash clan technique', text: '“Breathe before you release fire. Anger will make it louder, but it will not make it yours. Pressing 1 is the beginning of a technique. Choosing where to aim is the rest.”' },
        ],
      },
    ],
    landmarks: [
      {
        name: 'North training grounds', phase: 'both', clue: 'chakra-form', item: 'Ash-release training cord',
        text: 'You kneel inside the elemental circle. Water steadies your pulse; wind finds the gaps between your fingers; a small ember becomes a clean flame. The lesson is control rather than force. You complete the chakra-form trial. Practise the jutsus you already carry: 1 Ember Release, 2 Shadow Clone, and 3 Substitution.',
        completed: 'The practice circle bears your footprints beside Ren’s and Kaito’s. Its fire has gone out; the warmth remains.',
      },
      {
        name: 'Bamboo crossing', phase: 'both', clue: 'mission-scroll', item: 'Recovered mission scroll',
        text: 'Under the loose bridge rope, you find a scroll sealed with the Hidden Reeds crest. Its first page is a supply order. Beneath the ink, older names shine through: Kaito’s clan, a forbidden route, and an order to leave the gate closed. Someone hid it here to keep it from the council patrol. You recover the lost mission scroll.',
        completed: 'The bridge rope is secure again. Below it, the river carries a torn scrap of the old patrol order away.',
      },
      {
        name: 'Sealed watchtower', phase: 'both', clue: 'broken-seal', item: 'The erased mission ledger',
        text: 'The Threefold Oath forms three interlocking marks around the door. Your chakra steadies the broken third mark. Inside, the original ledger confirms the scroll: the border team obeyed a village order. They never deserted. A second signature shows who changed their record. You take a copy of the evidence, leaving the original where it can no longer be hidden.',
        completed: 'The watchtower is open. There is room on its memorial wall for the names that were missing.',
      },
    ],
    endings: [
      {
        id: 'truth', label: 'Read the ledger publicly. Rebuild the village’s oath.', reward: 75, item: 'Threefold Oath headband', rank: 'Chūnin · keeper of the oath',
        text: 'You read every name in the square. Ren testifies; Sora surrenders the seal. Kaito stands beside the families instead of drawing his blade. The village has a difficult season ahead. Its new oath begins with a promise to bring people home and ends with a way to hold its leaders to it.',
        worldConsequence: 'The former rogues rejoin the village and stop attacking. You become a chūnin, and the missing clan is restored to the memorial.',
        enemyDisposition: 'peaceful',
      },
      {
        id: 'exile', label: 'Give Kaito the evidence. Leave together to find the survivors.', reward: 75, item: 'Ash clan travel token', rank: 'Wandering shinobi · sworn companion',
        text: 'You give Kaito the ledger and a second travel pack. His revenge becomes a search: some names on the mission have no grave. Ren opens the gate without asking where you are going. You leave as companions, carrying proof the council can neither command nor erase.',
        worldConsequence: 'The rogues recognise Kaito’s return token and become peaceful. Your new rank is wandering shinobi; the village loses your obedience and keeps your friendship.',
        enemyDisposition: 'peaceful',
      },
      {
        id: 'order', label: 'Return the sealed ledger to the council. Preserve the treaty.', reward: 95, item: 'Council mission insignia', rank: 'Chūnin · council operative',
        text: 'The council thanks you for completing a sensitive mission. The border treaty holds. Your promotion arrives before sunset. Kaito waits for an explanation that you cannot make convincing. In the bamboo, the shinobi who remember the original oath continue to guard it.',
        worldConsequence: 'You become a council chūnin and receive extra ryō. The rogues remain hostile, and Kaito’s trust becomes the price of the village’s silence.',
        enemyDisposition: 'hostile',
      },
    ],
  },
};
