const baseIngredients = {
  shots: 0,
  milk: 0,
  foam: 0,
  water: 0,
  tea: 0,
  chocolate: 0,
  vanilla: 0,
  caramel: 0,
  coldMilk: 0,
};

const makeRecipe = (
  id,
  name,
  shortName,
  price,
  day,
  cup,
  ingredients,
  description,
  steps,
) => ({
  id,
  name,
  shortName,
  price,
  day,
  unlockDay: day,
  cup,
  ingredients: { ...baseIngredients, ...ingredients },
  description,
  steps,
});

export const recipes = {
  espresso: makeRecipe(
    "espresso",
    "Espresso",
    "Espresso",
    3,
    1,
    "hot",
    { shots: 1 },
    "A little cup with a big personality.",
    ["Take a hot cup", "Pull one espresso shot"],
  ),
  americano: makeRecipe(
    "americano",
    "Americano",
    "Americano",
    3.5,
    1,
    "hot",
    { shots: 1, water: 1 },
    "Espresso, stretched into a slow morning.",
    ["Take a hot cup", "Pull one espresso shot", "Add hot water"],
  ),
  latte: makeRecipe(
    "latte",
    "Café latte",
    "Latte",
    4.5,
    1,
    "hot",
    { shots: 1, milk: 1 },
    "One shot, silky steamed milk, happy hands.",
    ["Take a hot cup", "Pull one espresso shot", "Add steamed milk"],
  ),
  cappuccino: makeRecipe(
    "cappuccino",
    "Cappuccino",
    "Cappuccino",
    4.5,
    1,
    "hot",
    { shots: 1, milk: 1, foam: 1 },
    "A coffee wearing its favorite fluffy hat.",
    [
      "Take a hot cup",
      "Pull one espresso shot",
      "Add steamed milk",
      "Finish with milk foam",
    ],
  ),
  tea: makeRecipe(
    "tea",
    "House tea",
    "Tea",
    3,
    1,
    "hot",
    { tea: 1 },
    "A fragrant little pause in the day.",
    ["Take a hot cup", "Brew one serving of tea"],
  ),
  hotchocolate: makeRecipe(
    "hotchocolate",
    "Hot chocolate",
    "Hot chocolate",
    4,
    2,
    "hot",
    { milk: 1, chocolate: 1 },
    "A hug, conveniently served in a cup.",
    ["Take a hot cup", "Add chocolate", "Add steamed milk"],
  ),
  mocha: makeRecipe(
    "mocha",
    "Café mocha",
    "Mocha",
    5,
    2,
    "hot",
    { shots: 1, milk: 1, chocolate: 1 },
    "Coffee and chocolate are on the same team.",
    [
      "Take a hot cup",
      "Pull one espresso shot",
      "Add chocolate",
      "Add steamed milk",
    ],
  ),
  icedlatte: makeRecipe(
    "icedlatte",
    "Iced latte",
    "Iced latte",
    4.5,
    3,
    "iced",
    { shots: 1, coldMilk: 1 },
    "Cool, smooth, and ready for the sunny table.",
    ["Take an iced cup", "Pull one espresso shot", "Add cold milk"],
  ),
  vanillalatte: makeRecipe(
    "vanillalatte",
    "Vanilla latte",
    "Vanilla latte",
    5,
    2,
    "hot",
    { shots: 1, milk: 1, vanilla: 1 },
    "The house latte with a soft vanilla finish.",
    [
      "Take a hot cup",
      "Pull one espresso shot",
      "Add vanilla syrup",
      "Add steamed milk",
    ],
  ),
  caramellatte: makeRecipe(
    "caramellatte",
    "Caramel latte",
    "Caramel latte",
    5,
    3,
    "hot",
    { shots: 1, milk: 1, caramel: 1 },
    "A golden swirl for a well-earned break.",
    [
      "Take a hot cup",
      "Pull one espresso shot",
      "Add caramel syrup",
      "Add steamed milk",
    ],
  ),
};

export const foods = {
  croissant: {
    id: "croissant",
    name: "Butter croissant",
    shortName: "Croissant",
    price: 3,
    duration: 7,
    warm: true,
    description: "Warm until flaky and golden. Expect crumbs.",
  },
  toastie: {
    id: "toastie",
    name: "Cheese toastie",
    shortName: "Toastie",
    price: 5,
    duration: 10,
    warm: true,
    description: "Toasty bread, melty cheese, instant good mood.",
  },
  cinnamonroll: {
    id: "cinnamonroll",
    name: "Cinnamon roll",
    shortName: "Cinnamon roll",
    price: 3.5,
    duration: 8,
    warm: true,
    description: "A warm cinnamon spiral with a soft icing cap.",
  },
};

const choice = (label, response) => ({ label, response });
const story = (topic, aLabel, aReply, bLabel, bReply) => ({
  topic,
  choices: [choice(aLabel, aReply), choice(bLabel, bReply)],
});

const makeCustomer = (profile) => ({
  ...profile,
  opener: profile.greeting,
  topic: profile.stories[0].topic,
  choices: profile.stories[0].choices,
  chatChoices: profile.stories[0].choices.map((option, index) => ({
    id: `${profile.id}-${index}`,
    label: option.label,
    reply: option.response,
  })),
});

export const customers = {
  mina: makeCustomer({
    id: "mina",
    name: "Mina",
    role: "Neighborhood illustrator",
    shortBio: "Sketchbook regular. Collects tiny moments and enormous scarves.",
    skin: "#c38d6d",
    hairColor: "#392c34",
    shirtColor: "#de8377",
    accessory: "scarf",
    personality: "Curious, gentle, and quick to notice little details.",
    greeting: "Morning! Your window light is better than my entire studio.",
    orderLine: "A {drink}, please. A little creative fuel.",
    stories: [
      story(
        "I’m sketching a mural for the alley. Too many flowers, or never enough flowers?",
        "Never enough flowers.",
        "Correct answer. I’ll add one that looks suspiciously like your coffee cups.",
        "Leave room for a little cat.",
        "Oh! A tiny alley guardian. You’re officially on the art team.",
      ),
      story(
        "The mural is happening! A neighbor offered to help. He has one brush and eight opinions.",
        "Give him the biggest flower.",
        "An excellent diplomatic strategy. The sunflower committee is now in session.",
        "Let him paint the little cat.",
        "He named it Chairman Meow before I even asked. This is going beautifully.",
      ),
      story(
        "The mural’s finished. Someone left a little vase of flowers underneath it this morning.",
        "The neighborhood loves it.",
        "I think so. I wanted to brighten a wall, and somehow it brightened my whole week.",
        "You should sign it!",
        "I did, right beside the tiny cat. There’s a little coffee cup for you, too.",
      ),
    ],
    thanks: [
      "Exactly what I needed. You’re a lifesaver.",
      "This is lovely. Consider yourself drawn in my next sketch.",
      "Perfect. The mural runs on this.",
    ],
    impatient: "My sketchbook’s ready whenever my coffee is!",
    goodbye: "See you tomorrow. Save me a little patch of window light!",
  }),
  ollie: makeCustomer({
    id: "ollie",
    name: "Ollie",
    role: "Local mail carrier",
    shortBio: "Knows every dog on the block. Usually knows their humans, too.",
    skin: "#e4ad88",
    hairColor: "#925d36",
    shirtColor: "#6c8faa",
    accessory: "cap",
    personality: "Cheerful, chatty, and a little dramatic about pigeons.",
    greeting: "Special delivery: one very sleepy mail carrier.",
    orderLine: "Could I get a {drink}? The route has hills today.",
    stories: [
      story(
        "A pigeon keeps walking my route with me. I think I’ve accidentally hired an assistant.",
        "Give it a little uniform.",
        "A tiny cap! I’m writing that down. With postage-sized pockets, obviously.",
        "Does it accept crumbs as wages?",
        "Only premium crumbs. It has very strong feelings about rye.",
      ),
      story(
        "My pigeon assistant has recruited a second pigeon. Management is expanding rapidly.",
        "Time for a team meeting.",
        "Agenda item one: stop standing on the mail. Agenda item two: snacks.",
        "Your route must be famous now.",
        "I’m basically a moving bird café. The dogs are deeply confused.",
      ),
      story(
        "The pigeons escorted me here today. I think they’ve learned where the good smells are.",
        "Excellent taste, those birds.",
        "They agree. One just bowed at the door. That’s customer feedback, I think.",
        "Do they have names now?",
        "Stamp and Envelope. My supervisor says that counts as professional development.",
      ),
    ],
    thanks: [
      "That hits the spot. Back to delivering birthday cards!",
      "Perfect! This route just got much easier.",
      "Five stars from me. The pigeons are still deliberating.",
    ],
    impatient: "No rush. Well, a little rush. The mail does have places to be.",
    goodbye: "Catch you on the next round!",
  }),
  june: makeCustomer({
    id: "june",
    name: "June",
    role: "Plant shop owner",
    shortBio:
      "Brings plant cuttings as gifts and soil into every conversation.",
    skin: "#a66b4d",
    hairColor: "#252e28",
    shirtColor: "#839b62",
    accessory: "earrings",
    personality:
      "Soft-spoken, thoughtful, and enthusiastic about improbable plants.",
    greeting: "Hi! I brought good news and, possibly, a leaf in my hair.",
    orderLine:
      "A {drink} would be lovely. My plants already had their breakfast.",
    stories: [
      story(
        "My shy little lemon tree has its first flower. We’ve both waited three years for this.",
        "That deserves a celebration.",
        "I gave it a sunny spot and myself a café break. Very fair rewards.",
        "You must be so proud.",
        "Ridiculously proud. I showed a photo to the bus driver this morning.",
      ),
      story(
        "The lemon tree has a tiny lemon! It’s about the size of a pea with big ambitions.",
        "Little lemon, big dreams.",
        "Exactly. I understand it completely. We are both doing our best.",
        "Keep taking progress photos.",
        "I have twenty-six already. My phone thinks the lemon is my favorite person.",
      ),
      story(
        "My first lemon is ripe. I’m saving it for a cake to share with the whole shop.",
        "A cake three years in the making.",
        "The world’s slowest recipe. But I have a feeling it’ll be worth every day.",
        "Save a slice for yourself, too.",
        "I will. Thank you for reminding me that the gardener gets a little sunshine, too.",
      ),
    ],
    thanks: [
      "Lovely. You make this little corner feel like home.",
      "Perfectly made. I can feel my roots relaxing.",
      "Just right. I’ll bring you a cutting next time.",
    ],
    impatient: "I should open the plant shop soon. The ferns are expecting me.",
    goodbye: "Have a gentle day. Drink water, too!",
  }),
  theo: makeCustomer({
    id: "theo",
    name: "Theo",
    role: "Secondhand bookseller",
    shortBio:
      "Always halfway through a mystery. Sometimes it is an actual mystery.",
    skin: "#d29b77",
    hairColor: "#57413b",
    shirtColor: "#b5986e",
    accessory: "glasses",
    personality:
      "Dry humor, warm heart, and an endless supply of book recommendations.",
    greeting: "Hello. I’ve escaped a very suspenseful chapter for this.",
    orderLine: "A {drink}, please. Strictly for literary purposes.",
    stories: [
      story(
        "I found a love letter in an old cookbook. No name, just “meet me where the bread is warm.”",
        "That is incredibly romantic.",
        "Agreed. I’m shelving the cookbook under Romance. A bold but defensible choice.",
        "The bakery might know more.",
        "Excellent detective work. I’ll investigate, professionally, with a pastry.",
      ),
      story(
        "The baker recognized the letter! Her parents met at that bakery forty years ago.",
        "You found a family treasure.",
        "She cried a little. I pretended to be very interested in a loaf while she did.",
        "Did you return it to her?",
        "Of course. Some stories belong on a family mantel, not a shop shelf.",
      ),
      story(
        "The baker brought a framed photo of her parents for the shop. They’re holding that letter.",
        "A very happy ending.",
        "The best kind. No cliffhanger, unless you count how good her bread is.",
        "You should write this story down.",
        "Perhaps I will. Chapter one: a bookseller needed coffee. A strong opening, I think.",
      ),
    ],
    thanks: [
      "A satisfying ending. No notes.",
      "Beautiful. I’d recommend this to a friend.",
      "Exactly right. This earns a place on my favorites shelf.",
    ],
    impatient: "The bookshop opens soon. The books get impatient without me.",
    goodbye: "Until the next chapter!",
  }),
  bea: makeCustomer({
    id: "bea",
    name: "Bea",
    role: "Bicycle mechanic",
    shortBio: "Fixes squeaky bikes and finds excuses to take the scenic route.",
    skin: "#754c36",
    hairColor: "#292522",
    shirtColor: "#d2a350",
    accessory: "beanie",
    personality: "Upbeat, practical, and generous with encouragement.",
    greeting: "Hey! I’ve already fixed three punctures. One of them was mine.",
    orderLine: "A {drink}, please. My internal battery needs a charge.",
    stories: [
      story(
        "I’m organizing a little neighborhood bike ride. No racing. Maximum snack breaks.",
        "My kind of cycling.",
        "Right? The finish line is a picnic blanket. Everybody wins.",
        "Will beginners be welcome?",
        "Especially beginners. I’m bringing spare helmets and a lot of patience.",
      ),
      story(
        "Twelve people signed up! One asked if a basket full of flowers counts as equipment.",
        "Absolutely essential equipment.",
        "That’s what I said. Flowers, bell, snack. The bicycle holy trinity.",
        "You’ve made it sound so friendly.",
        "That’s the plan. Nobody should need fancy gear to have a nice afternoon.",
      ),
      story(
        "The ride was lovely. Someone rode a bike for the first time in twenty years.",
        "That must have felt amazing.",
        "They couldn’t stop smiling. Neither could I, honestly. Best ride all year.",
        "Make it a monthly thing!",
        "Already planned. You’re our official pre-ride coffee stop now.",
      ),
    ],
    thanks: [
      "Smooth service. Zero squeaks. Love it.",
      "Perfect. That’s the good kind of fuel.",
      "You nailed it. Back to the workshop!",
    ],
    impatient: "I’ve got a bike on the repair stand, so I’d better roll soon.",
    goodbye: "Take the scenic route today!",
  }),
  sam: makeCustomer({
    id: "sam",
    name: "Sam",
    role: "Bedroom musician",
    shortBio: "Carries a guitar pick everywhere. Hums while choosing pastries.",
    skin: "#cb9670",
    hairColor: "#463b62",
    shirtColor: "#a690b9",
    accessory: "headphones",
    personality:
      "Earnest, a little nervous, and always listening for a melody.",
    greeting: "Hey. If I hum at the menu, I promise it isn’t a complaint.",
    orderLine: "Could I have a {drink}? I’m rehearsing my order voice.",
    stories: [
      story(
        "I signed up for the open mic. Now my stomach is doing a drum solo.",
        "You’ve got this, Sam.",
        "Thanks. I keep telling myself the audience is just friends I haven’t met yet.",
        "Start with your favorite song.",
        "Good idea. That one feels like home. I can start from home.",
      ),
      story(
        "The open mic is tonight. I practiced so much my neighbor requested an encore. Or silence.",
        "Let’s assume it was an encore.",
        "Yes. A very firm, wall-tapping encore. They’re a passionate music fan.",
        "A little rest helps, too.",
        "You’re right. Coffee, a walk, then music. My hands can stop rehearsing for a bit.",
      ),
      story(
        "I did it! My voice shook at first, but people sang the chorus with me.",
        "That sounds magical.",
        "It was. Suddenly I wasn’t performing at them. We were making a song together.",
        "When’s your next show?",
        "Next week! Want a spot on the guest list? It’s currently a very short list.",
      ),
    ],
    thanks: [
      "Perfect. If this drink were a chord, it’d be a major seventh.",
      "Just right. You’ve put a good song in my day.",
      "Thanks! I can hear my brain tuning back up.",
    ],
    impatient: "Rehearsal starts soon. My drummer actually shows up on time.",
    goodbye: "See you around. Keep the good tunes playing!",
  }),
  ren: makeCustomer({
    id: "ren",
    name: "Ren",
    role: "Community librarian",
    shortBio:
      "Champion of quiet corners, loud laughs, and overly ambitious crosswords.",
    skin: "#bc8867",
    hairColor: "#1f393c",
    shirtColor: "#639b96",
    accessory: "glasses",
    personality:
      "Playful, patient, and secretly very competitive at word games.",
    greeting: "Hello! Consider this my officially sanctioned library escape.",
    orderLine: "A {drink}, please. Eight letters for “a very good decision.”",
    stories: [
      story(
        "We’re starting a puzzle club at the library. I’m worried nobody will show up.",
        "Put out some cozy chairs.",
        "Brilliant. A welcoming chair says more than my extremely detailed poster.",
        "I bet the word will spread.",
        "I hope so. I’ve already saved the crossword with the excellent coffee pun.",
      ),
      story(
        "Puzzle club had nine people! We spent half the time discussing biscuits. A great success.",
        "Biscuits are part of the puzzle.",
        "Exactly. An essential clue to happiness. I’m putting that in the minutes.",
        "Sounds like you found your people.",
        "I think I did. Everyone helped someone else with a clue. That was my favorite part.",
      ),
      story(
        "The club made a crossword about our neighborhood. Guess who’s the clue for “best coffee”?",
        "I’m blushing a little.",
        "A very appropriate response to a seven-across honor. You’ve earned it.",
        "Save me a copy!",
        "Already in my bag. There’s a pastry clue too, but that one’s a toughie.",
      ),
    ],
    thanks: [
      "Correct on every clue. Thank you!",
      "Lovely. A five-star intermission.",
      "Perfect. I’ll return the cup on time, library style.",
    ],
    impatient:
      "The library needs me soon. Someone always wants the big dinosaur book.",
    goodbye: "Have a lovely day. May all your clues be fair!",
  }),
  ada: makeCustomer({
    id: "ada",
    name: "Ada",
    role: "Retired engineer",
    shortBio:
      "Builds tiny things in a very untidy shed. Claims it is a system.",
    skin: "#e0b390",
    hairColor: "#c8c4b7",
    shirtColor: "#718ba0",
    accessory: "glasses",
    personality:
      "Wry, inventive, and delighted by a problem worth tinkering with.",
    greeting: "Good morning. I’m taking a break from making a very small mess.",
    orderLine:
      "A {drink}, please. Precision engineering requires refreshments.",
    stories: [
      story(
        "I’m building a tiny sailboat for the park pond. The first test was mostly a submarine.",
        "A successful submarine, though.",
        "Exactly! I simply misnamed the project. A classic engineering problem.",
        "What’s the next experiment?",
        "Less weight, more patience. Conveniently, both are available in my shed.",
      ),
      story(
        "The boat floats! Now it turns left forever. Very committed to one particular adventure.",
        "A scenic circular tour.",
        "An excellent rebrand. Tickets include unlimited views of the same duck.",
        "Maybe adjust the sail a little?",
        "That’s my next test. You have a good eye. Fancy a job in the very tiny shipyard?",
      ),
      story(
        "The little boat crossed the whole pond. A child cheered like we’d reached the moon.",
        "That’s a voyage to celebrate.",
        "I agree. I named it Second Pour, after my favorite supply station.",
        "What will you build next?",
        "A tiny lighthouse. Apparently every good adventure needs a place to come home to.",
      ),
    ],
    thanks: [
      "Precisely made. Excellent work.",
      "Perfect. I’ll record this as a successful experiment.",
      "Wonderful. The shipyard runs another day.",
    ],
    impatient:
      "I’d better get back before the glue sets. It has no respect for coffee breaks.",
    goodbye: "Keep making good things. I’ll see you soon.",
  }),
};

export const recipeList = Object.values(recipes);
export const foodList = Object.values(foods);
export const customerList = Object.values(customers);

// Both styles are exported so the game and view can share one authored menu.
export const RECIPES = recipes;
export const FOODS = foods;
export const CUSTOMERS = customerList;
